### ISSUE TITLE
Update react/socket to a more recent version

### ISSUE THREAD

**Issue by JABirchall** [botman/botman#1001]
- BotMan Version: 2.4.1
- PHP Version: 7.3.1
- Messaging Service(s): [JABirchall/botman-driver-discord](https://github.com/JABirchall/botman-driver-discord)
- Cache Driver: default

### Description:
My discord drivers require the use of react/socket `^1.1` but botman requires `0.4.*` I can't downgrade as the newer versions fix an bug. Botman should upgrade to a newer version of [react/socket](https://github.com/reactphp/socket/releases). Botman is 22 versions behind (3.4 years)

### Steps To Reproduce:
```
{
  "name": "something/overtherainbow",
  "description": "a bug",
  "minimum-stability": "stable",
  "license": "proprietary",
  "require": {
    "botman/botman": "~2.0",
    "php": ">=7.1",
    "charlottedunois/yasmin": "^v0.6.0",
  },
}

```
`composer install`

[yasmin](https://github.com/CharlotteDunois/Yasmin) requires [react-buzz](https://github.com/clue/reactphp-buzz) for async requests. Which requires react/socket `^1.1`

**Comment by JABirchall** [comment]
I noticed you have already fixed this issue in #943 but have not made a release. Can we make this a release?

**Comment by JABirchall** [comment]
I've been testing the unreleased code and it all works without any issues.

**Comment by isbkch** [comment]
Can we make a release for this?

**Comment by isbkch** [comment]
My PPM driver requires latest `react/socket` as well and I don't want to make yet another fork just for this...

**Comment by mpociot** [comment]
Sorry for the long waiting time. I just tagged 2.5.0
