### ISSUE TITLE
How to catch conversation cache time exceeds

### ISSUE THREAD

**Issue by Kollipso** [botman/botman#1003]
- BotMan Version: 2.#.#
- PHP Version: 7.0
- Messaging Service(s): Telegram
- Cache Driver: File

### Description:
How I can catch the conversation cache time exceed? I want to make it longer when it ends.

### Step to reproduce:
1. Start conversation with 30 min cache time
2. Wait 31 min
3. Answer on a question in conversation
4. Nothing happened in conversation  <-- catch this

**Comment by JABirchall** [comment]
You cant catch it, the only thing you can do is add this to your botman config

```php
'conversation_cache_time' => 30
```

to increase the convo length
