### ISSUE TITLE
How to delete message ?

### ISSUE THREAD

**Issue by nonobott** [botman/botman#1006]
How to delete message which was sent by bot ? 
I have message id, this way: $response=$bot->say('Message', '@MyChannel');

But cant find, how to delete it.

https://core.telegram.org/bots/api#deletemessage  

Thank you!

**Comment by nonobott** [comment]
Answer is: 
                   $apiParameters = [
                   'chat_id' => '@mychannel',
                   'message_id' => '10'
                   ];
                   $bot->sendRequest('deleteMessage', $apiParameters);

Thank's  https://github.com/botman/botman/issues/274#issuecomment-287222236

**Comment by stefandanaita** [comment]
Nice! Please close the issue once you've got it sorted out
