### ISSUE TITLE
Is this package still actively maintained?

### ISSUE THREAD

**Issue by yellow1912** [botman/botman#1008]
I can see lots of questions not being answered on issues in the last few months. Perhaps the owners are just busy or is this package not maintained anymore?

**Comment by isbkch** [comment]
It doesn't seem like it... I've been waiting for them to create a new release from Master for 6 months now... it's seriously 2 clicks, I ended up forking and doing my own thing

**Comment by christophrumpel** [comment]
Hey, BotMan is a project thas grown a lot over the last years. the current version of all drivers are robust and of great help if you want to create chatbots for one or multiple platforms. I have created myself several big applications that are currently live.

So to the question: Is this package still actively maintained?

Marcel answered that today on the Slack chat with a YES. But of course there are lots of issues and todos here and there. The BotMan family itself consists of dozens of repository. The maintaining work is HUGE and Marcel doesn't get any money from it. So it is difficult. I'm helping Marcel where I can but my time is also limited.

Regarding your point @isbkch : From your point, it is just two clicks. But from a maintainer point, it is much more overhead and every new code means more responsibility. But you can talk to me on the Slack team and I can do the release maybe.

I'm not offended by this issue and hope it doesn't sound like that. But everything is much easier when you look from a non-maintainer point of an open-source project.

**Comment by yellow1912** [comment]
I'm interested to help if help is needed. I think in the world of programming a few months feel like years. Things move too fast.

**Comment by isbkch** [comment]
I'd love to help as well.

**Comment by sbassah** [comment]
I'd love to help too

**Comment by christophrumpel** [comment]
Thanks. I know it was not meant to offend but it often comes that way. Always of a problem of open source :-)

Best way everyone can help right now is take a look at issues try to solve them or do PRs.  Thanks
