### ISSUE TITLE
Botman and Laravel-Websockets incompatibility on react/socket version

### ISSUE THREAD

**Issue by stefandanaita** [botman/botman#1009]
- BotMan Version: 2.4.1
- PHP Version: 7.3
- Messaging Service(s): any
- Cache Driver: redis

### Steps To Reproduce: Try to require both and it will gracefully fail 😭

**Comment by JABirchall** [comment]
#1001

**Comment by stefandanaita** [comment]
@christophrumpel is this something you can help with while Marcel is away/not caring about Botman anymore at all? This should be a fairly quick one to fix and would unblock many of us being completely stuck 😭

**Comment by christophrumpel** [comment]
Hey, I can try. Is there already a PR I can look at?

**Comment by stefandanaita** [comment]
Managed to get it working by requiring `v2.0.x-dev`, but this needs to make its way into a proper tag. Running a package like this on a branch is...

**Comment by mpociot** [comment]
I just tagged 2.5.0 - thanks for your patience :)
