### ISSUE TITLE
Get user information before starting conversation

### ISSUE THREAD

**Issue by Edd-G** [botman/botman#1018]
- BotMan Version: 2.4
- PHP Version: 7.2
- Messaging Service(s): web
- Cache Driver: redis

### Description:

How to get user information before starting conversation or any bot answer?

I trying:
`$uid = $botman->getUser()->getId();`
but $uid is empty.

In payload sended to botman userId is present.
I can get userId only from conversation, but i need before.

### Steps To Reproduce:

Starting any interaction whit botman from web-vidget.
Web-vidget send payload contain uiserId:

`------WebKitFormBoundaryqOE7zdgXfVHhPvzM
Content-Disposition: form-data; name="userId"

mngn7w1558546228
`

**Comment by ibes** [comment]
I did that first thing in the conversation. 

What is your goal with getting the user-id?

I caught the user id to check if the user is authentificated in my system. 
So with every conversation start I will check my database if the chat id / user id is already know. If yes - rock on. If no - go through the authentification process. 

It that is close enough to what you need I can share code.

**Comment by Edd-G** [comment]
@ibes in my case, if admin connected to conversation, temporarily mute bot.
Yes, thanks for the offer. Please share example code.

**Comment by ibes** [comment]
I put it in a gist:
https://gist.github.com/ibes/0491698105ad1d6582d2539242465776

This is just my code - cleaned a tiny bit but not really made pretty. 

In the conversation class you see the checkPermission method. 
This will run at the start of this Conversation. 
I guess this could also be put in a Trait (but I am not experienced with that) to have it easier in every Conversation that needs a permission check / other preparation. 

The UserConnect class is my way to handle the connection to our WordPress installation. 
That will likely be completely different for your system. 
But maybe you can figure out how I used the userStorage for caching the information that I need. 
That way I can access that data later + hopefully save execution time. 

Within the Conversation I put my relevant information in a variable too, to easier access it. 

If you have further questions, I will try to help you with that. 

Would be awesome if you want to share you solution in the end. So maybe others can build on that too :)
