### ISSUE TITLE
receivesLocation TelegramDriver

### ISSUE THREAD

**Issue by denx-b** [botman/botman#1019]
botman: 2.5
driver-telegram: 1.5
PHP Version: 7.3.1

```
$botman->receivesLocation(function (BotMan $bot) {
     $bot->reply('123');
});
```
I think it broke. I tried all the options. Maybe the telegram response has changed? When sending a location, there is no 'text' field, and receiveLocation listens on the '%%% _ LOCATION _ %%%' pattern.

Even if you resort to bones and forcefully call up any message when sending from a location telegram, as I understand it, even $curl->post() is not called.

Either I do wrong, or there is a problem. The question is important to me, if there is no answer, I will try to make a pool request.

**Comment by ibes** [comment]
This is the code of the documentation

use BotMan\BotMan\Messages\Attachments\Location;

```
$bot->receivesLocation(function($bot, Location $location) {
    $lat = $location->getLatitude();
    $lng = $location->getLongitude();
});
```
you don't use the second paramenter - that is where the location is handled.
Also maybe you need to add the driver for Telegram-Location handling.

Depending on your setup that could look like this:
DriverManager::loadDriver( \BotMan\Drivers\Telegram\TelegramLocationDriver::class );
