### ISSUE TITLE
Telegram in Russia

### ISSUE THREAD

**Issue by denx-b** [botman/botman#1020]
In Russia, telegram is blocked, to resolve the problem, I use a proxy by adding the following line:
`curl_setopt ($request, CURLOPT_PROXY, TELEGRAM_PROXY);`

This is not very good :)
I have seen some solutions for chat bots insert the optional proxy feature. Maybe this is in botman? Maybe I just did not find?

**Comment by sasha-ch** [comment]
Same trouble. Current hotfix is:
```php
class Curl extends \BotMan\BotMan\Http\Curl
{
    protected function prepareRequest($url, $parameters = [], $headers = [])
    {
        $request = parent::prepareRequest($url, $parameters, $headers);
        curl_setopt($request, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5_HOSTNAME);
        curl_setopt($request, CURLOPT_PROXY, "127.0.0.1:9050");
        return $request;
    }
}
```
Curl has a lot of useful options. 
How do you about add `HttpInterface` object as `BotManFactory::create()` argument? (send PR?)
Or how to pass my own Curl object to Botman/driver gracefully for now?

Related issues are: #677 , #781 , #1016 .
