### ISSUE TITLE
Type indicators do not work inside conversations

### ISSUE THREAD

**Issue by alexandrubau** [botman/botman#1024]
- BotMan Version: 2.4.*
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: Redis

### Description:
Type indicators do not work inside conversations.
Calling `$botman->typesAndWaits();` inside a conversation does not display Typing Indicators and does not throw any errors.

### Steps To Reproduce:

```php
// file1.php
$this->bot->hears('Hello', function () {
  $this->bot->typesAndWaits(1); // this will be displayed
  $this->bot->reply('First');
  $this->bot->startConversation(new HelloConversation());
});

// file2.php
class HelloConversation extends Conversation {
  public function run(){
    $this->getBot()->typesAndWaits(1); // this will NOT be displayed
    $this->say('Second');
  }
}
```

**Comment by Astriel** [comment]
Hello there. I've got the exact same problem. I'm trying to use it on Facebook, but unfortunatly, this is not working at all.
