### ISSUE TITLE
Conversation lost when reload page

### ISSUE THREAD

**Issue by aberaldo** [botman/botman#1029]
Hello, 

ive installed botman web widget. The issue is that when the user reload the page or goes to a nother page inside website, the conversation desapear and it start a new one. 
How can i develop in saving conversation state?. I think it will be with cookies. There is some documentation on how to implement that?

Thanks

**Comment by Edd-G** [comment]
Hi!

I see this way for save conversation state.
1. Store conversation in client side by use local storage.
2. Send the last conversation step to botman in first request to server.
I also want to implement it, but now it is not a priority task.
If you decide this question faster, I will be grateful for your help.

**Comment by aberaldo** [comment]
Edd thanks for the response.
When you Say local storage you referencie this ?

https://botman.io/2.0/storing-information
I don't know how i get the conversation ID once it's created. With that ID i can store in a cookie and then when page is reloaded i can find the file with that ID and retrieve the information.

**Comment by Poojabora** [comment]
How can we store the chat as whenever i reload the page or visits any other page in my website my chat gets removed and I have to start the chat again . I need the chat to stay as it is on page reload . Any help will be appreciated .

**Comment by aberaldo** [comment]
Hello,
what i remember, i did it using cookies. You can store the entire conversation in an cookie and then when reload the page insert the conversation using the api.

**Comment by Poojabora** [comment]
@aberaldo Thanks for your response . will try using cookies

**Comment by ZurabWeb** [comment]
@aberaldo Can you provide more info on reloading the conversation using api ?

**Comment by milad-jfr** [comment]
hey guys anyone who did this before ( save conversation state on client side or save in database ) has any done project to share ?
