### ISSUE TITLE
Question with attachment in conversation with Telegram

### ISSUE THREAD

**Issue by alexshalneff** [botman/botman#1031]
Hello!

First of all - sorry for my English.

So my question is - is there some way to add image to Question or on ask() method?

With code I can send text messages with buttons, but I need to attach the image like OutgoingMessage::create('test')->withAttachment($attachment);

Where on this code I can add Image?

$question = Question::create($testQuestion['text'])->addButtons([
                            Button::create($testQuestion[1])->value('111'),
                            Button::create($testQuestion[2])->value('222'),
                            Button::create($testQuestion[3])->value('333'),
                        ]);

                    $this->ask($question, function (Answer $answer){
                        if ($answer->isInteractiveMessageReply()) {
                              //Logic
                        }
                    });

Thanks!

**Comment by claretnnamocha** [comment]
At this time, there's currently no support for attachments using the Question class.  
Who knows it may come as an update

**Comment by lenniDespero** [comment]
I wrote an implementation of this functionality, but it affects 2 repositories, this one and botman/driver-telegram.
In what order is it best to send pull-requests?
With this functional it will be possible to do like:
`
        $question = Question::create('some text')->addButtons([
            Button::create('1')->value('111'),
            Button::create('2')->value('222'),
        ]);
        $attacment = new Image('pictureUrl');
        $question->withAttachment($attacment);
        $this->ask($question, function (Answer $answer){
            if ($answer->isInteractiveMessageReply()) {
                //Logic
            }
        });
`

**Comment by romansidorov** [comment]
> I wrote an implementation of this functionality, but it affects 2 repositories, this one and botman/driver-telegram. In what order is it best to send pull-requests? With this functional it will be possible to do like:

Hi, have you done the request? Thanks
