### ISSUE TITLE
I want Botman to start the conversation. I want to avoid writing Hi

### ISSUE THREAD

**Issue by vdesh0282** [botman/botman#1034]
I want Botman to start the conversation. I want to avoid writing "Hi". Please let me know How I can achieve that. I am using it on web

**Comment by michaellindahl** [comment]
I assume you are working on a web experience, as most other chat bot experiences require that the user message first to initiate the conversation. In this case, you might want to checkout the [Web Widget](https://github.com/botman/web-widget/). In the demo HTML it has a line of code where `<a href="#" onclick="botmanChatWidget.whisper('give me videos')">whisper</a>`, if you do something similar you can send a message to botman for it to respond without showing it to the user.

**Comment by sasha-ch** [comment]
Other option is `sendWidgetOpenedEvent: 1` in widget config.

**Comment by teevon** [comment]
@sasha-x Please how do I use the sendWidgetOpenedEvent,, a sample snippet would be helpful, the botmanwidget I have only exposes the properties listed here https://botman.io/2.0/web-widget. Wolud really appreciate any help on this

**Comment by Zeeshan-H** [comment]
Hi @michaellindahl Can you show me in details that how can i send the whisper text message in laravel botman code.

**Comment by ENI-Amelie** [comment]
Hi, do you find an issue ? I have the same problem but i didn't use botmanWidget.
