### ISSUE TITLE
Laravel Botman and Dialogflow

### ISSUE THREAD

**Issue by kunybert** [botman/botman#1035]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description: 
Hi, i am a beginner.
i want to develop a chatbot by using laravel, botman an dialogflow but i dont know how connect dialogflow with laravel can please help me someone?

### Steps To Reproduce:

**Comment by tom1097** [comment]
Here is what i made, but still not done yet
```
$dialogflow = ApiAi::create('Your API Client access token')->listenForAction();

// Apply global "received" middleware
$botman->middleware->received($dialogflow);

// Apply matching middleware per hears command
$botman->hears('my_api_action', function (BotMan $bot) {
    // The incoming message matched the "my_api_action" on Dialogflow
    // Retrieve Dialogflow information:
    $extras = $bot->getMessage()->getExtras();
    $apiReply = $extras['fulfillmentMessages'];
    // $apiAction = $extras['apiAction'];
    // $apiIntent = $extras['apiIntent'];
    
    $bot->reply(apiReply);
});
```
And view History tab on DialogFlow: `error`
```  
"webhookStatus": {
    "webhookEnabledForAgent": true,
    "webhookStatus": {
      "code": 9,
      "message": "Webhook call failed. Error: 405 Method Not Allowed."
    }
  },
```
Any hints ? Thank you

**Comment by pritamdanve** [comment]
Any Update?

**Comment by filippotoso** [comment]
Have you tried the documentation example?

https://botman.io/2.0/nlp

tom1097 code is missing the `->middleware($dialogflow);` call on the `hears()` method call
