### ISSUE TITLE
Botman + Dialogfow v2

### ISSUE THREAD

**Issue by rlvillacarlos** [botman/botman#1036]
Hi I am new to botman and I am trying all the samples from the documentation. I stumble upon the nlp integration with dialogflow. If I am not mistaken, the provided example uses dialogflow v1 token. 

When I tried creating my agent in dialogflow, I received a notice telling me that support for dialogflow v1 will cease this year. 

Will the example you provided still work for dialogflow v2 token? If not, is there any way that I can integrate dialogflow v2 with the current version of botman?

**Comment by claretnnamocha** [comment]
the token is the same whether v1 or v2 it does not make any difference

**Comment by atsoares** [comment]
@claretnnamocha Wrong, in v2 dialogflow uses OAuth 2 for Server-Server Applications instead access token like in v1. 

If the only way to integrate is using the token what I have to do once dialogflow v2 doesn't generate tokens anymore?
