### ISSUE TITLE
I can not get location on telegram 

### ISSUE THREAD

**Issue by marctaule** [botman/botman#1040]
- BotMan Version: 2.5.0
- PHP Version: 7.1
- Messaging Service(s): Telegram
- Cache Driver: DoctrineCache

### Description:
I have this code in my LocationConversation.php

```
namespace App\Http\Conversations;

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Log;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Question;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Attachments\Location;

class LocationConversation extends Conversation
{
	public function askLocation(){
		$this->askForLocation('Please send your location', function (Location $location) {
		    Log::info($location);
		});
	}

    public function run(){
        $this->askLocation();
    }
}

```

And in my TelegramBotController.php I have:
```
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\BotMan\Cache\DoctrineCache;

use App\Http\Conversations\LocationConversation;

class TelegramBotController extends Controller
{
    public function handleRequest(){
	    DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
            
        $cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
        
        $botman = BotManFactory::create(config('botman.config'), new DoctrineCache($cacheDriver));
        
        $botman->hears('location', function($bot){	        
	        $bot->startConversation(new LocationConversation());
        });
        $botman->listen();
    }
}
```

But I don't receive the location in my log file...  
If someone know what I'm doing wrong, it will help me so much!
Thanks!

### Steps To Reproduce:

**Comment by ibes** [comment]
Could be, that you need to load the location driver too:

`DriverManager::loadDriver( \BotMan\Drivers\Telegram\TelegramLocationDriver::class );`

**Comment by marctaule** [comment]
I also added this driver but it doesn’t work... when I type “Location” the bot says: “Please send your location”, but that’s all, I can not get lat or lng... :(

**Comment by ibes** [comment]
Did you send your location?
You not just type text (because that is text), you/your user needs to actually share your location. 

Think like: If your friend would want to know where you are, how would you share your location with them? To the same with the bot. 

Does that make sense?
If not, I can share a screenshot.

**Comment by marctaule** [comment]
Ok! I didn’t understand how it worked! I didn’t know that I need to share my location 🤦🏽‍♀️ Now it works!

**Comment by ibes** [comment]
As soon as you get it, it makes perfect sense, right?
Working with Bots is so different from working with HTML - needs a bit to get used to it.

Consider closing the issue :)
