### ISSUE TITLE
Generic Template Question (ask() method) only works for one time

### ISSUE THREAD

**Issue by abdalasif** [botman/botman#1041]
Hello,

I am trying to store a generic Facebook template in a conversation's ask() method. it does work for the first time but it fails to read the payload again on clicking the answer button. below is the code i am using:

```php
$question = GenericTemplate::create()
            ->addImageAspectRatio(GenericTemplate::RATIO_HORIZONTAL)
            ->addElements([
                 Element::create('Example')
                ->subtitle('')
                ->image('image_url')
                ->addButton(ElementButton::create('text here')->type('postback')->payload('eg1')),
                Element::create('Example')
                ->subtitle('')
                ->image('image_url')
                ->addButton(ElementButton::create('text here')->type('postback')->payload('eg2')),
                Element::create('Example')
                ->subtitle('')
                ->image('image_url')
                ->addButton(ElementButton::create('text here')->type('postback')->payload('eg3')),
                Element::create('Example')
                ->subtitle('')
                ->image('image_url')
                ->addButton(ElementButton::create('text here')->type('postback')->payload('eg4'))
            ]);

            $this->ask($question, function (Answer $answer) {
                 if($answer->isInteractiveMessageReply()) {
                    $this->bot->reply($answer->getValue());
                 }
            });
```

**Comment by abdalasif** [comment]
I just noticed that it is the caching issue the generic template question buttons works for few moments if user doesn't reply back in that time the $botman->fallback() function get triggers in response. really confused with this since cahe was working fine before.

**Comment by IljaPHP** [comment]
> I just noticed that it is the caching issue the generic template question buttons works for few moments if user doesn't reply back in that time the $botman->fallback() function get triggers in response. really confused with this since cache was working fine before.

https://github.com/botman/botman/issues/1205 Please, see this. There is a situation similar to yours! Maybe, you will have some idias...
