### ISSUE TITLE
Facebook conversation stop on first ask

### ISSUE THREAD

**Issue by gawielgo** [botman/botman#1042]
Hi everyone,
a few weeks ago all the bots that I had configured and that worked properly on Facebook, have stopped living, or rather occasionally through the botman I can send a couple of say, but the first ask the conversation hangs.

Do you think it's a problem of permissions on the facebook side, of app analysis or what?

Am I the only one who has had such a thing or is it a common evil?

**Comment by abdalasif** [comment]
i am facing the same problem with the conversation where as Facebook is sending the payloads on normal basis.

**Comment by gawielgo** [comment]
Perhaps you need to add some authorization or validation on the page created with the developer; I'm trying that way

**Comment by gawielgo** [comment]
I tried to detail the review of the Facebook app I associated with the bot, but still nothing, no positive results...

**Comment by ibes** [comment]
Have you checked:
- caching
- any errors in the logs
- I heard there might be an issue with Facebook sending "standbye" messages or so - have not figured that out myself.

No solution here - but maybe pointers that help finding something

**Comment by gawielgo** [comment]
I also think it's something related to both the cache and the messages sent by the user redirected by the facebook webhook, as putting me in debug, every time the response of an ask arrives, in addition to the user's message I get two more messages with empty text.

It would be nice to try to understand if we need to manage the middleware side or wait for a facebook fix...

**Comment by gawielgo** [comment]
some time ago I tried to manage with code like:

   ...
       if ($id_msg != "*") {
            if (Cache::has($id_msg)) {
                $already_received = true;
            } else {
                Cache::put($id_msg, $id_msg, 60); 
            }
          
        }
        if ($already_received) die();
   ...

but for some weeks this seems to block the arrival of the message sent by the user against an ask

**Comment by abdalasif** [comment]
There are no errors from Facebook. it's the cache issue i believe. the conversation ask() method only works for one time. if a generic template having multiple items is used in a conversation it won't work second time.
