### ISSUE TITLE
Problems with sharing multiple images

### ISSUE THREAD

**Issue by ibes** [botman/botman#1044]
- BotMan Version: 2.5.0
- PHP Version: 7.2.0
- Messaging Service(s): Facebook and Telegram
- Cache Driver: 
   "cache/filesystem-adapter": "^1.0",
   "symfony/cache": "^4.3",

### Description:
I use Botman without Botman Studio. 

When I 
```PHP
$this->askForImages('Do you want to save images to this post? Than please share now.', function ($images) {
```
 And there are more than one images shared at the same time I get trouble in both Telegram and Facebook Messenger. 

**In Telegram** 
in image works.
with multiple images: 
every image starts it's own conversation. So every future message and interaction is repeated for each image. Like AAA BBB CCC DDD not like ABCD ABCD ABCD

Seems like the Telegram Driver is not capable of collecting multiple images to one array.
What I get are multiple answers with arrays with one element. 

**in Facebook**
One image works. 
with multiple images:
I get the error message:
`[15-Jul-2019 14:19:20 UTC] PHP Fatal error:  Uncaught BotMan\Drivers\Facebook\Exceptions\FacebookException: Error sending payload: (#100) Length of param message[text] must be less than or equal to 2000 in /app/public/vendor/botman/driver-facebook/src/FacebookDriver.php:516
Stack trace:
#0 /app/public/vendor/botman/driver-facebook/src/FacebookDriver.php(411): BotMan\Drivers\Facebook\FacebookDriver->throwExceptionIfResponseNotOk(Object(Symfony\Component\HttpFoundation\Response))
#1 /app/public/vendor/botman/botman/src/BotMan.php(651): BotMan\Drivers\Facebook\FacebookDriver->sendPayload(Array)
#2 [internal function]: BotMan\BotMan\BotMan->BotMan\BotMan\{closure}(Array)
#3 /app/public/vendor/mpociot/pipeline/src/Pipeline.php(114): call_user_func_array(Object(Closure), Array)
#4 [internal function]: Mpociot\Pipeline\Pipeline->Mpociot\Pipeline\{closure}(Array)
#5 /app/public/vendor/mpociot/pipeline/src/Pipeline.php(102): call_user_func_array(Object(Closure), Array)
#6 /app/public/vendor/botman/botman/src/Middleware/MiddlewareManager.php(126): Mpociot\Pipelin in /app/public/vendor/botman/driver-facebook/src/FacebookDriver.php on line 516`

It seems like the Facebook Driver tries to handle the additional images as text and is like "wow, that is too big to handle".

Any ideas what I might miss?

I have a cache installed. I have imported a lot of drivers:
```
DriverManager::loadDriver( \BotMan\Drivers\Telegram\TelegramDriver::class );
DriverManager::loadDriver( \BotMan\Drivers\Telegram\TelegramLocationDriver::class );
DriverManager::loadDriver( \BotMan\Drivers\Telegram\TelegramPhotoDriver::class );
DriverManager::loadDriver( \BotMan\Drivers\Facebook\FacebookDriver::class );
DriverManager::loadDriver( \BotMan\Drivers\Facebook\FacebookLocationDriver::class );
DriverManager::loadDriver( \BotMan\Drivers\Facebook\FacebookImageDriver::class );
```

Also: Any ideas how I could just ignore images that come after the first one?
I can make it a requirement to just post one picture. 
But so far I can not just trash the extra images instead of handling them.

**Comment by Erick2011** [comment]
BotMan Version: 2.5.0
PHP Version: 7.2.0
Messaging Service(s):  Telegram

I got almost the same issue, when i place one image works perfectly, but if they are more than one i just receive the first one content. and the $images array just has 1 element. so idk how should i place the images to get them all on the array.

**Comment by ibes** [comment]
would you be willing to share code?

Actually - if I could manage to just get the first picture and ignore the rest, that would be awesome for my project.

**Comment by Erick2011** [comment]
Hi @ibes sure, i am using botmanStudio

`Steps To Reproduce:
$this->askForImages('😎 pongamosle una imagen o poster a la publicación.', function ($images) {
foreach ($images as $image) {

            $payload = $image->getPayload(); // The original payload
            $this->posterImage = $payload["file_id"];
            $this->say('Ahora si'.$this->posterImage);
        }
    }, function (Answer $answer) {
        $this->say('🤨 ehmmm te pedi una imagen');
        $this->askPosterImage();
    });
`

it seen even if i send multiples images the $image array just catch the first one, idk if its a normal behavior, i think not cuase of the foreach loop there.

how do u reproduce urs?

**Comment by Erick2011** [comment]
@ibes  the whole method here:

``private function askPosterImage()
    {
        $this->askForImages('😎 pongamosle una imagen o poster a la publicación.', function ($images) {
            foreach ($images as $image) {

                $payload = $image->getPayload(); // The original payload
                $this->posterImage = $payload["file_id"];
                $this->say('Ahora si'.$this->posterImage);
            }
        }, function (Answer $answer) {
            $this->say('🤨 ehmmm te pedi una imagen');
            $this->askPosterImage();
        });
    }``

**Comment by ibes** [comment]
I read in another thread that this is not a thing that Botman has to fix. Botman just tries to do the best out of the data it gets from the platforms. 

Telegram seems to send one request per image. 
Facebook seems to collect the images and send them as one request. 

They wrote that there might be a way to fix this with a middleware - I have too little experience to try that + we want that we get just one picture. 

In your example:
Are you sure that you don't get multiple calls.
Looks like you just have 
$this->posterImage
as a string, not as an array. So this will anyway just take one value.

**Comment by Erick2011** [comment]
I think u r rigth, i have debugged and it seems i am getting multiple calls, and i realized that when i start conversation a cache file is created, and the first time the works nicely but since the method is running in a different thread the main code keep running and when it hits the final code the cache file got delete and i got a file not found exception. i am using botmanStudio but idk how to avoid that

**Comment by Erick2011** [comment]
Hi @ibes do u have the post where it says that about the middleware? i am trying to do that about images ans still just getting the first one.

I also realize about a file cache is delete before the whole code is done, and the second call fails because of that, do u have any idea how to fix it?

**Comment by KilledDebtor** [comment]
Hey guys, i'm think receivesImage works fine. Its only AskForImages bug.
