### ISSUE TITLE
parse error botman latest version using composer on shared server php v7.0.33

### ISSUE THREAD

**Issue by inglesuniversal** [botman/botman#1045]
CODE:

`<?php
require($_SERVER["DOCUMENT_ROOT"].'/vendor/autoload.php');

$config = [
    // Your driver-specific configuration
    // "telegram" => [
    //    "token" => "TOKEN"
    // ]
];

DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);

// Create BotMan instance
//BotManFactory::create($config);

// Give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
});

// Start listening
$botman->listen();

?>
<!doctype html>
<html>
<head>
    <title>BotMan Widget</title>
    <meta charset="UTF-8">
</head>
<body>
<a href="#" class="btn" onclick="botmanChatWidget.open();return false;">Try out</a>
<br>
<a href="#" class="btn" onclick="botmanChatWidget.say('Hi');return false;">Try out</a>
<br>
<a href="#" class="btn" onclick="botmanChatWidget.sayAsBot('Hello sir!');return false;">Try out</a>

<script>
var botmanWidget = {
    frameEndpoint: 'iframe.html'    
};

//botmanWidget.say('Hi my friend!');

</script>
<script src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/widget.js'></script>
</body>
</html>`

Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in .../vendor/tightenco/collect/src/Collect/Support/Collection.php on line 179

**Comment by ibes** [comment]
Is `$botman` defined anywhere?
Seems like it is commented out. 

I read the Parse error as:
"I imagine some thing that you handle is of type "collection" (a thing that is used in Laravel - similar but different from Arrays) - the `->` wants to do a thing but this doesn't work. 

Similar to using array operators on strings. 

Could be any of the arrows.
