### ISSUE TITLE
Conversation disappear immediately when respond with text in question object

### ISSUE THREAD

**Issue by magicwarms** [botman/botman#1046]
- BotMan Version: 2.0
- PHP Version: 7.2.19
- Messaging Service(s): Telegram
- Cache Driver: File

### Description:
Hello, guys have it ever happened to you when we used the question object in botman, then we responded with text (typing) should choose the options, and the conversation session immediately disappeared.
anyone can help me, please?

### Steps To Reproduce:
so I tested the question object with typing respond not to choose the options, and then conversation cache immediately disappeared, so I have to repeat the conversation from the beginning.

**Comment by ibes** [comment]
can you share code?

**Comment by magicwarms** [comment]
Hi @ibes, of course, this is my code



```
$question = Question::create('May I help you, '.$username.'?')
        ->callbackId('select_feature')
        ->addButtons([
            Button::create('Search Tutor')->value('search_tutor'),
            Button::create('View my last matching tutor')->value('last_match'),
            Button::create('End Conversation')->value('nothing'),
        ]);
        $this->ask($question, function(Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                if($answer->getValue() == 'search_tutor'){
                	$this->bot->reply('I\'ll only need a minute of your time.');
                	$this->bot->reply('Let me find the best tutor for you!');
                    $this->bot->typesAndWaits(1);
                    $this->bot->userStorage()->save([
                        'use_preferences' => 2,
                    ]);
                    $this->askLevel();
                } else if ($answer->getValue() == 'last_match') {
                    $this->bot->reply('Okay, i will show your last matching tutor. Please give me a seconds.');
                    $this->bot->startConversation(new LastTutorMatchingConversation());
                } else if($answer->getValue() == 'nothing') {
                    $this->bot->reply('Oh, I\'ll leave you to it then.');
                    $this->bot->reply('Goodbye. Have a great day ahead!');
                    $this->bot->hears('nothing', function($bot) {
                        //gak ada reply apa-apa
                    })->stopsConversation();
                }
            } else {
                $this->bot->reply('Please choose an option above! :)');
            }
```

Yeah after that, I testing to respond with type some text, and conversation cache immediately disappeared, so I have to repeat the conversation from the beginning.

is there anything wrong with my code?

**Comment by Erick2011** [comment]
@magicwarms did u find something? i am getting the same issue, the conversation does not persist. once it reachs the last answer the cache file is deleted

**Comment by magicwarms** [comment]
Hi @Erick2011, yeah, I resolved my issue just like this, added `return $this->repeat('blabla);`
