### ISSUE TITLE
Problem responding with status code 22 with my own Driver

### ISSUE THREAD

**Issue by cubouyaka** [botman/botman#1050]
- BotMan Version: 2.0
- PHP Version: 7.2.19

### Description:
Hello everyone, I'm trying to make my own driver and I have some troubles, maybe someone can help me ? :
In my protocol I have to answer with a HTTP status code = 22 but I can not find the proper way to do it ..
I tried to do it in my buildServicePayload like : '$this->replyStatusCode = 22;', I tried also to use 'header("HTTP/1.1 22 OK");' and also 'http_response_code(22)' but at the end I'm always responding with status code 200 ...
Does anyone have an idea ?
Thanks!

**Comment by vdomah** [comment]
Hi, have you sorted out this issue? I have similar task, but I need to respond with 'OK' message, but I can't find how to achieve this. Thanks
