### ISSUE TITLE
askForImages does not support more than one image

### ISSUE THREAD

**Issue by Erick2011** [botman/botman#1054]
BotMan Version: 2.0
PHP Version: 7.2.19
Messaging Service(s): Telegram

Description:  when I use askForImages just work when i attach one image, but when i wanna do multiple images just get one, debugging i found out that $images array just got one element

Steps To Reproduce:
$this->askForImages('😎 pongamosle una imagen o poster a la publicación.', function ($images) {
            foreach ($images as $image) {

                $payload = $image->getPayload(); // The original payload
                $this->posterImage = $payload["file_id"];
                $this->say('Ahora si'.$this->posterImage);
            }
        }, function (Answer $answer) {
            $this->say('🤨 ehmmm te pedi una imagen');
            $this->askPosterImage();
        });

**Comment by valdu02100** [comment]
#1044
