### ISSUE TITLE
How can I send and receive information to the bot from the web view ?

### ISSUE THREAD

**Issue by 04211708AC** [botman/botman#1058]
- BotMan Version: 2.0
- PHP Version: 7.2.9

I would like to know if you can give me an example of sending information from the web view botman and from botman to the web view, I know that the Facebook SDK can be used but little information is coming and when working with botman the syntax changes a lot, I have enabled my web view, but now I want to send information from the web to the bot.

**Comment by sasha-ch** [comment]
Do you mean https://botman.io/2.0/web-widget ?
