### ISSUE TITLE
getText returns value of button instead of text

### ISSUE THREAD

**Issue by larsfoll** [botman/botman#1060]
- BotMan Version: 2.0
- PHP Version: 7.1.3
- Messaging Service(s):
- Cache Driver:

### Description:
When asking a question and creating buttons along with it, after picking an option and trying retrieve the text with getText() of the selected option it always returns the value. Basically getText and getValue return the same.

### Steps To Reproduce:
You can just implement the basic example from the docs.

    $question = Question::create('Do you need a database?')
        ->fallback('Unable to create a new database')
        ->callbackId('create_database')
        ->addButtons([
            Button::create('Of course')->value('yes'),
            Button::create('Hell no!')->value('no'),
        ]);

    $this->ask($question, function (Answer $answer) {
        // Detect if button was clicked:
        if ($answer->isInteractiveMessageReply()) {
            $selectedValue = $answer->getValue(); // will be either 'yes' or 'no'
            $selectedText = $answer->getText(); // will be either 'Of course' or 'Hell no!'
        }
    });

**Comment by chimit** [comment]
Confirm this issue in 2.6.1.

**Comment by smsalert-mobi** [comment]
is this fixed ?  i see that the issue was closed.

**Comment by filippotoso** [comment]
See this https://github.com/botman/botman/issues/1311

In any case, you can set an associative array with value => text pairs and pass it into the callback with "use". Then use it to obtain the text from the value.
