### ISSUE TITLE
how to "sendrequest" without using $botman->hears?

### ISSUE THREAD

**Issue by nyshokk** [botman/botman#1062]
- Messaging Service(s):Telegram

How i can use `$bot->sendRequest(...);`
and not using `$botman->hears(..., function(BotMan $bot)
{
$bot->sendRequest(...)
});`
I need to response on callback api request, i get some id and need to `sendRequest('answer...', $data)`. 
How use `BotMan $bot` without(or outside) hears???

**Comment by metanite** [comment]
use `$botman->say()`
https://botman.io/2.0/sending

**Comment by nyshokk** [comment]
> use `$botman->say()`
> https://botman.io/2.0/sending

I don’t need to send a message, I need to use the api telegram method after the bot hears a message

**Comment by nunomazer** [comment]
@nyshokk did you resolve this?

**Comment by nyshokk** [comment]
@nunomazer Yes i use GuzzleHttp\Client() library for this)

**Comment by poplach** [comment]
Add that method to BotMan.php
`$driver` can be `TelegramDriver::class` or `'Telegram'`.

```
    /**
     * Low-level method to perform driver specific API requests.
     *
     * @param string $endpoint
     * @param string $recipient
     * @param DriverInterface|string $driver
     * @param array $additionalParameters
     * @return Response
     * @throws BotManException
     */
    public function sendCustomRequest(string $endpoint, string $recipient, $driver, $additionalParameters = [])
    {
        if ($driver instanceof DriverInterface) {
            $this->setDriver($driver);
        } elseif (\is_string($driver)) {
            $this->setDriver(DriverManager::loadFromName($driver, $this->config));
        } else {
            throw new BotManException('Unknown driver format');
        }

        $this->message = new IncomingMessage('', $recipient, '');
        $response = $this->sendRequest($endpoint, $additionalParameters);

        return $response;
    }
```
