### ISSUE TITLE
Installer laravel 6

### ISSUE THREAD

**Issue by molbal** [botman/botman#1067]
- BotMan Version: latest
- PHP Version: -
- Messaging Service(s): -
- Cache Driver: -

### Description:
Can you update the isntaller so that the `botman new bot` generates a Laravel 6 based project instead of the current 5.8 one please?

### Steps To Reproduce:
Use this package: https://github.com/botman/installer to create a new chatbot

**Comment by pleone** [comment]
Sadly this project seems to abandoned, no one is answering not even by email ( i tried to contant @mpociot about an invoice issue regardinb his course, but one ever answered ... )

**Comment by pleone** [comment]
Very quick update by @mpociot : new mainters are being contacted. Hopefully we'll see botman working on laravel 6.x ;)

Ref. https://twitter.com/marcelpociot/status/1192867094175637504
