### ISSUE TITLE
Start Conversation in fallback method

### ISSUE THREAD

**Issue by bubunamawu** [botman/botman#1073]
- BotMan Version: 2.5.0
- PHP Version:7.2
- Messaging Service(s): Telegram
- Cache Driver:redis

### Description:
I am trying to start a conversations inside the $botman->fallback call.
I get an 500 response with no message indicating what went wrong when i try this.
If I just send reply with a string however everything works fine.

Is is possible to start a conversation in the callback that is handed to the fallback method and if so how?

**Comment by pjoimedia** [comment]
This is how I've done it (if that is what you mean):

```
$botman->fallback(function($bot) {
     $bot->startConversation(new FallbackConversation);
});
```

**Comment by bubunamawu** [comment]
Thank you.

Sorted it out just as you suggested.

**Comment by legreco** [comment]
How can you get the received message in the fallback call?  (the message that started the fallback conversation?)

**Comment by filippotoso** [comment]
```php
 $this->bot->getMessage()->getText();
```

**Comment by legreco** [comment]
Thank you! @filippotoso
