### ISSUE TITLE
Why when i install botman with composer and load vendor.php i got errors?

### ISSUE THREAD

**Issue by bulgariamitko** [botman/botman#1074]
- BotMan Version: 2.5.0
- PHP Version: 7.2.22
- Messaging Service(s):
- Cache Driver:

### Description:
When i load vendor/autoload.php i got a lot of errors from `tightenco/collect` errors like this one ` no such class: Tightenco\Collect\Support\Traits\Macroable`

### Steps To Reproduce:
Install botman with composer and then load autoload.php. 

I have those packages already installed i dont know if this info is helpful
firebase/php-jwt              v5.0.0 A simple library to encode and decode ...
google/apiclient              v2.4.0 Client library for Google APIs
google/apiclient-services     v0.118 Client library for Google APIs
google/auth                   v1.6.0 Google Auth Library for PHP
guzzlehttp/guzzle             6.3.3  Guzzle is a PHP HTTP client library
guzzlehttp/promises           v1.3.1 Guzzle promises library
guzzlehttp/psr7               1.6.1  PSR-7 message implementation that also...
monolog/monolog               2.0.0  Sends your logs to files, sockets, inb...
phpseclib/phpseclib           2.0.23 PHP Secure Communications Library - Pu...
psr/cache                     1.0.1  Common interface for caching libraries
psr/container                 1.0.0  Common Container Interface (PHP FIG PS...
psr/http-message              1.0.1  Common interface for HTTP messages
psr/log                       1.1.0  Common interface for logging libraries
ralouphie/getallheaders       3.0.3  A polyfill for getallheaders.
stichoza/google-translate-php v4.0.2 Free Google Translate API PHP Package
symfony/cache                 v4.3.5 Symfony Cache component with PSR-6, PS...
symfony/cache-contracts       v1.1.7 Generic abstractions related to caching
symfony/service-contracts     v1.1.7 Generic abstractions related to writin...
symfony/var-exporter          v4.3.5 A blend of var_export() + serialize()

**Comment by eeyon** [comment]
it would seem that composer has not been ran or failed in some way, as the package tightenco/collect is a required package for botman and it does not appear to be installed.
