### ISSUE TITLE
amazon-alexa driver

### ISSUE THREAD

**Issue by benrolfe** [botman/botman#1076]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s): amazon-alexa
- Cache Driver: redis

### Description:
I've successfully got "Botman" working using Tinker, and have installed the `amazon-alexa` driver - however when I run `php artisan botman:list-drivers` the only tick/check is against "web". Is this a known issue?

### Steps To Reproduce:

**Comment by ken717w** [comment]
You may look at `vendor/botman/studio-addons/src/Console/Commands/BotManListDrivers.php`.
In `handle()` and `isDriverInstalled()`, a driver is considered as 'installed' if its corresponding config file exists in your `config` folder.

In your case you can manually create `config/botman/amazon-alexa.php` which returns an empty array.
