### ISSUE TITLE
2019 Oct 23 V1 api will be shutdown

### ISSUE THREAD

**Issue by earlebrown** [botman/botman#1077]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
class ApiAi
protected $apiUrl = 'https://api.api.ai/v1/query?v=20150910';
Needs to be replaced as google will be shutting this down.

**Comment by eeyon** [comment]
This will require migrating from V1 to V2 as V1 sunsets May 31st, 2020.

Migration docs are here: https://dialogflow.com/docs/reference/v1-v2-migration-guide
