### ISSUE TITLE
Send custom parameters to Server

### ISSUE THREAD

**Issue by aberaldo** [botman/botman#1084]
Hello,

how can i send custom parameters to botman conversation. I use web widget. I know that userId can be sent. Can i send another? I try put some like in [https://botman.io/2.0/web-widget#configuration](https://botman.io/2.0/web-widget#configuration) but not work.

Any help?

Thanks

**Comment by luizjr** [comment]
I am having the same difficulty.
I would like to send a parameter and be able to use it to chat from the web widget.
