### ISSUE TITLE
undefined method WebDriver::matczesRequest() 

### ISSUE THREAD

**Issue by dmitrymalys** [botman/botman#1092]
- BotMan Version: 2.5.0
- PHP Version: 7.3
- Messaging Service(s): WebDriver
- Cache Driver: LaravelCache

### Description:
I have an error:

```
Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method BotMan\Drivers\Web\WebDriver::matczesRequest() in file /var/www/html/vendor/botman/botman/src/Drivers/DriverManager.php on line 174
```
I think there is a typo, how can i fix this issue?

When I use my custom driver with `matczesRequest()` I have  the same problem because by default botman check the webdriver

### Steps To Reproduce:

**Comment by feralheart** [comment]
You get this error because of a typo in your code.
Try to use `matchesRequest()`
