### ISSUE TITLE
Telegram doesn't hear images.

### ISSUE THREAD

**Issue by feralheart** [botman/botman#1096]
- BotMan Version: 2.5.0
- PHP Version: 7.2.24
- Messaging Service(s): Telegram
- Cache Driver: Laravel Cache

```
    $botman = $this->botman;
    
    $botman->hears('stop', function(BotMan $bot) {})->skipsConversation();
    
    $botman->receivesImages(function(BotMan $bot, $images) {
        foreach ($images as $image) {
            $url = $image->getUrl();
            $this->interpret($bot, $url, 'IMAGE');
        }
    });
    
   $botman->hears('{something}', function (BotMan $bot, $something) {
            $this->interpret($bot, $something, 'TEXT');
    });

    $botman->listen();
```

In the `interpret()` method I have a `$bot->reply("I have a " . $messageType)`;  where the `$messageType` is the third param of `interpret()`
My problem is, that when I send a text from Telegram it replies me back the "I have a TEXT", but when I send an image I got a HTTP Status 200 in ngrok and next to it nothing happens.
What am I missing?

**Comment by kak2z7702** [comment]
I have the same problem...
