### ISSUE TITLE
Expose botman in ubuntu server

### ISSUE THREAD

**Issue by valdu02100** [botman/botman#1099]
Hello,

I have taken a server with ubuntu 18.04. I use Apache2
I installed Botman and configured laravel.
I have a domain name in HTTPS set up with certbot.
When I execute the command "php artisan serve", I can access the main Botman page. 
However, when I want to access /botman/tinker or access the webhooks for Facebook, I get a 404 error.

I have configured ngrok which allows it to access /botman/tinker....

How do I configure my project to access the tinker and webhooks?

Thank you in advance for your help

Valentin

**Comment by rafaellaurindo** [comment]
Hi, I think it's a possible URL rewriting problem. Which HTTP server are you using?

**Comment by sebaxakerhtc** [comment]
May be it will help you...
https://github.com/sebaxakerhtc/My-Ubuntu-Server/blob/master/botman_install.md
