### ISSUE TITLE
BotMan web-driver button redirect to web page

### ISSUE THREAD

**Issue by PPredrag** [botman/botman#1101]
- BotMan Version: 2.5
- PHP Version:7.2
- Messaging Service(s): 'driver' => 'web'
- Cache Driver:

### Description:
I use a BotMan web driver ('driver' => 'web'). Unfortunately I can't redirect to another web page with the (Button :: create) buttons. 
As I can see it is possible using Facebook drivers:
ButtonTemplate :: create ('Open Webview')
        -> addButton (ElementButton :: create ('Click here')
             -> url (https://myurl.com/webview ')
             -> enableExtensions ()
        );

Is possible to achieve same kind of redirection with web-drivers?
Looking forward for your kind help and reply.

### Steps To Reproduce:

**Comment by christian482** [comment]
i got the same problem

**Comment by Edd-G** [comment]
Hi!
I make it with pass additional parameters and parse on client side.
Like this:

```
$question = Question::create('Choose a convenient way to communicate 👇')
    ->addButtons([
        Button::create('WhatsApp')->value('whatsapp')->image('https://siteurl/img/messenger/whatsapp.svg')->additionalParameters(['css' => 'rate txt', 'url' => 'https://wa.me/79998887766?text='.$WhatsApp_Text, 'conversion' => ['ym_rg' => YM_REQ_PDF]]),
        Button::create('Phone')->value('phone')->image('https://siteurl/img/messenger/phone.svg')->additionalParameters(['css' => 'rate txt']),
    ]);
```
By click on first button user redirects on whatsapp client.

**Comment by stefanerben** [comment]
@Edd-G Hi, I'm new to Botman and especially the web-widget gives me a lot of headaches. Could you please share how you render additional parameters in the front end button? I tried it with additional classes and ended up abusing the text to add data..
I hope you can help a little

**Comment by Edd-G** [comment]
Hi, @stefanerben!
I am using BotMan Vue Tinker component instead of web widget.
https://github.com/botman/vue-tinker-component
Component made with Vuejs.
Here is the example code for handling additional parameters on buttons:
```
<div v-if="message.original.type === 'actions'" class="ChatLog__message__suggestions">
    <div v-for="action in message.original.actions" class="ChatLog__message__suggestions__btn" :class="action.additional.css ? action.additional.css : false"
         @click="performAction(action.text, action.value, action.additional.url ? action.additional.url : false, action.additional.conversion ? action.additional.conversion : false, message.original)">
        <img v-if="action.image_url" :src="action.image_url" :title="action.text" />
        <span>{{ action.text }}</span>
    </div>
</div>
```
and expample handler click on button:
```
methods: {
	performAction(text, value, url, conversion, message) {
		if (url) {
			window.open(url, "_blank");
		}
	}
}
```

**Comment by stefanerben** [comment]
Hi @Edd-G 
havn't used BotMan Vue Tinker until now, I will check it out
Thx!
