### ISSUE TITLE
Botman handle fallback

### ISSUE THREAD

**Issue by valdu02100** [botman/botman#1106]
Hey,
I have a concern about understanding fallback and callback_id.

I'm in a conversation and I want to inform the user when I don't understand the answer and ask the question again so that the conversation can follow. 

How do I do this? 

```
$botman->fallback(function(BotMan $bot) {
    $bot->reply('Sorry, I did not understand these commands. Here is a list of commands I understand: ...');
});
```

Thanks

**Comment by Tidada** [comment]
same problem here
