### ISSUE TITLE
Remove keyboard after sendMessage Telegram

### ISSUE THREAD

**Issue by ExsyDev** [botman/botman#1110]
Hello. 

`$keyboard = Keyboard::create()->type(Keyboard::TYPE_KEYBOARD)
            ->oneTimeKeyboard()
            ->addRow(
               KeyboardButton::create('Send contact')->requestContact()
            )->toArray();`

`$this->ask('Add contact', function (Answer $answer) {
     $this->say('Thanks');
}, $keyboard);`

After custom keyboard not deleting.. Why? I need delete custom keyboard with button Send contact after send message. How I can do it?

**Comment by sinsotec** [comment]
Hello i'm here looking for the same issue, did you solve it?
