### ISSUE TITLE
Allow for typesAndWaits with milliseconds

### ISSUE THREAD

**Issue by roelofr** [botman/botman#1113]
- BotMan Version: 2.5.0
- PHP Version: 7.4.2
- Messaging Service(s): Telegram, Web
- Cache Driver: Redis

### Description:
I noticed the `typesAndWaits` uses the `sleep` method, but this only allows you to sleep whole seconds.

Wouldn't it be better to use `usleep`, so we can sleep for 2.5 seconds, or 0.5 seconds?

I noticed the code moved from the BotMan class to the drivers, but the change woud likely be comparable to this:

```diff
 class BotMan {
     // …
     /**
-     * @param int $seconds Number of seconds to wait
+     * @param float $seconds Number of seconds to wait
      * @return $this
      */
     public function typesAndWaits($seconds)
     {
         $this->getDriver()->types($this->message);
-        sleep($seconds);
+        usleep($seconds * 1000000);
 
         return $this;
     }
     // …
 }
```

Just a suggestion, let me know what you think.

**Comment by feralheart** [comment]
Hi @roelofr ,
Thank you for the request, it would be a nice addition for this project.

**Comment by diegorivas89** [comment]
Hi @feralheart,
I was looking open issues to contribute, and I saw that this issue was resolved by this PR https://github.com/botman/botman/pull/765 Is that right?

**Comment by gavinkalika** [comment]
https://github.com/botman/botman/pull/765 . Already completed. This should be closed, right?
