### ISSUE TITLE
Your site is not available in Russia.

### ISSUE THREAD

**Issue by starcevpro** [botman/botman#1121]
Your site is not available in Russia. =c

![image](https://user-images.githubusercontent.com/24702947/76090426-9cfcc600-5fcc-11ea-9309-b2fbd32a4044.png)

![image](https://user-images.githubusercontent.com/24702947/76090380-83f41500-5fcc-11ea-97c8-fd8fb211a1aa.png)

**Comment by karakhanyans** [comment]
@starcevpro the reason is that botman.io is hosted on DigitalOcean LLC. DigitalOcean is blocked in Russia, as I know because  Telegram is hosted in DigitalOcean, Russia banned the DigitalOcean))
