### ISSUE TITLE
Amazon Alexa - Certification

### ISSUE THREAD

**Issue by 04211708AC** [botman/botman#1122]
- BotMan Version: 2.0
- PHP Version: 7.2 

Hi, I'm trying to certify alexa's ability but it marks errors in my endpoint that I can't correct:

* The skill end-point is not validating the signatures for incoming requests and is accepting requests with an empty signature URL.

* The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL.

* The skill end-point is not validating the signatures for incoming requests and is accepting requests with an invalid signature URL specified.

* The skill end-point is not validating the signatures for incoming requests and is accepting requests when no signature URL headers are specified.

Instead of ngrok I use Heroku. My domain is in Godaddy, it already has SSL certificate. Use Expedited SSL to certify my domain with SSL.

**Comment by feralheart** [comment]
Hi, is there anything between your logs about this?

**Comment by Corlett** [comment]
I'm having the same issue.
