### ISSUE TITLE
State of development...

### ISSUE THREAD

**Issue by larrybeall** [botman/botman#1123]
I know this tends to be a touchy subject, but I am in the midst of planning a feature set for the startup I am working with that depends on a chatbot.  Initially Botman seemed to check all of the boxes for what we are looking for, but now I am starting to get a little concerned.  It does not appear that there has been any meaningful development on the product since the 2.5 release.  Has this project entered a phase of dormancy?

**Comment by richdynamix** [comment]
We have just recently had the same view on this. Whilst upgrading our Laravel project to 7.X we realised we now need to fork 3 Botman packages to allow us to upgrade our app. Currently our app has 3.4 million facebook subscribers and Botman has served us well to this point. We are now working on a major app upgrade that will remove the need for Botman due to these concerns.

**Comment by mpociot** [comment]
Hi @larrybeall  and @richdynamix 

Thank you for reaching out. Indeed, I do no longer have the time it takes to maintain BotMan, as well as the many drivers.
The main problem is that I personally do no longer work with chatbots - which makes ongoing development and innovation almost impossible for me. I tried to get in touch with possible new maintainers over the last year, but it never worked out, unfortunately.

If anyone wants to step up and help me with the maintenance - especially for all the specific drivers - that would be much appreciated. The drivers are actually the part that requires most of the in-depth knowledge and is the most time-consuming.

As you said @richdynamix, I believe that BotMan itself is really stable - but the individual drivers constantly change and I simply can no longer keep up with it. 

I still believe that the BotMan project is the best framework for chatbots that the PHP ecosystem has to offer and it would make me sad to see it "fade away".

**Comment by AntonLugtenburg** [comment]
Thank you very much for you work. I watched your Presentations on Youtube and started using botman for small project. I'm a Newbie, but could it be a solution to use notification channels instead of the driver packages for Botman stay up to date ? They are well maintained...

**Comment by feralheart** [comment]
Hi @larrybeall @richdynamix and @AntonLugtenburg 
I contacted @mpociot about this and I offered him my help in managing and improving the BotMan ecosystem what he gladly accepted :)

**Comment by brentkelly** [comment]
@feralheart @mpociot we (Zeald) have adopted using Botman on a new project. We're using Botman, Botman Studio, and Facebook Driver.

Step 1 for us is upgrading all of these packages to work on Laravel 7 - happy to PR anything that might be useful to the project. We've got a working install of it all running at the moment off forks of each repo.
