### ISSUE TITLE
support for laravel 7

### ISSUE THREAD

**Issue by Aksoom-Hussain** [botman/botman#1127]
- BotMan Version: ^2.5
- PHP Version: 7.2+
- Messaging Service(s):
- Cache Driver:

### Description:

  Problem 1
    - Installation request for botman/botman ^2.5 -> satisfiable by botman/botman[2.5.0].
    - Conclusion: remove symfony/http-foundation v5.0.5
    - Conclusion: don't install symfony/http-foundation v5.0.5
    - botman/botman 2.5.0 requires symfony/http-foundation ^2.8 || ^3.0 || ^4.0 -> satisfiable by symfony/http-foundation[2.8.x-dev, 3.0.x-dev, 3.1.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, 4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.43, v2.8.44, v2.8.45, v2.8.46, v2.8.47, v2.8.48, v2.8.49, v2.8.5, v2.8.50, v2.8.52, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.0-BETA1, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.0-BETA1, v3.1.0-RC1, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.18, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.13, v3.4.14, v3.4.15, v3.4.16, v3.4.17, v3.4.18, v3.4.19, v3.4.2, v3.4.20, v3.4.21, v3.4.22, v3.4.23, v3.4.24, v3.4.25, v3.4.26, v3.4.27, v3.4.28, v3.4.29, v3.4.3, v3.4.30, v3.4.31, v3.4.32, v3.4.33, v3.4.34, v3.4.35, v3.4.36, v3.4.37, v3.4.38, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6].
    - Can only install one of: symfony/http-foundation[2.8.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[3.0.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[3.1.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[3.2.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[3.3.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[3.4.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[4.0.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[4.1.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[4.2.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[4.3.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[4.4.x-dev, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.13, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.14, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.15, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.16, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.17, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.18, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.19, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.20, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.21, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.22, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.23, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.24, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.25, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.26, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.27, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.28, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.29, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.30, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.31, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.32, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.33, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.34, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.35, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.36, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.37, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.38, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.39, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.40, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.41, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.42, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.43, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.44, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.45, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.46, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.47, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.48, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.49, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.50, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.52, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v2.8.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.0.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.1.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.0-RC2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.13, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.14, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.2.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.13, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.14, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.15, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.16, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.17, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.18, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.3.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-BETA3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-BETA4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.0-RC2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.13, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.14, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.15, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.16, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.17, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.18, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.19, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.20, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.21, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.22, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.23, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.24, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.25, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.26, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.27, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.28, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.29, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.30, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.31, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.32, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.33, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.34, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.35, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.36, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.37, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.38, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v3.4.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-BETA3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-BETA4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.0-RC2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.13, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.14, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.15, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.0.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.0-BETA3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.1.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.12, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.2.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.10, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.11, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.6, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.7, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.8, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.3.9, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.0, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.0-BETA1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.0-BETA2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.0-RC1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.1, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.2, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.3, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.4, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.5, v5.0.5].
    - Can only install one of: symfony/http-foundation[v4.4.6, v5.0.5].
    - Installation request for symfony/http-foundation (locked at v5.0.5) -> satisfiable by symfony/http-foundation[v5.0.5].

### Steps To Reproduce:

**Comment by orukaz** [comment]
I am looking also Laravel 7.3 + support ;)

Maybe we should help to write the code.

**Comment by vesper8** [comment]
@mpociot any chance you can please add Laravel 7 compatibility to botman/botman please?

**Comment by aios** [comment]
i think we can make an PR to update that

**Comment by feralheart** [comment]
It's already added in #1117 but @mpociot doesn't tagged it yet.

**Comment by willianmaria** [comment]
I need install in Laravel 7 too.

**Comment by nikitabuida** [comment]
Same issue here. Laravel 7 would be greatly appreciated

**Comment by ekandreas** [comment]
Perhaps this lib already is dead?

**Comment by ara-oforiwa** [comment]
Still having this issue...any ideas to resolving this?

>   Problem 1
    - The requested PHP extension ext-zip * is missing from your system. Install or enable PHP's zip extension.

**Comment by Aksoom-Hussain** [comment]
"repositories": [
{
"type": "vcs",
"url": "https://github.com/botman/botman"
}
]

Then require
"botman/botman": "2.0.x-dev"

Thanks!
I found another way to solve my problem too: composer require botman/driver-web
This way botman/botman is installed and I can use the web driver also.

https://github.com/botman/botman/pull/1117#issuecomment-616577773

**Comment by feralheart** [comment]
Hi all,
The fix will be added in the next release

**Comment by vesper8** [comment]
@feralheart it's been 1 year and 1 day since the last release.. any idea when we can expect the next release? thanks

**Comment by feralheart** [comment]
@vesper8 I spoke with Marcel and he allowed me to help him in this project. So, the next release will be very soon :wink:

**Comment by ekandreas** [comment]
`composer require botman/botman:2.0.x-dev`

**Comment by nikitabuida** [comment]
> `composer require botman/botman:2.0.x-dev`

This doesn't work with certain drivers, like slack, so we need a proper solution.

**Comment by spmsupun** [comment]
Same issue with laravel 9
