### ISSUE TITLE
wit.php does not work because it uses post request instead of get request

### ISSUE THREAD

**Issue by tedselig** [botman/botman#1130]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I get
`"error": "Unsupported post request",
    "code": "bad-request"`
when using the wit.php middleware

### Steps To Reproduce:

connect wit ai middleware and send message and send message

I fixed the issue by change get to post in Wit.php in getResponse function and deleting the 3rd parameter

**Comment by feralheart** [comment]
I merged #1131 what fixes the issue on release

**Comment by feralheart** [comment]
The new version has been released.
