### ISSUE TITLE
2 bots from one laravel project are intersecting between each other

### ISSUE THREAD

**Issue by vdomah** [botman/botman#1132]
- BotMan Version: 2.5
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver: LaravelDriver

### Description:
I got two bots sharing one server and one Laravel project. Their webhooks are two separate urls:
/botrun
/botadmin

But somehow after I  interact with first bot, if I go to the second, I will see the main menu from the first bot there. After I do few actions the second bot starts to give me his own menus and buttons and texts.

Why is it happening? Do they share same cache? And are intersecting by user's telegram id?

### Steps To Reproduce:
Create two bots on one server and project, and set their webhooks to separate urls.

**Comment by vdomah** [comment]
For now I've found solution to use two separate Cache drivers for each bot. For the first I used LaravelCache, and for second DoctrineCache. But still, how can I separate two bots if I want to use only LaravelCache?

**Comment by feralheart** [comment]
Do you use `BotMan/Studio` or are you integraded BotMan manually to your Laravel project?

**Comment by vdomah** [comment]
> Do you use `BotMan/Studio` or are you integraded BotMan manually to your Laravel project?

Manually. I've found the cause of that behavior. It's because of how the cache is stored. Here: https://github.com/botman/botman/blob/2.0/src/Messages/Incoming/IncomingMessage.php#L92
you can see that the cache key is named only after sender and recipient ids. And if users are the same in different bots - for botman it's no difference.

To solve this I extended few botman classes. Here is my botman integration into OctoberCMS as plugin. I've added id_prefix parameter into cache key to differentiate bots:
https://github.com/vdomah/oc-botman-plugin/blob/master/classes/botman/IncomingMessage.php#L94

Here is also important line where I populate id_prefix to every driver I got in botman app:
https://github.com/vdomah/oc-botman-plugin/blob/master/classes/botman/BotManFactory.php#L40

**Comment by feralheart** [comment]
Hi,
Good thinking :)
Can you add a PR with your improvements?

**Comment by carlosclayton** [comment]
Hello there, I solved like that: 

// Facebook Controller
$config = [
            "web" => [
                "matchingData" => [
                    "driver" => "facebook",
                ]
            ],
            "botman" => [
                "conversation_cache_time" => 3600,
                "user_cache_time" => 3600,
            ],
            "facebook" => [
                "token" => env('FACEBOOK_TOKEN'),
                "app_secret" => env('FACEBOOK_APP_SECRET'),
                "verification" => env('FACEBOOK_VERIFICATION')
            ]

        ];

        DriverManager::loadDriver(FacebookDriver::class);
        $botman = BotManFactory::create($config, new LaravelCache());


   // Telegram Controller
       $config = [
            "web" => [
                "matchingData" => [
                    "driver" => "telegram",
                ]
            ],
            "botman" => [
                "conversation_cache_time" => 3600,
                "user_cache_time" => 3600,
            ],
            "telegram" => [
                "token" => env("TELEGRAM_TOKEN")
            ]
        ];

        DriverManager::loadDriver(TelegramDriver::class);
        $botman = BotManFactory::create($config, new LaravelCache());

**Comment by vdomah** [comment]
@carlosclayton that doesn't solve my case because I'm talking about using same driver for different bots.

Created PR. Used bot_id parameter name instead of id_prefix
