### ISSUE TITLE
Telegram button with long sentence

### ISSUE THREAD

**Issue by babaren** [botman/botman#1133]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s): Telegram
- Cache Driver:

### Description:

if the button on telegram contains many words, the other words will become ....  , is there any fix regarding that or workaround like making it bigger or having 2-3 lines on it ? thanks in advance

        $botman->hears('Keyword', function ($bot) {
	$question = Question::create('choices')
	->addButtons([
	(Button::create('type some long sentence here')->value('button1')),
	(Button::create('type some long sentence here')->value('button'2)),
	(Button::create('type some long sentence here')->value('button3')),
	(Button::create('type some long sentence here')->value('button4')),
	(Button::create('type some long sentence here')->value('button5')),
	(Button::create('Back')->value('/return'))
	]);
	$bot->reply($question);
});

![button](https://user-images.githubusercontent.com/16422452/78648011-f4ed5c00-78ed-11ea-9338-afc5ad9f17a8.PNG)

**Comment by feralheart** [comment]
The maximum number of characters in buttons/messages is specified on the messenger service side (in this case in the Telegram Bot API).
The most common workaround for it when you place the button-text in the message and assign it to an emoji. For example

:one:  : type some long sentence here
:two:  : type some long sentence here
:three: : type some long sentence here
[:one:] [:two:] [:three:]
