### ISSUE TITLE
Asynchronous Job inside conversation

### ISSUE THREAD

**Issue by aristotele** [botman/botman#1137]
- BotMan Version: 2.0
- PHP Version: 7.3.12
- Messaging Service(s): Messagebird (Whatsapp Business API)
- Cache Driver: Laravel (using botman studio)

### Description:
Hi, I would like to know if there is a way, inside a conversation, to launch an asynchronous Job (API call to query stuff) after a user input and how to re-hook back into the conversation triggering a method which process job's result and respond to the user.
The fact is: Messagebird after 10-12 second not receving response from the webhook pointing to bot application, re-send the same message thinking it was lost. This cause a bug sometimes because the bot consider the same message as answer for the next question.
Any suggestion would be appreciate even on a different way to tackle the problem.

Many thanks

**Comment by feralheart** [comment]
Hi,
Can I ask why is a 10-15 sec gap in your bot in the middle of a conversation? Did you tried to notify the user about the long wait?
