### ISSUE TITLE
Hi, why my dialogflow webhook does not respond the first time, always after 2nd or 3th time

### ISSUE THREAD

**Issue by jimmyhawkins** [botman/botman#1139]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Steps To Reproduce:

**Comment by feralheart** [comment]
Hi,
Which version of DialogFlow API are you using?
What's your BotMan and PHP version?
What's your Cache Driver?
Is there anything in the logs?

**Comment by jimmyhawkins** [comment]
Hi

I am using dialogflow v2
with a C# Asp.net Core webhook
For requests  am using this:
https://api.dialogflow.com/v1/query?v=20150910
POST
{
"sessionId": "b007140962474d3ac204d01f7fb3448c9e3246f6",​
"lang": "ES",​
"query": "what is my balance"
}

headers:
Authorization: Bearer 'Client Access token'
ContentType: application/json

Every day I ask the first 4 times, always returns the default Response (the  response in the section "Responses"), after that, it goes to webhook and returns the responses I spect.

This is every day, the first 4 times.


Greetings.



________________________________
De: feralheart <notifications@github.com>
Enviado: miércoles, 20 de mayo de 2020 5:43 a. m.
Para: botman/botman <botman@noreply.github.com>
Cc: Jimmy Hawkins <jimmy.hawkins@iisaonline.com>; Author <author@noreply.github.com>
Asunto: Re: [botman/botman] Hi, why my dialogflow webhook does not respond the first time, always after 2nd or 3th time (#1139)


Hi,
Which version of DialogFlow API are you using?
What's your BotMan and PHP version?
What's your Cache Driver?
Is there anything in the logs?

**Comment by feralheart** [comment]
DialogFlow V2 support is not yet included in BotMan, it's in a waiting PR with issue number #1010 
Can you try it with DialogFlow V1?

**Comment by jimmyhawkins** [comment]
Hi

This happens even if I go and try it at the configuration of my agent. I mean I thought the problema was the url am using to make request, but trying directly here happens the same things. In the picture, I ask about "cual es mi saldo" (language: es-ES), my default response is "Tengo dificultad para responder, por favor inténtelo más tarde."

[cid:44a8ccda-e0a2-4c2b-ba07-b3bbd8092c4a]

Default Response.
[cid:4171b5d5-11d0-4b64-bbea-0b27f14cc61b]

After 4 times, returns this "Disculpe, debe iniciar sesión para entonces poder responder a su pregunta", this message is my webhook responding which is fine befause the user is  not in session.
[cid:4776f9d9-107e-4934-9058-964b6a925488]

Greetings.
________________________________
De: Jimmy Hawkins <jimmy.hawkins@iisaonline.com>
Enviado: miércoles, 20 de mayo de 2020 8:26 a. m.
Para: botman/botman <botman@noreply.github.com>; botman/botman <reply@reply.github.com>
Cc: Author <author@noreply.github.com>
Asunto: RE: [botman/botman] Hi, why my dialogflow webhook does not respond the first time, always after 2nd or 3th time (#1139)

Hi

I am using dialogflow v2
with a C# Asp.net Core webhook
For requests  am using this:
https://api.dialogflow.com/v1/query?v=20150910
POST
{
"sessionId": "b007140962474d3ac204d01f7fb3448c9e3246f6",​
"lang": "ES",​
"query": "what is my balance"
}

headers:
Authorization: Bearer 'Client Access token'
ContentType: application/json

Every day I ask the first 4 times, always returns the default Response (the  response in the section "Responses"), after that, it goes to webhook and returns the responses I spect.

This is every day, the first 4 times.


Greetings.



________________________________
De: feralheart <notifications@github.com>
Enviado: miércoles, 20 de mayo de 2020 5:43 a. m.
Para: botman/botman <botman@noreply.github.com>
Cc: Jimmy Hawkins <jimmy.hawkins@iisaonline.com>; Author <author@noreply.github.com>
Asunto: Re: [botman/botman] Hi, why my dialogflow webhook does not respond the first time, always after 2nd or 3th time (#1139)


Hi,
Which version of DialogFlow API are you using?
What's your BotMan and PHP version?
What's your Cache Driver?
Is there anything in the logs?

**Comment by jimmyhawkins** [comment]
Well, every day I init my session at my configuration agent, receive this message.

[cid:aed99477-a1ba-46dc-a7ce-1b269f6b7395]

[cid:940434d1-5260-407c-920b-00474ac4ffc0]


[cid:d369aadb-2130-4a8d-b230-9f3c35b0d649]
Greetings.
________________________________
De: feralheart <notifications@github.com>
Enviado: miércoles, 20 de mayo de 2020 8:48 a. m.
Para: botman/botman <botman@noreply.github.com>
Cc: Jimmy Hawkins <jimmy.hawkins@iisaonline.com>; Author <author@noreply.github.com>
Asunto: Re: [botman/botman] Hi, why my dialogflow webhook does not respond the first time, always after 2nd or 3th time (#1139)


DialogFlow V2 support is not yet included in BotMan, it's in a waiting PR with issue number #1010<https://github.com/botman/botman/pull/1010>
Can you try it with DialogFlow V1?
