### ISSUE TITLE
how to preload converstion based on user id

### ISSUE THREAD

**Issue by karishmaagg21** [botman/botman#1143]
- BotMan Version: 2
- PHP Version: 7.2
- Messaging Service(s): we
- Cache Driver: codeginter

### Description:
I want to maintain a conversation state, such that when a conversation is loaded in a new tab or browser it loads the complete chat and persona can continue chat from where he left off

### Steps To Reproduce:

**Comment by feralheart** [comment]
Hi,
You can do it if you give every user different userId and store it in session/cookie. And when you initialize the bot on that page you give the userId what's stored.

**Comment by karishmaagg21** [comment]
Hi
Appreciate your relly
I tried the state of the conversation is maintained. What i need is to pre
load the chat in the chat window when the page is reloaded. I am not able
to do that.
If you can share the code snippet for this it will be very helpful

**Comment by arch2603** [comment]
I am also looking for a solution for this same issue. That is how to reload a conversation back, when a timer expires or the page is refresh

**Comment by filippotoso** [comment]
Botman doesn't offer this feature out of the box. You have to implement it.

I have a proprietary webchat and driver that save the message in the local storage and recover them on page load.

You should be able to fork the webchat widget and add a similar feature without too much effort.
