### ISSUE TITLE
Error installing botman in existing Laravel 7 project

### ISSUE THREAD

**Issue by ara-oforiwa** [botman/botman#1144]
- BotMan Version: 2.0
- PHP Version: 7.3.11
- Messaging Service(s): Website
- Cache Driver: Web Driver

I have tried fixes way to fix the issue but still not working. Some help please

**Description:**
>>Changed current directory to /Users/o/.composer
Using version ^1.0 for botman/installer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

>>  Problem 1
    - botman/installer 1.0.4 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - botman/installer 1.0.3 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - botman/installer 1.0.2 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - botman/installer 1.0.1 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - botman/installer 1.0.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.
    - Installation request for botman/installer ^1.0 -> satisfiable by botman/installer[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4].

>>Installation failed, deleting ./composer.json.

**Steps To Reproduce:**
I run this on terminal within an existing Laravel 7 project
>>composer global require "botman/installer"

**Comment by feralheart** [comment]
Hi @ara-oforiwa ,
Your problem is that `php-zip` isn't installed on your server. If you have sudo access you can easily fix it with `sudo apt install php-zip` (if your server uses apt as package manager)
Also if you fix it you can't still install BotMan under Laravel7 at the moment because the missmatching dependencies. There is a fix in #1117 for that what will be included in the next patch.

**Comment by ara-oforiwa** [comment]
> Hi @ara-oforiwa ,
> Your problem is that `php-zip` isn't installed on your server. If you have sudo access you can easily fix it with `sudo apt install php-zip` (if your server uses apt as package manager)
> Also if you fix it you can't still install BotMan under Laravel7 at the moment because the missmatching dependencies. There is a fix in #1117 for that what will be included in the next patch.

Sure thanks...but why tag it not botman related when it is? I fixed my php-zip issue and still could not get it to work. Looking forward to the patch release.

**Comment by feralheart** [comment]
The php-zip issue is the part what's not BotMan related, because it's webserver related.
The other issue what I mentioned (what was fixed in #1117 ) is the part what's waiting for release.
What do you mean under "still could not get it to work"? What's the error message?

**Comment by feralheart** [comment]
The new version has been released.
