### ISSUE TITLE
can not send image from unsecure http:// source

### ISSUE THREAD

**Issue by xenDE** [botman/botman#1145]
- BotMan Version: 2.5.0
- PHP Version: 7.3.17
- Messaging Service(s): Telegram
- Cache Driver:

Hi

i have problems with sending a image from a unsecure http source.

works fine:

```
$attachment = new Image('https://www.domain.com/Image.jpg');
$message = OutgoingMessage::create('Text')
	->withAttachment($attachment);
$this->say($message);
```

but this does not work with http:// URLs.

in php-telegram-bot/core its not allowed to send from http too, but i used a workaround with downloading the image first and attach the local file:

```
$image_file = sys_get_temp_dir().'/'.microtime(true).'.jpg';
file_put_contents($image_file, file_get_contents('http://unsecure.com/Image.jpg'));
$result = Longman\TelegramBot\Request::sendPhoto([
    'chat_id' => $telegram_update['message']['chat']['id'],
    'photo'   => $image_file
    ]);
unlink($image_file);
```

But this workaround does not work here, it does not send the text or the image and i have no error in the logs:

```
$image_file = sys_get_temp_dir().'/'.microtime(true).'.jpg';
file_put_contents($image_file, file_get_contents('http://unsecure.com/Image.jpg'));
$attachment = new Image($image_file);
$message = OutgoingMessage::create('Text')
            ->withAttachment($attachment);
$this->say($message);
#unlink($image_file);
```

i even tried

`$attachment = new Image('file://'.$image_file);`

without success.

What i do wrong?

best regards,
daniel

**Comment by xenDE** [comment]
my workaround atm:

use an /Image.php at https://mybot.com/ and cache the image:

```
$data = file_get_contents('http://unsecure.com/image.jpg');
file_put_contents(__DIR__.'/image.jpg',$data,);
header("Location: /image.jpg");
```

**Comment by feralheart** [comment]
You can't send images what's placed at a nonSSL certificated place because it's a defense mechanism against a "man in the middle attack".

Did you checked against 404 errors in your workaround?

**Comment by xenDE** [comment]
Yes, block unsecure is ok.
But allow local files is missing, like in telegrams php bot lib.

the workaround works perfect, no 404s:

```
149.1.2.3 - - [20/May/2020:13:20:43 +0200] "GET /getImage.php?1589973642.7153 HTTP/1.1" 302 5 "-" "TelegramBot (like TwitterBot)"
149.1.2.3 - - [20/May/2020:13:20:43 +0200] "GET /Image.jpg HTTP/1.1" 200 58550 "-" "TelegramBot (like TwitterBot)"
```

**Comment by qodri818** [comment]
Guys, how to solve this?

**Comment by xenDE** [comment]
> Guys, how to solve this?

use https:// and not http://

**Comment by qodri818** [comment]
> > Guys, how to solve this?
> 
> use https:// and not http://

Thx a lot
