### ISSUE TITLE
Missing required parameters to interact with Bot Framework simulator

### ISSUE THREAD

**Issue by awaschick** [botman/botman#131]
Hi, I'm integrating into Microsoft Bot Framework to interact with Skype.  I am using the framework simulator locally to do my development work.  In setting this up, I got as far as receiving a message, but when I would send a reply, it would always respond with:

```
{
	"error": {
		"code": "ServiceError",
		"message": "Cannot read property 'id' of undefined"
	}
}
```

After putting Charles Proxy between my PHP app and the simulator and reviewing the messaging API documentation, I was able to deduce that the reply() function in BotFrameworkDriver.php was sending this:

```
{
     "type": "message",
     "text": "Hello yourself."
}
```

But the simulator would only recognize the reply when it received messages formulated like this:

```
{
  "type": "message",
  "text": "Hello yoursef.",
  "from": {
    "id": "my-bot-handle",
    "name": "My Local Dev Bot"
  },
  "conversation": {
    "id": "f5i68dhi38i4dhgbac"
  }
}
```

When I modified the driver as indicated below, I was able to interact with the simulator correctly.

```
        // begin non-vendor changes waschick@gmail.com 20170112
        // Original code: this seems to be required for all interactions, with the simulator or otherwise 
        // if (strstr($apiURL, 'webchat.botframework')) {
        //     $parameters['from'] = [
        //         'id' => $this->config->get('microsoft_bot_handle'),
        //     ];
        // }
        
        $parameters['from'] = [
            'id' => $this->config->get('microsoft_bot_handle'),
            'name' => $this->config->get('user_friendly_bot_name'),
        ];

        $parameters['conversation'] = [
            'id' => $this->event->get('conversation')['id']
        ];
        
        // end non-vendor changes waschick@gmail.com 20170112

```

What am I missing here?  I am not convinced I found a bug, but I could only get it working by editing the library code.

**Comment by mpociot** [comment]
I have not used the bot simulator to be honest, so I haven't even tried it.
When I tested MS Bot Framework, I either used the integrated web chat on the microsoft development page, or added the bot to my Skype account.

Can you tell me the steps, that are needed to use / install the simulator?

**Comment by awaschick** [comment]
That's interesting, I wonder what will happen when I deploy my bot with my patch applied and register it with the framework.  I'll be finding out soon enough!

FWIW, the simulator is just a local app running natively on your dev machine, you can download it from Microsoft's bot framework's github.  It listens on a random high port, and when you start it up, you supply the url of your bot dev environment along with an app id and password.   The simulator docs claim you can run it without the id and password, but that doesn't seem to work when I set null values in botman config.  It was much happier once I registered my app and got a proper ID value.

Beware, if you are developing using something like Vagrant and you have set up a hosts file entry, the simulator will assume that it's remotely hosted and assume you need to establish a tunnel from the instance back to the simulator even if it's obviously right there on the local machine network.  The way around that is to 1) run the bot directly on localhost, or 2) set up proxying on both the inbound request (reverse-proxy localhost to the url of the bot in the vagrant - I used Charles for this) and outbound (reverse proxy localhost within the vagrant - I set up a simple apache proxy vhost here - back to the vm host's ip address, on the simulator's dynamic port)  It's a pain in the butt, though it works fine and gives a *lot* of insight into the REST API interaction once its up and running.

**Comment by mpociot** [comment]
I'm going to close this issue since I don't think the MS Bot Framework simulator is something that should work out of the box with a more complicated setup like using vagrant, proxies etc.
Feel free to reopen it / another one if you think otherwise.

**Comment by sudden-break** [comment]
Hey I would love to have the Simulator working with botman, that would make it easier to test things locally. As i cannot get the development page working with my dev setup + ngrok, because of a ssl cert requirement that ngrok isn't supporting.

**Comment by mpociot** [comment]
Can you help me with this and work on a pull request for this feature?

**Comment by sudden-break** [comment]
I can try but bare with me I'm pretty new to programming ;-)

**Comment by mpociot** [comment]
@sudden-break do you still want to work on this one? :)

**Comment by alexanikiev** [comment]
I just came across the same issue using botbuilder@^3.13.1 and BotFramework Emulator (V4 PREVIEW)
When using a standard Node sample from https://docs.microsoft.com/en-us/azure/bot-service/nodejs/bot-builder-nodejs-quickstart with ChatConnector I was always getting "400 Bad Request, Cannot read property 'id' of undefined" after sending my message to a bot in the emulator
...
{
  "payload": {
    "body": {
      "error": {
        "code": "ServiceError",
        **"message": "Cannot read property 'id' of undefined"**
      }
    },
    "destination": "service",
    "headers": {
      "content-length": 84,
      "content-type": "application/json"
    },
    "statusCode": 400,
    **"statusMessage": "Bad Request"**
  },
  "type": "response"
}
...
![image](https://user-images.githubusercontent.com/13533583/39640518-0f416568-4f80-11e8-9a5e-7e0a1dda25b7.png)

Thanks for the quick hint from @awaschick I tweaked the resulting "botframework" node_module: <your project folder>/node_modules/lib/bots/ChatConnector.js adding conversation/id to the message body
...
hatConnector.prototype.postMessage = function (msg, lastMsg, cb, method) {
        if (method === void 0) { method = 'POST'; }
        logger.info(address, 'ChatConnector: sending message.');
        this.prepOutgoingMessage(msg);
        var address = msg.address;
        msg['from'] = address.bot;
        msg['recipient'] = address.user;
        delete msg.address;
        if (msg.type === 'message' && !msg.inputHint) {
            msg.inputHint = lastMsg ? 'acceptingInput' : 'ignoringInput';
        }
        var path = '/v3/conversations/' + encodeURIComponent(address.conversation.id) + '/activities';
        if (address.id && address.channelId !== 'skype') {
            path += '/' + encodeURIComponent(address.id);
        }
        **//alex:>>
        /*
        msg['conversation'] = {
            id: address.conversation.id
        };
        */
        //alex:<<**
        var options = {
            method: method,
            url: urlJoin(address.serviceUrl, path),
            body: msg,
            json: true
        };
... 
By the result BotFramework Emulator (V4 PREVIEW) is now able to receive messages send using ChatConnector
![image](https://user-images.githubusercontent.com/13533583/39641037-b1ebb7a4-4f81-11e8-8173-b72b1984dc05.png)

Note: In BotFramework Emulator (V4 PREVIEW) neither MSA AppId nor MS App Password have been specified (they were left blank). Also in the app.js code none of environmental variables such as MicrosoftAppId, MicrosoftAppPassword, BotOpenIdMetadata, AzureWebJobStorage have been passed either (they were left blank). 

Looks like the original message submitted was lacking a correlation to conversation ID due to versions mismatch (V3 botframework and V4 PREVIEW BotFramework Emulator), incompatibility or other reasons. If anyone has more details or adjacent scenarios which may shed some more light here, please chime in

Thank you!

**Comment by holtkamp** [comment]
Also encountered this, it seems the error-message has changed though:

```json
{
  "error": {
    "code": "ServiceError",
    "message": "Cannot read property 'name' of undefined"
  }
}
```

Commenting out this line https://github.com/botman/driver-botframework/blob/9c3fc249f6b66e5f3a548c3bd6cb628772f6862d/src/BotFrameworkDriver.php#L195 made the Bot Framework Emulator work.

**Comment by robinvdvleuten** [comment]
Same here! When I comment out the lines mentioned by @holtkamp, the emulator works as expected.

**Comment by holtkamp** [comment]
As an addition on https://github.com/botman/botman/issues/131#issuecomment-403303898

When using the Bot Framework Emulator, `BotFrameworkDriver::$apiURL` looks something like:

` http://localhost:53550/v3/conversations/<SOME-UUID-INDICATING-USER-ID>%7Clivechat/activities`

Can this issue be re-opened?
