### ISSUE TITLE
Allow adding instantiated drivers to DriverManager

### ISSUE THREAD

**Issue by schmengler** [botman/botman#205]
Currently, you only can add drivers to the `DriverManager` by providing class names and Botman instantiates the driver when it is needed.

The problem is that this forces a constructor signature and makes it impossible to have a driver with additional dependencies (except if we abuse global state with static methods).

Suggestion
---

Make it possible to register drivers not only by class name but also by providing a prepared driver instance

Use case
---

I started to write a test driver that returns the bot reply directly in the HTTP response: https://github.com/magento-hackathon/magebot/blob/master/src/Botman/BotmanWebDriver.php (could be worth integrating in Botman itself)

I am currently using a dirty hack to make this work and output directly in `__destruct()`

A better solution would need access to a `Response` instance, which is not available by default. 

So instead of

    DriverManager::loadDriver(BotmanWebDriver::class);

I would be able to use

    DriverManager::loadDriver(new BotmanWebDriver(Request::createFromGlobals(), $config, new Curl, $response));

Then wherever the driver manager usually instantiates the driver, it checks if the driver is already instantiated and either uses that instance or clones it and sets the current $request, $config and $http parameters to ensure that it is configured correctly (to be decided)

**Comment by mpociot** [comment]
This is not going to happen anytime soon. I'll close this for now.
