### ISSUE TITLE
BotFramework not working on other channels other than Skype & Web Chat (e.g. FB, Telegram, Kik, etc)

### ISSUE THREAD

**Issue by dmainah** [botman/botman#228]
Hi. First: thanks @mpociot for this brillant work on botman! 
I've managed to setup the BotFramework connection and it works with the web chat & skype. But when I setup other channels on BotFramework (telegram, Kik, FB) none of those work. I tried playing around with the BotFramework Driver - taking in some tips posted on older issues (like adding the ('conversation')['id'] to the params being sent back), but still nothing.
Any ideas on what I should try?

**Comment by mpociot** [comment]
Hey,

Thank you! 
I haven't tried any other services through the bot framework myself, since most of them have their own corresponding BotMan driver. 
 So I will try it out and see what I can do

**Comment by dmainah** [comment]
Thanks. The other BotMan drivers do a decent job. I just began playing with BotFramework and was impressed at how many other channels they've got. It's probably easier either writing new BotMan drivers rather than using BotFramework either way. So I'll probably stick with those 😄
