### ISSUE TITLE
Slack integration, DM vs in Channel

### ISSUE THREAD

**Issue by cncshaggy** [botman/botman#365]
- BotMan Version: 1.5.5
- PHP Version: 7.1.4
- Messaging Service(s): Slack

### Question:
Is it possible to have botman react differently to DMs vs being in a channel? I would like to be able to DM the bot for direct interaction, but then also be able to @bot within a channel to interact too. I had started my bot with [Hubot](https://hubot.github.com/docs/scripting/) but Javascript drives me crazy. Anyways, I like how it has two different methods of responding.

From their docs: 
> Since this is a chat bot, the most common interactions are based on messages. Hubot can hear messages > said in a room or respond to messages directly addressed at it.
```
module.exports = (robot) ->
  robot.hear /badger/i, (res) ->
    # your code here

  robot.respond /open the pod bay doors/i, (res) ->
    # your code here
```
### Steps To Reproduce:
For example, if I DM my bot in slack, with "hi", it responds with "hello"

If I am in a different channel, which the bot is also in, and a different user comes on, and I say "hi" to them, the bot replies too.

**Comment by mpociot** [comment]
Okay, so you want to restrict the bot to only listen to either `@botname` mentions or DMs but not inside public channels?

**Comment by cncshaggy** [comment]
I think so, yes.

For example:
I have it listening for "tool ([0-9]+)" and I'm in a public channel and say to a co-worker, "is tool 6 is broken?" it will match and answer "tool 6 is blah blah blah"

I still want to be able to ask the bot, "@bot what is tool 6" and have it match and the bot answer.

I also want to DM the bot "what is tool 6" and get the same answer.

**Comment by cncshaggy** [comment]
BTW, I am using `resolve('botman')` in the routes file and mapping the `hear` to `Class@method` to use the RTM

**Comment by suushiemaniac** [comment]
I desperately need this. I've just spent ~6 weeks into developing a fully-fledged chat bot backed by API.AI NLP to help our economy department get done with smaller IT tasks. Basically a "min JARVIS" tailored towards our company's needs.
While everything had always been fine, upon launching at production I immediately realised the bot is useless because it spams every Slack channel we communicate on with the fallback message, because only `hears()` messages can be restricted to DM but the fallback can not :(

**Comment by mpociot** [comment]
@suushiemaniac you can restrict it:

```php
$botman->fallback(function ($bot) {
    /*
     * If the Slack channel starts with a "D" it's a direct message,
     * if it starts with a "C" it is a public channel.
     */
    $channel = $bot->getMessage()->getRecipient();
    if ($channel[0] === 'D') {
        // Reply here
    }
});
```

**Comment by suushiemaniac** [comment]
Woohoo, I didn't know that. Thanks a lot! :hugs:

**Comment by suushiemaniac** [comment]
However, upon further thinking this leads to a whole new issue… I will open an own thread for it

**Comment by hskrasek** [comment]
I feel like this question got asked here in combo with a few other questions, but @mpociot is it possible to restrict the bot hears to when it gets mentioned in a channel? For example in slack if I go `@botname how's it going` it will reply, but if I just do `how's it going` it wont reply

**Comment by dFayet** [comment]
Yes you can, you just need to know the bot user id, and you can do the following 
```
// You write "@botname how's it going"
$botman->hears('<@U60GR82A2> how's it going', function(Botman $bot) {
    // Your code here
});
```

**Comment by hskrasek** [comment]
@dFayet Gotcha, I had a feeling that was the case but honestly I was overthinking it in not wanting to hardcode the bots user id into the "hears" pattern. But sine this is just a for fun side project.. hard coding away! Thank you

**Comment by henkealg** [comment]
@dFayet @mpociot 
Hi guys,
Using the Realtime API (SlackRTMDriver) based on the documentation over at https://botman.io/2.0/driver-slack

Is there a simple way to get the bot user_id after initializing $loop->run() to be able to use it as in @dFayet ´s example?
Thanks!

**Comment by mpociot** [comment]
@henkealg Hi!
I just added support for this and tagged a new release (2.1.1):
https://github.com/botman/driver-slack/releases/tag/2.1.1

You can use this like this:

```php
$botUserId = $botman->getDriver()->getBotUserId();
```

**Comment by jamesez** [comment]
Kindly asking this be added to the Events driver as well, if possible.

**Comment by robertodormepoco** [comment]
@mpociot getBotUserId (both RTM and non RTM) has no return

**Comment by henkealg** [comment]
@robertodormepoco using release 2.1.1 I have no problem getting the bot Id by invoking
$botman->getDriver()->getBotUserId() from within $botman->receivesImages()

**Comment by robertodormepoco** [comment]
Sorry, i was looking at 2.1.2, though the issue holds with the latest commit [https://github.com/botman/driver-slack/blob/2.1.2/src/SlackDriver.php#L408](here)

**Comment by Thanh-DoiKhac** [comment]
I'm using 2.1.3 and direct add to routes/botman.php but this seem like don't work.

```
$botman->hears('Doi', function ($bot) {
            $botUserId = $botman->getDriver()->getBotUserId();
            $bot->reply($botUserId);
        });
```
