### ISSUE TITLE
Update method userStorage / channelStorage / driverStorage

### ISSUE THREAD

**Issue by davaxi** [botman/botman#373]
Hi,

Currently methods `userStorage`, `channelStorage` and `driverStorage` not accept any params. Can we update package to accept optionaly user / channel and drive ?

In use case:

```php
$bot->hears('Save my birth date {date}', function($bot, $date) {
   $bot->userStorage()->save([ 'birthDate' => $date]);
   $bot->reply('Your birth date saved');
});
$bot->hears('Get birth date of {userReference}', function($bot, $userReference) {
  $user = $botman->getUser($userRefence); // Method to return User from userReference
  $date = $bot->userStorage($user)->get('birthDate');
  $bot->reply(sprintf('Birth date of %s is %s', $userReference, $date));
});
```

Thanks

**Comment by mpociot** [comment]
Yeah, the new parameter should probably just replace the default key: https://github.com/mpociot/botman/blob/master/src/Traits/ProvidesStorage.php#L16

**Comment by davaxi** [comment]
I propose this case:

```php
/**
     * @return Storage
     */
    public function userStorage($sender = null)
    {
        if (is_null($sender)) {
              $sender = $this->getMessage()->getSender();
        }
       $storageProvider = $this->getStoragePovider();
        return $storageProvider
            ->setPrefix('user_')
            ->setDefaultKey($sender);
    }
```

It's a shame too that we can not put his own storage manager because `Storag`e is still used today. And so currently it is not possible, for example, to store the data in file mode whose path would be: `/specified/directory/{driverName}/user/{userId}-token.json`

**Comment by mpociot** [comment]
To store the files in a different directory structure, you could just create your own Storage driver and pass it to the factory.

**Comment by davaxi** [comment]
@mpociot is not possible because Storage doesn't now prefix and default key. Primary storage provider passed only generated key (hash).

**Comment by mpociot** [comment]
I'll look into this in the next major BotMan version.
