### ISSUE TITLE
Not able to start with botman

### ISSUE THREAD

**Issue by ruchitFirstAI** [botman/botman#396]
Hello Team,
Recently I install botman through composer in my fresh laravel application and followed all the steps, but didn't get where to start and from where I have to check the starting point of botman.
I mean from where I have to execute the command, need to create any specific view/blade?
At present, I am executing " php artisan botman:tinker"
but its shows  "?[KYou: "

What's wrong with the app, I didn't get.

Thanks,

**Comment by mpociot** [comment]
Which project did you use to start with BotMan? The Laravel start project?

BotMan does not come with any views / user interface. You only need to provide your bot with the logic of how to interact with incoming messages and how to reply to them.

If you use the Laravel starter project, there is a `routes/botman.php` file that contains a few example commands that your bot can "listen" to.

**Comment by ruchitFirstAI** [comment]
Yea I already followed laravel starter project, and I execute "php artisan botman: tinker", but its shows "?[Kyou:"
and I already referred botman.php routes but I didn't understand from where can I execute those commands?

Thanks,

**Comment by xmodulus** [comment]
It might have something to do with [this issue](https://github.com/symfony/symfony/issues/4974).  I wasn't able to run `botman:tinker` on my local windows machine, but it runs fine on my remote ubuntu machine. If  `botman:tinker` gives that problem, it might still be working, just that `botman:tinker` isn't. Try setting up a webhook to fb or telegram and using that to test your bot.
