### ISSUE TITLE
Wit Ai integration

### ISSUE THREAD

**Issue by icemanTopGun** [botman/botman#413]
Hi Marcel,

I hope you are well. I stumbled upon your framework as I am a new developer trying to build a chatbot through PHP. I was successful in connecting to FB and through the PHP framework, however I really want to leverage the WIT ai service to parse the messages coming from the user. I am trying to understand the code - middleware and read the documentation you have provided but I was wondering if there are any actual examples available for me to look at - i.e. how to pass, how to extract entities/intent, and how to call a story in wit. 

Thanks,

- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Steps To Reproduce:

**Comment by xmodulus** [comment]
Hi there, you can actually look through the middleware/wit.php file to check out how it works. From my understanding using `$bot->hears()` with your middleware listens to the intent that the wit.ai API returns. So best is to create a set of `$bot->hears('your_wit_ai_intent')` and instead teach the wit.ai NLP to return `your_wit_ai_intent` for that particular intent. E.g. I want "start conversation", "begin conversation", "start convo", etc to return `your_wit_ai_intent`.
