### ISSUE TITLE
Create Driver for CLI interface

### ISSUE THREAD

**Issue by davaxi** [botman/botman#419]
Hello,

It is currently difficult to test in a local environment. I propose to integrate a driver into CLI, potentially using the mini-framework CLImate.

What do you think ?

**Comment by mpociot** [comment]
There is already a "tinker" project that is exactly what you need. A CLI driver to interact with your chatbot.

https://github.com/botman/tinker

It requires Laravel in the background, because you need to somehow load the available BotMan commands prior to launching the CLI driver.

**Comment by davaxi** [comment]
Great :+1: 
Thanks :)
