### ISSUE TITLE
askForImages callback is not fired 

### ISSUE THREAD

**Issue by gterras** [botman/botman#428]
Hi, 

And thank you for your very nice lib. 

I have trouble using the askForImages callback :

     use Mpociot\BotMan\Answer;
     use Mpociot\BotMan\Button;
     use Mpociot\BotMan\Conversation;
     use Mpociot\BotMan\Question;
     use Mpociot\BotMan\Message;

    public function askScreenshot() {
      $this->askForImages('Please upload an image.', function ($images) { 
        $this->say('ok');
      });

Here "ok" is never said when an image is uploaded. The function is called though because of the "Please upload an image." fired when I do/say something else than an image. 

Do you have any idea of what's going on ? 

Thank you 
Botman latest master + slack driver

**Comment by mpociot** [comment]
Do you have a cache driver in use?

**Comment by gterras** [comment]
Thank you for your answer. I've just tried with the ApcCache and a new behavior takes places : "Please upload an image" is now triggered whether I upload an image or type gibberish text. 

Is this normal behavior ? I see the `askForImages` function has a `$repeat = null` parameter, does it mean it repeats indefinitely or never ?

**Comment by mpociot** [comment]
The `askForImages` methods should repeat the given text unless you upload an image. Then it should jump into the conversation.
The `$repeat` parameter can be used to modify the text that get's repeated.

**Comment by gterras** [comment]
Ok so ApcCache and ApcuCache keep looping (they are correctly setup on the server), I've tried PhpFileCache as suggested in other posts but get a 500 error : 

    local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method App\Conversations\OpenTicket::__set_state()

The generated cache file contains this code  : 

    <?php return array (
    'lifetime' => 1497372020,
    'data' => 
    array (
      'conversation' => 
      App\Conversations\OpenTicket::__set_state(array(
         'bot' => 
        Mpociot\BotMan\BotMan::__set_state(array(
        ...

So the error is triggered because my class OpenTicket does not contain the `__set_state` method. Do I miss an include ? 
Sorry to bother with my lame struggles :(

**Comment by mpociot** [comment]
Ahh I think the event based Slack integration does not allow you to receive incoming files. So you would need to switch to the RTM API instead!

**Comment by gterras** [comment]
Thank you I'm gonna try this !

**Comment by gterras** [comment]
Hi, 
I'm experiencing some really heavy performance/reliability issues with the RTM API as long as I do more than a simple `$bot-reply()` (which works flawlessly).

Just using the simple exampleConversation of your Laravel bundle I get random results every time : 

    public function askReason()
        {
            $question = Question::create("Huh - you woke me up. What do you need?")
                ->fallback('Unable to ask question')
                ->callbackId('ask_reason')
                ->addButtons([
                    Button::create('Tell a joke')->value('joke'),
                    Button::create('Give me a fancy quote')->value('quote'),
                ]);
    
            return $this->ask($question, function (Answer $answer) {
                if ($answer->isInteractiveMessageReply()) {
                    if ($answer->getValue() === 'joke') {
                        $joke = json_decode(file_get_contents('http://api.icndb.com/jokes/random'));
                        $this->say($joke->value->joke);
                    } else {
                        $this->say(Inspiring::quote());
                    }
                }
                else {
                    $this->say('This gets fired about 50% of the time');
                }
            });
        }    

Notice the last line I added. Apart from this I get random errors (500, 502, Failure when receiving data from the peer, Timeout was reached). I need to click several times on any button before the loading spinner next to the button appears.  All in all I'm not sure I got the correct result once. 

Is this something expected ? 

Tested with several desktop and web Slack clients. 

Thank you.

**Comment by mpociot** [comment]
How are you testing your bot? Slack has a time limit, where your application needs to reply. So if you're testing this using ngrok locally (and have a slow connection or long roundtrip to the ngrok server location) this might take pretty long.

**Comment by gterras** [comment]
Yes I'm using localtunnel which is a clone of ngrok (on a great speed network), but : 

-  Never experienced this in days of testing with standard API 
- Simple methods (`say()`) are instant and flawless 
- Timeout error are thrown in a couple of seconds, just as fast as other errors 
- Last line of posted code above send to the bot immediately after query. 

I'm gonna try to test all of this on a real server and tell you how it goes.

**Comment by gterras** [comment]
Ok so on a regular server I got rid of the inconsistencies, but not in a working way :

- `say()`method still works flawlessly. 
- `Question` class works for creating the buttons BUT not intercepting answers, using your conversation example this part is never called : 

        return $this->ask($question, function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                if ($answer->getValue() === 'joke') {
                $this->say('this is never called');
                } else {
                $this->say('this is never called');
                }
            }
            else {
                $this->say('this is never called');
            }
        });  

I worked flawlessly with the traditional API. Do you know if this is normal ?

**Comment by mpociot** [comment]
Okay, can you tell me which Slack integration you're now using exactly?
Since Slack offers quite a lot of different ways to add and connect your bot to it, this can get a bit confusing :)

This might also be an issue with the current master branch, because I am still working on the 2.0 version and did a LOT of refactoring over the last couple of days.
So another option would be to try this with the stable 1.5 version.

**Comment by gterras** [comment]
Hi and sorry for the delay ! I'm using this code to start the RTM API (with botman 1.5) : 

    $loop = Factory::create();
    $botman = BotManFactory::createForRTM([
        'slack_token' => 'xxxxxxxxxxx'
    ], $loop);
    
    $botman->hears('hey', function($bot) {
        $bot->reply('I heard you! :)');
    });
    
    $botman->hears('convo', function($bot) {
    	  $bot->startConversation(new ExampleConversation());
    });
    
    $loop->run();

and then `php bot.php` to start it. Note that the "hey" keyword always works nice, but the "convo" keyword leads to the example posted above and inactive buttons (no spinner, nothing sent). My bot is subscribed to all necessary message events.

Thanks a lot for taking some time.

**Comment by gterras** [comment]
Hi, me again sorry :/ 

Still no reaction from botman after a file is shared. 

I noticed a POST request is still sent to my app whenever an image is uploaded to the bot. The request looks perfectly filled : 

    {
        "token": "xxxx",
        "team_id": "xxxx",
        "api_app_id": "xxxx",
        "event": {
            "type": "message",
            "subtype": "file_share",
            "text": "<xxxx> uploaded a file: <https://xxxx/files/xxxx/xxxx.jpg>",
            "file": {
                "id": "xxxx",
                "created": 1498481246,
                "timestamp": 1498481246,
                "name": "xxxx.jpg",
                "title": "xxxx.jpg",
                "mimetype": "image/jpeg",
                "filetype": "jpg",
                "pretty_type": "JPEG",
                "user": "xxxx",
                "editable": false,
                "size": 13611,
                "mode": "hosted",
                "is_external": false,
                "external_type": "",
                "is_public": false,
                "public_url_shared": false,
                "display_as_bot": false,
                "username": "",
                "url_private": "https://files.slack.com/files-pri/xxxx.jpg",
                "url_private_download": "https://files.slack.com/files-pri/xxxx.jpg",
                "thumb_64": "https://files.slack.com/files-tmb/xxxx/xxxx.jpg",
                "thumb_80": "https://files.slack.com/files-tmb/xxxx/xxxx.jpg",
                "thumb_360": "https://files.slack.com/files-tmb/xxxx/xxxx.jpg",
                "thumb_360_w": 167,
                "thumb_360_h": 230,
                "thumb_160": "https://files.slack.com/files-tmb/xxxx/xxxx.jpg",
                "image_exif_rotation": 1,
                "original_w": 167,
                "original_h": 230,
                "permalink": "https://tradelabglobal.slack.com/files/xxxx/xxxx/xxxx.jpg",
                "permalink_public": "https://slack-files.com/xxxx",
                "channels": [],
                "groups": [],
                "ims": [],
                "comments_count": 0
            },
            "user": "xxxx",
            "upload": true,
            "display_as_bot": false,
            "username": "xxxx",
            "bot_id": null,
            "ts": "1498481247.213146",
            "channel": "xxxx",
            "event_ts": "1498481247.213146"
        },
        "type": "event_callback",
        "authed_users": [
            "xxxx"
        ],
        "event_id": "xxxx",
        "event_time": 1498481247
    }    


Is there any reason why the upload image callback wouldn't work ?

**Comment by mpociot** [comment]
The image upload problem is now fixed in Slack driver version 1.1.1
