### ISSUE TITLE
No response from bot on Facebook messenger

### ISSUE THREAD

**Issue by vivis93** [botman/botman#430]
- BotMan Version: 1.5.7
- PHP Version: 5.6.21
- Messaging Service(s): Facebook
- Xampp: 3.2.2
- Ngrok: 2.2.4

### Description:
Im using ngrok for the webhooks, token is verified from facebook. At http://localhost:4040 there no error.

**# The bot doesn't respond when i type.** 

```
{
    "object": "page",
    "entry": [
        {
            "id": "XXXXX",
            "time": 1497463255777,
            "messaging": [
                {
                    "sender": {
                        "id": "XXXXX"
                    },
                    "recipient": {
                        "id": "XXXXX"
                    },
                    "timestamp": 1497463255657,
                    "message": {
                        "mid": "mid.$cAAW3fUnqruFi2Qk6aVcp8Pulbc7o",
                        "seq": 529,
                        "text": "hello"
                    }
                }
            ]
        }
    ]
}
```

**The code i used i got from [doc](https://botman.io/1.5/installation) and [video](https://www.youtube.com/watch?v=ll-QC9h9KxE&t=409s)**
```
<?php

require __DIR__.'/vendor/autoload.php';
use Mpociot\BotMan\BotManFactory;
use Mpociot\BotMan\BotMan;

$config = [
    'hipchat_urls' => [
        'YOUR-INTEGRATION-URL-1',
        'YOUR-INTEGRATION-URL-2',
    ],
    'nexmo_key' => 'YOUR-NEXMO-APP-KEY',
    'nexmo_secret' => 'YOUR-NEXMO-APP-SECRET',
    'microsoft_bot_handle' => 'YOUR-MICROSOFT-BOT-HANDLE',
    'microsoft_app_id' => 'YOUR-MICROSOFT-APP-ID',
    'microsoft_app_key' => 'YOUR-MICROSOFT-APP-KEY',
    'slack_token' => 'YOUR-SLACK-TOKEN-HERE',
    'telegram_token' => 'YOUR-TELEGRAM-TOKEN-HERE',
    'facebook_token' => 'XXXXXXX',
    'facebook_app_secret' => 'XXXXXX',
    'wechat_app_id' => 'YOUR-WECHAT-APP-ID',
    'wechat_app_key' => 'YOUR-WECHAT-APP-KEY',
];

// create an instance
$botman = BotManFactory::create($config);

// In your BotMan controller
$botman->verifyServices('XXXXX');

// give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
});

// start listening
$botman->listen();
```

**Comment by mpociot** [comment]
Do you see the incoming request from Facebook?
Are you the Facebook page administrator?
Do you use HTTPS for the webhook URL?
Sometimes it helps to close and reopen the Facebook messenger chat. 
Facebook behaves a bit weird in some cases :)

**Comment by vivis93** [comment]
Everything you asked is already checked and everything is right, but still no response :'(

**Comment by mpociot** [comment]
Do you see the incoming request in ngrok? What's the response code?

**Comment by vivis93** [comment]
![2](https://user-images.githubusercontent.com/15004546/27155513-8b4c8e60-5159-11e7-8ae8-13ff3322b967.png)
![1](https://user-images.githubusercontent.com/15004546/27155514-8b546248-5159-11e7-938c-a81524fb2d90.png)

**Comment by mpociot** [comment]
Can you try logging something inside the "hears" closure, just to see if it jumps into the callback method?
Is the response empty? Can you see any additional response data?
It all looks good to me

**Comment by bipeen** [comment]
I am using live hosting instead of ngork, still not getting any response. what shall be verifyServices use in my case?

**Comment by mpociot** [comment]
verifyServices is used to respond with the Facebook security token, that you define when adding the webhook on Facebook.
