### ISSUE TITLE
[Question]Any way to detect Telegram client used?

### ISSUE THREAD

**Issue by blankster** [botman/botman#431]
- BotMan Version: 1.5.6
- PHP Version: 7.0.9
- Messaging Service(s): Telegram
- Cache Driver: Doctrine

Description: Is there any way to detect the Telegram client used? That would be very beneficial, as for example a Telegram location request is only possible (as far as I know) with the Telegram App and the Mail client. I try to optimize my UX in the direction where every interaction counts. As Work around I built some fix points (Home, Office) where I'm usually using a Desktop client but if detection is possible, I could further optimize the workflow(s) and always send the location request on Mobile and never on Desktop/Win.

Further reference: https://stackoverflow.com/questions/33836698/how-to-send-position-using-telegram-desktop

**Comment by mpociot** [comment]
If the Telegram API offers some call to determine the user client, you can just call it. I don't think this has something to do with BotMan itself.
