### ISSUE TITLE
Add Auth to RedisCache

### ISSUE THREAD

**Issue by flavioheleno** [botman/botman#432]
- BotMan Version: 1.5
- PHP Version: any
- Messaging Service(s): any
- Cache Driver: RedisCache

### Description:
I added support for Auth on RedisCache, but to make the tests work, it would require:

1) To have a Redis instance that requires password running side by side with a Redis instance that does not require password (in CI)

Or

2) To make the current Redis instance require password and then test if it fails with the wrong password.

I personally think that, albeit being more complex, option 1 is more complete than option 2.

### Steps To Reproduce:

Setup your bot to use RedisCache and connect to a server that requires authentication (password).

**Comment by mpociot** [comment]
Can you provide a pr for this? I'm also for option 1 :)

**Comment by flavioheleno** [comment]
Done :-)

I've checked around how to do option 1 and it seems that this is the solution: https://stackoverflow.com/questions/27297703/running-redis-on-travis-ci

If you are ok with it - and of course, if I can do it myself -, I'm happy to update travis.yml to include a new redis server with password and include the tests on my PR.
