### ISSUE TITLE
Missing Telegram events such "new_chat_member" and "left_chat_member"

### ISSUE THREAD

**Issue by Emulator000** [botman/botman#433]
- BotMan Version: @stable
- PHP Version: 5.6
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
Is not possible to hear an event with BotMan and extending with a Driver is not sufficient. An extended version of BotMan class is needed to achieve this but is not possible due to private functions.

**Comment by mpociot** [comment]
Upcoming master/2.0 version will have support for this.
