### ISSUE TITLE
Update react/socket version dependency

### ISSUE THREAD

**Issue by Nessworthy** [botman/botman#434]
- BotMan Version: dev-master (82eed9adebe431af246226c17c22afe9f0bf0661)
- PHP Version: 7.1.x
- Messaging Service(s): -
- Cache Driver: -

### Description:
Can't install `react/http-client` at `0.5.x` because the minimum dependency version for `react/socket` is `0.7.0`, while botman is on `0.4.x`

Temp solution is to `require react/http-client:*`, which installs the client at `0.4.17`

### Steps To Reproduce:

```
composer require mcpociot/botman
composer require react/http-client:^0.5
```

Are there any major BC breaks between socket updates? Wouldn't mind having a crack at this myself.

**Comment by mpociot** [comment]
The reason why it's stuck on 0.4.x is because of the RTM Slack Client: https://github.com/mpociot/slack-client

If we can update the slack client to the latest socket version, we're good to update it here too. 
Do you want to try this?

**Comment by Nessworthy** [comment]
\o/ Happy to try!

**Comment by mpociot** [comment]
Cloying this issue then :)
