### ISSUE TITLE
typesAndWait in conversations

### ISSUE THREAD

**Issue by Hirvesh** [botman/botman#435]
While using typesAndWait in conversations, I'm getting an error "Call to undefined method" typesAndWait.

Is the method not defined for conversations?

**Comment by christophrumpel** [comment]
Hey, yeah this should work too. Which version area you on and how have you tried it?

Should work like that in 1.5.* `$this->bot->typesAndWaits(1)`

**Comment by Hirvesh** [comment]
Hi Christoph, thank you so much for helping out! I was calling it using $this->typesAndWaits(1); **faceplam**

Let me try that and get back to you. On another note, is it possible to use Facebook templates within conversations? If yes, how to I handle the answers? I understand that the payload is sent back to the controller. Is there no way to associate a "value" to various items, in say, a list template, which I can then verify the choice of using getValue, similar to questions with buttons?

**Comment by christophrumpel** [comment]
No problem. Hope I was right ;-) Please use our Slack channel for such questions (the new one). The issued are just for issues :-) Joins us there for conversations. (PS: but yeah it is possible to use FB templates within conversations)
