### ISSUE TITLE
How to hear events like new user added to group?

### ISSUE THREAD

**Issue by xmodulus** [botman/botman#436]
Is it possible for botman to hear events like new user add/removed to a group?

**Comment by Emulator000** [comment]
Hi @xmodulus, unfortunately you can't do it yet.

Personally, I created an extended version of the TelegramDriver and I've implemented this feature directly inside. Here I can handle the Telegram array directly and call some events.

Anyway, the botMan team said that this feature will be implemented in the upcoming 2.0 version ;)

**Comment by mpociot** [comment]
Can you point me to the telegram API documentation where the events are listed? I wasn't able to find it a few weeks ago. 

But yeah - 2.0 will add support for these events.

**Comment by xmodulus** [comment]
@emulator000 that's good to hear... I was about to fix up the TelegramDriver myself, I guess I don't need to do that now

**Comment by xmodulus** [comment]
@mpociot Pretty sure they're under the message object, `new_chat_members` is listed there https://core.telegram.org/bots/api#message

**Comment by mpociot** [comment]
Will be implemented in 2.0 :)
