### ISSUE TITLE
Supergroup issue with chatId

### ISSUE THREAD

**Issue by Emulator000** [botman/botman#437]
- BotMan Version: 1.5.7
- PHP Version: 5.6.x
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
When you use the library inside a supergroup, all **$bot->reply()** functions are not working because the **chatId** passed internally via **getChannel()** is converted to a scientific notation of a number even if it is a string. Due to this, the parameter used and passed via Curl to the Telegram API is wrong and doesn't work.

### Steps To Reproduce:
Create a group, convert to Super group then test some hears command like this:
`$botman->hears('foo', function ($bot) {
    $bot->reply('Hello World');
});`

**Comment by mpociot** [comment]
Can you provide a pull request and test for this issue? Preferably on the telegram driver repository. 

https://github.com/botman/driver-telegram
