### ISSUE TITLE
Microsoft Bot Framework - Trying to get property of non-object

### ISSUE THREAD

**Issue by giansalex** [botman/botman#441]
- BotMan Version: ^1.4
- PHP Version: 5.6.25
- Messaging Service(s): BotFramework 
- Cache Driver: SymfonyCache

### Description:
At the time of testing from https://dev.botframework.com, using ngrok, i get this error:

> Notice: Trying to get property of non-object in C:\messenger-bot\vendor\mpociot\botman\src\Mpociot\BotMan\Drivers\BotFrameworkDriver.php on line 133

I tested from Postman, sending the Content-Type: application/x-www-form-urlencoded, and it's work, but in botman code not send header > content-type:

**Comment by mpociot** [comment]
Please use the latest stable version: ^1.5

**Comment by kenzouno1** [comment]
same this issue in botman v2.5
