### ISSUE TITLE
Counter-intuitive userStorage access interface

### ISSUE THREAD

**Issue by suushiemaniac** [botman/botman#444]
- BotMan Version: 1.5.7
- PHP Version: 7.0.20
- Messaging Service(s): N/A
- Cache Driver: N/A

### Description:
The method calls for reading certain values in the `userStorage`, `driverStorage` or `channelStorage` are not clearly understandable when compared to the method calls for saving.

### Steps To Reproduce:
Say we want to save value `"John Doe"` under the key `user.name` in user storage.
```php
$bot->userStorage()->save([
    'user.name'    =>    'John Doe'
]);
```
which reads as "access user storage and save the given key value pair". When reading that same value later, the following method call chain is necessary:
```php
$bot->userStorage()->get()->get('user.name');
```
and in my opinion the "doubled" `get` is higly confusing. Why not use `userStorage()->get('user.name')` in the first place?

**Comment by mpociot** [comment]
Yeah you're right.

Can you provide a PR for this? (for the master branch)
