### ISSUE TITLE
Add viber driver

### ISSUE THREAD

**Issue by iboldurev** [botman/botman#453]
Hi, please add viber driver on botman

**Comment by ikakey** [comment]
any news ?

**Comment by mpociot** [comment]
Current focus is documentation and latest adjustments for the 2.0 release, not new drivers.
I will provider a driver skeleton package for you to write custom drivers.

**Comment by sketchminds** [comment]
Hi Marcel,

Just like to ask for the update of your driver skeleton package.

Thanks.

**Comment by yarkm13** [comment]
https://github.com/TheArdent/botman-viber-driver
