### ISSUE TITLE
Wrong version of Laravel? (5.3 instead of 5.4)

### ISSUE THREAD

**Issue by sahibalejandro** [botman/botman#455]
- BotMan Version: ~1.0

### Description:
I was reading the docs at https://botman.io/1.5/installation-laravel and it says that installing with `composer create-project` will install a Laravel 5.4, but it installs 5.3.

I just discover it when trying to use `assertDatabaseHas()` in my tests, wich does not yet exists in Laravel 5.3.

I think if Laravel 5.4 support is not yet stable then you should update the docs.

### Steps To Reproduce:
Run `composer create-project mpociot/botman-laravel-starter` and check that the Laravel version in `composer.json` is 5.3

**Comment by mpociot** [comment]
That's true, the documentation is misleading. 
With the Laravel 5.5 release ahead, I will update the botman/studio package straight to 5.5
