### ISSUE TITLE
Facebook template is not working

### ISSUE THREAD

**Issue by hkalancheung** [botman/botman#456]
- BotMan Version: 1.5
- PHP Version: 5.6.4
- Messaging Service(s): Facebook
- Cache Driver: /

### Description:

Facebook template is not output probably. ERROR:

Object of class Mpociot\BotMan\Facebook\ButtonTemplate could not be converted to string

This happens to other templates as well, such as list / generic template.

### Steps To Reproduce:

Just copy & paste the example code from document.

$botman->reply(ButtonTemplate::create('Do you want to know more about BotMan?')
                    ->addButton(ElementButton::create('Tell me more')->type('postback')->payload('tellmemore'))
                    ->addButton(ElementButton::create('Show me the docs')->url('http://botman.io/'))
                );

**Comment by hkalancheung** [comment]
found the cause; The template works fine on Facebook Driver but not on Console Driver.

I think it needs to add a handling on ConsoleDriver.php of the say and reply function.

**Comment by mpociot** [comment]
Oh yeah, the console driver (tinker) currently doesn't support them. Not sure how you would simulate them.
