### ISSUE TITLE
AskLocation on facebook works only ask

### ISSUE THREAD

**Issue by IgorDePaula** [botman/botman#458]
- BotMan Version: 1.5.7
- PHP Version: 5.6
- Messaging Service(s): facebook
- Cache Driver: default

### Description:
On use the asklocation method, it do not ask location  with a button like facebook docs.
its works like another normal ask method.
![selecao_001](https://user-images.githubusercontent.com/2833993/27962997-fc52f86c-6309-11e7-85b6-2dcf4df9ea00.png)

### Steps To Reproduce:

use askLocation method on conversation

**Comment by mpociot** [comment]
Yeah, it acts the same for each driver.

If you want quick replies on facebook, you can add additional request parameters:

```php
$this->askForLocation('Please share your location:', function (Location $location) {
    $this->say('Received: '.print_r($location, true));
}, null, [
    'message' => [
        'quick_replies' => json_encode([
            [
                'content_type' => 'location'
            ]
        ])
    ]
]);
```

**Comment by IgorDePaula** [comment]
OK, I'll test. The botman docs do not explain this. I'll test.

2017-07-07 12:13 GMT-03:00 Marcel Pociot <notifications@github.com>:

**Comment by IgorDePaula** [comment]
Its works fine, thank you very much.

2017-07-07 13:00 GMT-03:00 principe.borodin@gmail.com <
principe.borodin@gmail.com>:
