### ISSUE TITLE
Slack RealTimeClient class is not included in 1.5

### ISSUE THREAD

**Issue by Hnto** [botman/botman#459]
- BotMan Version: 1.5
- PHP Version: 7.1
- Messaging Service(s): RealTimeClient
- Cache Driver: none

### Description:
The "use Slack\RealTimeClient;" has no effect since that package is not available. 

### Steps To Reproduce:
Use the BotManFactory::createForRTM function

**Comment by fliespl** [comment]
How did you solver it?

I can find it in 2.0 as well
