### ISSUE TITLE
Bot answering too early in conversation on SlackRTM

### ISSUE THREAD

**Issue by dFayet** [botman/botman#460]
- BotMan Version: dev-master#d303832
- PHP Version: 7.1.6
- Messaging Service(s): SlackRTM
- Cache Driver: ~

### Description:
I created a conversation on slack RTM, it's the same `OnboardingConversation` as the one in the doc.
I start the conversation, the bot then ask me a question, and then when I type anything, without sending the message, he answers me, but without the sent value.

For example:
me :  Hello
bot : Hello! What is your firstname?
me typing......
bot:  Nice to meet you <= here we miss the firstname which is supposed to be sent
and then he continues, it will be the same for all his questions.

### Steps To Reproduce:
Use the `OnboardingConversation` available in the doc https://botman.io/master/conversations
Then I do the following :
```
DriverManager::loadDriver(SlackRTMDriver::class);
$loop = Factory::create();
$botman1 = BotManFactory::createForRTM([
    'slack_token' => getenv('SLACK_TOKEN')
], $loop);

$botman1->hears('Hello', function($bot) {
    $bot->startConversation(new OnboardingConversation);
});

$loop->run();
```
Maybe I am missing something in the way to use conversation, if it is a real bug and not a misconfiguration I would be happy to look for a fix, and PR it.

Note : I am using `botman/botman` , `mpociot/slack-client` and `botman/driver-slack`, all the 3 on `dev-master`

**Comment by dFayet** [comment]
Alright, after some investigation I have found that when you type (in a conversation or not) a payload is sent, it looks like 
```
Illuminate\Support\Collection Object
(
    [items:protected] => Array
        (
            [type] => user_typing
            [channel] => D5ZR3KR8D
            [user] => U5Z1GCA64
        )

)
```
The bot listen to this event and answers, which is definitely not the goal.

This is simply due to that the RealTimeClient registers this event and react when he is executed, which is the right behavior.

I have fixed the ticket by editing the `HandlesConversations->loadActiveConversation()`  and adding a clause to ignore when the message is a user typing.

But I am not sure if this is the correct fix, I might also prevent the SlackDriver Factory to trigger the `botman->listen()` call when it is a `user_typing` event.

The 3rd solution would be to say to the `RealTimeClient` to ignore the `user_typing` action, but I thing it is still something we might want to have, in case of.

I would be glad to do a PR to patch this up, but I need to know which solution you prefer @mpociot ?

**Comment by mpociot** [comment]
Thank you for looking into this! We already differentiate between a message and an "event". Which would be "user_typing" in that case. 
So the loadActiveConversations / entire listen method should not get called when it only contains event payload data and not a real message. 
It would be great if you could provide a PR for this on the slack driver repository.

**Comment by dFayet** [comment]
I have a last question before the PR, in the `RealTimeClient` of slack-client, you consider all websocket message as message, which you will later attach to the `_internal_message` event. (https://github.com/mpociot/slack-client/blob/master/src/RealTimeClient.php#L120-L122)

Won't it be a better solution to split the `_internal_message` in 2 parts for eg. `_internal_message` and `_internal_event` it won't have impact outside of the slack parts, and it would allow us to separate the messages and all the others stuff (like status changing or so)

What do you think @mpociot ?

**Comment by mpociot** [comment]
@dFayet splitting this is a bit harder because we want to call "listen" from botman in all cases.

What I did to fix this is: https://github.com/botman/driver-slack/commit/0d7942e2d98dfdd79ed3a447240228ae6fac2a19#diff-3c453307ed85ca095f7ad8e60070ddf4R148
I now check if the incoming payload is an event, and if it is we just don't return a message array (which wouldn't contain any information anyway).
