### ISSUE TITLE
Add an attachment

### ISSUE THREAD

**Issue by lucadegasperi** [botman/botman#464]
I have browsed the entire documentation as well as searching in the issues but haven't found how to attach a file to a telegram message. So far what I found is:

```php
$botman->say('message', 'telegramId', 'driverToUse', [ SOMETHING HERE ] );
```

Can someone point me in the right direction?

**Comment by mpociot** [comment]
This is currently not possible with the 1.5 version.
With 2.0 / dev-master you can do this:

```php
$file = new File('www.my-file-url.com/file.pdf');
$message = OutgoingMessage::create('Hello')->withAttachment($file);
$botman->say($message, 'telegramId, 'driver')
```
