### ISSUE TITLE
Catching Facebook Postback Payloads inside a Conversation

### ISSUE THREAD

**Issue by jusdeleon** [botman/botman#465]
Is there an easy way to catch Payloads set without repeating code?

```
 $this->botman->group(['driver' => FacebookPostbackDriver::class], function($bot) {
            $bot->hears('GET_STARTED', function (BotMan $bot) {
                $user = $bot->getUser();

                $bot->reply("Welcome {$user->getFirstName()}! Let us know what you need.");
            });

            $bot->hears('ACTION1', function (BotMan $bot) {
                $bot->startConversation(new Action1Conversation);
            });

            $bot->hears('ACTION2', function (BotMan $bot) {
                $bot->startConversation(new Action2Conversation);
            });
        });

```

If within the `Action2Conversation`, when I select an item from the persistent menu (i.e. ACTION1), The listener does not get triggered.

Desired use case is: if during the Action2Conversation, user decides to tap on "ACTION1" from the persistent menu, the hears function should get triggered and Action1Conversation should start

**Comment by christophrumpel** [comment]
This is how I right now manage it:

```php
/**
     * @param Message $message
     * @return bool
     */
    public function skipConversation(Message $message)
    {
        $skipWords = ['restart_payload', 'neustarten', 'neu starten', 'restart', 'noch einaml', 'get_url_for_current_session'];

        return in_array(strtolower($message->getMessage()), $skipWords);
    }
```

There is a `skipConversation` method that you can use in every conversation. If it returns true, the request will leave the conversation and you can trigger `hears` method from outside. This is what I used to leave conversations when the user hit a menu item from the persistent menu. Is this what you needed?

**Comment by jusdeleon** [comment]
Thanks @christophrumpel! This is what I need. I used the `stopConversation` method though.
