### ISSUE TITLE
Slack not showing images from message

### ISSUE THREAD

**Issue by PhilETaylor** [botman/botman#466]
- BotMan Version: whatever composer gave
- PHP Version: 7.1.2
- Messaging Service(s): slack/facebook
- Cache Driver: redis

### Description:

using code below, slack channel only shows the text and not the image. Same code in facebook messenger shows the image

### Steps To Reproduce:

```
$botman->hears('photo', function (BotMan $bot) {
        // Build message object
        $message = Message::create('This is a photo of me')
               	->image('https://www.gravatar.com/avatar/4c7eec676a9b4662214e9198afa29acb');

        // Reply message object
        $bot->reply($message);
});
```

**Comment by gterras** [comment]
Hi, 

Same trouble for me [here](https://github.com/botman/botman/issues/428), still unanswered :( Please share if you find something !

**Comment by mpociot** [comment]
I'll try to look into both issues later today

**Comment by gterras** [comment]
Thanks a lot mate !

**Comment by Simperfit** [comment]
Maybe what could be done to ease the understanding and the issue is to clone the starter version of botman, which is studio and add the code that is failling.

**Comment by mpociot** [comment]
Which Slack integration method are you all using? Slack has quite a few options.
RTM API
Incoming webhook
Message events

**Comment by kursusHC** [comment]
Hi thank you for your interest. 

There is more information in my [thread](https://github.com/botman/botman/issues/428). Whatever the driver I'm using I get unsuccessful results. 

Although it's not very clear what driver is in use in some cases, until there I thought webhooks and message events used the same drivers. It is made harder by the differences between botman / studio and different versions of botman. Latest (unreleased master) botman seem to have changes in it but I can't get to make it work in Studio. 

I've spent the whole day trying to debug the process with botman 1.5.6 without luck. I'd like to avoid the RTM API which is harder to setup and weaker. 

All that I could get is that when a file is uploaded, two POST requests (one `"type": "file_shared"` and one `message`) are sent to botman, containing every useful information possible (including a working image URL) so the Slack side should be correctly set up.  

But, **unlike when you respond with plain text**, the `Mpociot\BotMan\Message Object` is empty (`message` and `payload`) when an image is uploaded, so the image pattern is never checked for, and the requests voids. 

Could you please post an example of the correct way to use the non RTM slack driver ? 

I'm desperate to find a working solution. I can do anything to help debugging.

Thanks a lot
