### ISSUE TITLE
Support for multiple bots

### ISSUE THREAD

**Issue by iboldurev** [botman/botman#472]
Hi, @mpociot How to implement support for multiple bots in one application?

**Comment by mpociot** [comment]
It depends on how you use BotMan. 
You're need to determine which token / config values to use dynamically using the incoming request.

**Comment by iboldurev** [comment]
At the moment I have 2 bots, I want to unite them in 1 application

You can implement an example

**Comment by mpociot** [comment]
I'm not sure I understand you correctly.

You have two running bot applications that you want to combine into one? But depending on where the request comes from, it should use different configuration?

I'm not so sure if that's a good approach. 
It feels like you have for example two Laravel applications that have different databases, but now you want to merge them into one application and load the configuration dynamically.

**Comment by iboldurev** [comment]
On the contrary, for example I have 2 bots in telegrams, 4 bots in a fb, and I want it to be all in 1 application

**Comment by iboldurev** [comment]
All bots have 1 logic, just different pages and drivers

**Comment by mpociot** [comment]
If you're using Laravel, you can modify the IOC container closure that loads BotMan and give it the custom configuration you need:

```php
<?php

namespace App\Providers;

use BotMan\BotMan\Cache\LaravelCache;
use Illuminate\Support\ServiceProvider;
use BotMan\BotMan\BotManServiceProvider;
use BotMan\BotMan\Storages\Drivers\FileStorage;

class BotManServiceProvider extends BotManServiceProvider
{
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton('botman', function ($app) {
            $config = config('services.botman', []);

            $request = app('request');
            $json = json_encode($request->getContent()));
            if ($json) {
                // Look for whatever you need to determine which config to use.
                $config['facebook_token'] = $your_custom_token;
                // etc.
            }

            $storage = new FileStorage(storage_path('botman'));

            return BotManFactory::create($config, new LaravelCache(), $app->make('request'),
                $storage);
        });
    }
}
```

Something like this

**Comment by johntiror** [comment]
if I'm not wrong it should be 

`class BotManServiceProvider extends ServiceProvider`

right?

**Comment by dara-t** [comment]
Hi,

I have add the code above to provider folder and I define it in app config. But it didn't work. When I open in browser, it return {"status":200,"messages":[]}.  verify webhook in facebook is no problem.

**Comment by marcus-campos** [comment]
I has the same problem...

**Comment by marcus-campos** [comment]
I discovered that this bug occurred because the web-driver was being loaded. I pulled out and everything went back to normal.

**Comment by shamnascv** [comment]
> It depends on how you use BotMan.
> You're need to determine which token / config values to use dynamically using the incoming request.

How to do this?

**Comment by 0msm0** [comment]
@mpociot @marcus-campos Any clue on how to implement the above code? I have one laravel app and two chatbots (messenger & telegram) however both are meant for different purposes. For example, messenger bot is for one class of users while telegram is for other (say admin). How do I go about it?
