### ISSUE TITLE
UserStorage->Delete don't work

### ISSUE THREAD

**Issue by TLMWork** [botman/botman#473]
When i save some data in the UserStorage with

`$bot->userStorage()->save([
			'supersecretpassword' => $pw
		]);`

i cannot remove this data with 

`$bot->userStorage()->delete('supersecretpassword');`

The JSON is still there....

**Comment by mpociot** [comment]
You can not delete specific keys from the JSON. The `delete` method deletes everything on a given user-id (or the current user, if no key is provided).

So you would need to set `supersecretpassword` to null or delete the complete user storage.
