### ISSUE TITLE
How To make as this button?

### ISSUE THREAD

**Issue by BarGo94** [botman/botman#477]
I want to know how we can make as this buttons with botman : 
![button](https://user-images.githubusercontent.com/26595448/28461388-b365ea7a-6e16-11e7-9129-3d41449da97d.PNG)

**Comment by christophrumpel** [comment]
Hey @BarGo94 ,

these are the "normal" BotMan Buttons. You can create them with a BotMan Question object:

```php
$question = Question::create('Do you need a database?')
        ->fallback('Unable to create a new database')
        ->callbackId('create_database')
        ->addButtons([
            Button::create('Of course')->value('yes'),
            Button::create('Hell no!')->value('no'),
        ]);
```

Then you can send this question with `$botMan->reply($question);` or inside a conversation class with:

```php
$this->ask($question, function (Answer $answer) {
    // ... your code here to answer
}
```
