### ISSUE TITLE
Messages with Slack Variables / Mentions are broken

### ISSUE THREAD

**Issue by hskrasek** [botman/botman#478]
- BotMan Version: 1.5.7
- PHP Version: 7.1.4
- Messaging Service(s): Slack
- Cache Driver: Slack

### Description:
When I try to send a message using Slack's variable to embed an @everyone mention, or a time, the library breaks those portions due to sending the message through `replyWithToken`.

[Expected message](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Group%20up%20with%20me!%22%2C%22text%22%3A%22Group%20up%20with%20me!%22%2C%22pretext%22%3Anull%2C%22color%22%3A%22%235d5956%22%2C%22footer%22%3Anull%2C%22footer_icon%22%3Anull%2C%22ts%22%3Anull%2C%22image_url%22%3Anull%2C%22thumb_url%22%3Anull%2C%22title%22%3Anull%2C%22title_link%22%3Anull%2C%22author_name%22%3Anull%2C%22author_link%22%3Anull%2C%22author_icon%22%3Anull%2C%22fields%22%3A%5B%5D%2C%22callback_id%22%3A%22plans-4%22%2C%22actions%22%3A%5B%7B%22name%22%3A%22rsvp%22%2C%22text%22%3A%22Let%27s%20FIGHT!%22%2C%22style%22%3A%22primary%22%2C%22type%22%3A%22button%22%2C%22value%22%3A%221%22%7D%2C%7B%22name%22%3A%22rsvp%22%2C%22text%22%3A%22Me%3F%20NEVER!%22%2C%22style%22%3A%22danger%22%2C%22type%22%3A%22button%22%2C%22value%22%3A%220%22%7D%5D%7D%5D%2C%22text%22%3A%22%3C!everyone%3E%2C%20I%27ve%20started%20a%20plan%20%3C!date%5E1500751800%5E%7Bdate_pretty%7D%20at%20%7Btime%7D%7CSaturday%2C%2022-Jul-2017%2019%3A30%3A00%20UTC%3E.%22%7D)

[Actual message](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22fallback%22%3A%22Group%20up%20with%20me!%22%2C%22text%22%3A%22Group%20up%20with%20me!%22%2C%22pretext%22%3Anull%2C%22color%22%3A%22%235d5956%22%2C%22footer%22%3Anull%2C%22footer_icon%22%3Anull%2C%22ts%22%3Anull%2C%22image_url%22%3Anull%2C%22thumb_url%22%3Anull%2C%22title%22%3Anull%2C%22title_link%22%3Anull%2C%22author_name%22%3Anull%2C%22author_link%22%3Anull%2C%22author_icon%22%3Anull%2C%22fields%22%3A%5B%5D%2C%22callback_id%22%3A%22plans-4%22%2C%22actions%22%3A%5B%7B%22name%22%3A%22rsvp%22%2C%22text%22%3A%22Let%27s%20FIGHT!%22%2C%22style%22%3A%22primary%22%2C%22type%22%3A%22button%22%2C%22value%22%3A%221%22%7D%2C%7B%22name%22%3A%22rsvp%22%2C%22text%22%3A%22Me%3F%20NEVER!%22%2C%22style%22%3A%22danger%22%2C%22type%22%3A%22button%22%2C%22value%22%3A%220%22%7D%5D%7D%5D%2C%22text%22%3A%22%26lt%3B!everyone%26gt%3B%2C%20%26lt%3B%40U622GKZ4H%7Chunter.skrasek%26gt%3B%20started%20a%20plan%20%26lt%3B!date%5E1500751800%5E%7Bdate_pretty%7D%20at%20%7Btime%7D%7CSaturday%2C%2022-Jul-2017%2019%3A30%3A00%20UTC%26gt%3B.%22%7D)

### Steps To Reproduce:

Have botman reply with a message like so:

```php
// Left in message replacements for brevity 
$botman->reply('<!everyone>, <@:user_id|:mention> started a plan <!date^:time^{date_pretty} at {time}|:time_formatted>.');
```

**Comment by mpociot** [comment]
Will be fixed in 2.0!
