### ISSUE TITLE
Conversation don't work with the Slack Event API

### ISSUE THREAD

**Issue by TLMWork** [botman/botman#481]
- BotMan Version: 1.5
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver: ?

### Description:

When Botman starts a Conversation and i type a reply than i get the Fallback Message instead of the next Conversation Step

### Code:

`$botman->hears('testconv', function($bot) {
		/**
		 * @var $bot \Mpociot\BotMan\BotMan;
		 */
		$bot->startConversation(new TLM\MarcBot\TestconvConversation());
	});`

Conversation Code:
`<?php
	
	namespace TLM\MarcBot;
	use Mpociot\BotMan\Conversation;
	
	class TestconvConversation extends Conversation
	{
		protected $firstname;
		
		protected $email;
		
		public function askFirstname()
		{
			$this->ask('Hello! What is your firstname?', function(Answer $answer) {
				// Save result
				$this->firstname = $answer->getText();
				
				$this->say('Nice to meet you '.$this->firstname);
				$this->askEmail();
			});
		}
		
		public function askEmail()
		{
			$this->ask('One more thing - what is your email?', function(Answer $answer) {
				// Save result
				$this->email = $answer->getText();
				
				$this->say('Great - that is all we need, '.$this->firstname);
			});
		}
		
		public function run()
		{
			// This will be called immediately
			$this->askFirstname();
		}
	}`

**Comment by mpociot** [comment]
How are you creating the BotMan instance?
You need a persistent cache driver because conversations get stored in the cache.

**Comment by TLMWork** [comment]
with `$botman = BotManFactory::create($config);`
I don't use the Laravel package

**Comment by mpociot** [comment]
Then you need a cache driver.

Install the doctrine cache package: `composer require doctrine/cache`
```php
use Mpociot\BotMan\Cache\DoctrineCache;

$doctrineCacheDriver = new FilesystemCache(__DIR__);
$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));
```

**Comment by TLMWork** [comment]
Its works, Thank you,

you should Link the info from https://botman.io/1.5/installation#cache-drivers in the Docs on https://botman.io/1.5/conversations ;)
