### ISSUE TITLE
Facebook webview

### ISSUE THREAD

**Issue by EdisonLV** [botman/botman#488]
- BotMan Version: 1.5.8
- PHP Version: 7.1
- Messaging Service(s): FaceBook
- Cache Driver: File

### Description:
Not sure if webview is implemented, couldn't find it in the documentation.
Is there a way to display webview for facebook?
https://developers.facebook.com/docs/messenger-platform/webview/showing

Thank you

**Comment by mpociot** [comment]
This has nothing to do with BotMan itself. You simply need to add the webview(s) you want to add in the Facebook messenger to the page:

https://developers.facebook.com/docs/messenger-platform/webview/extensions

**Comment by EdisonLV** [comment]
Is there a way to add attributes/options to the ElementButton (messenger_extensions, webview_height_ratio)?
https://developers.facebook.com/docs/messenger-platform/send-api-reference/url-button

~~~
    "buttons":[
      {
        "type":"web_url",
        "url":"https://petersfancyapparel.com/classic_white_tshirt",
        "title":"View Item",
        "webview_height_ratio": "compact",
        "messenger_extensions": true,  
      }
~~~

Thanks, Ed

**Comment by mpociot** [comment]
Not with 1.5.* unfortunately.

2.0 will add the ability to do this:

```php
$button = ElementButton::create('View Item')
            ->url('https://petersfancyapparel.com/classic_white_tshirt')
            ->heightRatio(ElementButton::RATIO_COMPACT)
            ->enableExtensions();
```

ETA for 2.0: 3-4 weeks

**Comment by mauriciorockman** [comment]
OMG! I was looking for hours for this! Thank you so much! I searched whole documentation for this, but I could not find. This framework is just awesome, I'm loving it, but I think the current documentation still lacks many information, like this.

**Comment by christophrumpel** [comment]
@mauriciorockman feel free to add stuff to the doc that you find missing. Help appreciated :-)

**Comment by 04211708AC** [comment]
How can I send and receive information to the bot from the web view ?

**Comment by 04211708AC** [comment]
@NedStrk Have you tried sending and receiving information?
