### ISSUE TITLE
What is the best way to pre process user input before any processing?

### ISSUE THREAD

**Issue by hemratna** [botman/botman#489]
Hi Everyone,

I am new to chatbot development and botman really help me a lot.
Thank you so much for such a great package.

I am using botman with Laravel 5.4
I am looking for some pre-precessing user input before it goes to 'hears' functions call.

For example,
The user can send 'Hello', 'hi', 'hi!!!', 'hi.' etc But in the all the cases I have to reply with the same onboarding msg.

Can anybody suggest me some good ways to achieve this?
I took a look at middleware But didn't figure out how I can use in this case.

Thanks in advance.
Regards,

**Comment by christophrumpel** [comment]
Hey @hemratna , have you checked out the NLP section of the botman docs? https://botman.io/1.5/nlp

This is what you need, a external NLP service like api.ai oder wit.ai. Botman will send the request to this service and there you can define what is sent back to botman. This way you can let the service detect the `intention` and you can handle multiple messages, like you mentioned`, with one response.

**Comment by hemratna** [comment]
Hi @christophrumpel 

Thanks a lot for your response.

I am looking for some in-house solutions.
Can we have some control before our function is being called?

Regards,
Hem

**Comment by mpociot** [comment]
@hemratna you can use a middleware for pretty much everything :)
https://botman.io/2.0/middleware
