### ISSUE TITLE
Slackbot does not send a reply

### ISSUE THREAD

**Issue by happyDemon** [botman/botman#493]
- BotMan Version: 1.5.1 (through the laravel starter)
- PHP Version: 7.0
- Messaging Service(s): Slack
- Cache Driver: n/a

### Description:
I'm using the command that came bundled with the start, as well as catching an action through api.ai.

As you can see, I log the payloads if they're validly called,
however the bot never sends a reply.
I'm a bit puzzled.

 ```php
$botman = app('botman');
        $botman->verifyServices(env('TOKEN_VERIFY'));

        // Simple respond method
        $botman->hears('Hello', function (BotMan $bot) use($request) {
            \Log::info('heard hello', $request->all());
            $bot->reply('Hi there :)');
        });


        $botman->hears('bookMeetingRoom', function (BotMan $bot) use($request) {
            $payload = $bot->getMessage()->getExtras();
            \Log::info('heard book meeting room', [
                'nlp' => $payload,
                'request' => $request->all()
            ]);
            $bot->reply('Hi there :)');
        })->middleware(ApiAi::create('XXXXXXXXXXXXX')->listenForAction());

        $botman->listen();
```

### Steps To Reproduce:

I've set the slack token to the **Verification Token** I've received from slack.
I'm also subscribed to the 2 bot events that were required by the documentation.

Under oAuth & permission scopes I've selected: Send messages as testbot, Add a bot user with the username @testbot.

**Comment by mpociot** [comment]
Which token do you use in the configuration? Is it the bot token? Or the general access token?

**Comment by kevinjon27** [comment]
@mpociot I have a question. I am using existing project laravel 5.5 to test BotMan but bot not return anything.

my code on routes/api.php
`Route::post('test', function(Request $request) {
    $botman = app('botman');

    $botman->hears('hello', function ($bot) use ($request) {
        $bot->reply('Hello yourself.');
    });

    // start listening
    $botman->listen();
});`

and I'm using postman to test the apps

url: localhost:8000/api/test
body: 
{
 message: 'hello'
}

return blank page

**Comment by mpociot** [comment]
@kevinjon27 make sure to use the web driver with the correct configuration. See https://botman.io/2.0/driver-web
