### ISSUE TITLE
Any tutorial for configuring api.ai?

### ISSUE THREAD

**Issue by BarGo94** [botman/botman#494]
Hello, sorry for my bad english , 
i want to know if there are a tutorial to integrate Api.Ai with botman how to do that?

**Comment by mpociot** [comment]
Please note that the Github issues are for issues with the BotMan core such as bugs.
If you have implementation specific questions, please visit our Slack team https://rauchg-slackin-jtdkltstsj.now.sh/ .
---

The official documentation covers BotMan in combination with API.ai: https://botman.io/1.5/nlp#api-ai
