### ISSUE TITLE
Fallback parameters?

### ISSUE THREAD

**Issue by BarGo94** [botman/botman#495]
there is a way to have parameters in fallback as hears?
for example in hears we can add parameters as name and adjective or others.
$botman->hears('call me {name} the {adjective}', function ($bot, $name, $adjective) 

there is no way to add parameters like this in fallback?

$botman->fallback('{other}',function($bot,$other) ?

**Comment by mpociot** [comment]
You can access the fallback text using: 
```php
$botman->fallback(function($bot) {
    $text = $bot->getMessage()->getText();
});
```

**Comment by BarGo94** [comment]
when i add     $text = $bot->getMessage()->getText();
the reply of fallback doesn't work any more
