### ISSUE TITLE
using template in say method Conversation

### ISSUE THREAD

**Issue by BarGo94** [botman/botman#496]
That's some one can help me with an exemple in Conversation how to use :  
ButtonTemplate ,GenericTemplate and others?

**Comment by christophrumpel** [comment]
Hey @BarGo94,

In conversations you can use the `$this->ask($myButtonTemplate)` method to accomplish that.

**Comment by BarGo94** [comment]
as $bot->reply(GenericTemplate::create()
	->addImageAspectRatio(GenericTemplate::RATIO_SQUARE)
	->addElements([
		Element::create('BotMan Documentation')
			->subtitle('All about BotMan')
			->image('http://botman.io/img/botman-body.png')
			->addButton(ElementButton::create('visit')->url('http://botman.io'))
			->addButton(ElementButton::create('tell me more')
				->payload('tellmemore')->type('postback')),
		Element::create('BotMan Laravel Starter')
			->subtitle('This is the best way to start with Laravel and BotMan')
			->image('http://botman.io/img/botman-body.png')
			->addButton(ElementButton::create('visit')
				->url('https://github.com/mpociot/botman-laravel-starter')
			)
	])
);


we can do change $bot->reply by $this->ask?

**Comment by christophrumpel** [comment]
Is it not working? Yes you can use the ask or the reply method with the templates.

**Comment by christophrumpel** [comment]
PS: `$bot->reply` can be used outside of conversations, like in your `hears` callbacks. Inside your conversations you need to use `$this->ask(...` oder $this->bot->reply(...`
