### ISSUE TITLE
Not getting response in conversations

### ISSUE THREAD

**Issue by alshaikh1** [botman/botman#497]
- BotMan Version: 1.5.8
- PHP Version: 5.6.0
- Messaging Service(s): FB Messenger
- Cache Driver: no cache driver

### Description:
When the conversation starts, I'm getting (Hello! What is your firstname?).
Then the user types the name.
Then no response comes after while I should get (Nice to meet you... etc).
Any suggestion?

`public function askFirstname()

    {

        $this->ask('Hello! What is your firstname?', function(Answer $answer) {

            // Save result

            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);

            $this->askEmail();

        });
    }
`

### Steps To Reproduce:

**Comment by mpociot** [comment]
You need a cache driver.

Install the doctrine cache package: `composer require doctrine/cache`
```php
use Mpociot\BotMan\Cache\DoctrineCache;

$doctrineCacheDriver = new FilesystemCache(__DIR__);
$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));
```

**Comment by alshaikh1** [comment]
Thank you @mpociot 
I got the following error
PHP Fatal error:  Class 'FilesystemCache' not found. Any suggestion?

**Comment by mpociot** [comment]
You need to import the class. It's in the doctrine cache package and namespace.

**Comment by alshaikh1** [comment]
Thank you @mpociot 
I have added the doctrine path to the $prefixDirsPsr4 array in autoload_static.php to make it work.
