### ISSUE TITLE
Can't use DoctrinCache driver properly

### ISSUE THREAD

**Issue by wong0630** [botman/botman#499]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver: DoctrinCache driver

### Description:
Hi All

As I need to use conversation inside my bot, I know that I need to pass DoctrinCache driver to the bot instance as below
`$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));`

However, there is error 
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mpociot\BotMan\Cache\DoctrineCache::__construct() must be an instance of Doctrine\Common\Cache\Cache, null given, called in /app/index.php on line 98

I did some research in Internet and someone said I need to put this line into the code as well
`$cacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');`

However, after I put this code, there will be another error
PHP Fatal error:  Uncaught Error: Class 'Doctrine\Common\Cache\ApcuCache' not found in /app/index.php:98

Would someone give me some idea on how to solve this issue and what are the correct codes?

Thanks,
Jacky

### Steps To Reproduce:

**Comment by tucq88** [comment]
How did you resolve this ?
