### ISSUE TITLE
Storing data

### ISSUE THREAD

**Issue by BarGo94** [botman/botman#500]
I want to know how to store data as Generic Template
as this example: 
when you click there it's saving the item of generic template
![1](https://user-images.githubusercontent.com/26595448/29210025-d185535c-7e91-11e7-8b03-06ed1e02decf.PNG)
and when the user click in this button of persistent menu ,the item is displaying
![2](https://user-images.githubusercontent.com/26595448/29210026-d1a3ac12-7e91-11e7-8146-1a90c61d3176.PNG)

**Comment by christophrumpel** [comment]
Hey @BarGo94 , I am not quite sure what you want to accomplish. Do you want to save items dynamically to the persistent menu?

**Comment by BarGo94** [comment]
Yes the items that user choose

**Comment by christophrumpel** [comment]
Ok, so the user selects an item from something like Generic template and then you want that item inside the peristent menu only for this user, correct?

I don't think this is possible right now with Facebook. You can only create a menu for all users. You can just change it for different locale. But not for individual users.
