### ISSUE TITLE
Slackbot RTM InteractiveMessageReply

### ISSUE THREAD

**Issue by cguijt** [botman/botman#502]
- BotMan Version: 1.5.8
- PHP Version: 7.1.7
- Messaging Service(s): Slack RTM
- Cache Driver: ArrayCache (default)

### Description:
When I click on a interactive button within a conversation it loads for a second, but never does anything. I've used the **Bot User OAuth Access Token** from slack (found in _OAuth & Permissions_) and the **Interactive Messages Request/Options URL** are set to the _/botman_ url of my application. I've added the following rule to the **ExampleConversation** class in the **$this->ask** callback;
`$this->say($answer->isInteractiveMessageReply() ? 'interactive' : 'not');`

There's no reply at all when I press a button, but as soon as I send another message it will reply with _not_.

### Steps To Reproduce:
1. Install with laravel with `composer create-project mpociot/botman-laravel-starter`
2. Run `composer install` and `composer update`
3. Remove the CSRF validation in _app/Http/Kernel.php_
4. Insert **Slack bot user OAuth Access Token**
5. Set **Interactive Messages Request/Options URL** to the _/botman_ url in Slack
6. Start slack conversation

**Comment by vikingmaster** [comment]
Also, may be a little bit different question, but how do you make Interactive Messages work with SlackRTM?
I have a supervisor running the socket, conversation contains a question. The URL for interactive messages is setup. How to make BotMan recognize such a request and communicate to the socket instance, that an answer has arrived?

    public function postInteractive(Request $request)
    {
//        Log::debug(print_r($request->toArray(), true));

        $bot = BotManFactory::create(config('services.botman'));
        App::instance('botman', $bot);

        require base_path('routes/botman.php');

        $bot->listen();
    }

**Comment by mpociot** [comment]
@vikingmaster yeah, that's a different issue.
I still don't have a fix for this yet. The problem currently is, that the RTM instance runs in a separate context than the HTTP requests. So they can't communicate.

**Comment by vikingmaster** [comment]
@mpociot 
Theoretically requests be used to store data in the database, and the RTM looper could check for presence of the new data -> getting answers from there.
Would be nice to have **Answers** working in RTM in 2.0, if possible :)
