### ISSUE TITLE
Not have button of telegram?

### ISSUE THREAD

**Issue by criscompbr** [botman/botman#504]
- BotMan Version: 1.0
- PHP Version: 7.1
- Messaging Service(s): -
- Cache Driver: -

### Description:
Hello .. Good evening!

I need to implement the telegram that supports button or dialog to ask the questions, and has how to implement the botman?

### Steps To Reproduce:

**Comment by mpociot** [comment]
Please note that the Github issues are for issues with the BotMan core such as bugs.
If you have implementation specific questions, please visit our Slack team https://slack.botman.io/ .

---

You can read more about BotMan conversations and buttons in the documentation: https://botman.io/1.5/conversations
