### ISSUE TITLE
botman in my ejabberd chat

### ISSUE THREAD

**Issue by shazvan275** [botman/botman#505]
I am using XMPP ejabberd chat system can you botman in my system..? if yes, then how..? please help me...

thanks in advance...

**Comment by mpociot** [comment]
Please note that the Github issues are for issues with the BotMan core, such as bugs.
If you have implementation specific questions, please visit our Slack team https://slack.botman.io/ .

---

BotMan does not support ejabbered systems out-of-the-box right now. But you can develop your own BotMan driver to add support for it.
