### ISSUE TITLE
Facebook API endpoint deprecated.

### ISSUE THREAD

**Issue by herzcthu** [botman/botman#507]
- BotMan Version: 1.5.8
- PHP Version: 7.0
- Messaging Service(s): Facebook
- Cache Driver: FIle

### Description: 
Facebook API endpoint used botman is v2.6. Latest API version are 2.9 and 2.10.
Botman do not reply to facebook page.

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey @herzcthu ,

why do you think it is higher than 2.6? From what I've seen for the messenger API it is still 2.6 https://developers.facebook.com/docs/messenger-platform/reference/send-api

If BotMan is not responding, it must be something else.

**Comment by herzcthu** [comment]
I mean webhook API.
https://developers.facebook.com/docs/graph-api/reference/v2.10/message/

**Comment by herzcthu** [comment]
Anyway BotMan not responding is something else. Not related with API version.

**Comment by christophrumpel** [comment]
Ok I see what you mean, but 2.6 is still a valid version. Bu we will keep that in mind, thx. "The Graph API version should be set to 2.6 or greater."
