### ISSUE TITLE
Features and use cases not entirely clear from website and docs

### ISSUE THREAD

**Issue by wowcut** [botman/botman#508]
It is not entirely clear what features for which use cases botman provides. E.g. it is not clear to me if botman can be used to build a chat room or if it 'only' provides a bridge to several commercial platforms. Also it is not clear if open source chat servers can be used or not. 

It would be great if you wrote some features and what exactly botman is about right on the website frontpage, thanks!

**Comment by mpociot** [comment]
Hi!

I recently released version 2.0 of BotMan - please take a look at the new documentation, as it should clarify the use case.
