### ISSUE TITLE
Bot->hear not working in Middleware

### ISSUE THREAD

**Issue by TLMWork** [botman/botman#513]
- BotMan Version: 2.0.1
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver: Doctrine

### Description:

I want to react in a middleware for diffrent Commands to make My Botman more like OOP

`$bot->hears('hallo',function (BotMan $bot){
				$bot->reply('Hallo');
			});`

throw an Error:

`Fatal error: Uncaught TypeError: Argument 1 passed to BotMan\BotMan\Messages\Matcher::isMessageMatching() must be an instance of BotMan\BotMan\Messages\Incoming\IncomingMessage, null given, called in /MySecretPathOnMyPC/thebotman/vendor/botman/botman/src/Commands/ConversationManager.php on line 80 and defined in /MySecretPathOnMyPC/thebotman/vendor/botman/botman/src/Messages/Matcher.php on line 31`

### Steps To Reproduce:

**Comment by mpociot** [comment]
Please fill out the steps to reproduce the error. I don’t quite get what you’re trying to do.

**Comment by TLMWork** [comment]
bot.php:
```
$config = [
		'slack'=> ['token' => MySecretToken]
	];

$doctrineCacheDriver = new \Doctrine\Common\Cache\FilesystemCache( __DIR__ );
	$botman              = BotManFactory::create( $config, new DoctrineCache( $doctrineCacheDriver ) );



$middleware = new MyBot\Middleware\TestMiddleware();
	$botman->middleware->received($middleware);
```

TestMiddleware.php: 
```
public function received( IncomingMessage $message, $next, BotMan $bot ) {
			$bot->on('hallo',function (BotMan $bot){
				$bot->reply('Hallo');
			});
		}
```

I try to catch all incoming Message and hear for spezific Commands. I'll create a Middleware for every Thing i would like to make with the Bot.

### Example: 

#### Games Library:

GameslibraryMiddleware:

Commands: 
- games all | Show all your Steam Games
- games wishlist | Show your Steam Wishlist
- games wishlist add {Game} | Add a Game to your Wishlist

#### Coffee

CoffeeMiddleware:

Commands:
- coffee make | Make's some Coffee
- coffee stats | Shows some Statistic

And thats i want to do with `$bot->hear('games|coffee someCommand')` in the function **received()**

**Comment by mpociot** [comment]
@TLMWork okay - that is not the purpose of middlewares.
The middleware can be used to modify incoming messages and change how the messages should be matched.

You just need to structure your code, if you want to have multiple "topics" in your bot - but that's possible with hears commands anyway.
