### ISSUE TITLE
Empty token preventing Slack reply from Botman

### ISSUE THREAD

**Issue by anuashley** [botman/botman#514]
- BotMan Version: 2
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver: file

### Description:

I installed Botman Studio and have set up a Slack App with Event API and a bot user and put the Bot User OAuth token in config/botman/slack.php

I am using the default Hi as a test, it is being processed by Botman and a call is being sent back to Slack API but the token is empty.

This is what Slack is sending Botman:

local.INFO: Symfony\Component\HttpFoundation\ParameterBag Object
(
    [parameters:protected] => Array
        (
            [token] => (redacted)
            [team_id] => (redacted)
            [api_app_id] => (redacted)
            [event] => Array
                (
                    [type] => message
                    [user] => (redacted)
                    [text] => Hi
                    [ts] => 1504202388.000120
                    [channel] => (redacted)
                    [event_ts] => 1504202388.000120
                )

            [type] => event_callback
            [authed_users] => Array
                (
                    [0] => (redacted)
                )

            [event_id] => (redacted)
            [event_time] => 1504202388
        )

)

This is what Botman is sending back to Slack:

[2017-08-31 17:59:50] local.INFO: Array
(
    [as_user] => 1
    [token] =>
    [channel] => (redacted)
    [text] => Hellooo!
)

(I changed the text to Hellooo!)

I am struggling to debug why it is not picking the token up from the slack.php file.

Here is my botman.php route:

<?php
use App\Http\Controllers\BotManController;

$botman = resolve('botman');

$botman->hears('Hi', function($bot){
    $bot->reply('Hellooo!');
});

//$botman->hears('Start conversation', BotManController::class.'@startConversation');

Any ideas?

**Comment by christophrumpel** [comment]
@anuashley found the problem himself. Please share it here as well.
