### ISSUE TITLE
Response does not match challenge

### ISSUE THREAD

**Issue by damienpicca** [botman/botman#515]
- BotMan Version: 2
- PHP Version: 7.0.3
- Messaging Service(s): Messenger
- Cache Driver:

### Description:
I installed last Botman version (before I was on the old mpociot/botman that is not maintained) and it turns out that I can no longer use the function $bot->verifyServices('facebook_verification').

On the new version the drivers are separated from the core project, so I installed the messenger driver and here is my code : 

    	$config = [
			'facebook' => [
				'token' => 'mytoken',
				'app_secret' => 'myappsecret',
				'verification' => 'myverif',
			],
		];

		$botman = BotManFactory::create($config);

		//$botman->verifyServices('myverif'); don't work anymore

		$botman->hears('hello', function (BotMan $bot) {
		    $bot->reply('Hello yourself.');
		});

		$botman->listen();

I thought that now the function 'verifyServices' was launched automatically but Facebook returns me an error when I configure the webhook: **Response does not match challenge, expected value="1805657020", received="**

Did I perhaps forget a detail? 
Thank you for your attention!

### Steps To Reproduce:

**Comment by mpociot** [comment]
Please load the driver manually using:
DriverManager::loadDriver(FacebookDriver::class);

This needs to be before creating the botman instance. I’ll add that to the documentation. 

The driver now automatically verify themselves. I’m going to add this to the upgrade guide too :)

**Comment by damienpicca** [comment]
Thanks you for your very quick answer, it works now!

**Comment by simonbarbone** [comment]
HI,
I have the same problem, could you please tell me how I can load the driver in laravel ?  

DriverManager::loadDriver(FacebookDriver::class); 


thanks very much
