### ISSUE TITLE
running a command manually

### ISSUE THREAD

**Issue by sedehi** [botman/botman#517]
- BotMan Version: 2
- PHP Version:7.0
- Messaging Service(s): telegram
- Cache Driver:redis

I would like to run a command without using hears... How can do it  manually?

**Comment by mpociot** [comment]
What exactly do you mean? Please explain it a bit further.

**Comment by sedehi** [comment]
I have two commands in hears: 1- Start 2- add. 

When I receive a "start" message and start command runs, I want to run "add" command after start by myself and not user.

**Comment by mpociot** [comment]
No, that's currently not possible.
You need to structure your code for these commands, so that you can call them separately.
