### ISSUE TITLE
Warning when creatin a bot with BotMan Studio

### ISSUE THREAD

**Issue by johntiror** [botman/botman#518]
- BotMan Version: 2.0.1
- PHP Version: 7.1

### Description:
When I create a new bot with the command "botman new MyAwesomeBot" I see this warning "Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.". Is it expected? If so can I update the BotMan documentation saying that in such case the user shoud open the new folder and run a "composer update" (just to let the user know that it's normal and he's not doing anything wrong)

### Steps To Reproduce:

MBP-di-Stefano:bots stefanogiacone$ botman new ranka
Building your next great chatbot...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

Thanks

**Comment by mpociot** [comment]
I just fixed this and tagged BotMan Studio 1.0.1
