### ISSUE TITLE
Small docs issue

### ISSUE THREAD

**Issue by jbardnz** [botman/botman#522]
Is their a way to make PRs for documentation - would be happy to fix this up myself if it is possible.

Anyway the issue is with the Facebook Getting Started button. The correct command is 
`php artisan botman:facebookAddStartButton`

the docs list it as 
![image](https://user-images.githubusercontent.com/1628446/30045493-d4d78162-9258-11e7-9d86-1fe49c027c51.png)

**Comment by mpociot** [comment]
Yes of course! Please send a pr to https://github.com/botman/docs

Thank you!
