### ISSUE TITLE
Issue Installing/Upgrading to BotMan 2: Incorrect Configuration Steps

### ISSUE THREAD

**Issue by Alexander-Karsten** [botman/botman#523]
- BotMan Version: 2.0.1
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver: None

### Description:
I have found two issues, following your steps with a stand alone app to get a Slackbot working results in unresolvable dependencies.

### Steps To Reproduce:
1. composer require botman/botman
2. composer require botman/driver-slack
3. composer require mpociot/slack-client

Result:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: evenement/evenement[v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v2.1.0, v2.0.0].
    - Can only install one of: evenement/evenement[v2.0.0, v2.1.0].
    - mpociot/slack-client 0.3.1 requires evenement/evenement 2.0.* -> satisfiable by evenement/evenement[v2.0.0].
    - Installation request for mpociot/slack-client ^0.3.1 -> satisfiable by mpociot/slack-client[0.3.1].
    - Installation request for evenement/evenement (locked at v2.1.0) -> satisfiable by evenement/evenement[v2.1.0].

Installation failed, reverting ./composer.json to its original content.
```

**Comment by shealan** [comment]
Getting the same

**Comment by shealan** [comment]
Was it fixed?

**Comment by Alexander-Karsten** [comment]
Hey @shealan there is just some confusion with the documentation. Make sure you select 2.0 in the version in the top left of the docs and then navigate to Slack, you'll see the correct instructions.

I'm not able to raise a new issue as I don't really understand what is happening, maybe you get a better idea?

**Comment by Alexander-Karsten** [comment]
Okay so, after a bit of playing around, you can get past the above issue by simply recording all dependencies in the composer.json at once like such:

```
    "botman/botman": "2.0.*",
    "botman/driver-slack": "1.0.*",
    "mpociot/slack-client": "^0.3.1",
```

However, the current implementation is still broken, when running the example provided on the website you will get `Undefined index: createForRTM` when trying to use the Slack driver.

I have been able to use the new repository by locking myself into my old version `    "botman/botman": "1.5.8",` so I do not have to worry about `mpricot/botman` being deleted from packagist but we really need this fixed please.

**Comment by mpociot** [comment]
This is now fixed with the latest release of the slack driver.

**Comment by Alexander-Karsten** [comment]
Thank you @mpociot! I will give it a try tomorrow.
