### ISSUE TITLE
Is their a way to hook into the Facebook "linked" event

### ISSUE THREAD

**Issue by jbardnz** [botman/botman#524]
Hey,

So I am wondering if I can improve this process:

-User requests an action
-This action requires user to link account, so we send the link account button
-User links account
-Nothing happens so user has to request action again

Facebook sends a webhook when an account is linked successfully - is their anyway to hook into this and then continue the last action they requested?

**Comment by christophrumpel** [comment]
Hey @jbardnz , is this this subscription field `messaging_account_linking` ?

**Comment by jbardnz** [comment]
Yes I believe that is the one.

**Comment by mpociot** [comment]
@jbardnz you can already listen for an `account_linking` event.

```php
$botman->on('account_linking', function ($data, $bot) {
  // Handle account linking
});
```
