### ISSUE TITLE
Hearing attachments didn't work.

### ISSUE THREAD

**Issue by theemfs** [botman/botman#526]
- BotMan Version: dev-master
- PHP Version: 7.0
- Messaging Service(s): telegram
- Cache Driver: LaravelCache

### Description:

Hearing text messages works.
Hearing attachments didn't work

```
    Log::info('webhook fired');
   
    $botman->hears('hello', function (BotMan $bot) {
        $bot->reply('Hello yourself.');
    });

    $botman->receivesImages(function($bot, $images) {
        Log::info('image received');
    });
```
on sending images in log only "webhook fired"

### Steps To Reproduce:

**Comment by mpociot** [comment]
I’m going to update the telegram driver in a bit. 
In the meantime you need to manually load the other telegram attachment drivers. 
See:
https://github.com/botman/driver-telegram/tree/master/src

In your case the telegram photo driver. 

After the update of the driver this is no longer required.
