### ISSUE TITLE
Installing Botman Studio via composer create project gives error

### ISSUE THREAD

**Issue by goodnesskay** [botman/botman#528]
- BotMan Version: #.#.#

- PHP Version:
PHP 5.6
- Messaging Service(s):
- Cache Driver:

### Description:
[InvalidArgumentException]                                   
 Could not find package botman/studio with stability stable.  

### Steps To Reproduce:

**Comment by mpociot** [comment]
Fixed. Please note that BotMan requires at least PHP 7.0

**Comment by David-Crty** [comment]
I'm on php7.0 and I have error when install via composer and Botman Studio : 

> `$ botman new awbot                                                                                                                                                                                                   
> Building your next great chatbot...
> Loading composer repositories with package information
> Installing dependencies (including require-dev) from lock file
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
>     - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>   Problem 2
>     - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (7.0.22) does not satisfy that requirement.
>     - phpunit/phpunit-mock-objects 4.0.4 requires doctrine/instantiator ^1.0.5 -> satisfiable by doctrine/instantiator[1.1.0].
>     - Installation request for phpunit/phpunit-mock-objects 4.0.4 -> satisfiable by phpunit/phpunit-mock-objects[4.0.4].
> 
> BotMan Studio ready! Build an amazing chatbot!`

**Comment by David-Crty** [comment]
Running **composer update** fix the issue
