### ISSUE TITLE
Getting Location

### ISSUE THREAD

**Issue by salahy2** [botman/botman#534]
I have this code

```
$botman->hears('NEAREST_LOCATION', function ($bot) {
    $bot->reply("Location");
	$bot->receivesLocation(function($bot, Location $location) {
	    $lat = $location->getLatitude();
	    $lng = $location->getLongitude();
	    \Log::info($lng);
	});	
});
```

but I am not getting anything, this code in the route, I am using the new version 2.0

any help please ?
thanks

**Comment by mpociot** [comment]
The `receivesLocation` method is a replacement for `hears`.

So instead of hearing for a keyword, you can hear for a location attachment:

```
$bot->receivesLocation(function($bot, Location $location) {
    $lat = $location->getLatitude();
    $lng = $location->getLongitude();
    \Log::info($lng);
});	
```

If you want to ask for a location, you can use a conversation and the `askForLocation` method. See: https://botman.io/2.0/conversations#asking-for-data
