### ISSUE TITLE
Unable to run the the bot with messenger (in case of Botman/Botman) 

### ISSUE THREAD

**Issue by satyamkapoor** [botman/botman#535]
- BotMan Version: #.#.#
- PHP Version: 7.0.23
- Messaging Service(s): FB Messenger
- Cache Driver: NO

### Description:
Hi, I watched a video to understand the workong of botman with facebook messenger https://www.youtube.com/watch?v=ll-QC9h9KxE

So i used all the steps using Mpociot\BotMan and it works nice.
Now when I shift to BotMan\Botman  it doesn't work.
Error : Uncaught Error: Class 'DriverManager' not found in.....

Can you help? Thanks

### Steps To Reproduce:

**Comment by johntiror** [comment]
please try to follow the instructions here: http://christoph-rumpel.com/2017/09/build-a-facebook-chatbot-with-laravel-and-botman-studio/

**Comment by christophrumpel** [comment]
@satyamkapoor I think you're using BotMan but not the Studio version? Have you made sure that you are importing the DriverManger class? `use BotMan\BotMan\Drivers\DriverManager;`

**Comment by satyamkapoor** [comment]
Thanks @christophrumpel  and @johntiror . I think the issue is related to the importing of DriverManager class as the error which I see is "Uncaught Error: Class 'DriverManager' not found in.."

I'll check on this and I think it will work now. :)
