### ISSUE TITLE
account_unlink not working

### ISSUE THREAD

**Issue by salahy2** [botman/botman#538]
I am trying to use the unlink button but I keep getting error, title is not required and when I remove it I get Too few arguments to function 

`ElementButton::create('logout')->type("account_unlink")` title is not required
`ElementButton::create()->type("account_unlink")`  Too few arguments

**Comment by christophrumpel** [comment]
hey @salahy2 , what is an unlink button? Can you show me in the FB docs?

**Comment by mpociot** [comment]
@christophrumpel here it is: https://developers.facebook.com/docs/messenger-platform/send-messages/buttons/logout/

In fact, we already have it in the templates - we just need to add it here: 

https://github.com/botman/driver-facebook/blob/d12326b236b759460e70eb249dcdf859a16cac17/src/Extensions/ElementButton.php#L149

**Comment by christophrumpel** [comment]
Ah ok. Can add it tomorrow.

**Comment by mpociot** [comment]
@christophrumpel don't worry - I'm going to update all drivers later today to fix #537 - then I'll take care of this too 👍

**Comment by christophrumpel** [comment]
👍
