### ISSUE TITLE
No answer in conversation

### ISSUE THREAD

**Issue by aptgorizia** [botman/botman#539]
- BotMan Version: 1.5
- PHP Version: 7.0
- Messaging Service(s):
- Cache Driver:

### Description:
Hello i use botman 1.5 i can't get answer in conversation  this is my code 

$botman->hears('sir', function( $bot) {
    $bot->startConversation(new OnboardingConversation);
});

class OnboardingConversation extends Conversation
{
   protected $size;
	protected $topping;
	protected $address;
	
	public function bidaya()
	{
		
		$this->ask('Where can we deliver your tasty pizza?', function($answer) {
			$this->address = $answer->getText();
			$this->say('Okay. That is all I need.');
			//$this->say('Size: '.$this->size);
			//$this->say('Topping: '.$this->topping);
			$this->say('Delivery address: '.$this->address);
		});
		
		
	}

   

    public function run()
    {
        // This will be called immediately
        $this->bidaya();
    }
}

// start listening
$botman->listen();
( Facebook connexion and app configuration is ok  can use hear fonction and got messages with no problems )

i tried with doctrine but it seem not working even if including doctrine library it generate an error in doctrine code 

the is solutio to use conversation without cache ? 
### Steps To Reproduce:

**Comment by mpociot** [comment]
Conversations need a working cache driver in order to persist the cache state.

Install the doctrine cache package: `composer require doctrine/cache`
```php
use Mpociot\BotMan\Cache\DoctrineCache;

$doctrineCacheDriver = new FilesystemCache(__DIR__);
$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));
```

**Comment by aptgorizia** [comment]
Thanks for reply
i installer doctrine with composer in this path :  vendor/doctrine/cache/lib/Doctrine/Common/Cache

i add thoses  lines 

use Mpociot\BotMan\Cache\DoctrineCache;
use Doctrine\Common\Cache\FilesystemCache;

and those lines  : $doctrineCacheDriver = new FilesystemCache(__DIR__);
$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));

But i got this error  : 

Uncaught Error: Class 'Doctrine\Common\Cache\FilesystemCache' not found

**Comment by aptgorizia** [comment]
Thanks it' worked finnaly i update my compose folder and all is ok

**Comment by Afaq25** [comment]
use Mpociot\BotMan\Cache\DoctrineCache;
use Doctrine\Common\Cache\FilesystemCache; 
use file but coversion start askfirst name..
public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function(Answer $answer) {
            // Save result
            $this->firstname = $answer->getText();
            $this->say('Nice to meet you '.$this->firstname);
            $this->askEmail();
        });
    }
but say "nice to meet you cannot work and not gettext

**Comment by Afaq25** [comment]
$botman->hears('Hy', function($bot) {
    $bot->startConversation(new OnboardingConversation);
});
![screenshot_24](https://user-images.githubusercontent.com/34199261/33981614-622473b2-e0cf-11e7-90de-ba282dae0a1b.png)
