### ISSUE TITLE
$answer->getCallbackId() is empty

### ISSUE THREAD

**Issue by johntiror** [botman/botman#540]
- BotMan Version: 2.0.4
- PHP Version: 7.1
- Messaging Service(s): messenger/telegram
- Cache Driver: redis

### Description:

When a question is asked `$answer->getCallbackId()` is empty

### Steps To Reproduce:

botman.php

```
$botman->hears('callback', function(BotMan $bot) {
    $bot->startConversation(new TestConversation());
});
```

TestConversation.php

```
class TestConversation extends Conversation
{
    public function askSomething() {
        $question = Question::create('test callback id')
            ->callbackId('test')
            ->addButtons([
                Button::create('premimi')->value('spremuto')
            ]);

        $this->ask($question, function (Answer $answer){
            $this->say('callback id: ' . $answer->getCallbackId());
        });
    }

    public function run()
    {
        $this->askSomething();
    }
}
```

<img width="695" alt="schermata 2017-09-16 alle 16 57 02" src="https://user-images.githubusercontent.com/3677019/30515957-2007ff72-9b00-11e7-8270-95e74b584f94.png">

**Comment by mpociot** [comment]
The callback id is only available for slack

**Comment by mikeddeeson** [comment]
I have been looking at Botman for a project and wanted to be able to use the buttons as part of a question. I am not using Facebook/ Slack to build the bot but just rely on the API to build a react app for my bot.

From what you are saying here (along with other closed issues), does the ability to use buttons **only** work when using Slack or Facebook?

Nothing in the documentation seems to indicate this?
