### ISSUE TITLE
Question about function say()

### ISSUE THREAD

**Issue by damienpicca** [botman/botman#541]
- BotMan Version: last
- PHP Version: 7.0.3
- Messaging Service(s): Messenger
- Cache Driver: None

### Description:
Hello, I've a question in that concerning the $botman->say() function to send external message.

In fact my chatbot have to localize flight and when provider that I use push my web page with post request (http://mysite.com/botman.php) I check like it :

**"botman config........"**

**if($_POST.............) { //check if i received post request from my provider
$botman->say("$_POST...........", userid); // if received I can use the information and send it to user
}**
**$botman->listen();**

The problem is that : the say() function doesnt send anything.
I hope that you can help me !
### Steps To Reproduce:

**Comment by mpociot** [comment]
Please pass the driver, that should be used to send the message, as a third parameter:

For example:

```php
$botman->say('message', 'user_id', FacebookDriver::class);
```

You do not need the ´listen` call when you only want to send a message.
