### ISSUE TITLE
Delete messages ?

### ISSUE THREAD

**Issue by salahy2** [botman/botman#543]
Hello guys, sorry I know its not related to the chatbot directly, I am developing chatbot for a bank that use login and get accounts,cards,balance,transfer ...etc but all these are sensitive data, the admin can see everything, do you guys know if I can hide/delete messages from the admin or its not possible ?

Thanks

**Comment by mpociot** [comment]
Which messaging service / driver do you use?

**Comment by salahy2** [comment]
Facebook

**Comment by mpociot** [comment]
Hm I believe the page administrator is always allowed to take a look at the Facebook page inbox. At least I do not know of a way to disable this.

So if you go with Facebook you would certainly need to check security / privacy agreements - especially depending on which country you live in.

**Comment by salahy2** [comment]
Yeah I checked it, its strange they allow it, I am building a chatbot with very sensitive data and the admins can see everything, I saw solution to use webviews which I wont use.
Thanks for the reply :)

**Comment by mpociot** [comment]
No problem.
Do you build the bot with BotMan? Would love to get updated once the bot launches! :)

**Comment by salahy2** [comment]
of course I am using botman from the first release :) and I LOVE IT
