### ISSUE TITLE
PHP Fatal error:  Class 'BotMan\\BotMan\\BotManFactory' not found 

### ISSUE THREAD

**Issue by kishorhase** [botman/botman#546]
We have download the BotMan from the github place src in my document root BotMan/BotMan/

In my document root, we have added index.php file code is below...

```
<?php
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;


// create an instance
$botman = BotManFactory::create($config);

// give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
});

// start listening
$botman->listen();
```

We got the following error...
PHP Fatal error: Class 'BotMan\\BotMan\\BotManFactory' not found

**Comment by sschlein** [comment]
Hi @kishorhase 

That's not how it works. If you don't want to use BotMan Studio, you can install BotMan via composer and start from scratch without a framework or use a different one.

Your steps are:

1. Install composer from https://getcomposer.org/
2. Go to your web root directory and run "composer require botman/botman"
3. Place your index.php in your root directory

**Comment by malucy** [comment]
Fatal error: require(): Failed opening required '/home/vbiz/weatherbot/vendor/au                                 toload.php' (include_path='.:/usr/local/php56/pear') in /home/vbiz/weatherbot/ar                                 tisan on line 18

Anyone know how/where to include this path?
