### ISSUE TITLE
How to add GenericTemplate to quick reply ?

### ISSUE THREAD

**Issue by binhpt2612** [botman/botman#547]
- BotMan Version: 2.0
- PHP Version:7
- Messaging Service(s): Facebook
- Cache Driver:redis

### Description:
How to add GenericTemplate to quick reply like theguardian bot ?

![image](https://user-images.githubusercontent.com/8828376/30739191-b458a216-9fb6-11e7-910a-dbdca1de5bfc.png)

I can't create a question with GenericTemplate .
Do you have an ideal ?
Here my code 

               $listNews = GenericTemplate::create()
                	->addImageAspectRatio(GenericTemplate::RATIO_HORIZONTAL)
                	->addElements($arrElement);
                
                $arrBtn = [     
                    Button::create('yes !')->value('true'),
                    Button::create('no !')->value('false'),
                ];
                
                $bot->types();
                
                $question = Question::create($listNews)
                    ->fallback('sory...')
                    ->callbackId('confirm')
                    ->addButtons($arrBtn);
            
                $this->ask($question, function (Answer $answer) {
                    if ($answer->isInteractiveMessageReply()) {
                        $selectedValue = $answer->getValue();
                        if($selectedValue == 'true'){
                            $bot = $this->bot;
                            $bot->startConversation(new GreetingConversation($bot));
                        }else{

                        }
                    }
                });

### Steps To Reproduce:

**Comment by binhpt2612** [comment]
who cant help ??

**Comment by christophrumpel** [comment]
Hey @binhpt2612 ,

never seen the combination like that before. You can definitely send the generic template and additionally a text with quick replies. So the only difference would be some text between the template and the buttons. Which would still makes sense like "Do you like the suggested articles or do you want more on other topics? (+ quick replies)

Since the text for quick reply buttons is required (https://developers.facebook.com/docs/messenger-platform/send-messages/quick-replies) I cant think of a way right now to achieve the exact same thing. But I would go with the text and quick replies as addition.

**Comment by panserhio** [comment]
Hello
I have the same problem.
How I can solve it without addition text?

Thank you

**Comment by panserhio** [comment]
who cant help ???

**Comment by haikajymada** [comment]
Unfortunately in 2021

```
use BotMan\Drivers\Facebook\Extensions\QuickReplyButton;

$question = Question::create('Great. Can you give me your location?')
            ->addAction(QuickReplyButton::create('test')->type('location'));
```

The error caught in **laravel.log**

local.ERROR: Error sending payload: (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Location Quick Reply is now deprecated on API 4.0. Please refer to our Developer Documentation for more info. at E:\\laragon\\www\\botman-facebook\\vendor\\botman\\driver-facebook\\src\\FacebookDriver.php:517)
