### ISSUE TITLE
facebook verify token.. what does it mean?

### ISSUE THREAD

**Issue by vesper8** [botman/botman#550]
Trying to get facebook default connection working again.. it used to work before.. when the verifyServices fired

now you say that drivers self-verify.. but when I am setting up the webhook on facebook it still asks for a verification token

<img width="835" alt="screenshot 2017-09-25 07 31 34" src="https://user-images.githubusercontent.com/816028/30806421-afcc2920-a1c3-11e7-8f12-a4831e463369.png">

when I don't put one in, or if I put any one in.. it just shows an error with
<img width="455" alt="screenshot 2017-09-25 07 33 36" src="https://user-images.githubusercontent.com/816028/30806476-dfaf7f98-a1c3-11e7-9272-73d515b7e006.png">

This is my BotManController

```
    public function handle()
    {
            DriverManager::loadDriver(FacebookDriver::class);

            $config = config('services.botman');
            $botman = BotManFactory::create($config);


            $botman->hears('hello', function (BotMan $bot) {
                $bot->reply('Hello yourself.');
            });

            $botman->listen();
    }
```

I really wish there was a clear example just to get you started. Could anyone please rectify what is the working way to setup the webhook with the latest iteration?

**Comment by vesper8** [comment]
I was able to get it working by following the example here https://github.com/Xhoii/chatbot_23

Maybe this is very easy to get going when using studio.. but when integrating it to an existing application.. I gotta say the instructions for setting up Facebook could be clearer

It is still very unclear to me the purpose of the /routes/botman.php, why use that at all when you can use the /botman route

**Comment by mpociot** [comment]
@vesper8 you wanted to integrate BotMan into an existing Laravel application?

It would be great if you could help me and send a pull request to the documentation repository, so the documentation can improve.

https://github.com/botman/docs
