### ISSUE TITLE
how can i apply middleware only for specific drivers?

### ISSUE THREAD

**Issue by vesper8** [botman/botman#552]
basically how do I get the driverName? it's protected

I want to use different middleware for Facebook then I do for Slack

**Comment by mpociot** [comment]
You can access it using `$bot->getDriver()->getName()`

**Comment by vesper8** [comment]
I ended up doing exactly that inside my middleware itself

```
        if ($bot->getDriver()->getName() == "Facebook") {
//
}
```

But what I really wanted to do was higher up the chain

```
        $botman = app('botman');
        
        if($botman->driverName == "Facebook") {
            $botmanMiddleware = new FacebookMiddleware();
            $botman->middleware->received($botmanMiddleware);
            $botman->middleware->captured($botmanMiddleware);
            $botman->middleware->heard($botmanMiddleware);
            $botman->middleware->sending($botmanMiddleware);
        }
        
        $botman->hears('GET_STARTED', function (BotMan $bot) {
            $bot->reply("Let's get started!");
        });
        
        ...

        $botman->listen();
```

I tried calling getDriver on the botman instance but that doesn't work. Is it possible to do it at this level?

**Comment by vesper8** [comment]
@mpociot could you answer please. How can I know what driver is being used outside of the middleware?

**Comment by mpociot** [comment]
You can access it using `$botman->getDriver()->getName()` - just like inside the middleware.

**Comment by vesper8** [comment]
Thanks! That works.. dunno why I was having problems before

I find it a little bit odd however that when using the Facebook Bot.. for any interaction including just a simple Hello, `$botman->getDriver()->getName() ` returns 'FacebookVideo'

Can you explain what's going on here @mpociot ?
