### ISSUE TITLE
different persistent menu based on user ?

### ISSUE THREAD

**Issue by vesper8** [botman/botman#553]
I don't think this is possible but thought I would ask

I'm building a bot that initially has limited features, but once you manually link it with another app, then it becomes much more powerful

and one of things I wanted to do was to add way more options in the persistent menu based on whether the user has linked the accounts or not

is this possible?

**Comment by mpociot** [comment]
No, it's not possible to have a dynamic persisted menu on Facebook messenger: 
https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/persistent-menu/
