### ISSUE TITLE
Originating Message on Slack Channel

### ISSUE THREAD

**Issue by seagyn** [botman/botman#556]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver: Laravel

I'm using a webhook from another system as a notification in a Slack channel (with the possibility of a convo later).

However, I can't actually get the bot to say anything in the channel. Here is the code:

```<?php

namespace App\Http\Controllers;

use BotMan\BotMan\BotMan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class GitHubController extends Controller
{
    public function webhook(Request $request){

        $botman = app('botman');

        $botman->say('help', 'channelid', SlackDriver::class);

    	//Log::debug($request->input());

    	return response('ok', 200);
    	
    }
}
```
Any ideas?

**Comment by mpociot** [comment]
Can you log the response of the say method? It returns a response object. I’m originating messages on Slack myself without any problem.
