### ISSUE TITLE
Conversations from referrals are not working

### ISSUE THREAD

**Issue by johntiror** [botman/botman#562]
- BotMan Version: 2.1.0
- PHP Version: 7.1
- Messaging Service(s): facebook
- Cache Driver: redis

### Description:

Conversation started from `$botman->on('messaging_referrals', function($payload, BotMan $bot)` are not working.

### Steps To Reproduce:

in `botman.php`
```
// react to Facebook Referral events
$botman->on('messaging_referrals', function($payload, BotMan $bot) {
    $bot->startConversation(new TestConversation());
});
```
in `TestConversation.php``
```
class TestConversation extends Conversation
{

    public function start() {
        $question = Question::create('test question?')
            ->addButtons([
                Button::create('one')->value('one'),
                Button::create('two')->value('two')
            ]);
        $this->ask($question, function (Answer $answer) {
            $this->say('You said: ' . $answer->getText());
        });
    }

    public function run()
    {
        $this->start();
    }
}
```

The question is asked, but the method `say` is never fired. No errors are showed in logs.
<img width="715" alt="schermata 2017-10-02 alle 00 39 36" src="https://user-images.githubusercontent.com/3677019/31059951-422bd068-a70a-11e7-954c-e2b51b599632.png">

Here the payload coming from Facebook with this link `http://m.me/pixideapp?ref=join_voijcotq`:
```
{
    "object": "page",
    "entry": [
        {
            "id": "651547884999009",
            "time": 1506898409482,
            "messaging": [
                {
                    "recipient": {
                        "id": "651547884999009"
                    },
                    "timestamp": 1506898409482,
                    "sender": {
                        "id": "1273694102759240"
                    },
                    "referral": {
                        "ref": "join_voijcotq",
                        "source": "SHORTLINK",
                        "type": "OPEN_THREAD"
                    }
                }
            ]
        }
    ]
} 
```

**Comment by johntiror** [comment]
Maybe it's related: if you try to do a `$this->bot->getUser()` inside that conversation you'll receive the following exception: 

> BotMan\Drivers\Facebook\Exceptions\FacebookException: Error sending payload: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api in file /Applications/MAMP/htdocs/rank_bot/vendor/botman/driver-facebook/src/FacebookDriver.php on line 426

**Comment by johntiror** [comment]
This is a working workaround:

```
// react to Facebook Referral events
$botman->on('messaging_referrals', function($payload, BotMan $bot) {
    $ref = $payload['referral']['ref']; //currently unused in this example
    $userBotId=$payload['sender']['id'];
    $bot->startConversation(new TestConversation(),$userBotId,FacebookDriver::class);
});
```

**Comment by dhritimanrick** [comment]
Any  Workarounds for facebook checkbox optin ..  
{
    "object": "page",
    "entry": [
        {
            "id": "127170944691708",
            "time": 1507109389806,
            "messaging": [
                {
                    "recipient": {
                        "id": "127170944691708"
                    },
                    "timestamp": 1507109389806,
                    "optin": {
                        "user_ref": "155647"
                    }
                }
            ]
        }
    ]
}

**Comment by johntiror** [comment]
optin can't be solved with this workaround, please open a different issue in order to keep track of this

**Comment by johntiror** [comment]
I'm still getting the error:
> BotMan\Drivers\Facebook\Exceptions\FacebookException: Error sending payload: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api in file /var/www/html/rankbot/vendor/botman/driver-facebook/src/FacebookDriver.php on line 424

**Comment by mpociot** [comment]
@johntiror I looked into this issue right now. This is the expected behavior.
Facebook does not allow to retrieve user information using the `user_ref` parameter. 
After you receive an `opt_in` event, you can reply to the user. The response from this reply will contain the regular recipient_id that you can use to get the user information.

**Comment by johntiror** [comment]
What you say is correct for opt_in, I'm talking about referral. Referral do not contains user_ref

**Comment by mpociot** [comment]
Okay - got it. I fixed another issue in this regard.
