### ISSUE TITLE
No response from botframework

### ISSUE THREAD

**Issue by metanite** [botman/botman#563]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s): BotFramework
- Cache Driver: File

### Description:
I have successfully integrate botman and ngrok in botframework but when i try to chat using the web, the bot will not respond.

> {
    "type": "message",
    "id": "e701ace3437f487ebb86b1c779e026d0|0000001",
    "timestamp": "2017-10-03T03:04:23.376936Z",
    "serviceUrl": "https://webchat.botframework.com/",
    "channelId": "webchat",
    "from": {
        "id": "FnXOp0SFaBh",
        "name": "You"
    },
    "conversation": {
        "id": "e701ace3437f487ebb86b1c779e026d0"
    },
    "recipient": {
        "id": "metro_notifier@XMdTfGrBelE",
        "name": "ChatBot Notifier"
    },
    "textFormat": "plain",
    "locale": "en-US",
    "text": "Hi",
    "channelData": {
        "clientActivityId": "1506999803657.7970960637263507.2"
    }
}

**Comment by metanite** [comment]
when i try to log the reply method. This is the error.

> {
  "error": {
    "code": "BadArgument",
    "message": "Conversation ID not found"
  }
}

**Comment by metanite** [comment]
After some research. I have found out that url to send messages to botframework is changed.

> POST /v3/conversations/{conversationId}/activities/{activityId}

And the current url from the BotFrameWorkDriver is this.

> /v3/conversations/'.urlencode($recipient).'/activities'

I changed the url to

> /v3/conversations/'.urlencode($payload['conversation']['id']).'/activities'

and it works. :)

**Comment by mpociot** [comment]
Hmm okay - can you check if that also works with the Skype implementation?
Is this change documented anywhere?

**Comment by metanite** [comment]
Yes, it will work on skype also. Please check this documentation

https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-send-and-receive-messages

**Comment by mpociot** [comment]
Hm - taking a look at the driver implementation, we are using the conversation ID as the recipient.

https://github.com/botman/driver-botframework/blob/master/src/BotFrameworkDriver.php#L79

**Comment by metanite** [comment]
Please take at look at this.

https://github.com/botman/driver-botframework/blob/master/src/BotFrameworkDriver.php#L190

when the getSender is not empty the from id will be passed to the uri which is not a conversation id

**Comment by mpociot** [comment]
Hm but this only happens when originating messages.
When does the error occur in your case?

**Comment by metanite** [comment]
When i try to chat to the web and in skype. When i try to log the reply method this error will generate.

> {
"error": {
"code": "BadArgument",
"message": "Conversation ID not found"
}
}

**Comment by marcus-campos** [comment]
I had this problem too, it seems that at the moment the botframework driver does not work for the Microsoft WEB option, however it is working normally with Skype and Skype for Business.

**Comment by Mike1002** [comment]
Following on from @metanite - that resolves communication (ie the bot replying) on the web chat service. However the documentation seems to have changed again and the correct URI should now be
`POST /v3/conversations/{conversationId}/activities/{activityId}`

**Comment by mpociot** [comment]
Can you send a pull request with the api changes to the botframework driver repository?

**Comment by Mike1002** [comment]
I've only been able to cobble it together to get this far, so was literally just referring to the docs I'm afraid :(

**Comment by mpociot** [comment]
I released a new version of the driver , that fixed the issue and is now able to reply to users again.
