### ISSUE TITLE
One line buttons for Telegram

### ISSUE THREAD

**Issue by MEGApixel23** [botman/botman#564]
- BotMan Version: 2.1.0
- PHP Version: 7.1
- Messaging Service(s): Telegram
- Cache Driver: Redis

By default buttons in telegram are one per line. I need to group some of them in one line. Actually, I need to obtain the exact opposite from what had been fixed here: https://github.com/botman/botman/issues/132

**Comment by MEGApixel23** [comment]
@mpociot Could you help me with this one, please? Thanks!

**Comment by mpociot** [comment]
That's currently only possible by extending the Telegram driver and changing the methods.
