### ISSUE TITLE
why no wechat driver on Packagist? 

### ISSUE THREAD

**Issue by rooney1989315** [botman/botman#565]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
apparently there is no wechat driver on Packagist anyone help?

### Steps To Reproduce:

**Comment by mpociot** [comment]
Whoops - seems like I forgot to publish it on Packagist. 

Fixed.

https://packagist.org/packages/botman/driver-wechat
