### ISSUE TITLE
wechat driver is for team account rather personal

### ISSUE THREAD

**Issue by rooney1989315** [botman/botman#566]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I think the wechat driver is only for team account rather than personal account, any idea how to apply on personal account? please 

### Steps To Reproduce:

**Comment by mpociot** [comment]
I don’t know much about WeChat personal accounts and the difference between team and personal accounts. What’s the issue?
