### ISSUE TITLE
Error in creating commands

### ISSUE THREAD

**Issue by metanite** [botman/botman#568]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s): BotFramework
- Cache Driver: File

### Description:
I'm trying to create an artisan command the will progmatically say to a certain user. When i try to run the command it will generate this error.

> [Illuminate\Contracts\Container\BindingResolutionException]
  Target [BotMan\BotMan\Interfaces\CacheInterface] is not instantiable while building 
  [App\Console\Commands\chatbotSay, BotMan\BotMan\BotMan].

### Steps To Reproduce:
Here is the code.

`<?php

namespace App\Console\Commands;

use BotMan\BotMan\BotMan;   
use Illuminate\Console\Command;

class ChatbotSay extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'bot:say';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Initiate chat';

    /**
     * The bot handler
     *
     * @var string
     */
    protected $botman;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct(BotMan $bot)
    {
        parent::__construct();

        $this->botman = $bot;
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        return $this->$botman->say("Hello I'm Testbot", '29-xxxxx', BotFramework::class);
    }
}`

**Comment by mpociot** [comment]
Please manually load the BotMan object from the container instead of passing it in the constructor:

```


/**
 * Create a new command instance.
 *
 * @return void
 */
public function __construct()
{
    parent::__construct();

    $this->botman = app('botman');
}
```

**Comment by Punith1234** [comment]
@metanite were you able to solve this .

**Comment by metanite** [comment]
yes. just follow @mpociot answer

**Comment by kidox** [comment]
@metanite can you share a working code? I'm also facing problems sending bot messages from cron, as @tech4solitude.

This is my code:

```
<?php

namespace App\Console\Commands;

use BotMan\BotMan\BotMan;
use Illuminate\Console\Command;


class SendDailyMessage extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'send:dailymessage';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send a daily message to subscribed users';

    /**
     * The bot handler
     *
     * @var string
     */
    protected $botman;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();

        $this->botman = app('botman');
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        return $this->botman->say("Hello I'm Testbot", '662XXXX', TelegramDriver::class);
    }
}
```

Messages seem to be sended but never received. 
However, if I use the same logic in a regular method called from "hears" it works without any problem.
