### ISSUE TITLE
Api.ai muti actions

### ISSUE THREAD

**Issue by rooney1989315** [botman/botman#569]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

Hi I want to access muti actions through APIAI, can I do that?
### Steps To Reproduce:

**Comment by mpociot** [comment]
What exactly do you mean with "multi actions"?

**Comment by rooney1989315** [comment]
like this example, I know I can access muti actions in this way, but is there any other way to make it easier?
$botman->hears('my_api_action1', function (BotMan $bot)
$botman->hears('my_api_action2', function (BotMan $bot)

**Comment by mpociot** [comment]
Yes, you can combine them with a pipe operator, as it's just a regular expression underneath:

```
$botman->hears('my_api_action1|my_api_action2', function(...
```
