### ISSUE TITLE
Question with facebook ButtonTemplate ask() method

### ISSUE THREAD

**Issue by sherwin062** [botman/botman#571]
- BotMan Version: master 
- PHP Version: 7
- Messaging Service(s): Facebook
- Cache Driver: Doctrine

### Description:
I have a conversation, but I cannot get the payload inside the button template in facebook

class OnboardingConversation extends Conversation
{
    protected $firstname;
    
    protected $email;
	
	protected $payload;

    public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function($answer) {
            $this->firstname = $answer->getText();
            // Save 

            $this->say('Nice to meet you '.$this->firstname);
			$this->askHelp();
			
        });
    }
	
public function askHelp()
{
    $question = ButtonTemplate::create('Do you need a help?')
        ->addButton(ElementButton::create('Yes')->type('postback')->payload('yes'))
		->addButton(ElementButton::create('No')->type('postback')->payload('no'))
		;

    $this->ask($question, function ($answer) {
        // Detect if button was clicked:
        if ($answer->isInteractiveMessageReply()) {
            $selectedValue = $answer->getValue(); // will be either 'yes' or 'no'
            $selectedText = $answer->getText(); // will be either 'Of course' or 'Hell no!'
			$this->say('wewew');
        }
		//$this->say('wewew');
    });
}
	

### Steps To Reproduce:

**Comment by sherwin062** [comment]
I cant seem to get the value of postback payload in buttontemplate: 

Recopied the code below:


public function askHelp()
{
    $question = ButtonTemplate::create('Do you need help?')
        ->addButton(ElementButton::create('Yes')->type('postback')->payload('yes'))
		->addButton(ElementButton::create('No')->type('postback')->payload('no'))
		;

    $this->ask($question, function ($answer) {
        // Detect if button was clicked:
        if ($answer->isInteractiveMessageReply()) {
            $selectedValue = $answer->getValue(); // will be either 'yes' or 'no'
            $selectedText = $answer->getText(); // will be either 'Of course' or 'Hell no!'
			$answer->say('Answer: ' .$selectedText);
			$answer->say('Answer: ' .$selectedValue);
        }
		//$this->say('wewew');
    });
}

**Comment by sherwin062** [comment]
when i click on the Yes or No ButtonTemplate, it doesnt seen to register the action since no entry was generated in ngrok. 

Can someone help me in using the method isInteractiveMessageReply() for facebook button template?

**Comment by mpociot** [comment]
@sherwin062 Make sure that you register for the `message_postback` webhooks, as they have the button payloads.

**Comment by sherwin062** [comment]
![webhooks](https://user-images.githubusercontent.com/16132590/31353991-3927e098-ad67-11e7-93a9-ba9db0dd035f.PNG)


I am registered to the message_postbacks but still cant see  some response from webhook.

**Comment by sherwin062** [comment]
I'm getting a response from webhooks now, but it still doesn't seem to recognize the isInteractiveMessageReply() method when clicking the button because the bot doesnt reply

if ($answer->isInteractiveMessageReply()) {
			$payload = $answer->getText();
			$this->say('Answer: ' .$payload);
        }

here is my code snippet for the button click.
