### ISSUE TITLE
Imossible to reply : "Error sending payload"

### ISSUE THREAD

**Issue by damienpicca** [botman/botman#572]
- BotMan Version: master
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver:

### Description:
Hello, since I have update my botman version it is impossible to reply on messenger with my bot.
I really don't understand why.
This code generates an error :

```
               $config = [
			'facebook' => [
				'token' => 'mytoken',
				'app_secret' => 'appsecret',
				'verification' => 'verifcode',
			],
		]; 

	        DriverManager::loadDriver(FacebookDriver::class);
		$botman = BotManFactory::create($config);

		$botman->hears('FACEBOOK_WELCOME', function ($bot) {
		 $bot->reply("test");
		});

               $botman->listen();
```
When I start conversation, the error occurs and it shows me : **Error sending payload:  (500 Internal Server Error)**
This same code worked yet 2 weeks ago.

I thank you !

**Comment by mpociot** [comment]
Have you created a new Get started button payload with a different access token? I just tried it and it works without a problem.

**Comment by damienpicca** [comment]
In fact, the problem will occur regardless of the word that hears() listening for.

A simple botman->say() will trigger the error... I really don't understand, because my config is correct

**Comment by mpociot** [comment]
Please log the response of the `reply` method. It returns a Response object.

**Comment by damienpicca** [comment]
When I use var_dump($bot->reply("test")); it displays nothing and shows the error 500 with "Error sending payload:"

**Comment by damienpicca** [comment]
Aldo I believe that a simple $bot->getUser() will trigger the error.

The problem could be associated with Facebook?
