### ISSUE TITLE
I can't reply message to Telegram

### ISSUE THREAD

**Issue by yorkbc2** [botman/botman#573]
- BotMan Version: 2.0
- PHP Version: 7.1.7
- Messaging Service(s): Telegram
- Cache Driver:  file

### Description:

I have created my bot logic, but I can't reply message to chat bot in Telegram. Always, I have a 200 status in ngrok, but always it without reply. I use BotMan Studio. 

``` php
<?php
namespace App\Http\Controllers;

use Spatie\SslCertificate\SslCertificate;
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use Illuminate\Http\Request;
use App\Conversations\ExampleConversation;

class BotManController extends Controller
{
    public function handle()
    {
        $config = array(
            "telegram" => "XXXXX"
        );

        $botman = BotManFactory::create($config);

        error_log("Worked!");

        $botman->hears("foo", function (BotMan $bot) {
            error_log("First hear worked!");
            $bot->reply("Hello maaaan!");
        });

        

        $botman->listen();
    }
    public function tinker()
    {
        return view('tinker');
    }
    public function startConversation(BotMan $bot)
    {
        $bot->startConversation(new ExampleConversation());
    }
}
```

### Steps To Reproduce:

**Comment by mpociot** [comment]
If you're using BotMan studio, just add your Telegram token in your `config/botman/telegram.php` file. You don't need to manually create the BotMan instance from the factory:

Just like this: https://github.com/botman/studio/blob/master/app/Http/Controllers/BotManController.php#L16

But I would suggest that you place your bot logic inside the `routes/botman.php` file and use the standard BotManController class, as this allows you to write tests for your bot.

**Comment by decadence** [comment]
@mpociot I use BotMan (not Studio) in Laravel Controller, Telegram bot receives messages but reply doesn't work.

```php
Log::info("ACCESS");

DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);

// Create BotMan instance
$botman = BotManFactory::create([
    "token" => "SECRET",
]);

// give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
    Log::info("HELLO");
});

$botman->fallback(function (BotMan $bot) {
    $bot->reply('Sorry, I did not understand these commands. Here is a
     list of commands I understand: ...');
    Log::info("FALLBACK");
});

// start listening
$botman->listen();
```

I can see Log messages but bot doesn't send any answers. I use Localtunnel for HTTPS access.

**Comment by decadence** [comment]
If I print to log reply result I get:
`["[object] (Symfony\\Component\\HttpFoundation\\Response: HTTP/1.0 404 Not Found\r\nCache-Control: no-cache\r\n\r\n{\"ok\":false,\"error_code\":404,\"description\":\"Not Found\"})"] `

**Comment by iampuma** [comment]
Had the same issue, try and use the following if you have a class:

```php
  $this->driver = DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
  $this->config = [
    'telegram' => [
      'token' => '410529884:AAEQQ07m-DNp0RcJJeSI3u4qV7dyUaWg7yg'
    ]
  ];
```
