### ISSUE TITLE
isInteractiveMessageReply() method issue

### ISSUE THREAD

**Issue by sherwin062** [botman/botman#574]
- BotMan Version:master
- PHP Version:7
- Messaging Service(s):facebook
- Cache Driver:Doctrine

### Description:
Related to issue #571.

I'm getting a response from webhook.

![image](https://user-images.githubusercontent.com/16132590/31356683-869d859e-ad71-11e7-861f-6721d15432e0.png)

But it still doesn't seem to recognize the isInteractiveMessageReply() method when clicking the button because the bot doesnt reply

if ($answer->isInteractiveMessageReply()) {
$payload = $answer->getText();
$this->say('Answer: ' .$payload);
}

here is my code snippet for the button click.

### Steps To Reproduce:

**Comment by mpociot** [comment]
How do you instanciate the BotMan instance? You need a persistent cache driver in order for conversation responses to work.

**Comment by sherwin062** [comment]
$doctrineCacheDriver = new FilesystemCache(__DIR__);
$botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));

**Comment by mpociot** [comment]
Sorry, I am unable to reproduce this issue and don't see an issue in the BotMan codebase.
If you have any questions, please join our [Slack team](https://slack.botman.io)
