### ISSUE TITLE
Returning HTTP Response to run as socket [ReactPHP]

### ISSUE THREAD

**Issue by khanhicetea** [botman/botman#575]
- BotMan Version: 2.1.2
- PHP Version: 7.1
- Messaging Service(s):
- Cache Driver:

### Description:

Botman already have `createForSocket` to run as a socket server, but it doesn't work because no HTTP response is returned (It emitted sending a response).

Could we re-structure Botman to compatible with https://github.com/reactphp/http ?

Thanks

### Steps To Reproduce:

**Comment by mpociot** [comment]
I’m not really sure how I feel about the socket implementation. 
That’s why it’s not documented ;)
I feel the Webhook based implementation has a lot of advantages compared to long running processes. 
What would be the advantage in your opinion?

**Comment by khanhicetea** [comment]
Hm.. I think at least we get
- Better performance (no need serialize and unserialize next conversation data)
- Nicer design (can integrate with any framework not only Laravel and PSR7 is good API to consider)

Thanks, btw you did great works :+1:

**Comment by mpociot** [comment]
Can you tell me what we need in order to make this compatible?

And btw: BotMan is framework agnostic and not Laravel dependent at all. It’s just favored with BotMan Studio. 

One main argument against the serialization is that we lose the ability of zero downtime deployments. 
And it adds another possibility to use BotMan, which is confusing in the documentation. That’s also the reason the socket method is currently not in the documentation. 
You still need to have a route, run a socket server and send the data to the socket server.

**Comment by khanhicetea** [comment]
This React HTTP server implementation : 

```php
$server = new React\Http\Server(function (Psr\Http\Message\ServerRequestInterface $request) {
    return new React\Http\Response(
        200,
        array('Content-Type' => 'text/plain'),
        "Hello World!\n"
    );
});
```

So what we need is re-structure Botman to returning Psr7 Response (or Symfony Response  then convert it to Psr7). Could we have a method of Botman class like this

```php
public function handle(ServerRequestInterface $request) : ResponseInterface {
// ...
}
```

> zero downtime deployments

I think this is deployment problem, we can fix it via right strategy (load balancing, failover, ...).

Botman is easy and good way to implements a bot. If it can run as socket (async way from http server to http bot client to reduce I/O blocking), it will be great ! :smile:

**Comment by khanhicetea** [comment]
I have some idea

- We could split the network thing away from Botman core (Botman core receives : **Message** (What user input), **Context** (about sender : user, sender platform) and it returns **BotResponse** (replied message, and replying driver))
- Then we develop front interface on top the Core (HTTP server, Websocket server, SMTP server, ...)

How do you think ?

**Comment by mpociot** [comment]
So right now there are two possibilities on how the driver that should be used is detected:

1. If BotMan is running in a HTTP based environment, the `DriverManager` will get the incoming `Request` object and passes it to every available driver, asking them if they match for this request.
The first driver that returns `true` wins and will be used. (See https://github.com/botman/botman/blob/master/src/Drivers/DriverManager.php#L170-L176 )
After that, the incoming HTTP request is *not* available to the BotMan instance, but only to the driver. So the BotMan instance does not know anything about an HTTP request (and it does not need to).

2. If BotMan is running with a specific driver (for example the Slack websocket based RTM driver), the driver will be passed to the BotMan instance explicitly. (See https://github.com/botman/driver-slack/blob/master/src/Factory.php#L63-L64 )

So we already can develop different front interfaces for the Core.

Using the React PHP HTTP component should be as simple as this:

```php
use Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory;
use BotMan\BotMan\BotManFactory;

$loop = React\EventLoop\Factory::create();

$server = new Server(function (ServerRequestInterface $request) {
	$httpFoundationFactory = new HttpFoundationFactory();
	$symfonyRequest = $httpFoundationFactory->createRequest($request);

	$botman = BotManFactory::create($symfonyRequest);
	$botman->runsOnSocket(true);
	$botman->listen();
});

$socket = new React\Socket\Server(8080, $loop);
$server->listen($socket);

$loop->run();
```

**Comment by khanhicetea** [comment]
Yup, your solution works fine for webhook request but not verify service request (it needs return a custom response)

```php
$server = new Server(function (ServerRequestInterface $request) {
	$httpFoundationFactory = new HttpFoundationFactory();
	$symfonyRequest = $httpFoundationFactory->createRequest($request);

	$botman = BotManFactory::create($symfonyRequest);
	$botman->runsOnSocket(true);
	$botman->listen();

        return new Response(); // Blank Psr7 response with 200 status code
});
```

That why botman need to return a http response instead `listen`

**Comment by mpociot** [comment]
I think we can’t make this change without breaking existing apps that use BotMan, so I’ll skip this feature for now. 
The driver verification would need to return the response instead of sending it instantly. 
Also drivers like slack, where a Bot response could be a HTTP response, would need to return the response object too. 
I’ll reopen this, once I think that we should target a 3.0 - but that’s not going to happen right now. 
In the meantime you could create a package that allows the React Http server to run, while users would need to verify the driver manually.

**Comment by WyriHaximus** [comment]
Hey sorry for the bump, but I'm from the @reactphp team and if you pick this up please let me know, just started out with botman and gladly help out on this subject.
