### ISSUE TITLE
Getting an error below during installation

### ISSUE THREAD

**Issue by nandollo** [botman/botman#577]
- BotMan Version: Botman 2.0
- PHP Version: PHP 7.1.10 
- Cache Driver:

### Description:
I am getting the error below. Am I missing something?

PHP Fatal error:  Uncaught Error: Class 'BotMan\BotMan\BotManFactory' not found in /Applications/MAMP/htdocs/PietroBot/index.php:13
Stack trace:
#0 {main}
  thrown in /Applications/MAMP/htdocs/PietroBot/index.php on line 13

### Steps To Reproduce:
I am accessing the site created for the Facebook webhook request. 
index.php 
---------
<?php
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;

$config = [
    // Your driver-specific configuration
    'facebook_token' => 'here',
    'facebook_app_secret' => 'here'
];

// create an instance
$botman = BotManFactory::create($config);

// give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
    $bot->reply('Hello yourself.');
});

// start listening
$botman->listen();

composer.json
----------------

{
    "require": {
        "botman/botman": "^2.1",
        "botman/driver-facebook": "^1.2"
    }
}

**Comment by mpociot** [comment]
Looks like you have not required your composer autoload.php file

**Comment by nandollo** [comment]
I have added the line below.

require __DIR__ . '/vendor/autoload.php';

Getting this error

Fatal error: Uncaught Error: Class 'DriverManager' not found in D:\xampp7\htdocs\Pietrobot\index.php:12 Stack trace: #0 {main} thrown in D:\xampp7\htdocs\Pietrobot\index.php on line 12

**Comment by christophrumpel** [comment]
Seems like you need to import the namespace for the class
`use BotMan\BotMan\Drivers\DriverManager;`

**Comment by nandollo** [comment]
Thanks, Chris.
I still get an error. May I ask if you could assist me with a compressed folder with all the files needed to run a "Hello World" instance for botman. 

ERROR
=====
Fatal error: Uncaught Error: Class 'Botman\Botman\BotManfactory' not found in D:\xampp7\htdocs\Pietrobot\index.php:19 Stack trace: #0 {main} thrown in D:\xampp7\htdocs\Pietrobot\index.php on line 19
