### ISSUE TITLE
Hears method does not work with question marks ("what is the price?")

### ISSUE THREAD

**Issue by RickD123** [botman/botman#578]
- BotMan Version: 2.1.2
- PHP Version:7.1.10
- Messaging Service(s):
- Cache Driver:

### Description:

Use the following code as a very basic example of Botman:

```
<?php
use App\Http\Controllers\BotManController;

$botman = resolve('botman');

$botman->hears('Hello', function ($bot) {
        $bot->types();
        $bot->reply('Hello!');
});

```
Code works like a charm. If I put in a question mark in the "hears()" method, it does not work, i.e. it returns nothing.

```
<?php
use App\Http\Controllers\BotManController;

$botman = resolve('botman');

$botman->hears('Hello?', function ($bot) {
        $bot->types();
        $bot->reply('Hello!');
});

```
I guess this is a bug?

### Steps To Reproduce:

See above

**Comment by RickD123** [comment]
I forgot to stay that hears() works with exclamation marks for example, but not with question marks.

**Comment by mpociot** [comment]
Since the hears method gets passed to a regular expression marcher, you should escape the question mark
