### ISSUE TITLE
How to welcome a user prior to hearing a message?

### ISSUE THREAD

**Issue by RickD123** [botman/botman#579]
- BotMan Version: 2.1.2
- PHP Version: 5.6
- Messaging Service(s): web
- Cache Driver:

### Description:
Hi,

more of a question really: I am using the web interface via botman:tinker and would like to welcome a user before hearing any message from him/her. So something like "Welcome to the XYZ bot. How can I help?" - how can I do this?

Thanks.

Best regards
RickD

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey,

it depends here again on the Frontend you use. The WebDriver is made so you can use any frontend to receive the messages and show them.
For example in the Tinker example you could add a default start message like this:

`messages: [{'isMine': false, 'user': '🤖',text: 'Welcome you'}],``

so this would be the first shown message.

**Comment by mamarneh** [comment]
Where to add this message please?
