### ISSUE TITLE
HTML formatting botman responses

### ISSUE THREAD

**Issue by RickD123** [botman/botman#583]
- BotMan Version: 2.1.2
- PHP Version: 5.6
- Messaging Service(s): Web
- Cache Driver:

### Description:
Hi,

how can I do HTML formatting for the responses of botman? I am returning multiple elements of a JSON object and I would like to have new lines between each element printed to the user. I tried <br>, <wbr>, \r, \r\n, \n - nothing seems to work in the browser window. Any ideas?

Thanks.

Best regards
RickD

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey @RickD123 , do you mean inside of the text of messages of between multiple message responses?

**Comment by RickD123** [comment]
Hi! In fact I would be interested in both, although my message was referring to the text of messages. So for example, I would like to say something like "Here is the weather for XYZ.<br>Temperature: ..." but as mentioned the newline does not work. Any ideas?

**Comment by christophrumpel** [comment]
Ah ok I see. Just checked our latest project. There we used \n, but I saw that this alone is not working. I need to check how our frontend team did that. I guess the transformed the \n on the frontendside to an <br> but not sure now. Between whole messages you can of course change the HTML and CSS to make more line breaks or space.

**Comment by christophrumpel** [comment]
So one option would be like this:

Use the br inside the text
`$bot->reply("First line <br> second line");`

and output the text as html with Vue like this: (changed example from BotMan tinker : BotManTinker.vue)
`<p class="ChatLog__message" v-html="message.text"></p>`

But it depends on your frontend to "not escape" html.

**Comment by pradiptaagus** [comment]
using `<br>` like `$bot->reply("First` line <br> second line");` doesnt work for me. There any solustion?

**Comment by LiamRoelsWA** [comment]
Does anyone have an idea how to do this in a Question? Im trying to get a question from a database and then type something else on a new line myself every time.

I tried like this but it just prints the `<br>`

`$question = Question::create($foundData . '<br><br>Does this solve your issue?');`

**Comment by lucacanella** [comment]
Same problem here. Tried almost everything and can't get a new line.

**Comment by rudwolf** [comment]
> So one option would be like this:
> 
> Use the br inside the text
> `$bot->reply("First line <br> second line");`
> 
> and output the text as html with Vue like this: (changed example from BotMan tinker : BotManTinker.vue)
> `<p class="ChatLog__message" v-html="message.text"></p>`
> 
> But it depends on your frontend to "not escape" html.

This worked for me! Thanks!

**Comment by JFoxRegistrations** [comment]
<br> works , just make sure that the previous 'try' is not cached
