### ISSUE TITLE
How to react to Wit.Ai boolean entities?

### ISSUE THREAD

**Issue by RickD123** [botman/botman#586]
- BotMan Version: 2.1.2
- PHP Version: 5.6
- Messaging Service(s): Web
- Cache Driver:

### Description:
Hi,

I have Wit.AI integration working. Now I created some intents and it is all working fine. However, I cannot figure out how to react to generic entities, so for example there is one wit/greetings which will fire whenever the user types in a greeting like "hello, hi" etc.

How can I pick this up in my bot?

I tried the following but it did not work:

```
<?php
use App\Http\Controllers\BotManController;
use BotMan\BotMan\Middleware\Wit;

$botman = resolve('botman');

$WitAi = Wit::create('ABC...');

$botman->middleware->received($WitAi);

$botman->hears('greetings', function ($bot) {
    
    $bot->types();
    $bot->reply('Hello and welcome to our chatbot.!');
});
```

Any ideas?

Thank you.

Best regards
RickD

### Steps To Reproduce:

**Comment by RickD123** [comment]
Nope.

**Comment by huuloc4193** [comment]
so far, did you solve it?

**Comment by christophrumpel** [comment]
Hey @RickD123,

Wit.ai isn't supported for quite some time now. I don't think this is even possible anymore.

**Comment by Satyam-Bhalla** [comment]
@christophrumpel @huuloc4193 @RickD123 @Ilnicki010  https://github.com/botman/botman/pull/1195 Update your wit.php code and do something like this:-
`$botman = BotManFactory::create($config);
$wit = Wit::create('Wit token');
$botman->middleware->received($wit);

$botman->hears('greetings', function (Botman $bot) { // greetings is an intent created in wit
    $extras = $bot->getMessage()->getExtras();
    $intents = $extras['intents'];
    $bot->reply("Welcome to this chatbot ");
})->middleware($wit);`
