### ISSUE TITLE
Facebook Messenger Apostrophe

### ISSUE THREAD

**Issue by mikelovely** [botman/botman#602]
- BotMan Version: 2.1.3
- PHP Version: 7.1.10
- Messaging Service(s): Facebook Messenger
- Cache Driver: 

### Description:

I've noticed that when typing via the mobile app using iPhone, an apostrophe is the "curved" version, but on the desktop service, the apostrophe is a "straight up and down" version.

This happened to impact my bot as he was waiting for a specific phrase that expected an apostrophe but only the "straight up and down" version was being catered for.

I'm not really suggesting anything is wrong with BotMan. I just found this behaviour surprising - perhaps it could be added to the documentation?

### Steps To Reproduce:

Create a Facebook Messenger bot. Use an apostrophe in the expected `$pattern` and try sending from both desktop and iPhone app.

**Comment by mpociot** [comment]
Thanks for reporting this. As you already mentioned, this is not an issue with BotMan itself. If you feel like this could be added to the documentation, please make a PR to the https://github.com/botman/docs repository. 

Thank you!
