### ISSUE TITLE
Request: Add support for IBM's Watson AI/conversation service

### ISSUE THREAD

**Issue by RickD123** [botman/botman#603]
- BotMan Version: n/a
- PHP Version: n/a
- Messaging Service(s): n/a
- Cache Driver: n/a

### Description:
Hi,

apart from supporting Wit.AI and Api.Ai it would be great for Batman to support IBM's Watson AI/conversation service.

Thanks.

Best regards
RickD

### Steps To Reproduce:

**Comment by mpociot** [comment]
Closing this for now - any help on this is highly appreciated. I'll come back to this, once I have the time.
