### ISSUE TITLE
allow closures AND callback for botman->on

### ISSUE THREAD

**Issue by di5abled** [botman/botman#605]
- BotMan Version: 2.1.3
- PHP Version: 7.1
- Messaging Service(s):
- Cache Driver:

### Description:
Also allow to pass callback to `$botman->on` (like for `$botman->hears`) to be more flexibel. 

### Steps To Reproduce:
https://github.com/botman/studio/issues/37

**Comment by mpociot** [comment]
Would you like to send a PR to enable this feature?

**Comment by di5abled** [comment]
could you release this version? then we can activate our route caching in laravel again

**Comment by di5abled** [comment]
I think we also need this for '$botman->fallback', maybe I'm able to make a PR the next days
