### ISSUE TITLE
Facebook integration errors

### ISSUE THREAD

**Issue by tommiekn** [botman/botman#609]
- BotMan Version: 2.1.3
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: Botman studio

### Description:

Hi

I have installed Botman Studio and followed the docs to install the facebook driver.

I were unable to validate the request on the webhook so i started to debug the driver and found the problem, all the variables from the config was returning null.

In FacebookDriver.php,  these vars doesn't return any value: (consider the facebook.php settings file is correctly set, as well with .env conf)
```
$this->config->get('token')
$this->config->get('app_secret')
$this->config->get('verification')
```

To fix the issue i've just created some static variable in the driver file and used it to validate the hook, all working, also if thats not a real fix.

Then I've tried then to execute this from shell:

`php artisan botman:facebookAddGreetingText`

and i got back: 

> Something went wrong: An active access token must be used to query information about the current user.

I believe this could be still related to what i just reported as system doesn't load the config basically.

Thank you

**Comment by mpociot** [comment]
@tommiekn have you configured the app correctly? 
Did you modify the `config/botman/facebook.php` file?

**Comment by tommiekn** [comment]
@mpociot yes. i have followed the docs, edited .env and facebook.php with token, secret and verification.

If i try to echo any of these from FacebookDriver.php it returns no value.

```
$this->config->get('token')
$this->config->get('app_secret')
$this->config->get('verification')
```

For my understanding, the facebook.php file doesnt get parsed for some reason

**Comment by tommiekn** [comment]
Nevermind this issue, i have discovered the error and it was unrelated to your app. 

Thanks!

**Comment by FeChagas** [comment]
@tommiekn can you describe how do you managed to solve this issue? I'm having the very same problem. Thank you.

**Comment by salahy** [comment]
@FeChagas you should publish configuration file for the botman using php artisan vendor:publish
