### ISSUE TITLE
messenger not responding

### ISSUE THREAD

**Issue by aldrinmagno** [botman/botman#614]
- BotMan Version: ~2.0
- PHP Version: 7.1.10
- Messaging Service(s): driver-facebook: ^1.2
- Cache Driver:n/a

Description:

I have followed this tutorial http://christoph-rumpel.com/2017/09/build-a-facebook-chatbot-with-laravel-and-botman-studio/ to the letter and was successful in setting up the webhook.

Unfortunately, chatbot is not responding to anything. Tinker is working good.

Steps To Reproduce:
follow this steps
http://christoph-rumpel.com/2017/09/build-a-facebook-chatbot-with-laravel-and-botman-studio/

**Comment by mpociot** [comment]
Please make sure that you are writing the Facebook chatbot as a page administrator.
Use a tool like ngrok / Laravel valet to see incoming requests when testing your chatbot.

If the problem remains, feel free to join our [Slack team](https://slack.botman.io) to ask additional questions.
