### ISSUE TITLE
ButtonTemplate  class not found

### ISSUE THREAD

**Issue by tommiekn** [botman/botman#615]
- BotMan Version: 2.1.3
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: Botmanstudio

### Description:

Hi, I'm using botman studio,  and trying to use ButtonTemplate method from botman.php routes file but can't make it work.

I think this is more an error of my setup than a  bug, anyway,  I've tried to load:
use Mpociot\BotMan\Facebook\ButtonTemplate;

but doesnt find the class.

I been using laravel back in the years but it has been a while and i'm unable to understand what should be the best way to use it with botman studio. Like not having logic in botman.php but in the controller or somewhere else. Im not using conversations yet as i dont need for the current develop of the bot.

Beside the ButtonTemplate problem, If you could suggest a default setup would be great, as now im using botman.php for everything and calling the controller for some method like:
$controller = new BotManController;
$controller->logUser($user->getId());

Thank you,

**Comment by mpociot** [comment]
@tommiekn You are loading the class from the wrong namespace.
Since BotMan 2.x everything moved from my personal namespace to the `BotMan` namespace.

Regarding the default setup: I think it depends on the size of your commands. Simpler commands could just be closures inside the botman.php - larger commands should be moved into their own classes / controllers.

**Comment by tommiekn** [comment]
@mpociot I have tried already with : 

use Mpociot\BotMan\Facebook\ButtonTemplate;
use BotMan\BotMan\Facebook\ButtonTemplate;
use BotMan\Facebook\ButtonTemplate;

None of these works in botman.php

As for the default setup, for the size of this application i could use botman.php only to make the calls and handle the responses, then forward to conversations if its the case.
I just need a place to write the logic, some recurrent function or so.
Should i keep using the controller and calling it directly as I'm doing it now (See the previous message) or should i create a separate class and just initialize it instead the controller?
Sorry for the probably very stupid question, just curious at whats the best setup to start.

**Comment by tommiekn** [comment]
@mpociot I have tried already with : 

use Mpociot\BotMan\Facebook\ButtonTemplate;
use BotMan\BotMan\Facebook\ButtonTemplate;
use BotMan\Facebook\ButtonTemplate;

None of these works in botman.php

Could you help?

**Comment by tommiekn** [comment]
Fixed with

use BotMan\Drivers\Facebook\Extensions\Element as Element;
use BotMan\Drivers\Facebook\Extensions\ElementButton as ElementButton;
use BotMan\Drivers\Facebook\Extensions\ButtonTemplate as ButtonTemplate;
use BotMan\Drivers\Facebook\Extensions\GenericTemplate as GenericTemplate;
use BotMan\Drivers\Facebook\Extensions\ListTemplate as ListTemplate;
