### ISSUE TITLE
Storage functionality in conversation file

### ISSUE THREAD

**Issue by tommiekn** [botman/botman#618]
- BotMan Version: 2.1.5
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: File

### Description:

Hi,

How can i use the storage functionalities inside a conversation ?

on botman.php i've loaded : 
`use BotMan\BotMan\Storages\Storage;`

and this works:

```
$bot->userStorage()->save([
    			'userid' => $userid
			]);

$userinformation = $bot->userStorage()->find();
$element = $userinformation->get('userid');
$bot->reply($element);
```

However in the conversation i can't get the right way to use it as i don't have $bot and if i call it statically doesn't work.

Thank you

**Comment by filippotoso** [comment]
Use $this->bot to access the botman instance within a conversation.
