### ISSUE TITLE
Originating Messages Implement Process

### ISSUE THREAD

**Issue by rubelbitm** [botman/botman#619]
- BotMan Version: 2.0
- PHP Version:7.1
- Messaging Service(s):Facebook Messanger
- Cache Driver:n/a

### Steps To Reproduce:

**Comment by mpociot** [comment]
Please take a look at the documentation. It describes how you can originate messages:

https://botman.io/2.0/sending#originating-messages

**Comment by rubelbitm** [comment]
I see this. If you send any example code then it's very helpful for me.@mpociot

**Comment by christophrumpel** [comment]
@rubelbitm it is really nothing more than that:

`$botman->say('Message', 'my-recipient-user-id', TelegramDriver::class);`

You call the say method with `message`, `recipient-id` and the class name of the driver. You can trigger this with an URL or with Laravel Artisan Command to trigger it with a command / cronjob. Hope that helps.

**Comment by gborgonovo** [comment]
OK, maybe I had to knwo it, but I missed and spent some time to get the issue...

Here it is the process.
`<?php
...
use BotMan\Drivers\Telegram\TelegramDriver; // <- this is important
...
class BotManController extends Controller
{
...
	public function sendDailyEvents()
	{
                $botman = app('botman'); // <- this is important
	        $botman->say($message, $event->ownerid, TelegramDriver::class,['parse_mode' => 'HTML']);
	}
}
`
I added `['parse_mode' => 'HTML']` to get formatted text.

I hope this can save time to someone.
