### ISSUE TITLE
Method names typo in Docu: skipConversation & stopConversation

### ISSUE THREAD

**Issue by dorjeduck** [botman/botman#624]
- BotMan Version: 2.0.0
- PHP Version: 7.1
- Messaging Service(s):
- Cache Driver:

### Description:
Thanks for this great project.

There seems to be two typos in the docu

> While being in a conversation it is sometimes useful to stop it for a certain reason. In order to make this possible there a two methods available in every conversation class: skipConversation() and stopConversation()

Digging into the source code as i couldn't get this to work revealed that the methods in the Conversation Class are called

skip**s**Conversation & stop**s**Conversation

These typos - if i am right - are also in the source code example

> public function stopConversation(IncomingMessage $message)
	{
		if ($message->getText() == 'stop') {
			return true;
		}
		return false;
	}
	public function skipConversation(IncomingMessage $message)
	{
		if ($message->getText() == 'pause') {
			return true;
		}
		return false;
	}

### Steps To Reproduce:

**Comment by mpociot** [comment]
Thank you. The documentation is modified.
