### ISSUE TITLE
Originating messages with additional parameters is broken

### ISSUE THREAD

**Issue by crocodele** [botman/botman#627]
- BotMan Version: 2.1.0
- PHP Version: 7.0.25
- Messaging Service(s): Slack
- Cache Driver: -

### Description:

Sending messages using `$botMan->say()` and additional parameters doesn't seem to work anymore. This is probably due to https://github.com/botman/botman/commit/b561e1afe9fda6ee2b557384ff0126695302b4cf. If a string key is present in both arrays, `array_merge()` uses the later value while `array_merge_recursive()` creates an array with both values, which is probably not the behaviour wanted in those driver methods. Example:

```
$parameters = ['as_user' => true, 'token' => 'ABC123', 'channel' => 'A123456'];
$additionalParameters = ['as_user' => false];

$merged = array_merge($parameters, $additionalParameters);
print_r(var_export($merged, true));
/* output:
array (
  'as_user' => false,
  'token' => 'ABC123',
  'channel' => 'A123456',
)
*/ 

$recursiveMerged = array_merge_recursive($parameters, $additionalParameters);
print_r(var_export($recursiveMerged, true));
/* output:
array (
  'as_user' =>
  array (
    0 => true,
    1 => false,
  ),
  'token' => 'ABC123',
  'channel' => 'A123456',
)
*/
```

### Steps To Reproduce:

```
DriverManager::loadDriver(SlackDriver::class);

$botMan = BotManFactory::create([
    'slack' => [
        'token' => 'SLACK_TOKEN',
    ],
]);

$botParameters = ['as_user' => false, 'username' => 'Sample bot', 'link_names' => true];

$botMan->say('Sample message', '#sample_channel', SlackDriver::class, $botParameters);
```

### EDIT: Suggested fix

I bumped into [`array_replace_recursive`](http://php.net/manual/en/function.array-replace-recursive.php), which should do the trick. If that looks good to you, I can create PRs if you want.

**Comment by mpociot** [comment]
Can you create a PR with the suggested change? If all tests pass, I don't have a problem merging the change!

**Comment by crocodele** [comment]
@mpociot Sure, I'll start with the Slack drivers, as those are the ones I'm most familiar with.
