### ISSUE TITLE
Storing data in Botman 2 Conversations (to use in the answer)

### ISSUE THREAD

**Issue by martonbaranyai** [botman/botman#628]
- BotMan Version: 2.1.3
- PHP Version: 7.1
- Messaging Service(s): Facebbok
- Cache Driver: Laravel default

### Description:

Silly fast example. $this->office is NULL in the answer, even if it was an integer, but ideally I would love to have that as an Eloquent model.

I'm guessing the problem is that conversations don't store data. But I read they used to in Botman 1.X

Any help or hints to solve this? 

Thanks!

<img width="918" alt="screen shot 2017-11-14 at 19 24 04" src="https://user-images.githubusercontent.com/3105178/32797446-12dc5370-c972-11e7-9d99-c5f270f74d04.png">

### Steps To Reproduce:

Spin up a Facebook bot, and start this conversation:

`
class ExampleConversation extends Conversation
{
    /**
     * @var Office
     */
    private $office;

    /**
     * ExampleConversation constructor.
     * @param Office $office
     */
    public function __construct(Office $office)
    {
        $this->office = $office;
    }

    /**
     * First question
     */
    public function outOfOffice()
    {
        $question = Question::create("Hi! How can we help you?")
            ->fallback('Unable to ask question')
            ->callbackId('how_can_we_help');

        return $this->ask($question, function (Answer $answer) {
            $this->say("We are sorry but {$this->office->title} is not available this time.");
        });
    }
}
`

**Comment by mpociot** [comment]
I'm unable to reproduce this.

Example:

```php
class ExampleConversation extends Conversation
{
    protected $data;

    public function __construct($data)
    {
        $this->data = $data;
    }

    public function run()
    {
        return $this->ask("Data in question is: ".$this->data, function (Answer $answer) {
            $this->say("Data in answer is: ".$this->data);
        });
    }
}
```

In `routes/botman.php`:
```php
$botman->hears('test', function($botman) {
    $botman->startConversation(new ExampleConversation('foo'));
});
```

**Comment by martonbaranyai** [comment]
Auch, this is weird. I tried your exact example, it was really working. Then I put an eloquent model in $data, and even that worked. Thanks for your help! Looks like the issue is something else...

**Comment by martonbaranyai** [comment]
Ok I think I found it. Property can't be "private", it does not work with private

**Comment by mpociot** [comment]
Okay Great.
