### ISSUE TITLE
'botman new' doesn't download master

### ISSUE THREAD

**Issue by goodbytes-gb** [botman/botman#632]
Running `botman new` downloads 2.1.0, which prevents the Facebook driver from working, it has an error:

`Call to undefined method BotMan\BotMan\Messages\Incoming\IncomingMessage::setText()`

This is fixed in a later version but it is not immediately clear what causes the Facebook driver to fail on 2.1.0

Not sure if that's intended behaviour but thought it may help others out, it took me quite a while to figure out why I was not able to receive a response from Botman, thinking the problem was related to Facebook configuration.

(Possibly other drivers but only tested with Facebook)

**Comment by mpociot** [comment]
Fixed 👍
