### ISSUE TITLE
Google home driver

### ISSUE THREAD

**Issue by marcus-campos** [botman/botman#633]
Does anyone have any plans to implement a driver for Google home?

**Comment by mpociot** [comment]
Yes, I do have plans to integrate the driver but I currently don't have a timeframe for this.

**Comment by marcus-campos** [comment]
Do you have any "kickstart" so I can start developing this driver?

**Comment by mpociot** [comment]
@marcus-campos I have plans on creating a skeleton project for a custom BotMan driver, but I haven't found the time to do it yet.
You can probably use the Alexa driver as a starting point. Let me know if you need any help with the implementation.

**Comment by barryvdh** [comment]
If that uses the same API as Google Assistant, take a look here: https://github.com/botman/driver-google-assistant
