### ISSUE TITLE
verifyRequest   (Facebook).

### ISSUE THREAD

**Issue by rafaelarapiracati** [botman/botman#635]
- BotMan Version: 2.1.0
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: doctrine

### Description:

Hello, I'm having problems with my bot. (Facebook).
I was not able to validate though I read botman/botman#593 and changed the verifyRequest method to echo $ request->get('hub_challenge'); and I was able to validate.

### Steps To Reproduce:

"botman/driver-facebook": "^1.3"
However the return log
\Log::info('verification:'.$request->get('token'). 'hub_mode:'.$request->get('hub_mode').' - hub_verify_token: ' . $request->get('hub_verify_token') );

log laravel
[2017-11-15 21:17:26] local.INFO: verification:hub_mode:subscribe - hub_verify_token:
[2017-11-15 21:18:53] local.INFO: verification:hub_mode:subscribe - hub_verify_token:

it is always empty.
I do not know if this can have any relation, but my bot does not respond

Test with web bot tinker is working

routes/botman.php
############################
hears('Hi', function ($bot) { $bot->reply('Hello!'); }); 
$botman->hears('Start conversation', BotManController::class.'@startconversation'); 

############################## Thanks for the help.

**Comment by mpociot** [comment]
Sorry, I am unable to reproduce this issue.
Please make sure to use the latest BotMan and Facebook Driver version available.
