### ISSUE TITLE
How do I get a list drivers?

### ISSUE THREAD

**Issue by Telegramsrv** [botman/botman#637]

**Comment by salahy2** [comment]
did you try this ?
`php artisan botman:list-drivers
`
https://botman.io/2.0/botman-studio#list-drivers

**Comment by Telegramsrv** [comment]
Сan not find the code for this class?

**Comment by Telegramsrv** [comment]
https://github.com/botman/studio-addons/blob/18e93eba69d85deefdfc8cc56434d0d004d0cafb/src/Console/Commands/BotManListDrivers.php 
found
