### ISSUE TITLE
Callback for location is not fired from conversation

### ISSUE THREAD

**Issue by neandher** [botman/botman#639]
- BotMan Version: 2.1.3
- PHP Version: 7.*
- Messaging Service(s): Facebook
- Cache Driver: Psr6Cache

### Description:
I try to get location for user but is not working :( 
I get the message "Send location" and I send location but nothing happen after it.
The post with coordinates is received, but the callback is not fired.
Help pls!!!

I use Symfony Framework.

<pre>
$this->askForLocation(
            'Send location',
            function (Location $location) {
                $this->say('Received: ' . print_r($location, true));              
            },
            null,
            [
                'message' => [
                    'quick_replies' => json_encode([
                        [
                            'content_type' => 'location'
                        ]
                    ])
                ]
            ]
        );
</pre>

**Comment by neandher** [comment]
I changed adapter cache, but not work to fire callback in askForLocation in Symfony :disappointed:
Only works with laravel cache????

$adapter = new ApcuAdapter();
BotManFactory::create($config, new SymfonyCache($adapter));

$adapter = new ApcuAdapter();
BotManFactory::create($config, new Psr6Cache($adapter));

$adapter = new FilesystemAdapter();
BotManFactory::create($config, new Psr6Cache($adapter));

$adapter = new FilesystemAdapter();
BotManFactory::create($config, new SymfonyCache($adapter));

$adapter = new PhpFilesAdapter();
BotManFactory::create($config, new Psr6Cache($adapter));

$adapter = new PhpFilesAdapter();
BotManFactory::create($config, new SymfonyCache($adapter));

**Comment by mpociot** [comment]
I'm not sure how you setup your cache adapter - is the target directory writable?
I used this example with BotMan and it worked:

```php
$cache = new FilesystemAdapter('', 0, base_path('storage'));
            
BotManFactory::create($config, new SymfonyCache($cache));
```

**Comment by neandher** [comment]
Still not work :(

The target directory is writable.

config: https://github.com/neandher/my-first-chatbot/blob/master/src/AppBundle/Bot/Botman.php
conversation location: https://github.com/neandher/my-first-chatbot/blob/master/src/AppBundle/Conversations/LocationConversation.php
messenger: https://www.messenger.com/t/355383231569532 (Type **location** to test)

**Comment by sugoireed** [comment]
Had a similar problem. The solution is that you need to also import/load/add the location driver for the driver you are using i.e Facebook Location driver

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookLocationDriver::class);

**Comment by neandher** [comment]
Thank you @sugoireed , it's works!!!! \o/

<pre>
$config = [
            'facebook' => [
                'token' => $this->token,
                'app_secret' => $this->secret,
                'verification' => $this->verification,
            ],
            'botman' => [
                'conversation_cache_time' => $this->conversationCacheTime
            ]
        ];

        DriverManager::loadDriver(FacebookDriver::class);
        DriverManager::loadDriver(FacebookLocationDriver::class);

        $adapter = new FilesystemAdapter('', 0, $this->cacheDir);

        return BotManFactory::create($config, new SymfonyCache($adapter));
</pre>
