### ISSUE TITLE
Not able to connect with MySQL database

### ISSUE THREAD

**Issue by suhasadhav** [botman/botman#640]
- BotMan Version: 2.0
- PHP Version: 7.0
- Messaging Service(s): tinker
- Cache Driver:

### Description:
I am not able to reply from MySQL database in laravel botman. Also not able to produce buttons in reply.
For connectivity with MySQL tried everything I know, Laravel Model/direct connection to database using mysqli_connect(), but its not working.

### Steps To Reproduce:

**Comment by mpociot** [comment]
I'm using BotMan in combination with Eloquent models and database connections. Don't think this is a problem related to BotMan itself.
