### ISSUE TITLE
Codeigniter - Conversations - bot not replying

### ISSUE THREAD

**Issue by pohkit91** [botman/botman#641]
- BotMan Version: 2.1
- PHP Version: 7.0.12
- Messaging Service(s): Facebook
- Cache Driver: Codeigniter
- Codeigniter version: 3.1.6

### Description:
Follow as per [Cache Drive](https://botman.io/2.0/cache-drivers#codeigniter) guide to setup
and setup Conversations & it's not working...

More info @ this [stackoverflow](https://stackoverflow.com/questions/47499424/codeigniter-botman-conversations-method-not-replying) link

- Test files [fbchatbot.zip](https://github.com/botman/botman/files/1504609/fbchatbot.zip)
- Mainly I'm using these 2 files **application/controllers/Bot.php** & **application/libraries/Botconversations/**

**Comment by pohkit91** [comment]
Sorry guys, I overlook on a simple syntax issue.. everything is working fine right now..

Instead of :
$bot->startConversation(OnboardingConversation);

I've update my codes to :
**$bot->startConversation(New OnboardingConversation);**

**Comment by wilfredonoyola** [comment]
Hi, @mavichow. Could you help me with some advices for setup correctly the project on Codeigniter?

Thanks!
