### ISSUE TITLE
Attempted to call function "curl_init" from namespace "BotMan\BotMan\Http".

### ISSUE THREAD

**Issue by JuanWilde** [botman/botman#642]
- BotMan Version: 2.1
- PHP Version: 7.1
- Messaging Service(s): slack
- Cache Driver: Array

### Description:
Attempted to call function "curl_init" from namespace "BotMan\BotMan\Http".

### Steps To Reproduce:
    public function createBotman()
        {
            DriverManager::loadDriver(SlackDriver::class);
            $botman = BotManFactory::create([
                'slack' => [
                    'token' => $this->container->getParameter('slackbot_token'),
                ],
            ]);

            return $botman;
        }

**Comment by mpociot** [comment]
This looks like you don't have the PHP curl extension installed. Please check that and try again.
