### ISSUE TITLE
How to send image within localhost

### ISSUE THREAD

**Issue by metanite** [botman/botman#643]
- BotMan Version: 2.1
- PHP Version: 7.0
- Messaging Service(s): Facebook Messenger
- Cache Driver: File

### Description:
First I just want to thank you for this wonderful framework.

How to send image attachment within the localhost? I tried this but it wont work.

### Steps To Reproduce:
$image_url = asset('image/logo.jpg');

$image = new Image($image_url);

$message    = OutgoingMessage::create('Sample Photo')
                      ->withAttachment($image);

**Comment by mpociot** [comment]
Most messaging services don’t send local URLs but only allow you to send URLs to files. 
So you need to make sure that your image is available through a public HTTP url.

**Comment by metanite** [comment]
I'm using ngrok so the url will look like this http://630aa8ac.ngrok.io/image/metro.jpg. That does count as public url? I tried using the link in the browser and it loads.

**Comment by herleeyandi** [comment]
@metanite I also doing that but not working, do you know how to use ngrok to send our local image files?

**Comment by metanite** [comment]
No. I just uploaded my image files to an image hosting site.

**Comment by MarcoPostiglione** [comment]
Hi all, is there any news? 
Using a valid http url it works properly but with ngrok or a custom rest service that returns an image with FB it doesnt work. I read on FB documentation that it's also possible send file via curl in this approach:

curl  \
  -F 'message={"attachment":{"type":"image", "payload":{"is_reusable":true}}}' \
  -F 'filedata=@/tmp/shirt.png;type=image/png' \
  "https://graph.facebook.com/v2.6/me/message_attachments?access_token=<PAGE_ACCESS_TOKEN>"

is it possible to use the same approach with botman?

Regards,
M
