### ISSUE TITLE
Auto-responding on Facebook comments

### ISSUE THREAD

**Issue by XAPKIB** [botman/botman#649]
Can I use the Botman for autoresponding on Facebook Comments through Messenger like it on ManyChat or ChatFuel? And how can I do it when I knod ID of a post?

**Comment by richdynamix** [comment]
@XAPKIB This is not a Messenger API feature that Botman can listen for. What you will need is the Facebook Pages Real Time API to listen for comments or likes on a page. When this happens you will receive the Facebook's user profile ID which you can use in Botman to construct a message to the user - 

```
$botman->say('Message', 'facebook-profile-id', FacebookDriver::class);
```
Hope that helps.

**Comment by mpociot** [comment]
As @richdynamix said, this is not part of the Messenger features.
