### ISSUE TITLE
add Quick Replies to botman

### ISSUE THREAD

**Issue by medozeus** [botman/botman#651]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

like this image
[https://i.stack.imgur.com/Xbb3k.png](https://i.stack.imgur.com/Xbb3k.png)

### Steps To Reproduce:

**Comment by Jeroen-G** [comment]
Check this out: https://botman.io/2.0/conversations#asking-questions

**Comment by medozeus** [comment]
thank you :) 👍
