### ISSUE TITLE
Request Location when NOT in Conversation

### ISSUE THREAD

**Issue by zynamis** [botman/botman#652]
- BotMan Version: 2.1.
- PHP Version:7+
- Messaging Service(s):Facebook Messenger
- Cache Driver:Facebook

### Description:
I am trying to ask for location and need to do it outside of the Conversation context (Not within a conversation). I am able to ask for the location using the code below but do not get the Callback locatio n receives location.

$botman->hears('{loc}', function (BotMan $bot, $loc) {
           $bot->reply($message, [
            'message' => [
                'quick_replies' => json_encode([
                    [
                        'content_type' => 'location'
                    ]
                ])
               ]
              ]);
       });

  $botman->receivesLocation(function($bot, Location $location) {
      $lat = $location->getLatitude();
      $lng = $location->getLongitude();

      Log::info("Loc".$lat.$lng); //This is never logged/called back

    });

   $botman->listen(); 

### Steps To Reproduce:

**Comment by mpociot** [comment]
I just tested this and it works for me. Please make sure to also import the `Location` class or remove the typehint.

**Comment by sugoireed** [comment]
Had a similar proble. The solution is that you need to also import/load/add the location driver for the driver you are using i.e Facebook Location driver

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookLocationDriver::class);
