### ISSUE TITLE
Unserialize Error Exception

### ISSUE THREAD

**Issue by YesayaSoftware** [botman/botman#655]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s): Facebook Messenger
- Cache Driver: database

### Description:
message: "unserialize(): Error at offset 75 of 78 bytes", exception: "ErrorException",…}
exception
:
"ErrorException"
file
:
"/app/vendor/laravel/framework/src/Illuminate/Cache/DatabaseStore.php"
line
:
81
message
:
"unserialize(): Error at offset 75 of 78 bytes"

### Steps To Reproduce:
This occurs when I send the message on Tinker and also through Facebook Messenger

**Comment by mpociot** [comment]
Seems like this is an issue with database caching. Can you switch to a different cache driver and try it again?
