### ISSUE TITLE
Send Welcome Message After Scan Messenger Code

### ISSUE THREAD

**Issue by dara-t** [botman/botman#656]
- BotMan Version: #.#.#
- PHP Version: 7.1.12
- Messaging Service(s): messaging_referrals
- Cache Driver:

### Description:

I try to use Messaging_referrals event to send welcome message when user "Scan Messenger Code" But see the event not happen. In log also not see any event happen. 

### Steps To Reproduce:
I have read follow this document on facebook 
**https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_referrals**

class OnboardingConversation extends Conversation
{
    public function start() {
        $this->ask('How are you ?', function (Answer $answer) {
            $this->say('You said: ' . $answer->getText());
        });
    }
    public function run()
    {
        $this->start();
    }
}

$botman->on('messaging_referrals', function($payload, $bot) {
    $userBotId=$payload['sender']['id'];
    $bot->startConversation(new OnboardingConversation(),$userBotId,$fbdriver);
//    $bot->startConversation(new OnboardingConversation());

});

**Comment by alexbudin** [comment]
Hi @dara-t 

**To start receiving these events you need to subscribe to messaging_referrals in the webhook settings for your app.**

You can see here: https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messaging_referrals
