### ISSUE TITLE
Infinite looping with Facebook Webhook

### ISSUE THREAD

**Issue by jeanpfs** [botman/botman#659]
- BotMan Version: #.#.#
- PHP Version: 7.1.9
- Messaging Service(s):
- Cache Driver:

### Description:
Using Facebook Drive with DialogFlow, I am trying to send multiple responses and the result is an infinite loop.

### Steps To Reproduce:

`/routes/botman.php`

```
$dialogflow = ApiAi::create(env('DIALOGFLOW_TOKEN'))->listenForAction();

// Apply global "received" middleware
$botman->middleware->received($dialogflow);

$botman->hears('input.start-test', function (BotMan $bot) {
    
    $bot->typesAndWaits(1);
    $bot->reply("msg 1");

    $bot->typesAndWaits(2);
    $bot->reply("msg 2");    
     
})->middleware($dialogflow);
```

**Comment by mpociot** [comment]
You only have a limited amount of time to send the result to Facebook.
Either try putting the bot replies onto a queue, or reduce the wait time.
