### ISSUE TITLE
How to send message to multiple users at once?

### ISSUE THREAD

**Issue by melihovv** [botman/botman#660]
- BotMan Version: 2.1.5
- PHP Version: 7.1.1
- Messaging Service(s): Telegram
- Cache Driver: Laravel

### Description:
In [documentation](https://botman.io/2.0/sending) in "Originating Messages" section it is stated that

> BotMan also allows you to send messages to your chat users programatically. You could, for example, send out a daily message to your users that get's triggered by your cronjob.

Is it possible to send message to several users at once? (I tried this code it doesn't work)
```php
Botman::say($request->message, Subscriber::pluck('id_in_telegram')->toArray(), TelegramDriver::class);
```
or I need to send message to each user separately? (this code works)
```php
foreach (Subscriber::pluck('id_in_telegram') as $subscriberId) {
    Botman::say($request->message, $subscriberId, TelegramDriver::class);
}
```

**Comment by mpociot** [comment]
Hey,

you're right - the `say` method didn't accept an array until now. I just published 2.1.6 which adds support for this.

**Comment by niksib** [comment]
Hello @mpociot.
How many users can be sent at once?

**Comment by christophrumpel** [comment]
hey @niksib , this will probably depend on the driver. There is no limit in BotMan itself.

**Comment by niksib** [comment]
@christophrumpel Thanks.
