### ISSUE TITLE
Can you please update example project for PHP Laravel

### ISSUE THREAD

**Issue by Punith1234** [botman/botman#661]
- BotMan Version: lates
- PHP Version: 7
- Messaging Service(s): Slack
- Cache Driver:

### Description:
I'm not able to run botman in php laravel project. All i get is Call to a member function hears() on null . Can you please help me out with the example project in laravel 

I've used it like this 

```
<?php
require 'vendor/autoload.php';

use React\EventLoop\Factory;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\Drivers\Slack\SlackRTMDriver;

// Load driver
// DriverManager::loadDriver(SlackRTMDriver::class);

$loop = Factory::create();

$botman = BotManFactory::createForRTM([
     'slack_token' => 'xoxxoxxoxxoxxoxxoxxoxxoxxoxxoxxoxxoxxoxxox'
], $loop);

$botman->hears('keyword', function($bot) {
    $bot->reply('I heard you! :)');
});


$loop->run();
```

**Comment by mpociot** [comment]
You need to actually load the driver.
In your example, the driver is not getting loaded, because you commented it out:

` // DriverManager::loadDriver(SlackRTMDriver::class); `
