### ISSUE TITLE
How to properly queue a bot Reply

### ISSUE THREAD

**Issue by ajmariduena** [botman/botman#667]
- BotMan Version: 2.1
- PHP Version: 7.1
- Messaging Service(s): Slack
- Cache Driver:

### Description:
How to queue a bot reply?, Im trying to perform some database queries and send that in my reply but im getting duplicated messages :
```
$botman->hears('/command {id}', function ($bot, $id) {
            $user = User::where('id', $id)->first();
            $bot->reply('Some user information');
});
```
Now just for testing im trying to queue a reply:
```
$botman->hears('/command {id}', function ($bot) {
            \App\Jobs\ReplyJob::dispatch($bot);
});
```
and in my ReplyJob class:
```
use BotMan\BotMan\BotMan;

protected $botman;

public function __construct(BotMan $botman)
    {
        $this->botman = $botman;
    }
public function handle()
    {
        $this->bot->reply('Some user information');
    }
```
### Edited 
Here is my handle method
```
DriverManager::loadDriver(SlackDriver::class);
        
        $config = [
            'slack' => [
                'token' => '--HIDDEN--'
            ]
        ];

        $botman = BotManFactory::create($config);

        $botman->hears('Hi', function ($bot) {
            CheckSell::dispatch($bot);
        });

        $botman->listen();
```
And my job
```
use BotMan\BotMan\BotMan;
protected $botman;

    public function __construct(BotMan $botman)
    {
        $this->botman = $botman;
    }
    function handle()
    {
        $this->botman->reply('Some user information');
    }
```
Job is running:
<img width="494" alt="screen shot 2018-01-03 at 5 01 11 pm" src="https://user-images.githubusercontent.com/31521624/34541817-be487d7c-f0a7-11e7-8601-9d84785abb7e.png">

**Comment by mpociot** [comment]
Hi,

which RTM API implementation do you use?
This should be the correct way to queue messages with BotMan.

**Comment by ajmariduena** [comment]
Hi im using botman/driver-slack 2.0, here is my handle method:
```
       DriverManager::loadDriver(SlackDriver::class);

        $config = [
            'slack' => [
                'token' => '--HIDDEN--',
            ],
        ];

        $botman = BotManFactory::create($config);
        $botman->hears('/command {id}', function ($bot) {
            \App\Jobs\ReplyJob::dispatch($bot);
        });
```
The job is working fine but im not getting any reply.

**Comment by Jeroen-G** [comment]
Maybe `$this->botman->reply` instead of `$bot->reply` in the handle method of the Reply job.

**Comment by ajmariduena** [comment]
Sorry i just updated my reply.

**Comment by ajmariduena** [comment]
Well after some research i finally make it work, the problem was when BotMan instance get serialized and unserialized inside the Job class for some reason the driver is not being loaded again. So you need to load the driver manually.

```
public function __construct(BotMan $botman)
    { 
        $this->botman = $botman;
    }

public function handle()
    {
        DriverManager::loadDriver(SlackDriver::class);
        $this->botman->loadDriver(SlackDriver::class);
        $this->botman->reply('Some user information');
    }
```
I think we can extract this to a trait. Hope helps someone.

**Comment by mpociot** [comment]
@ajmariduena thank you for looking into this and glad that you sorted it out - but this should of course work out of the box.

I will look into this later to see what's the issue and why the serialization removes the driver.

**Comment by ajmariduena** [comment]
@mpociot i just made more research and finally figure it out. Is not working because 
 when the botman instance get unserialized tries to get the driver instance from ```DriverManager``` but this doesn't have any drivers in ```protected static $drivers = [];``` so to make it work you need to register ```DriverServiceProvider``` but this one is in the ```botman/studio-addons``` package, i think this one needs to be inside botman package or at least add this aditional step to botman documentation.

The magic happens in ```$this->discoverDrivers();```

**Comment by mpociot** [comment]
The `DriverServiceProvider` should be automatically registered.
What do you use to run the queue jobs? Have you tried restarting the queue worker?

**Comment by ajmariduena** [comment]
Yeah i know im just saying that if you dont install botman/studio-addons you cant queue a bot reply out of the box.

**Comment by mpociot** [comment]
@ajmariduena This should now be fixed, since all drivers make use of Laravel's package discovery feature to load itself in the DriverManager.
