### ISSUE TITLE
Can't install Slack Driver on fresh BotmanStudio

### ISSUE THREAD

**Issue by lakhai** [botman/botman#668]
- BotMan Version: 2.1.5
- PHP Version: 7.1.7
- Messaging Service(s): Slack
- Cache Driver: None

### Description:
After setting up a new botman studio instance and trying to install the Slack driver with the command `php artisan botman:install-driver slack` I get the following error:
```
Installing driver "Slack"
Using version ^2.0 for botman/driver-slack

./composer.json has been updated

Loading composer repositories with package information

Updating dependencies (including require-dev)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for botman/driver-slack ^2.0 -> satisfiable by botman/driver-slack[2.0.0].
    - botman/driver-slack 2.0.0 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0] but these conflict with your requirements or minimum-stability.



Installation failed, reverting ./composer.json to its original content.

Error installing driver "Slack"
```
When trying to install the composer package directly via `composer require botman/driver-slack` I get a similar error:

```
Problem 1
    - Installation request for mpociot/slackbot ^0.1.2 -> satisfiable by mpociot/slackbot[0.1.2].
    - Conclusion: remove symfony/http-foundation v3.4.1
    - Conclusion: don't install symfony/http-foundation v3.4.1
```
It might just be me doing something wrong here, but I'm really quite stumped and not being able to make any progress.

Whatever other information might be relevant that you need, just let me know and I'll do my best to provide it fast.

Thank you!

### Steps To Reproduce:

1. Installed BotMan Studio and created a new project using `botman new testbot`
2. Ran normal Laravel setup commands, `composer install`, renamed `.env.example` and ran `php artisan key:generate`
3. Ran command `php artisan botman:install-driver slack`

**Comment by ajmariduena** [comment]
Same thing happens to me yesterday, i ended up installing slack driver before botman in an empty laravel project, i just cant make it work in botmanstudio :(

Hope it helps.

**Comment by Akash4927** [comment]
Try using `composer require botman/driver-slack 1.0`.

Hope it helps.

**Comment by mpociot** [comment]
I think I broke something with the 2.0 release / it’s dependencies. I’ll look into this asap

**Comment by kadinho** [comment]
same here :/

**Comment by lakhai** [comment]
@mpociot Is there a specific commit we can go back to in botman/studio to have a running version?

**Comment by gabolecointere** [comment]
I'm having this  same issue today :( someone has made it work in botman studio?

**Comment by mpociot** [comment]
This is finally fixed in all new BotMan studio installations.

If you still have this issue, please make sure your composer.json looks like this:

https://github.com/botman/studio/blob/43b818f06b13addf890fd23cda121e6148fb0e09/composer.json#L13-L20

**Comment by jlubeck** [comment]
What if I don't want Studio? Just botman?
