### ISSUE TITLE
Setup facebook webhook url

### ISSUE THREAD

**Issue by MagSag** [botman/botman#674]
- BotMan Version: 2.0
- PHP Version: 7
- Messaging Service(s): Facebook Messenger

What or where should I get the url to put in my messenger webhook... I don't get the documentation well ... controllers have routes , I really need to know how this

 
>   After that you can setup the webhook, which connects the Facebook application with your BotMan application. which is explained in this article

And also is there any possibility of running multiple bots from one application(laravel), They will be each connected their own pages. How can I acheive that without killing the performance of the application, 1000 bots for 1000 pages but there will be more than 1000 pages (more than 1000 bots then)?

**Comment by mpociot** [comment]
The webhook URL is the public URL to your BotMan application - in case of BotMan studio, the controller lives at `/botman`. So it would be something like: `https://your-awesome-bot.com/botman`

Regarding multiple bots on a single application: You could move the reply/say logic of your bot onto a queue system, but if you want to server a bot for multiple thousand applications/pages you still need to be aware that your system will receive a lot of facebook webhooks.

**Comment by MagSag** [comment]
Thanks for the explaination but what do you mean by  

> You could move the reply/say logic of your bot onto a queue system
I don't understand .
And will the application receiving many facebook wehooks not affect its performance very badly?
