### ISSUE TITLE
Method Say has incorrect IncomingMessage

### ISSUE THREAD

**Issue by luckyraul** [botman/botman#681]
- BotMan Version: 2.0.0

### Description:

https://github.com/botman/botman/blob/master/src/BotMan.php#L501
Recipient becomes Sender, and proceed with empty Recipient

**Comment by mpociot** [comment]
No , that’s actually correct. 
The say method gets used to originate messages to other users. In order to do this I create a new incoming message object and fake it as if the recipient of this message is the one that should get the reply.

**Comment by luckyraul** [comment]
@mpociot  Ok, it doesn't work with hipchat driver, It can't find match with api URL from config
