### ISSUE TITLE
Say method on the Hipchat 

### ISSUE THREAD

**Issue by luckyraul** [botman/botman#682]
- BotMan Version: 2.0
- Messaging Service(s): Hipchat

### Description:
Method say doesn't work with a hipchat driver, It can't find match with api URLs from the config without a Recipient

https://github.com/botman/driver-hipchat/blob/master/src/HipChatDriver.php#L98
$matchingMessage->getRecipient() - is empty

**Comment by mpociot** [comment]
Fixed this and tagged 1.0.1
