### ISSUE TITLE
Command Groups multiple recipients

### ISSUE THREAD

**Issue by rickkuilman** [botman/botman#683]
I have made an enhancement in the 'recipients' command groups so that multiple recipients can be access the group.

```
$botman->group(['recipient' => '700001'], function($bot) {
  ...
});
```

```
$botman->group(['recipient' => ['700001', '700002', '700003']], function($bot) {
  ...
});
```

For now I have hacked it into place, but if this enhancement is appreciated by more people I can turn it into [well structured code with tests](https://github.com/botman/botman/blob/master/CONTRIBUTING.md). So, is this a nice little addition or should this be implemented differently (via middleware or something)?

**Comment by mpociot** [comment]
I like this 👍 
If you want, send me a PR :)

**Comment by rickkuilman** [comment]
Aight, cool. Expect something later this week (:
