### ISSUE TITLE
Error DriverManager class not found with codeigniter

### ISSUE THREAD

**Issue by prdpspkt** [botman/botman#686]
- BotMan Version: 1.5
- PHP Version: 7.02
- Messaging Service(s): Facebook
- Cache Driver: Codeigniter Cache (File)

### Description:
An uncaught Exception was encountered
Type: Error

Message: Class 'Botman\Botman\Drivers\DriverManager' not found

Filename: C:\xampp2\htdocs\application\controllers\Welcome.php

Line Number: 22

Backtrace:

File: C:\xampp2\htdocs\index.php
Line: 315
Function: require_once

### Steps To Reproduce:
1. Download Codeigniter 3.x and installed.
2. composer require botman\botman
3. composer require botman\driver-facebook
4. Then run following code:
`<?php
use Botman\Botman\Botman;
use Botman\Botman\BotmanFactory;
use Botman\Botman\Drivers\DriverManager;
defined('BASEPATH') OR exit('No direct script access allowed');

class Welcome extends CI_Controller {

	 public function __construct()
        {
                parent::__construct();
                $this->load->driver('cache');
                $config = [
                	'facebook' => [
					  	'token' => 'YOUR-FACEBOOK-PAGE-TOKEN-HERE',
						'app_secret' => 'YOUR-FACEBOOK-APP-SECRET-HERE',
					    'verification'=>'MY_SECRET_VERIFICATION_TOKEN',
					]

                ];

                DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);
                $botman = BotManFactory::create($config, new CodeIgniterCache($this->cache->file));
        }

	public function index()
	{
		$botman->hears('hello', function (BotMan $bot) {
    		$bot->reply('Hello yourself.');
		});

		// Start listening
		$botman->listen();
	}
}
`

**Comment by arshidkv12** [comment]
Please add following code in `application/config/config.php` .

`$config['composer_autoload'] = TRUE;  `

**Comment by prdpspkt** [comment]
Already Added, But not working.

**Comment by mpociot** [comment]
This issue seems to be not directly related to the BotMan core. Please see how you can use the composer autoloader in your script in order to access the driver manager.

**Comment by wilfredonoyola** [comment]
Hi @prdpspkt , Did you find the solution for this?

Thanks.

**Comment by lakinmohapatra** [comment]
Any updates here ?
