### ISSUE TITLE
Hears no message only postbacks are listened.

### ISSUE THREAD

**Issue by prdpspkt** [botman/botman#688]
- BotMan Version: 2.#.#
- PHP Version: 7
- Messaging Service(s): Messenger
- Cache Driver: Lumen

### Steps To Reproduce:
```
<?php 
 use BotMan\BotMan\BotMan;
 use BotMan\BotMan\BotManFactory;
 use BotMan\BotMan\Drivers\DriverManager;

 $router->post('/webhook', function(){
 $config = [
            'facebook' => [
            'token' => 'token',
            'app_secret' => 'secret',
            'verification'=>'varification'
            ]
        ];
        // I have added all required config variable in code
        // Load the driver(s) you want to use
        DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

        // Create an instance
        $botman = BotManFactory::create($config);

        // Give the bot something to listen for.
        $botman->hears('hello', function (BotMan $bot) {
            $bot->reply('Hello yourself.');
        });

        $botman->fallback(function($bot) {
            $bot->reply('You said: '.$bot->getMessage()->getText());
        });

        // Start listening
        $botman->listen();
});
```

No other error thrown.

**Comment by mpociot** [comment]
Have you checked the correct webhooks to be sent to your endpoint? Do you see that regular messages are coming in?

![image](https://user-images.githubusercontent.com/804684/35143168-03ebe372-fd01-11e7-985d-079b2992013f.png)

**Comment by prdpspkt** [comment]
Yes, I have. Message not sent. But sends 200 Ok

**Comment by quocthinh212** [comment]
I got same error with botman studio!,
`$botman->on('messaging_postbacks', function ($payload, $bot) {
            $bot->reply(json_encode($payload));
        });`
event: messaging_postbacks not catch,
I use this function:
`$botman->fallback(function($bot) {
            $bot->reply('You said: '.$bot->getMessage()->getText());
        });`
to get postback->payload  data from button.
