### ISSUE TITLE
Telegram Bot doesn't respond

### ISSUE THREAD

**Issue by pavlovpa4o** [botman/botman#696]
- BotMan Version: 2.1.5
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver: file

### Description:
**Telegram Bot doesn't respond**

### Steps To Reproduce:
botman new bot
cd bot
php artisan botman:install-driver telegram
add token to .env
php artisan botman:telegram:register => ok

/botman/tinker works fine and response to "Hi", but in telegram there is no response.

Tried on local with ngrok with no success, and then tried on digitalocean with valid certificates again with no success.

Last friday - 01.19 everything worked fine,  but after weekend i can't make it work.

**Comment by pavlovpa4o** [comment]
I made a stupid mistake setting up webhooh with slash at the end.

**Comment by christophrumpel** [comment]
Great it works now 👍
