### ISSUE TITLE
Originating Conversations and Slack channels

### ISSUE THREAD

**Issue by Jkwakkel** [botman/botman#697]
- BotMan Version: 2.1.9 (Without studio)
- PHP Version: 7
- Messaging Service(s): Slack (Driver version 2.1.0)
- Cache Driver: Memcache using MemcacheCachePool (https://github.com/php-cache/memcache-adapter)

### Description:
I can not get a originating  conversation to work in slack channels. It will start and send the first question, but you it will not respond to a reply. It seems obvious why. Because the person who replies is different then the `$recipient` value you give when starting the conversation. The sender of the incoming message will then be the user who send the actuall reply to the question. Not the id of the channel.  

It does work when using it in hears (If of course the person answers who triggers the conversation, no-one else can reply)  or if you "DM" using as the slack apps bot. I am not sure if it is intended not to work in channels. From comments in the code and in the issue here it seems like it's supposed to. 

### Steps To Reproduce:
- Load SlackDriver

        DriverManager::loadDriver(\BotMan\Drivers\Slack\SlackDriver::class);

- Set config with slack token

         $config = [
            'slack' => [
                'token' => 'xoxb-code-code'
            ]
        ];

- Setup MemcacheCachePool

        $client = new Memcache(); 
        $client->connect('127.0.0.1', 11211);
        $mem = new MemcacheCachePool($client);

- 'Start' BotMan

        $this->roybot = BotManFactory::create($config, new Psr6Cache($mem));

- Trigger Conversation

        $this->roybot->startConversation(new conv(), 'X0XXX00X0', 
        \BotMan\Drivers\Slack\SlackDriver::class);`

*`conv()` is a class extending `BotMan\BotMan\Messages\Conversations\Conversation`. It has a `run` function and this same `conv()` works in other situation. the "sender" of the simulated message (X0XXX00X0) is the channel-id. However when I reply to the question X0XXX00X0 the recipient and I will be the sender (so it wont be able to find the `OriginatedConversationIdentifier`) 

I managed to "fix" the channel problem this by changing `getOriginatedConversationIdentifier()` to the following

        public function getOriginatedConversationIdentifier()
        {
               return 'conversation-'.sha1($this->getRecipient() ?: $this->getSender()).'-'.sha1('');
        }
 
However then a direct message to the user-id does not work anymore. You could work around that by using the bot-id instead, but this clearly is not a proper solution.

**Comment by mpociot** [comment]
So the problem I see is, that you are originating a *conversation*. This is usually a 1 on 1 concept.
What exactly do you want to happen? The conversation only works with one person replying - not multiple persons.
For example, if you would originate a conversation to a Slack channel with 100 users, should anyone be able to answer? This doesn't work right now, and I do not see a good way of solving this.
So the concept of originating conversations is always: you send the conversation to one person / dm.

**Comment by Jkwakkel** [comment]
My hope was that I was able to ask a question within a channel, using buttons and dropdowns, if an action needs to be taken by a team. However, like I said, was not sure if it was supposed to work in regular channels (as you could actually initiate them).

Thanks for the reply and for BotMan!

**Comment by Lux589** [comment]
Somehow when other users in my slack team DM the bot. it doesn't respond. It only responds to me. would it have to do anything with the above?
