### ISSUE TITLE
Promote botman on one `awesome-list`, the hackerkid/bots

### ISSUE THREAD

**Issue by fititnt** [botman/botman#698]
This list <https://github.com/hackerkid/bots> does not mention botman, botman/studio or https://playground.botman.io.

How could we make suggestion there? Botman is actually more powerful than a lot of others on that list.

**Comment by christophrumpel** [comment]
Hey @fititnt , have you tried to make a PR on that list or tell the maintainer about BotMan? Guess that would be the easiest approach.

**Comment by fititnt** [comment]
Sure. The point here is _**what**_ to tell to the maintainer about BotMan. I'm not sure about this _what_, so I can't even do a clean pull request there.

I'm a bit new to BotMan, but more older collaborators from here or even @mpociot could give a hand on how to classify BotMan-related work. This list is just what comes to my mind that already do not cite botman, but should have another places on github or even these sites that suggest tools for what BotMan do.

Some marketing is important. In my honest opinion features of BotMan are underrated compared to some another more searchable tools for make bots on internet. And I'm sayng this because I'm testing other tools.

This issue is not a urgent thing. I think it's worth talking unhurriedly.

**Comment by mkopinsky** [comment]
This is an open source project! Marketing isn't limited to just the core developers - anyone in the community can contribute both in code and in things like marketing and documentation.

I opened a PR in the hackerkid/bots repo - https://github.com/hackerkid/bots/pull/50

(I definitely agree about BotMan being underrated compared to other things out there!)
