### ISSUE TITLE
askForLocation not working in current setup

### ISSUE THREAD

**Issue by mofman** [botman/botman#699]
- BotMan Version: 2.1.9
- PHP Version: 7.1.13
- Messaging Service(s): Facebook
- Cache Driver: Yii2 https://github.com/DaveFerger/botman-yii2-cache

### Description:

I have integrated Botman into  Craft CMS 3 as a plugin and am using the above cache driver. Everything works fine in conversation - bot correctly asks and listens for answer. 

However I'm having trouble listening for the answer to askForLocation.

```
        $this->askForLocation('Please share your location:', function ($location) {
            //this code is not executed
            $this->say('Received: '.print_r($location, true));
        }, null, [
            'message' => [
                'quick_replies' => json_encode([
                    [
                        'content_type' => 'location'
                    ]
                ])
            ]
        ]);

```

Its worth noting that I can get this working in botman studio, is there something a miss with the caching? Can you give me any pointers?

Thanks

**Comment by mofman** [comment]
Looks like a duplicate of  #639

**Comment by mpociot** [comment]
Hm..this somehow needs to be related to the cache driver.
I just tried it and could not reproduce the issue.
Since it seems to work with the core cache drivers of BotMan, I would ask you to ask the maintainer of the cache driver, as this doesn't seem to be related to the BotMan repository.

**Comment by sugoireed** [comment]
Had a similar problem. The solution is that you need to also import/load/add the location driver for the driver you are using i.e Facebook Location driver

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookLocationDriver::class);
