### ISSUE TITLE
Use with Symfony

### ISSUE THREAD

**Issue by desrat** [botman/botman#708]
Is it possible to get a quick write up (even just bullet point steps would do) of how to set this up in Symfony?

- install botman
- install driver
- create route and controller function to render chatbot
- create route and controller function for botman endpoint 
- ?

I tried using the example code in 'Basic Usage without BotMan Studio' in a controller action but I never get anything but a 200 response with no message

```
<?php

namespace App\ChatBotBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\Drivers\Web\WebDriver;

class DefaultController extends Controller
{
    /**
     * @Route("/test", name="embed_chatbot")
     */
    public function embedChatBotAction()
    {
        return $this->render('@theme/chatbot/chatbot.html.twig');
    }

    /**
     * @Route("/botman")
     */
    public function startConversationAction()
    {
        // Load the driver(s) you want to use
        DriverManager::loadDriver(WebDriver::class);

        // Create an instance
        $botman = BotManFactory::create([
            'web' => [
                'matchingData' => [
                    'driver' => 'web',
                ],
            ]
        ]);

        // Give the bot something to listen for.
        $botman->hears('hi', function (BotMan $bot) {
            $bot->reply('Hello yourself.');
        });

        // Start listening
        return new Response($botman->listen());
    }
}
```

**Comment by PeteLawrence** [comment]
Hi @desrat,

I've just started myself with Symfony and BotMan, you can take a look at it at https://github.com/PeteLawrence/EagleChatBot, which may give you some pointers.

I think your particular problem may be down to how you're posting the data to the /botman route, as I had the same problem. I found that I needed to send the data as a form (Content-Type: multipart/form-data).  I've not yet had a chance to dig into the code to figure out whether BotMan will allow other formats or not, or whether Symfony is doing something to the data on it's way in.

Pete

**Comment by desrat** [comment]
Got me past the initial hump (so thanks for that) so now It will do simple 'hears' commands but the conversations system doesn't seem to work (subsequent responses after the initial question are ignored/not detected) and interactive is set to true (just fyi)

**Comment by mpociot** [comment]
@desrat would you like to help me create a boilerplate Symfony project with BotMan? Or maybe even a custom bundle if this makes sense?
I'm not a Symfony developer, so I don't know what makes sense. But anything that would help other people not run into this issue would be great.

**Comment by gildas15** [comment]
Good evening here, PLease After installing botman in symfony I get the following error
![botman](https://user-images.githubusercontent.com/36203062/55294139-cfca3180-53ed-11e9-83e5-030fb747d9ce.png)

**Comment by gildas15** [comment]
Please can someone help how to go about it

**Comment by gildas15** [comment]
Please could someone help me on how to register the Botman bundle in symfony

**Comment by veroxy** [comment]
> 
> 
> Please could someone help me on how to register the Botman bundle in symfony

You use the wrond "use" its an botman component not DBAL  >> use BotMan\BotMan\Drivers\DriverManager;

all requierement for [botman web is here ](https://symfony.com/projects/botman)

**Comment by gildas15** [comment]
ok thank
