### ISSUE TITLE
Don't remove inline keyboards automatically

### ISSUE THREAD

**Issue by w3bit** [botman/botman#709]
- BotMan Version: 2.1.5
- PHP Version: 7.1
- Messaging Service(s): Telegram

### Description:
Botman removes inline keyboards automatically after the user clicks on them, I want to update keyboards markup, but botman removes it.
Is there any option to change this behavior?

**Comment by antimech** [comment]
@mpociot Do you have any idea?

**Comment by kubk** [comment]
Here is my suggestion how to avoid the problem: https://github.com/botman/driver-telegram/issues/44

@mpociot Do you have a better solution? I can make a PR.
