### ISSUE TITLE
"RECEIVES IMAGES" NOT WORKING

### ISSUE THREAD

**Issue by alvinmurimi** [botman/botman#712]
- BotMan Version: 2.0
- PHP Version:7.2.2
- Messaging Service(s): Telegram
- Cache Driver:

I've been trying to retrive the url of an image sent by a user using the code below:
```
require 'vendor/autoload.php';

use BotMan\BotMan\BotMan;
use BotMan\BotMan\Messages\Message;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Messages\Attachments\File;
use BotMan\BotMan\Messages\Attachments\Image;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;
use BotMan\BotMan\Drivers\DriverManager;
$config = [
    'telegram' => [
      'token' => '<token>'
    ]
  ];

// create an instance
$driver=DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);

$botman = BotManFactory::create($config);
$botman->receivesImages(function($bot,$image) {
   $url=$image->getUrl();
      $bot->reply($url);
});

```
However, the bot doesn't seem to respond with anything. I also tried this:

```
$botman->receivesImages(function($bot, $images) {

    foreach ($images as $image) {

        $url = $image->getUrl(); // The direct url
        $title = $image->getTitle(); // The title, if available
        $payload = $image->getPayload(); // The original payload
            $bot->reply($url);
    }

});
```
But both codes still result to the bot replying with nothing.
What might be the problem?

**Comment by mpociot** [comment]
Hi @alvinmurimi ,

if you load the driver manually, make sure to also load the Telegram driver that takes care of receiving image attachments.

Add this code, to load the appropriate driver:

```php
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\ TelegramPhotoDriver::class);
```

**Comment by laskarazhar-hiveup** [comment]
> Hi @alvinmurimi ,
> 
> if you load the driver manually, make sure to also load the Telegram driver that takes care of receiving image attachments.
> 
> Add this code, to load the appropriate driver:
> 
> ```
> DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
> DriverManager::loadDriver(\BotMan\Drivers\Telegram\ TelegramPhotoDriver::class);
> ```

Please update this to Documentation as well.

**Comment by php-ninja** [comment]
I tried to connect the driver this way:

```php
// Load the driver(s) you want to use
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
```

And I got the next mistake:
`
Backend fatal error: PHP Fatal error: Uncaught Error: Class 'BotMan\\Drivers\\Telegram\\TelegramFileDrive' not found in /var/www/vendor/botman/botman/src/Drivers/DriverManager.php:173
Stack trace:
#0 /var/www/vendor/botman/botman/src/BotManFactory.php(68): BotMan\\BotMan\\Drivers\\DriverManager->getMatchingDriver(Object(Symfony\\Component\\HttpFoundation\\Request))
#1 /var/www/tbot/tbot.php(58): BotMan\\BotMan\\BotManFactory::create(Array, Object(BotMan\\BotMan\\Cache\\SymfonyCache))
#2 {main}\n thrown in /var/www/vendor/botman/botman/src/Drivers/DriverManager.php on line 173
`

**Comment by alvinmurimi** [comment]
> ```
> DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramDriver::class);
> DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramPhotoDrive::class);
> DriverManager::loadDriver(\BotMan\Drivers\Telegram\TelegramFileDrive::class);
> ```

You loaded ```\TelegramPhotoDrive::class``` and ```\TelegramFileDrive::class``` instead of ```\TelegramPhotoDriver::class``` and ```\TelegramFileDriver::class``` 
It's "Driver" not "Drive"

**Comment by php-ninja** [comment]
@alvinmurimi omg!!! Thx bro!!!
