### ISSUE TITLE
Attachment Extras

### ISSUE THREAD

**Issue by PeteLawrence** [botman/botman#718]
- BotMan Version: 1.5.8
- PHP Version: 7.1.13
- Messaging Service(s): N/A
- Cache Driver: N/A

### Description:
I am working on a piece of middleware that will make use of an external service (Amazon Recognition) to analyse any images sent to a bot, and to make those results available within $bot->receivesImages(...).

When using middleware to process a regular text based message, the middleware can add results to the message via the extras field of the IncomingMessage, but there is no facility to do the same using an Image (or any kind of Attachment).

Do others think it'd be useful to add an extras field onto the Attachment class?

### Steps To Reproduce:
N/A

**Comment by christophrumpel** [comment]
Interesting use case. Besides the question of if it makes sense to add attachments there. I would be interested in why you need to return an attachment in your case. Such services normally just return to you data about the attachment right?

**Comment by PeteLawrence** [comment]
Yes, the Amazon Rekognition service just provides an array of labels relating to the image being analysed.  I'm looking at adding this array to the Image object rather than returning an attachment, in order to allow the bot to say something like 'Hey, you uploaded a photo of a boat.  Do you want to find out more about boats?'

As things stand at the moment I can add the array of labels to the IncomingMessage via addExtras(), but doing it that way I lose the mapping between the image that has been submitted by the user, and the array of labels associated with that particular image.

**Comment by christophrumpel** [comment]
Ah got you. From my perspective it would makes sense yes. Let's see what @mpociot thinks about it.

**Comment by mpociot** [comment]
@PeteLawrence that sounds like a great addition to BotMan. Do you want to create a pull request for this feature?

**Comment by mpociot** [comment]
I just tagged 2.3.0 which adds support for this. Thanks again @PeteLawrence
