### ISSUE TITLE
Facebook Exception: Error sending payload.

### ISSUE THREAD

**Issue by rajsandy** [botman/botman#724]
- BotMan Version: 2.3
- PHP Version: 7.1.9
- Messaging Service(s): Facebook
- Cache Driver:

### Description:

My bot isn't replaying for below code, instead its throwing a error on ngrok localhost:4040

// Load the driver(s) you want to use
DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

// Create an instance
$botman = BotManFactory::create($config);

// Give the bot something to listen for.
$botman->hears('hello', function (BotMan $bot) {
   var_dump( $bot->reply('Hello yourself.'));
});

// Start listening
$botman->listen();

### error
When is send "hello" on messenger, getting below error...
<br />
<b>Fatal error</b>:  Uncaught BotMan\Drivers\Facebook\Exceptions\FacebookException: Error sending payload:  in C:\wamp64\www\testbot\vendor\botman\driver-facebook\src\FacebookDriver.php:442
Stack trace:
#0 C:\wamp64\www\testbot\vendor\botman\driver-facebook\src\FacebookDriver.php(365): BotMan\Drivers\Facebook\FacebookDriver-&gt;throwExceptionIfResponseNotOk(Object(Symfony\Component\HttpFoundation\Response))
#1 C:\wamp64\www\testbot\vendor\botman\botman\src\BotMan.php(616): BotMan\Drivers\Facebook\FacebookDriver-&gt;sendPayload(Array)
#2 [internal function]: BotMan\BotMan\BotMan-&gt;BotMan\BotMan\{closure}(Array)
#3 C:\wamp64\www\testbot\vendor\mpociot\pipeline\src\Pipeline.php(114): call_user_func_array(Object(Closure), Array)
#4 [internal function]: Mpociot\Pipeline\Pipeline-&gt;Mpociot\Pipeline\{closure}(Array)
#5 C:\wamp64\www\testbot\vendor\mpociot\pipeline\src\Pipeline.php(102): call_user_func_array(Object(Closure), Array)
#6 C:\wamp64\www\testbot\vendor\botman\botman\src\Middleware\MiddlewareManager.php(126): Mpociot\Pipeline\Pipeline- in <b>C:\wamp64\www\testbot\vendor\botman\driver-facebook\src\FacebookDriver.php</b> on line <b>442</b><br />

### Note: I installed botman via composer and i use ngrok for https and also i updated cacert.pem on localhost(wamp).

**Comment by rajsandy** [comment]
Its my mistake, i added the cacert.pem path in php.ini file but i didn't uncommented it.

;openssl.cafile="C:\wamp64\cacert\cacert.pem"

now i uncommented it and restarted the services... now my bot is replying.

**Comment by parselynk** [comment]
Hi,
I am using the same method on my localhost to connect to facebook with valet share, and no need cacert.pem. btw I am using a mac. but when i deploy my files to server I  receive the same issue


[2018-02-27 09:08:40] local.INFO: {"object":"page","entry":[{"id":"169729017137704","time":1519722519853,"messaging":[{"sender":{"id":"1828119507207295"},"recipient":{"id":"169729017137704"},"timestamp":1519710555656,"message":{"mid":"mid.$cAACaXj_qthRoBxQWCFh1c7Lvf_8l","seq":44490,"text":"hi"}}]}]}
[2018-02-27 09:08:40] local.ERROR: Error sending payload:  {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload:  at /home/phpdeveloper/weatherbot3/vendor/botman/driver-facebook/src/FacebookDriver.php:442)


on local host i found out i have to check       standby event to recieve postback from facebook.

im wondering if anyone can help me.
