### ISSUE TITLE
Botman not returning response on Telegram

### ISSUE THREAD

**Issue by Itsdenty** [botman/botman#727]
- BotMan Version: #.#.# 2.1.3
- PHP Version: 7.1
- Messaging Service(s): Telegram
- Cache Driver: file

### Description:
The $bot->reply function not responding I am using botstudio on laravel 5.5
I logged the reply function and got: [2018-02-28 07:56:35] local.DEBUG: HTTP/1.0 500 Internal Server Error
Cache-Control: no-cache, private
Date:          Wed, 28 Feb 2018 07:56:35 GMT

however without this debug there was no error both in laravel log ang ngrok request log, it just keeps failing to send the response.
I am using ngrok to connect my local server to telegram webhook.

### Steps To Reproduce:
$botman->hears('Hi', function ($bot) {
    \Log::debug($bot->reply('Hello!'));
    $bot->reply('Hello!');
});

**Comment by Itsdenty** [comment]
Solved, my cacert is old so I had to reference a newer one in my php.ini

**Comment by aliwesome** [comment]
@Itsdenty 
could you please mention how did you solve this?

**Comment by Itsdenty** [comment]
@aliwesome Are u trying to solve it on linux or on windows?

**Comment by aliwesome** [comment]
@Itsdenty on linux ubuntu. 
I've tried to set `cacert.pem` in php.ini for `curl.cainfo` and also `openssl.cafile`, but still I got this issue.

**Comment by Itsdenty** [comment]
Are u sure you updated the right php.ini? attempt echoing php_info() in your project root and attempt to confirm the php.ini your server is currently using via the php_info output.

**Comment by aliwesome** [comment]
@Itsdenty 
Yes, I did what you said. it's correct.
