### ISSUE TITLE
Error due to deprecated signatures for React/Socket constructor and its methods

### ISSUE THREAD

**Issue by robertodormepoco** [botman/botman#729]
- BotMan Version: 2.3.0
- PHP Version: 7.0.25
- Messaging Service(s): slack
- Cache Driver: none

### Description:
Botman requires react/socket ~0.4, but mpociot/phpws requires react/socket ^0.8.6, this leads to deprecated signatures for React/Socket constructor and its methods.

i.e. in BotManFactory::createForSocket

```
....
old:     $socket = new Server($loop); <--- deprecated

new:     $uri = '127.0.0.1:' . $port;  <-- FYI: the host should be configurable
         $socket = new Server($uri, $loop);
....
old:       $socket->listen($port); <--- deprecated
new:       // removed
....
```

### Steps To Reproduce:

Install from composer
Launch a simple BotMan instance on a socket

**Comment by mpociot** [comment]
Would you like to send me a PR that fixes this issue?

**Comment by robertodormepoco** [comment]
@mpociot i'll get on that ASAP 👍

**Comment by ellisonpatterson** [comment]
Any updates on this?

**Comment by cawolf** [comment]
I just provided a possible solution sketched out by @robertodormepoco.

@mpociot, please verify the new version requirement of [react/socket](https://github.com/reactphp/socket), as it is now tighter than before.

**Comment by robertodormepoco** [comment]
@mpociot bump

**Comment by cawolf** [comment]
So my PR #783 was just closed without further notice. Any update on this?
