### ISSUE TITLE
Showcase of Botman projects and bots - Awesome list

### ISSUE THREAD

**Issue by Giorat** [botman/botman#731]
My idea is to create a list ( plus jekyll website list ) of all the currently public projects and bot using botman to help the community see already built solution to get inspired or to learn and help others.

Would you support or create an awesome-list-botman repo to contribute to?

**Comment by Giorat** [comment]
What do you use to process the markdown?  

I'd love to help making it, I have some experience with jekyll to elaborate markdown.

Do you have any design in mind for that website? I could make some prototype or sketch fast.

**Comment by mpociot** [comment]
I would personally just start with a Github repository right now. 
I already created a repository and added you as a collaborator: https://github.com/botman/awesome-botman

Let's start with this and when it get's some more traction and content, we can integrate it into the BotMan website.
