### ISSUE TITLE
[Bridge] Add a Symfony bridge

### ISSUE THREAD

**Issue by dkarlovi** [botman/botman#736]
Botman supports Laravel out of the box which is great, but the implementation seem scattered around the codebase.

It would be cool if you'd consider reorganizing code a bit into "bridges" (basically, isolated glue code, [example](https://github.com/theofidry/AliceDataFixtures/tree/master/src/Bridge)) which would make way to adding a Symfony bridge, making botman usable out of the box with Symfony. I could then start a basic implementation and am sure more people would get involved.

**Comment by mpociot** [comment]
Hi,

Yes that’s a great idea. Can you tell me how/where you see it throughout the whole codebase?
BotMan ships with a Laravel specific service provider - everything else is framework agnostic.

**Comment by dkarlovi** [comment]
The approach linked is used widely in Symfony-related projects and works well there, here's [another example](https://github.com/api-platform/core/tree/master/src/Bridge).

IMO, it would work if you dedicate `Botman\Bridge` to it, then you'd have `Botman\Bridge\Laravel`, `Botman\Bridge\Symfony`, etc.

I said "seems scattered" because of commands, cache adapters, etc. That could all end up in the bridge.

**Comment by kubk** [comment]
What do you want to include in the bridge? BotMan is already framework agnostic and works fine with Symfony.

**Comment by dkarlovi** [comment]
A bundle definition which would allow to configure it directly via Symfony config? Symfony commands? Symfony-specific services?

**Comment by mpociot** [comment]
I'm totally open for this if someone provides a pull request for a Symfony bridge

**Comment by dkarlovi** [comment]
@mpociot great, do you see this to be part of the base package or an additional package?

**Comment by mpociot** [comment]
As the Laravel specific parts are also in the base repository, I think it would be good to have this for Symfony too.
If we come to a point where we want to have something like BotMan Studio based on Symfony, this would definitely go into a separate package.

It depends a bit on what will be part of the base package bridge. The Laravel specific commands etc. are all inside the botman/studio-addons package.

**Comment by dkarlovi** [comment]
Roughly, you'd have 3-4 PHP files and an XML file for services, it's probably easiest to add to this repo, splitting later should be easy if it has a dedicated namespace.

I'll try to add a PR to do it in the next couple of days.

**Comment by mpociot** [comment]
That's great, thank you.

**Comment by coudenysj** [comment]
Any progress on this? @dkarlovi need any help?
