### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rfrkk** [botman/botman#743]
In BotMan.php,the line 223 seems has syntax error near ?? 30

$this->cache->put('user_'.$this->driver->getName().'_'.$user->getId(), $user, $this->config['user_cache_time'] ?? 30);

**Comment by decadence** [comment]
This is not error. It's PHP 7 new operator.
https://wiki.php.net/rfc/isset_ternary

**Comment by rfrkk** [comment]
Thank you for your help , it seems that i need to update php from 5.6.x to 7.x
