### ISSUE TITLE
$botman->getUser() is invalid

### ISSUE THREAD

**Issue by 40243225** [botman/botman#744]
BotMan Version: 2.3.0
PHP Version: 7.1
Messaging Service(s): Facebook
-Cache Driver:doctrine

I can use this function($botman->getUser()) on March 10th,, but it has failed today.

I didn’t even change any code,I only test it,and this function is invalid

**Comment by mpociot** [comment]
https://developers.facebook.com/status/

Looks like Facebook has some problems with their API. There’s nothing I can do about it. 
Hopefully it’ll be resolved soon.

**Comment by 40243225** [comment]
ok,I got it,thank you

**Comment by feralheart** [comment]
Same issue. I hope they will resolve it soon.
