### ISSUE TITLE
Issues with tightenco/collect (v5.6.11) on fresh install of botman studio

### ISSUE THREAD

**Issue by mofman** [botman/botman#745]
- BotMan Version: 2.30
- PHP Version: 7.1.10
- Messaging Service(s):
- Cache Driver:

Just create fresh project user composer and updated all dependencies using composer update and getting the following error. 

Type error: Argument 1 passed to Illuminate\Routing\Router::sortMiddleware() must be an instance of Illuminate\Support\Collection, instance of Tightenco\Collect\Support\Collection given, called in /Users/andrew/Sites/deepriverrock/vendor/laravel/framework/src/Illuminate/Routing/Router.php on line 676

Happening accross multiple computers. 

<img width="1267" alt="screen shot 2018-03-15 at 22 33 28" src="https://user-images.githubusercontent.com/3038169/37494560-3b912708-28a1-11e8-91da-06a0b5dd6bab.png">

**Comment by Nur777** [comment]
This is relatied with this issuer:
#https://github.com/tightenco/collect/issues/92

**Comment by Nur777** [comment]
#https://github.com/tightenco/collect/issues/92

**Comment by mofman** [comment]
@Nur777 thanks I didnt spot this
