### ISSUE TITLE
Bot can hears message in channel when the bot called

### ISSUE THREAD

**Issue by jorhendz** [botman/botman#746]
- BotMan Version: 2.0.0
- PHP Version:7+
- Messaging Service(s):Slack
- Cache Driver:Redis

### Description:
Hi, how to set the bot that can only hears the message when the bot called? for example, my bot name is _@angela_ and i want to add her in channels, then, when i said _@angela_ then message she will be able to reply, but when i send a message into channel bot is replying my message, how to avoid that one? please help, i want to implement the bot using that way. thanks in advance.

**Comment by jorhendz** [comment]
Somebody help me from my problem?

**Comment by mpociot** [comment]
You would need to change your hears commands so that the bot is is also in it. Take a look at the incoming response to see the message text. Also, please use the forum at BotMan.io/forum for these kind of topics, as this is not a bug.
