### ISSUE TITLE
How to get message_id response by facebook 

### ISSUE THREAD

**Issue by giapt** [botman/botman#747]
- BotMan Version: 2.3.0
- PHP Version: 7+
- Messaging Service(s): Facebook
- Cache Driver: Doctrine\Common\Cache\FilesystemCache

### Description:
I want to get message_id response by facebook like below, but $bot->reply() return nothing.

![selection_034](https://user-images.githubusercontent.com/12484508/37591353-d58fe2f0-2b9d-11e8-9e14-18f2bd7fb10e.jpg)

**Comment by mpociot** [comment]
The reply method should return a response object with the return value. What is you reply response?

**Comment by giapt** [comment]
I use this code to save reply response to text : 
![selection_035](https://user-images.githubusercontent.com/12484508/37631062-76dd2e2a-2c1a-11e8-84ef-281d5de8dcab.jpg)

And this is result : 
![selection_036](https://user-images.githubusercontent.com/12484508/37631085-97e072a8-2c1a-11e8-88bc-ea7bf41826db.jpg)

**Comment by mpociot** [comment]
@giapt maybe this is related to the json_encode, not sure. Try logging the response body:

```php
$response = $bot->reply('tell me more');
$responseContent = $response->getBody()->getContents(); // <-- Log this
```

**Comment by giapt** [comment]
Its error : 
Error: Call to undefined method Symfony\Component\HttpFoundation\Response::getBody()
then i try $response->getContent();
Now i have message_id, thanks you .
