### ISSUE TITLE
Multiple replies within slack slash command hears

### ISSUE THREAD

**Issue by mwiekens** [botman/botman#749]
- BotMan Version: 2.3.0
- PHP Version: 7.2.0
- Messaging Service(s): Slack
- Cache Driver: 

### Description:
Can't send multiple replies when using a slack slash command.
Only this first reply is send.

### Steps To Reproduce:
```
$botman->hears("/info|/info ", function($bot){
    $bot->reply("This is what I know about you: ");
    $bot->reply("Seriously");
});
```

**Comment by mpociot** [comment]
This depends on the slack integration method. The webhook integration expects a single JSON response, so only one reply works.
You can either use the event based api or the slack rtm api for this.
