### ISSUE TITLE
Slack slash command startConversation timeout

### ISSUE THREAD

**Issue by mwiekens** [botman/botman#750]
- BotMan Version: 2.3.0
- PHP Version: 7.2.0
- Messaging Service(s): Slack
- Cache Driver:

### Description:
Starting a conversation when using a slash command results in:
```
Darn - that slash command didn't work (error message: `Timeout was reached`).
```

### Steps To Reproduce:
```
$botman->hears('/connect', function ($bot){
    $bot->startConversation(new ConnectVoysConversation);
});
```

**Comment by mpociot** [comment]
Do you have anything special in your conversation?
