### ISSUE TITLE
Is it possible to get inbox id for conversation?

### ISSUE THREAD

**Issue by tmoldri** [botman/botman#754]
- BotMan Version: 2.3.0
- PHP Version: 7.2
- Messaging Service(s): Facebook
- Cache Driver: Redis

### Description:
I would like make it possible for a real person to overtake the conversation if bot fails to help customer with their problem.  How would be the best way to notify the customer support person? I would like to get an url for the facebook inbox for that specific person so i could redirect support person directly to that conversation.

Facebook has this url for page inboxes: https://www.facebook.com/pagename/inbox/?selected_item_id=someid

Is it possible to get this ID from bot conversation?

**Comment by chenwenbang** [comment]
hey, have you solved this problem? Can you tell how to get the selected_item_id? Thank you!
