### ISSUE TITLE
Botman not functional after connected to my database

### ISSUE THREAD

**Issue by kelvintoh0809** [botman/botman#759]
- BotMan Version: 2.0
- PHP Version: 7.2.2
- Messaging Service(s): Facebook Messenger
- Cache Driver: Laravel

### Description:
why after i connect my database to botman and the chatbot function is not working anymore?

### Steps To Reproduce:
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:EwFtftA5ViVePNRBwoRuLBVEuR4sTLJE+RUjzmMlFpo=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

**Comment by iboldurev** [comment]
@kelvintoh0809, please add your reproduce steps

**Comment by kelvintoh0809** [comment]
`APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:EwFtftA5ViVePNRBwoRuLBVEuR4sTLJE+RUjzmMlFpo=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
`
i created a database and when i key in to DB_DATABASE , it's connected but my botman can't function well

**Comment by mpociot** [comment]
@kelvintoh0809 This is not really helping as it does not show the code that fails.
