### ISSUE TITLE
isInteractiveMessageReply() always true when using the web widget

### ISSUE THREAD

**Issue by filippotoso** [botman/botman#760]
- BotMan Version: 2.3.0
- PHP Version: 7.1.11
- Messaging Service(s): Web Widget
- Cache Driver:

### Description:

Using the web widget, the $answer->isInteractiveMessageReply() always returns true.
Also, checking the POST request from the widget, the interactive parameter is passed as 1 and 0 but in line 84 of BotMan\Drivers\Web\WebDriver it's checked as follows:

`$interactive = $interactive !== 'false';`

I modified it as follows and now it's working correctly;

`$interactive = ($interactive !== 'false') && ($interactive !== '0');`

**Comment by mpociot** [comment]
This is fixed in version 1.5.1 of the web driver.
