### ISSUE TITLE
$bot->say() command is not working

### ISSUE THREAD

**Issue by hromao** [botman/botman#761]
- BotMan Version: 2.0
- PHP Version: 7
- Messaging Service(s): Facebook

### Description:
Conversation is not working properly, only the first `ask` command is triggered. When the user inputs the answer, anything inside the answer function is executed.

Additionally, the method `say `is never executed, even if it's inside a simple `hear `method. The script does not output any error in my `error.log` file. Is there anything wrong? How can I debug?

I am using the code provided on the docs.

```
use BotMan\BotMan\Messages\Conversations\Conversation;

class IniConversation extends Conversation
{
    protected $firstname;

    protected $email;

    public function askFirstname()
    {
        $this->ask('Hello! How can I call you?', function(Answer $answer) {
            // Anything inside this is executed
            $this->firstname = $answer->getText();
            $this->say('Nice to meet you, '.$this->firstname); //this is never called, whereever it is
            $this->askNeed();
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askFirstname();
    }
}
```

**Comment by mpociot** [comment]
@hromao what cache driver do you use?
Conversations get cached in order to save the conversation state. Make sure to provide a persisting cache driver.
