### ISSUE TITLE
I can't install any drivers

### ISSUE THREAD

**Issue by schymon17** [botman/botman#762]
Hi,

php artisan botman:install-drive facebook

Response:
Unable to fetch BotMan driver repository.
Please check your internet connection ang try again.

But connections works fine

Composer:
"require": {
        "php": ">=7.1.3",
        "botman/botman": "~2.0",
        "botman/driver-web": "~1.0",
        "botman/studio-addons": "~1.2.1",
        "botman/tinker": "~1.0",
        "fideloper/proxy": "~4.0",
        "laravel/framework": "5.6.*",
        "laravel/tinker": "~1.0"
},

**Comment by christophrumpel** [comment]
This error could mean something else. Check here https://github.com/botman/studio-addons/blob/master/src/Console/Commands/BotManInstallDriver.php#L60-L62

You could try to log the exact error like this:

```php
try {
            $response = $this->client->get(self::DRIVER_REPOSITORY_URL);
            $drivers = json_decode($response->getBody(), true);
        } catch (\Exception $e) {
            \Log::info('Error: ' . $e->getMessage()); //new line
            $this->error('Unable to fetch BotMan driver repository.');
            $this->error('Please check your internet connection ang try again.');
            exit(1);
        }

```

**Comment by mpociot** [comment]
If - for whatever reason - the BotMan driver installation command does not work for you, you can simply use composer for it too.

For example:
`composer require botman/driver-facebook`

**Comment by stevenay** [comment]
If you are on Windows and Wamp Server, you may be on the same ship like me. 

For me, the issue was curl certificate problem and solved it by the following answer.

https://stackoverflow.com/a/49071524/3229851
