### ISSUE TITLE
Botman isn't storing user input data; gets stuck completely

### ISSUE THREAD

**Issue by vasu001** [botman/botman#763]
- BotMan Version: 2.0
- PHP Version: 7.1.11
- Messaging Service(s):
- Cache Driver:

### Steps To Reproduce:
Look at the below Functions in some conversation:

```
public function askWelcomeP(){
        $this->ask('Now, what would be your welcome text?', function(Answer $answer){
            $webheaderpara = $answer->getText();
            $this->say($webheaderpara);
            $this->say('Got it! Just wait for a moment while we generate your webpage');
            $this->storeInfo();
        });
    }

```

```
 public function storeInfo(){
        $data = array(
            'name' => $name,
            'webact' => $webact,
            'webname' => $webname,
            'webbrand' => $webbrand,
            'webimage' => $webimage,
            'webheader' => $webheader,
            'webheaderpara' => $webheaderpara
            );
        return view('/store')->with($data);
    }

```
The response in the widget or in botman/tinker is nothing. It just takes the input and remains stuck. When the **$this->storeinfo()** is removed from the askWelcomeP(), it works with two given say  response in that function.

The same problem with $bot->getUser()->save method.

**Comment by vasu001** [comment]
6 days and still no response? Is this project dead or what? Nothing seems to work for storing information provided by user. Any help will be appreciated. I have a project deadline issue.

**Comment by mpociot** [comment]
No, this project is not dead. But we were having Easter holidays and I was sick for 3 days. I’ll take a look into this tomorrow.

**Comment by slashequip** [comment]
Even though you are super rude to someone who has provided you with a free library that is helping you to complete a project so you don't have to write all this code yourself, I'll try and help you.

Is that `storeinfo` method a direct copy from your codebase?

If it is, I'd suggest closing this issue and relearning some PHP basics.

If it isn't please show a copy of the full class so I can help further debug your issue.

**Comment by vasu001** [comment]
Sorry if it sounded rude but that wasn't my intention. I had some issues. Anyways, this is my full class:

`<?php

namespace App\Http\Conversations;


use Illuminate\Foundation\Inspiring;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Question;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Conversations\Conversation;

class ChatConversation extends Conversation
{   
    public $name;
    public function askName(){
        return $this->ask('Hello! I am Webber, your personal webpage designer. What\'s your name?', function(Answer $answer){
            $name = $answer->getText();
            $this->say('Welcome '.$name. ', let\'s create your new webpage!');            
            $this->askWebpageActivity();
        });
    }
    
    public function askWebpageActivity(){
        $question = Question::create("What type of activity would your webpage be for?")
        ->fallback('Unable to ask question')
        ->callbackId('ask_webpage_activity')
        ->addButtons([
            Button::create('Blog')->value('blog'),
            Button::create('Food')->value('food'),
            Button::create('Art')->value('art'),
            Button::create('Portfolio')->value('portfolio'),
            Button::create('Start Up')->value('stup'),
            Button::create('Social Media')->value('socmed'),
        ]);
        
        $this->ask($question, function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                if ($answer->getValue() === 'blog') {
                    $webact = 'Blog';
                    $this->say($webact);
                } else if($answer->getValue() === 'food') {
                    $webact = 'Food';
                    $this->say($webact);
                } else if($answer->getValue() === 'art') {
                    $webact = 'Art';
                    $this->say($webact);
                } else if($answer->getValue() === 'portfolio') {
                    $webact = 'PortFolio';
                    $this->say($webact);
                } else if($answer->getValue() === 'stup') {
                    $webact = 'Start Up';
                    $this->say($webact);
                } else if($answer->getValue() === 'socmed') {
                    $webact = 'Social Media';
                    $this->say($webact);
                }
            }
            $this->say('Good, now let\'s name your webpage');
            $this->askTitle();
       });
    }

    public function askTitle(){
        $this->ask('What\'s the title of your page?', function(Answer $answer){
            $webname = $answer->getText();
            $this->say('Got it!');
            $this->say('Now let\'s name your brand'); 
            $this->askBrand();
        });
    }

    public function askBrand(){
        $this->ask('What would you like your brand name be?', function(Answer $answer){
            $webbrand = $answer->getText();
            $this->say('Thankyou');
            $this->askWelcome();
        });
    }

    public function askWelcome(){
        $this->ask('What will be your welcome text? [this is the heading text]', function(Answer $answer){
            $webheader = $answer->getText();
            $this->say($webheader);
            $this->say('Great!');
            $this->askWelcomeP();
        });
    }

    public function askWelcomeP(){
        $this->ask('Now, what would be your welcome text?', function(Answer $answer){
            $webheaderpara = $answer->getText();
            $this->say($webheaderpara);
            $this->say('Got it! Just wait for a moment while we generate your webpage');
            $this->storeInfo();          
        });
    }
     
    public function storeInfo(){
        //   $data = collect([
        //     "name" => $name,
        //     "webact" => $webact,
        //     "webname" => $webname,
        //     "webbrand" => $webbrand,
        //     "webheader" => $webheader,
        //     "webheaderpara" => $webheaderpara
        //     ]);
        // return view('/store', ['data' => $data]);
        $this->say("Hello");
    }

    public function run()
    {
        // This will be called immediately
        $this->askName();
    }
  

}`

I would like to know what I am doing wrong here, especially in storeInfo(). I tried using the inbuilt botman functionality of storing user messages as mentioned in OP but it gets stuck as well.

Any help will be appreciated at this point.

**Comment by slashequip** [comment]
The issue *is* with that method. You need to look into some PHP basics, in particular variable scopes. What is `$name` etc, they doesn't exist in the scope of that method. Ultimately you need to spend some time learning the fundamentals. 

You should also learn how to debug errors. I'd imagine the error is being logged in Laravel's error logs and would tell you the exact issue you are having. If you are still struggling try asking on a forum (like Laracasts) first where people will offer their help with issues like this. Perhaps look at also investing in a IDE (like PHPStorm) where it will warn you of these errors as you type type them.

This is not an issue with BotMan in any way this issue needs to be closed. If you do have further questions please ask them in a forum as suggested. 

@mpociot feel free to close this issue now.

**Comment by mpociot** [comment]
Thanks @slashequip
