### ISSUE TITLE
Facebook - Dialogflow. Not responding when attach images

### ISSUE THREAD

**Issue by jrafaelborja** [botman/botman#766]
- BotMan Version: 2.0
- PHP Version: 7
- Messaging Service(s): Facebook
- Cache Driver:

### Description:

Using Facebook Messenger with DialogFlow, after the chatbot sends any image stops conversation.
Chatbot works fine hearing and sending text, but when send images stop conversation.

### Steps To Reproduce:

use BotMan\BotMan\Middleware\ApiAi;
use BotMan\BotMan\Messages\Attachments\Image;
use BotMan\BotMan\Messages\Outgoing\OutgoingMessage;

$botman = resolve('botman');
$dialogflow = ApiAi::create('xxxxxxxxxx11111111111xxxxxxxxxx')->listenForAction();
$botman->middleware->received($dialogflow);

$botman->hears('.*', function ($bot) {
	$extras = $bot->getMessage()->getExtras();
	$apiReply = $extras['apiReply'];
	$bot->reply($apiReply);
// ADDING THIS TWO BELOW LINES CHATBOT STOPS RESPONDING
	$message = OutgoingMessage::create('Here is a nice image')->withAttachment(Image::url('https://www.mydomain.com/images/pic.jpg'));
	$bot->reply($message);
})->middleware($dialogflow);

**Comment by slashequip** [comment]
Is it sending the image or just no response?

From my experience if there is no response at all its down to an uncaught error, anything in the error logs?

**Comment by jrafaelborja** [comment]
Yes, the chatbot sends the image, it is ok, but when the user make a new question just after the image shows, the chatbot stops

**Comment by gdpsysgarage** [comment]
I have a similar issue. 
I have put my code in a comment here -> #706

**Comment by LeonanCarvalho** [comment]
Any work around for it?
