### ISSUE TITLE
Facebook - Dialogflow When I upload an image any intent is triggered

### ISSUE THREAD

**Issue by gdpsysgarage** [botman/botman#769]
- BotMan Version: 2.3.0
- PHP Version: 7.1.0
- Messaging Service(s): Facebook

### Description:
I have a flow with some questions created in DialogFlow. 
Effectivelly, when some input reaches the intent, the bot start asking these questions. 
After the user answer all, the bot ask them to upload one or more images.
When the user do this, botman doesnt do anything. 
I have logged the answer, and the answer and intent is empty. 

### Steps To Reproduce:
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;
use BotMan\BotMan\Middleware\ApiAi;
use BotMan\Drivers\Facebook;
use BotMan\Drivers\Facebook\Extensions\ButtonTemplate;

$config = [
  'facebook' => [
  'token' => 'xxx',
  'app_secret' => 'xxxx',
   'verification'=>'xx',
  ]
];

DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

// Create an instance
$botman = BotManFactory::create($config);

$dialogflow = ApiAi::create('XXXX')->listenForAction();

// Apply global "received" middleware
$botman->middleware->received($dialogflow);

// Apply matching middleware per hears command
$botman->hears('.*', function (BotMan $bot) {

    // Retrieve Dialogflow information:
    $extras = $bot->getMessage()->getExtras();
    $apiReply = $extras['apiReply'];
    $apiAction = $extras['apiAction'];
    $apiIntent = $extras['apiIntent'];

    if ($apiIntent === 'Welcome') {
      $bot->reply(ButtonTemplate::create('Hi !!)
      	->addButton(ElementButton::create('Hi')->type('postback')->payload('hi'))
      );
    }else {
      $bot->reply($apiReply);
    }
})->middleware($dialogflow);

// Start listening
$botman->listen();
```

**Comment by gdpsysgarage** [comment]
@mpociot can u help me ?

**Comment by mpociot** [comment]
@gdpsysgarage The problem is that you're listening for all incoming messages using `.*` this will also be executed when you send an image.
I don't know how you want to connect the images to DialogFlow. 
Your best option would be to code the conversation logic manually and deal with the image uploads yourself.

**Comment by poojanetsol** [comment]
Hello @gdpsysgarage , Did you get any solution regarding multiple intents.How to call them .How to use them in conversation.

Please help me with this..

Thanks 
Pooja
