### ISSUE TITLE
Telegram request_contact support

### ISSUE THREAD

**Issue by vitalyiegorov** [botman/botman#771]
- BotMan Version: 2.3.1
- PHP Version: 7.1
- Messaging Service(s): Telegram
- Cache Driver: SymfonyCache

### Description:
How go retrieve Telegram contact(request_contact)

### Steps To Reproduce:
@mpociot  No docs/examples are found for this, Location is the docs but Contact is not.

**Comment by kubk** [comment]
You can use additional params for requests if you need telegram-specific functionality:
```php
$bot->ask('Show phone', function (Answer $answer) use ($bot) {
    $bot->reply('Handled!');
}, ['reply_markup' => json_encode([
    'keyboard' => [[['text' => 'Show phone', 'request_contact' => true]]]
])]);
```

**Comment by vitalyiegorov** [comment]
@kubk Thank you! Super, it works, but one further question, how I can then read the Contact? because when I click my button with request_contact=true nothing happens and botman does not react. I do not receive any my Webhook calls

**Comment by mpociot** [comment]
@vitalyiegorov You can access the raw incoming request data using:
```
$bot->getMessage->getPayload();
```

**Comment by willianmaria** [comment]
Still work?

**Comment by leseulgentil** [comment]
> Still work?

working for me, i'm just testing!

**Comment by chimit** [comment]
Noticed that @kubk's solution doesn't work if you instantiate a question using `use BotMan\BotMan\Messages\Outgoing\Question`. It only works when the `ask()` method receives a plain text.
