### ISSUE TITLE
"botman new" comman issue

### ISSUE THREAD

**Issue by pjoimedia** [botman/botman#774]
- BotMan Version: BotMan Installer version 1.0.0
- PHP Version: 7.1.7
- Messaging Service(s):
- Cache Driver:

$botman new test

produces an error:
Fatal error: Cannot use lexical variable $eventName as a parameter name in /Users/pj/.composer/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 49

**Comment by Continuum81** [comment]
Update your guzzle as per this SO
>composer global update

https://stackoverflow.com/questions/44100316/laravel-cli-fails-to-create-new-app-due-to-cannot-use-lexical-variable-eventnam
