### ISSUE TITLE
Facebook: getPayload() is null

### ISSUE THREAD

**Issue by feralheart** [botman/botman#776]
- BotMan Version: 2.3.0
- PHP Version: 7.0.28
- Messaging Service(s): Facebook
- Cache Driver:

### Description:
If I use like this:
`$payload = $bot->getMessage()->getPayload();`
`$payload` is 'null'

### Steps To Reproduce:

**Comment by mpociot** [comment]
Where / how do you use this code?
It is meant to be called inside of a hears command closure / callback:

```
$botman->hears('message', function($bot) {
    $payload = $bot->getMessage()->getPayload();
});
```
