### ISSUE TITLE
How to track the progress of the conversation with the web driver?

### ISSUE THREAD

**Issue by pjoimedia** [botman/botman#778]
- BotMan Version: 2.0
- PHP Version: 7.2.1
- Messaging Service(s): Web Driver
- Cache Driver:

So I'm getting this after starting a botman conversation:

    {
    "status": 200,
    "messages": [
        {
            "type": "actions",
            "text": "What animal person are you?",
            "fallback": null,
            "callback_id": null,
            "actions": [
                {
                    "name": "I like cats",
                    "text": "I like cats",
                    "image_url": null,
                    "type": "button",
                    "value": "cat",
                    "additional": []
                },
                {
                    "name": "I like dogs",
                    "text": "I like dogs",
                    "image_url": null,
                    "type": "button",
                    "value": "dog",
                    "additional": []
                }
            ],
            "additionalParameters": []
        }
    ]
    }

What do I need to send back to the botman web api so the botman knows I'm replying to this question. How does the botman know that the user is in this conversation? Does it happen on the server side in PHP or do I need to send something back like a conversation question session id or something? I haven't found information about it neither in the course nor in the documentation. There is very little about the web driver, unfortunately.

botman php code:

    <?php
    require_once(dirname(FILE) . '/vendor/autoload.php');

    use BotMan\BotMan\BotMan;
    use BotMan\BotMan\BotManFactory;
    use BotMan\BotMan\Messages\Conversations\Conversation;
    use BotMan\BotMan\Messages\Outgoing\Actions\Button;
    use BotMan\BotMan\Messages\Outgoing\Question;
    use BotMan\BotMan\Drivers\DriverManager;

    class OnboardingConversation extends Conversation
    {
        protected $firstname;
        
        protected $email;

        public function askFirstname()
        {
            $question = Question::create('What animal person are you?')
                ->addButtons([
                    Button::create('I like cats')->value('cat'),
                    Button::create('I like dogs')->value('dog')
                ]);
            $this->ask($question, function($answer) {
                if ($answer->isInteractiveMessageReply()) {
                    $this->say('You selected: '.$answer->getValue());
                }
            });
        }

        public function run()
        {
            // This will be called immediately
            $this->askFirstname();
        }
    }

    $config = [];

    DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);

    // create an instance
    $botman = BotManFactory::create($config);

    $botman->hears('Hello', function($bot) {
        $bot->startConversation(new OnboardingConversation);
        //$bot->reply('Hello World');
    });

    // start listening
    $botman->listen();

**Comment by mpociot** [comment]
When you send a message to the web driver, you can pass a `userId` attribute along with the message.
This user ID  is also used to store conversation state and lookup if the incoming message is for a user inside a conversation or not.

See: https://github.com/botman/driver-web/blob/master/src/WebDriver.php#L147

I know that the web driver API documentation is still missing and I try to find some time to work on this soon.

**Comment by pjoimedia** [comment]
Thanks Marcel.

The cache seems to be working now.

After sending `message=hello` it sends `Hello! What is your firstname?` but then when I send `message=myname` to reply it returns server error 500. If I send a new userId and start a new session it works fine again so it is definitely a problem with the second stage of the conversation, either the cache driver or something.

I'll try to find the issue but If you have any ideas let me know.

This is my code:

    <?php
    require_once(dirname(FILE) . '/vendor/autoload.php');

    use BotMan\BotMan\BotMan;
    use BotMan\BotMan\BotManFactory;
    use BotMan\BotMan\Messages\Conversations\Conversation;
    use BotMan\BotMan\Messages\Outgoing\Actions\Button;
    use BotMan\BotMan\Messages\Outgoing\Question;
    use BotMan\BotMan\Drivers\DriverManager;
    use BotMan\BotMan\Cache\DoctrineCache;

    class OnboardingConversation extends Conversation
    {
        protected $firstname;
        
        protected $email;

        public function askFirstname()
        {
            $this->ask('Hello! What is your firstname?', function($answer) {
                // Save result
                $this->firstname = $answer->getText();

                $this->say('Nice to meet you '.$this->firstname);
            });
        }

        public function run()
        {
            // This will be called immediately
            $this->askFirstname();
        }
    }

    $config = [];

    DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);

    // create an instance
    $doctrineCacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
    $botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));

    $botman->hears('Hello', function($bot) {
        $bot->startConversation(new OnboardingConversation);
        //$bot->reply('Hello World');
    });

    // start listening
    $botman->listen();

**Comment by pjoimedia** [comment]
Ok. It seems to be PHP version issue. It didn't work on `7.2.1` but it seems to be working fine on `7.1.12`.

Thanks for providing prompt support Marcel.
