### ISSUE TITLE
botman not responding

### ISSUE THREAD

**Issue by judzk** [botman/botman#786]
- BotMan Version: 2.0.0
- PHP Version: 7.2
- Messaging Service(s): "botman/driver-telegram": "^1.5"
- Cache Driver:

### Description:
Hi,
Telegram don't respond to my "hi"
the token is set in the .env

Thank you :)
### Steps To Reproduce:
composer create-project --prefer-dist botman/studio blabla
composer require botman/driver-telegram

upload to heroku,
register the webhook : {"ok":true,"result":{"url":"https://XXXXXX.herokuapp.com/botman","has_custom_certificate":false,"pending_update_count":0,"max_connections":40}}

say hi, nothing in return :(

**Comment by judzk** [comment]
found my issue, when a push my files on heroku the .env is not pushed...

**Comment by kubk** [comment]
Yes, in Heroku you need manually set env vars: https://devcenter.heroku.com/articles/heroku-local#copy-heroku-config-vars-to-your-local-env-file
For local testing you can use ngrok, if you need https.
