### ISSUE TITLE
Tinker not replying

### ISSUE THREAD

**Issue by justoX** [botman/botman#787]
- BotMan Version: 2.0
- PHP Version: 7.2.4
- Messaging Service(s): web
- Cache Driver:

### Description:
I have set up BoTMan Studio and created a chatbot in /Applications/XAMPP/xamppfiles/htdocs/dev. However when I run ``` php artisan botman:tinker``` on the terminal I get the ```You:``` prompt to which I type ```Hi``` but instead of getting ```Hello``` as explained in the docs I get another ```You``` prompt.
I am trying to add a simple chatbot to my simple website. Please note I am a beginner.

Also when I navigate to http://localhost/botman/tinker I get:
![image](https://user-images.githubusercontent.com/13330271/39128937-c709cc20-4711-11e8-9d4d-78ccb153ba44.png)

### Steps To Reproduce:
1. Install Botman Studio
2. Create new chatbot
3. run ```php artisan botman:tinker```

**Comment by Husband** [comment]
I have the same problem, but I use laradock on ubuntu 16.04 lts

**Comment by mpociot** [comment]
Hi,

please use GitHub issues only for issues with the library. 
If you have questions about how to use the library, join us on [Slack](https://slack.botman.io) or use the [Forum](https://botman.io/forum).

Thank you

**Comment by Delindel** [comment]
@mpociot Hey man! Im having this issue as well and heading to the forum as you requested, the search function is broken. Just to let you know!
