### ISSUE TITLE
Conversation not replying

### ISSUE THREAD

**Issue by giovannikuntadi** [botman/botman#789]
- BotMan Version: 2.0
- PHP Version: 7.1.3
- Messaging Service(s): Web
- Cache Driver:

### Description:
I'm using Laravel 5.6 and my bot doesn't reply the conversation that i made by following this guide https://botman.io/2.0/conversations, what should i do? What Cache Driver should i install?

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
hey @giovannikuntadi ,

can you please fill out the "Steps To Reproduce"? We can only help if you provide enough information. Please tell exactly what you did, how you are using BotMan (Studio or not), what you have changed, show your code and error, what did you expect and what exactly is not working etc.

**Comment by giovannikuntadi** [comment]
Hi @christophrumpel ,

**Steps To Reproduce : **
I just installed a new fresh botman studio for Laravel by typing **composer global require "botman/installer"** and **botman new testbot**. Then i started to make a conversation through **php artisan botman:make:conversation**. Then i add the function askfirstname() inside this conversation exactly the same as in https://botman.io/2.0/conversations. The function run smoothly for the first line "what is your name?" and then it stopped replying after i input my name.

**Comment by christophrumpel** [comment]
Thank you but still, some important information missing:

1. Have you checked for errors in your logs? (BotMan Studio: `storagel/logs/laravel.log`

2. Please show your conversation code

**Comment by giovannikuntadi** [comment]
1. There is no error

2. `<?php

namespace App\Http\Conversations;

use BotMan\BotMan\Messages\Conversations\Conversation;

class AnotherConversation extends Conversation
{	
	protected $first_name;

    protected $email;

    public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function(Answer $answer) {
            // Save result
            $this->first_name = $answer->getText();

            $this->say('Nice to meet you '.$this->first_name);
            $this->askEmail();
        });
    }

    public function askEmail()
    {
        $this->ask('One more thing - what is your email?', function(Answer $answer) {
            // Save result
            $this->email = $answer->getText();

            $this->say('Great - that is all we need, '.$this->firstname);
        });
    }

    /**
     * Start the conversation.
     *
     * @return mixed
     */
    public function run()
    {
        $this->askFirstname();
    }
}
`

**Comment by christophrumpel** [comment]
You are using the WebDriver? How do you test conversation? Via the API or Tinker?

And have you tested the given BotMan example conversation before? Does this work?

**Comment by giovannikuntadi** [comment]
Actually i'm not sure if i'm using the web driver because every time i checked on my installed driver list, it says "?" on the installed column. But i did installed the web driver.

Yes i'm using tinker, and the example conversation works. Actually i'm afraid this is caused by cache driver because i haven't installed any cache driver yet, could it be?

**Comment by christophrumpel** [comment]
When the example conversation works, then everything should be fine. Also BotMan Studio uses the file driver by default. You shouldn't need to do anything else. You could try deleting the cache with `php artisan clear:cache`

**Comment by giovannikuntadi** [comment]
I have tried to do `php artisan config:clear` and `php artisan cache:clear` as you said, but it just the same, it looked like this in the tinker

![image](https://user-images.githubusercontent.com/33314858/39228029-199a593a-4886-11e8-9155-d49d2a2b7161.png)

**Comment by giovannikuntadi** [comment]
Found the problem,

i forgot to input this on my conversation

`use BotMan\BotMan\Messages\Incoming\Answer;`
`use BotMan\BotMan\Messages\Outgoing\Question;`

and now everything works normally :)

**Comment by arifnofriadi** [comment]
i have the same problem with my code and i have followed this instruction till the end but result is still the same
my code and result look like this
![problem 1](https://user-images.githubusercontent.com/53391649/133103204-5efb7d3d-5250-4c75-bb10-19d75fb61f91.png)


`<?php

namespace App\Conversations;

use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Incoming\Answer;

class OnboardingConverstation extends Conversation
{
    /**
     * Start the conversation.
     *
     * @return mixed
     */

    protected $firstname;

    public function askFirstname()
    {
        $this->ask('Hello! What is your firstname?', function(Answer $answer) {
            // Save result
            $this->firstname = $answer->getText();

            $this->say('Nice to meet you '.$this->firstname);
        });
    }

    public function run()
    {
        // This will be called immediately
        $this->askFirstname();
    }
}
`
