### ISSUE TITLE
Web-widget css overlap with project css ?

### ISSUE THREAD

**Issue by giovannikuntadi** [botman/botman#791]
- BotMan Version: 2.0.
- PHP Version: 7.1.3
- Messaging Service(s): Web
- Cache Driver: none

### Description:
Why does my web widget look like this?

![image](https://user-images.githubusercontent.com/33314858/39287992-6fbc53fc-4950-11e8-932c-bf564b27c792.png)

Here is my css includes:
`<link rel="stylesheet" type="text/css" id="theme" href="{{ asset('css/theme-blue.css') }}"/>

    <link href="{{ ('assets/plugins/css/bootstrap-datepicker.min.css') }}" rel="stylesheet" type="text/css">
    <script src="{{ url('assets/plugins/js/bootstrap-datepicker.min.js') }}"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/jquery/jquery-ui.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/plugins/bootstrap/bootstrap.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript" src="{{ asset('js/plugins.js') }}"></script>        
    <script type="text/javascript" src="{{ asset('js/actions.js') }}"></script>     `

### Steps To Reproduce:
I installed botman through botman studio, everything was fine until i use joli admin template `http://themifycloud.com/demos/templates/joli/` as my project main template.

**Comment by IacopoOrtis** [comment]
this is not a botman problem. You should study css. last css rule has priority. "!important" gives an extra push. between "!important" same thing: last css rule has priority.
