### ISSUE TITLE
HipChat config documentation

### ISSUE THREAD

**Issue by janvernieuwe** [botman/botman#794]
- BotMan Version: lastest
- PHP Version: -
- Messaging Service(s): HipChat
- Cache Driver: -

### Description:
There is no sample configuration in the documentation for the HipChat driver. The main documentation only says 'driver specific config'.
It would be nice to have a sample of how the hipchat configuration should look.

### Steps To Reproduce:
-

**Comment by mpociot** [comment]
Here's the config for hipchat: https://github.com/botman/driver-hipchat/blob/master/stubs/hipchat.php
I'll update the docs 👍
