### ISSUE TITLE
cant send msg via say() method to fb user

### ISSUE THREAD

**Issue by sohaibilyas** [botman/botman#795]
BotMan Version: 2.3.2
    PHP Version: 7.0.9
    Messaging Service(s): facebook messenger
    Cache Driver:

### Description:
cant send message to facebook user using say method, no response/error
i used getUser()->getId() to get the  user id and simply hard-coded it in the code but no success
code is pasted below, am i missing something!

### Steps To Reproduce:
'<?php
require('./vendor/autoload.php');

use BotMan\BotMan\BotMan;
use BotMan\BotMan\BotManFactory;
use BotMan\BotMan\Drivers\DriverManager;

$config = [
  'facebook' => [
  	'token' => 'facebook_page_token',
    'app_secret' => 'app_secret',
    'verification' => 'code_43'
  ]
];

// Load the driver(s) you want to use
DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

$botman = BotManFactory::create($config);

$botman->say('test', '1868838989806400', FacebookDriver::class);'

**Comment by crunck1** [comment]
I hope you've edited your token and app_secret before posting here...

**Comment by mpociot** [comment]
Hi,

please use GitHub issues only for issues with the library. If you have questions about how to use the library, join us on [Slack](https://slack.botman.io) or use the [Forum](https://botman.io/forum).

Thank you

--

Take a look at the response from the `say` method, it should contain an error message.
