### ISSUE TITLE
wit.ai called on every request - not desired

### ISSUE THREAD

**Issue by pjoimedia** [botman/botman#796]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s):
- Cache Driver:

### Description:
**I'm using wit.ai and this is how I initiate it:**

    $wit = Wit::create('SDGDSFGSDGSDFG');
    $botman->middleware->received($wit);

most of my conversations are driven by conversation class and buttons which doesn't require wit.ai, like this:

    $botman->hears('start', function($bot) { // start
        $bot->startConversation(new OnboardingConversation);
    });

only a few hears are using wit.ai like this:

    $botman->hears('general', function($bot) {
    })->middleware($wit)->stopsConversation();

but wit.ai is triggered on every request which 1) is not necessary 2) causes delay because of querying wit.ai api

**My question is how can I prevent calling wit.ai on every request?**

**Is it posibble to do something that if there is a matching `$botman->hears('start'...` sent as a message, e.g. "start", it triggers `$botman->hears('start'...` without calling wit.ai and only it is calling wit.ai if there is no matching `$botman->hears`?**

There is a similar issue with buttons, e.g.:

        $question = Question::create(Q24)
            ->addButtons([
                Button::create('Yes')->value('user_cliecked_yes'),
                Button::create('No')->value('user_clicked_no')
        ]);

When the user clicks "user_cliecked_yes" this is also sent to wit.ai and what is even worse if wit.ai comes back with an intent, e.g. "general" the whole conversation is broken because it triggers `$botman->hears('general',...` This happens even if I use `$answer->isInteractiveMessageReply()`.

This is kind of complicated but I hope it is clear what issues I'm having.

If you could advise on a possible solution it would be great.

### Steps To Reproduce:

**Comment by mpociot** [comment]
This is currently not possible, no. The middleware currently takes *every* incoming message and sends it to wit.ai.
Right now, you'll need to handle this manually in your `fallback` method. But this is already on my list for the next release.

**Comment by pjoimedia** [comment]
I've found a hacky way to achieve not calling wit.ai on every request. I'm sure it can be done in a much nicer way but with this simple change I managed to increase the speed on the chatbot 100x on 90% of requests that don't require wit.ai:

    $skiparray = array('start', 'answer', 'stop'); // messages starting conversations and button values

    if (!in_array($_POST['message'], $skiparray)) {
        $botman->middleware->received($wit);
    }

From my initial testing it looks like it doesn't affect conversation flows or other things.
