### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method BotMan\BotMan\BotMan::__set_state()

### ISSUE THREAD

**Issue by pjoimedia** [botman/botman#797]
- BotMan Version: 2.0
- PHP Version: 7.0.12
- Messaging Service(s):
- Cache Driver: Doctrine/cache

### Description:
I had to downgrade doctrine/cache and symfony/http-foundation for php 7.0 compatibility but still getting this:

```
[01-May-2018 16:34:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method BotMan\BotMan\BotMan::__set_state() in /Applications/MAMP/htdocs/chatbot/cache/58/5b636f6e766572736174696f6e2d373231336261383837373231396133373063323362616364653338663366373039363464363862302d373231336261383837373231396133373063323362616364653338663366373039363464363862305d5b315d.doctrinecache.php:8
Stack trace:
#0 /Applications/MAMP/htdocs/chatbot/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php(112): include()
#1 /Applications/MAMP/htdocs/chatbot/vendor/doctrine/cache/lib/Doctrine/Common/Cache/PhpFileCache.php(63): Doctrine\Common\Cache\PhpFileCache->includeFileForId('[conversation-7...')
#2 /Applications/MAMP/htdocs/chatbot/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(124): Doctrine\Common\Cache\PhpFileCache->doContains('[conversation-7...')
#3 /Applications/MAMP/htdocs/chatbot/vendor/botman/botman/src/Cache/DoctrineCache.php(31): Doctrine\Common\Cache\CacheProvider->contains('conversation-72...')
#4 /Applications/MAMP/htdocs/cha in /Applications/MAMP/htdocs/chatbot/cache/58/5b636f6e766572736174696f6e2d373231336261383837373231396133373063323362616364653338663366373039363464363862302d373231336261383837373231396133373063323362616364653338663366373039363464363862305d5b315d.doctrinecache.php on line 8
```

The documentation says that BotMan 2.0 is compatible with PHP >= 7 but I'm really struggling to get it to work so any help would be appreciated.

When I clear the cache and start the conversation it works but then a second call in the conversation causes the error above.

I got it all working fine on php 7.1 but now need to run on the server with php 7.0.

Configuration:
```
{
    "require": {
        "botman/botman": "^2.3",
        "botman/driver-web": "^1.5",
        "doctrine/cache": "1.6.2",
        "symfony/http-foundation": "3.4.9"
    },
    "platform": {
        "php": "^7.0.12"
    }
}
```

### Steps To Reproduce:

**Comment by mpociot** [comment]
This issue seems to be related to your cache implementation.
Can you show me the code that you use to create the botman instance?

**Comment by pjoimedia** [comment]
I think it is related to the cache implementation. This is how it was:

    $doctrineCacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
    $botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));

since then I changed to Symfony Cache:

    $adapter = new FilesystemAdapter();
    $botman = BotManFactory::create($config, new SymfonyCache($adapter));

which fixed the issue. I think that basically while botman is compatible with php 7.0, doctrine/cache v1.6.2 (which is the highest version that works on php 7.0) is not compatible with botman.

Changing to Symfony Cache fixes it.

I do still have some issues, however, with cache on some servers due to inability to write files. Some kind of MySQL cache that doesn't rely on writing files would be helpful (on the standalone botman version not on botman studio).

Regardless of the issues I'm having botman has been tremendous in terms of helping me putting together my chatbot, conversations etc. when it works it works great :)

@mpociot if you could look into this issue as well it would be great:
https://github.com/botman/botman/issues/796
