### ISSUE TITLE
Serialisation in conversations and PDO

### ISSUE THREAD

**Issue by tasselchof** [botman/botman#799]
- BotMan Version: latest

Can you tell me is it possible to write answers from the bot directly to a database? I need to make something like this:
```
        $this->askForLocation(
            sprintf(
                $this->getTranslator()->translate(
                    'What is your current location?')),
            function (Location $location) use ($objectManager, $userLocation
            ) {
                $userLocation->setCoordinates([
                    'latitude' => $location->getLatitude(),
                    'longitude' => $location->getLongitude(),
                ]);

                $objectManager->flush();
            });
```

The idea is when the user enters a conversation I want to ask him for location and put it into a database. In the current situation I am getting an exception:

> You cannot serialize or unserialize PDO instances

I understand, that it's because of caching mechanism to make conversations work on webhooks...

**Comment by mpociot** [comment]
Hi,

please use GitHub issues only for issues with the library. If you have questions about how to use the library, join us on [Slack](https://slack.botman.io) or use the [Forum](https://botman.io/forum).

Regarding your question: you can probably work around it by implementing custom `__sleep` and `__wakeup` methods in your conversation.

Thank you
