### ISSUE TITLE
Multi image/files attachments doesnt work properly

### ISSUE THREAD

**Issue by MarcoPostiglione** [botman/botman#802]
- BotMan Version: 2.0
- PHP Version: 7.1
- Cache Driver: Redis 

### Description:
With TelegramDrive and FacebookDriver when I try to send a msg with more then one attachments
the webhook is called one time per attachment, and the receiveImages/Video method contains only one element.

Right now, in order to solve this issue, i've developed a middleware where test the media_group_id.
BUT, this workaround doesnt work for files different from images/videos because the media group id is not provided.

Any fix?

Regards, 
M

**Comment by mpociot** [comment]
This is not really an issue with BotMan. This is the way the webhooks work. If a service sends multiple attachments in a single webhook, you can retrieve them all at once. Otherwise you will have to implement something yourself.

**Comment by MarcoPostiglione** [comment]
Could you give me any suggestions? (Middleware?)

**Comment by romansidorov** [comment]
How have you solved it with several images as an attachment? Thanks.

**Comment by ibes** [comment]
@MarcoPostiglione 
Have you ended up with a solution?

**Comment by Erick2011** [comment]
Hello, @MarcoPostiglione can u give me a clue how to do that middleware? i am trying to send multples files of the same type and maybe what u did work perfect for my project

**Comment by IljaPHP** [comment]
Hello, @romansidorov , @MarcoPostiglione , @ibes, @Erick2011!
Did you done this middleware? Can you help me with it?
