### ISSUE TITLE
getting started and persistent menu without botman studio (laravel)

### ISSUE THREAD

**Issue by sohaibilyas** [botman/botman#803]
- BotMan Version: 2.3.2
- PHP Version: 7.0.9
- Messaging Service(s): facebook messenger
- Cache Driver: none

### Description:
i want to make persistent menu and getting started using simple botman (without botman studio)!

**Comment by mpociot** [comment]
Hi,
please use GitHub issues only for issues with the library. If you have questions about how to use the library, join us on [Slack](https://slack.botman.io) or use the [Forum](https://botman.io/forum).

Thank you
