### ISSUE TITLE
Payload after request

### ISSUE THREAD

**Issue by tasselchof** [botman/botman#804]
Hello!

I want to edit a message, which I send to a user instead of writing a new one. For this purpose, I need message id, but as I see from the code (for example, in Conversations):

```
    /**
     * @param string|\BotMan\BotMan\Messages\Outgoing\Question $message
     * @param array $additionalParameters
     * @return $this
     */
    public function say($message, $additionalParameters = [])
    {
        $this->bot->reply($message, $additionalParameters);

        return $this;
    }

```

It's not saved anywhere.

What is the idea behind this?

**Comment by mpociot** [comment]
This is currently not possible with the BotMan 2.x design.
If you want to access the reply payload, please use `$this->bot->reply` in your conversation directly, instead of using the `say` method.
