### ISSUE TITLE
Answer::getText() returns the content of Answer::getValue()

### ISSUE THREAD

**Issue by PinkTiu** [botman/botman#805]
- BotMan Version: 
botman/botman: 2.3.3
botman/botman: 2.3.3   
botman/driver-web: 1.5.1  
botman/studio-addons: 1.2.2
botman/tinker: 1.0.3 
laravel/framework: 5.6.20 
- PHP Version: 7.2.4
- Messaging Service(s): driver-web
- Cache Driver: Laravel Cache

### Description:
`$answer->getText()` returns the content of `$answer->getValue()`. According [to the docs ](https://botman.io/2.0/conversations) `$answer->getText()` should return the caption of the Button.

### Steps To Reproduce:
Normal Botman Studio and start this conversation:

```
<?php

namespace App\Conversations;

use BotMan\BotMan\Messages\Conversations\Conversation;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Outgoing\Question;

class TestConversation extends Conversation {

	public function askForDatabase()
	{
		$question = Question::create('Do you need a database?')
		                    ->fallback('Unable to create a new database')
		                    ->callbackId('create_database')
		                    ->addButtons([
			                    Button::create('Of course')->value('yes'),
			                    Button::create('Hell no!')->value('no'),
		                    ]);

		$this->ask($question, function (Answer $answer) {
			// Detect if button was clicked:
			if ($answer->isInteractiveMessageReply()) {
				$selectedValue = $answer->getValue(); // will be always 'yes' or 'no'
				$selectedText = $answer->getText(); // will be always 'yes' or 'no', never 'Of course' or 'Hell no!'

				$this->say("Your answer (value): " . $selectedValue); // will be always 'yes' or 'no'
				$this->say("Your answer (text): " . $selectedText); // will be always 'yes' or 'no', but should be 'Of course' or 'Hell no!'
			}
		});
	}

	public function run()
	{
		$this->askForDatabase();
	}

}
```

**Comment by mpociot** [comment]
This depends on the driver implementation. 
The web driver accepts a `value` parameter when an answer gets sent. It could be that the default vue tinker component does not use this parameter.

See: https://github.com/botman/driver-web/blob/master/src/WebDriver.php#L117-L118

**Comment by PinkTiu** [comment]
It's definitely related to the vue tinker component. 

The vue tinker component doesn't POST the `value` to the server. Instead only the `text` is POSTed but with the expected **content** of `value`. Botman recognizes that `value` is missing and replaces it with `text`.

So both `$answer->getText()` and `$answer->getValue()` return the `value`. 

Maybe you should post your issue here: https://github.com/botman/vue-tinker-component

The changes you have to make aren't that complicated.
