### ISSUE TITLE
Need a Fix removeStoredConversation() for this method

### ISSUE THREAD

**Issue by lohiloki** [botman/botman#821]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s):
- Cache Driver:

### Description:
I am creating 3buttons Hi, Hello and Bye. When I click first button I am getting response as Hello, But I am not getting response again when I click same button or other buttons. It goes to fallback message. When I tried to figure it out I found removeStoredConversation() this function clearing the conversation cache. Is there anyway to fix this method. If I comment this I am getting responses. 

HandlesConversations.php -> removeStoredConversation() 

this is the method which is causing problem.

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Actually, it is not a problem.  Buttons or other interactive elements, that the user already used, are not part of the conversation anymore. So when they get clicked again, the user is already at another part of the conversation. is there are command or things that are more important than the current conversation, then you can add listeners for that with the `stopsConversation` method like.

```
$botman->hears('important text or payload', function(BotMan $bot) {
    ...
})->stopsConversation();
```

This will even be called if you are currently in a conversation. There is also `skipsConversation()` which will let the conversation move on afterward. Stops, will kill the conversation.
