### ISSUE TITLE
Slack Driver fails to install on clean install of botman without botman studio

### ISSUE THREAD

**Issue by pjfsilva** [botman/botman#832]
- BotMan Version: 2.3.3
- PHP Version: 7.0.30 x64
- Messaging Service(s): Slack
- Cache Driver: None
- OS: Win7 64

### Description:
Slack driver fails to install on a clean installation of BotMan without studio following the Documentation instructions.

#668 seems to be related but it also seems to only be fixed for Botman Studio installations and not Botman without Studio (and I can't have studio because it requires PHP > 7.1.3)

For me this seems a big issue since new users are immediately discouraged to using Botman with Slack since it fails to install. 

```
D:\www\public_html\botman7>composer require botman/driver-slack
Using version ^2.1 for botman/driver-slack
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for react/event-loop (locked at v0.5.2) -> satisfiable by react/event-loop[v0.5.2].
    - botman/driver-slack 2.1.0 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0].
    - botman/driver-slack 2.1.1 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0].
    - botman/driver-slack 2.1.2 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0].
    - botman/driver-slack 2.1.3 requires mpociot/slack-client ~1.0 -> satisfiable by mpociot/slack-client[1.0].
    - Conclusion: don't install mpociot/slack-client 1.0
    - Installation request for botman/driver-slack ^2.1 -> satisfiable by botman/driver-slack[2.1.0, 2.1.1, 2.1.2, 2.1.3].


Installation failed, reverting ./composer.json to its original content.

```
### Steps To Reproduce:
 - composer require botman/botman
 - composer require botman/driver-slack

**Comment by r0b3r7** [comment]
Any updates? Have same problems...
Installation of 1.0 version helps `composer require botman/driver-slack 1.0` but I want to use Realtime API and it requires `composer require mpociot/slack-client`

**Comment by mpociot** [comment]
This is now fixed. I just tagged `slack-client` version 1.1 which resolves this issue.
