### ISSUE TITLE
Docs: correct PHP min version required for Botman Studio 

### ISSUE THREAD

**Issue by pjfsilva** [botman/botman#833]
On this page: https://botman.io/2.0/installation there is no information that Botman Studio requires PHP 7.1.3 or higher.

The docs mislead the user because they say for Botman requirement is PHP 7 and for Studio check Laravel requirements that again only say > 7.0.0 but when I try to install botman studio symfony/console v4.1.0 seems to require php 7.1.3.

The docs should clearly say that Botman Studio requires > 7.1.3.

**Comment by mpociot** [comment]
Done, thanks
