### ISSUE TITLE
Handling big files

### ISSUE THREAD

**Issue by antonioribeiro** [botman/botman#834]
As telegram accepts files up to 1.5GB, it would be nice to see BotMan handling them, because Telegram does not prevent users to upload big files. So when that happens, currently we get a 

```
Bad Request: file is too big
```

But, probably only because BotMan is trying to download the uploaded file:

```
$response = $this->http->get($this->buildApiUrl('getFile'), [
    'file_id' => $file['file_id'],
]);
```

But, if the 'file_size' is too big, instead of downloading it, it could just handle this file info to the application:

```
'document' =>
 array (
   'file_name' => 'update-atto-pixel-20180510.upk',
   'mime_type' => 'application/zip',
   'file_id' => 'BQBDAQAXiQADdasxRXRWEb5kWS7TAk',
   'file_size' => 390830746,
),
```

This should be enough for the bot to forward the file to another user on on a channel without being compromised.

**Comment by Erick2011** [comment]
can u please give me an little example to handle this, i dont need to download any file, i will forward them bu fileids. pls help me with it
