### ISSUE TITLE
Starting new conversation inside of other conversation

### ISSUE THREAD

**Issue by leon0399** [botman/botman#835]
- BotMan Version: 2.3.3
- PHP Version: `PHP 7.2.4-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:55:11) ( NTS )`
- Messaging Service(s): Telegram
- Cache Driver: LaravelCache

### Description:

e.g.
When I tryes to call `$this->bot->startConversation(new SecondConversation())` inside `FirstConversation`, the Cache Driver **does not delete** previous conversation from cache, so if I trying to reply on any message inside messenger (Telegram), it pulls the first cached instance by name (look at screenshot, it will pull an upper cached instance). 

![Alt text](https://monosnap.com/image/S4wjN0HFctDEflECSNW9ABbHFi2cMW.png)
![Alt text](https://monosnap.com/image/9jfxS50TN8M9WpDxBTwsWpeFlW9WJF.png)

Is it an any proper way to start a new Conversation from other one?

### Steps To Reproduce:

Try to start a new conversation inside of one other: `$this->bot->startConversation(new SecondConversation())`

**Comment by christophrumpel** [comment]
Normally, this works without any problems. I am doing this all the time. Do you maybe got a permission problem with your cache folders?

**Comment by aleksey-kornienko** [comment]
I fixed it by removing of current conversation from cache  before calling of new conversation like this(inside answer callback function):
```
$this->ask($question, function (Answer $answer) {
    $this->say('text');
    $this->bot->removeStoredConversation($answer->getMessage());    
    $this->bot->startConversation(new NextConversation());
});
```
