### ISSUE TITLE
How do I send message using userid or message id or sequence ?

### ISSUE THREAD

**Issue by prdpspkt** [botman/botman#844]
- BotMan Version: 2.0.0
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: Doctorine

### Description:
I Didn't find an idea to send message to specific user. After user subscribes to messenger.

### Steps To Reproduce:
Not an error.

**Comment by kubk** [comment]
Hello @prdpspkt 

You can use `$botman->say('message', 'user-id', $driver)` for this purpose.
Check 'Originating Messages' section here https://botman.io/2.0/sending

**Comment by magicwarms** [comment]
Hi @christophrumpel 

i cannot sending a message to spesific user, i have user-id from telegram, and when i test, its not working,

**Comment by christophrumpel** [comment]
Please come to the BotMan Slack team and ask there.
