### ISSUE TITLE
How can I send information to Slack and not the other way around?

### ISSUE THREAD

**Issue by PointfullDevelopers** [botman/botman#845]
I'm able to chat with a bot when I'm in Slack but what I wanted to do was grab the information the user is giving me on facebook/website/etc and create a Slack channel for him where a human could reply to his question. Is this possible? From what I've seen in the documentation it seems it's not

Thanks in advance

**Comment by christophrumpel** [comment]
Hmm I am not sure if this even possible. Is the user already in your Slack team or would he need to login to a new slack team first?

**Comment by mpociot** [comment]
@PointfullDevelopers you would need to use raw Slack API calls to do this. I did something similar to link between Telegram and Slack: https://gist.github.com/mpociot/1305e7590c3f1c2cc3824ae91441fbdc
