### ISSUE TITLE
Facebook Messenger does not work on CodeIgniter

### ISSUE THREAD

**Issue by wilfredonoyola** [botman/botman#846]
- BotMan Version: ^2.3
- PHP Version: 7.0.22
- Messaging Service(s): Facebook / Web
- Cache Driver:

### Description:
I have integrated botman with CodeIgniter Framework and also I followed all steps for setup the bot (https://botman.io/2.0/driver-facebook-messenger) and I seen the video tutorial (https://buildachatbot.io/video/install-facebook-driver).

Now, I spent much time on this. But, I do not find the solution to it works correctly.

### Steps To Reproduce:

1. Setup all steps as video tutorial (https://buildachatbot.io/video/install-facebook-driver)
2. And type a text "hi" on chat, The bot does not work.

MY CODE:

 // Load the driver(s) you want to use
        DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);

        // Create an instance
        $botman = BotManFactory::create($config);

        // Give the bot something to listen for.
        $botman->hears('hi', function (BotMan $bot) {
            $bot->reply('Hello');
        });

        $botman->hears('delayed', function (BotMan $bot) {
            $bot->reply('Field will remain in yellow (delayed)unless a game is scheduled on it.');
        });

        $botman->hears('canceled', function (BotMan $bot) {
            $bot->reply('Games cancelled due to poor field conditions.');
        });

        // Start listening
        $botman->listen();

Please, you could help me with some advice.

Thanks.

**Comment by christophrumpel** [comment]
hey @wilfredonoyola , what do you mean by it does not work? Don't you get a reply? Do you get any errors? Have you checked your log files? Have you defines `$config` somewhere because I don't see it in your example`?
