### ISSUE TITLE
Contexts Dialogflow 

### ISSUE THREAD

**Issue by lucas95t** [botman/botman#847]
Hey, I want to access the Contexts Parameters from the Dialogflow JSON. I tried to add a function to the apiai.php but it's not working.
I added the following lines to the received function

$context = isset($response->result->contexts->parameters) ? (array)
$response->result->contexts->parameters : [];
$message->addExtras('apiContext', $context);

**Comment by jjhamkuijpers** [comment]
Hey @lucas95t!! I think you want the parameters from de JSON result? If so than you should use do this:

```
$context = isset($response->result->parameters) ? (array) $response->result->parameters : [];
$message->addExtras('apiContext', $context);
```

Or if you do want the Context Parameters than you should have a good look at the json result and see that context is an array. So this could be a solution:

```
$context = isset($response->result->contexts[0]->parameters) ? (array) $response->result->contexts[0]->parameters : [];
$message->addExtras('apiContextParameters', $context);
```

I hope this helps you?

**Comment by lucas95t** [comment]
Yes, that works. Thank you
