### ISSUE TITLE
'startConversation()' fails in a 'hears()' closure, triggered from a Slack Command

### ISSUE THREAD

**Issue by th3d0g** [botman/botman#851]
- BotMan Version: 2.0
- PHP Version: 7.1.9
- Messaging Service(s): Slack Driver 2.1
- Cache Driver: Botman Studio

### Description:

Calling 'startConversation()' fails when called from the 'hears()' closure. See example below:

`$botman->hears('/project', function ($bot) { `
`   $bot->startConversation(new ExampleConversation()); `
` });`

This is being triggered from a Slack command, which responds with:

`/project failed with the error "invalid_attachments_format"`

It's worth noting that the example included works which calls a controller function. This works differently as it's triggered via an Event as opposed to a Command in the example above.

`$botman->hears('Start conversation', BotManController::class.'@startConversation');`

### Steps To Reproduce:

1. Setup a Slack bot, and add a command.

2. Create a 'hear()' function to listen out for this command. Within the closure run `$bot->startConversation(new ExampleConversation()); `.

3. Call the command from Slack.

**Comment by christophrumpel** [comment]
What is the error you get?
