### ISSUE TITLE
Google Assistant

### ISSUE THREAD

**Issue by barryvdh** [botman/botman#857]
Should we create a Google Assistent driver? As far as I can tell, the flow is a bit like this:

 - Create a project on https://console.actions.google.com/ with a Custom Intent -> creates DialogFlow project
 - Add webhook URL to botman, either for the fallback intent or custom intents
 - The incoming Dialogflow request can be parsed
 - Return with a Dialogflow response: https://dialogflow.com/docs/fulfillment

In the most basic example we can just parse the queryText, but it also includes the action and intent. So I guess the DialogFlow parser could be used, except no need to call the API ourself, just parse the incoming message and respond.

**Comment by mpociot** [comment]
Yeah I looked at it too - I think we can use a specific driver in combination with the Dialogflow middleware for this, yeah.

**Comment by barryvdh** [comment]
Should I create a local implementation, or is it easier to setup a base repository and work from there?

**Comment by barryvdh** [comment]
Work in progress: https://github.com/botman/driver-google-assistant

**Comment by SergiX44** [comment]
Any progress about that? @barryvdh 
I tried to use the dev-master version, but seems that it doesn't return anything.
