### ISSUE TITLE
[Feature] Listening to Telegram commands

### ISSUE THREAD

**Issue by feralheart** [botman/botman#859]
- Messaging Service(s): Telegram

### Description:
Will be in the future a way to add Telegram commands?

For example a `->hearsCommand('command', function(){});` method what parses the command and the attributes, too (like the images in `hearsImage` method)

**Comment by christophrumpel** [comment]
Hey @feralheart , do you if they get send in a special format? Or is it just a string? Guess you could just use `hears('/yourCommand {param1} {param2}')` right?

**Comment by holtkamp** [comment]
To make this working for other drivers as well, one can make the initial slash optional:

```php
hears('/?yourCommand {param1} {param2}')
```

**Comment by jonnywilliamson** [comment]
Please don't forget that Telegram will have an "entities" section in the Update data packet sent to the webhook with full details about any command the user has sent. It's much cleaner to use that to detect commands.

https://core.telegram.org/bots/api#messageentity
