### ISSUE TITLE
How can I send multiple attachments?

### ISSUE THREAD

**Issue by NikHaker** [botman/botman#862]
Hello. I'm implemeting my custom driver. I have the following question can I attach multiple objects to bot's message?
It seems like the `BotMan\BotMan\Messages\Outgoing\OutgoingMessage` can only store one instance  `BotMan\BotMan\Messages\Attachments\Attachment`, or I am wrong?
Or it`s supposed that bot can only attach one object per message...
Thanks in advance!

**Comment by romansidorov** [comment]
How have you solved it with several images as an attachment? Thanks.

**Comment by shadowusr** [comment]
I didn't solve this issue. I decided that this feature isn't very important for my project. Unfortunately, the developers totally ignored my question.
