### ISSUE TITLE
Facebook chat: Error sending payload

### ISSUE THREAD

**Issue by pixelshocks** [botman/botman#863]
- BotMan Version: 2.4
- PHP Version: 7.2.3
- Messaging Service(s): Facebook
- Cache Driver:

### Description:
Hello,

I am using ngrok with XAMPP on my local machine and am receiving the `Error sending payload: ` error. 

I have looked around for similar errors and found that other users had experienced it due to SSL errors but I am using ngrok and have ensured I don't have any SSL cert in my apache settings. 

Any help will be appreciated and thanks in advanced!

```
<b>Fatal error</b>:  Uncaught BotMan\Drivers\Facebook\Exceptions\FacebookException: Error sending payload:  in D:\Programs\XAMPP\htdocs\chat\vendor\botman\driver-facebook\src\FacebookDriver.php:503
Stack trace:
#0 D:\Programs\XAMPP\htdocs\chat\vendor\botman\driver-facebook\src\FacebookDriver.php(398): BotMan\Drivers\Facebook\FacebookDriver-&gt;throwExceptionIfResponseNotOk(Object(Symfony\Component\HttpFoundation\Response))
#1 D:\Programs\XAMPP\htdocs\chat\vendor\botman\botman\src\BotMan.php(638): BotMan\Drivers\Facebook\FacebookDriver-&gt;sendPayload(Array)
#2 [internal function]: BotMan\BotMan\BotMan-&gt;BotMan\BotMan\{closure}(Array)
#3 D:\Programs\XAMPP\htdocs\chat\vendor\mpociot\pipeline\src\Pipeline.php(114): call_user_func_array(Object(Closure), Array)
#4 [internal function]: Mpociot\Pipeline\Pipeline-&gt;Mpociot\Pipeline\{closure}(Array)
#5 D:\Programs\XAMPP\htdocs\chat\vendor\mpociot\pipeline\src\Pipeline.php(102): call_user_func_array(Object(Closure), Array)
#6 D: in <b>D:\Programs\XAMPP\htdocs\chat\vendor\botman\driver-facebook\src\FacebookDriver.php</b> on line <b>503</b><br />
```

```
$config = [
    'facebook' => [
        'token' 	=> 'token',
        'app_secret' 	=> 'app_secret',
        'verification'	=> 'verification',
    ]
];
$botman = BotManFactory::create($config);
$botman->hears('hey', function (Botman $bot) {
    $bot->reply('hello there');
});
$botman->listen();
```

**Comment by christophrumpel** [comment]
Hey, the `Error sending payload:` is just a general error message that is created by BotMan if there happens an error while trying to send a request to FB. So unfortunately this doesn't tell us exactly what is happening. But, normally with this error we get the error message, which is missing in your output.

Can you confirm that CURL is installed on your environment?

**Comment by pixelshocks** [comment]
Yes cURL is installed and enabled in my environment.

I actually went on to manually develop the chatbot via cURL and it is running properly. However it will be great if I can use botman :)

**Comment by christophrumpel** [comment]
Hm, what about the Facebook webhook. Did it work to setup the webhook for your BotMan application?

**Comment by pixelshocks** [comment]
Yes I was able to verify with BotMan, I only encountered the error when I do the `$bot->reply()`

**Comment by christophrumpel** [comment]
Hmm I see. It is really difficult to tell because there could many reasons for this not working. Here is where the exception is thrown. I would try to check the `$response` here and see what status code the request responds. Maybe this helps you.

**Comment by pixelshocks** [comment]
Thanks for the advice, it was indeed hard to tell, will wish to use BotMan someday :)

**Comment by reiner-vaca** [comment]
Hello Good afternoon, I would like to know if there is a solution to the message

**Comment by binhlvit** [comment]
You need to disable Require App Secret in facebook app advance settings.
