### ISSUE TITLE
Insufficient permission to access user profile

### ISSUE THREAD

**Issue by kisese** [botman/botman#864]
- BotMan Version: 2.4.1
- PHP Version: 7.1.3
- Messaging Service(s): Facebook
- Cache Driver:

### Description:
When trying to access user information in a conversation

Getting the following error

Error sending payload: (#100) Insufficient permission to access user profile. {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Insufficient permission to access user profile.

### Steps To Reproduce:

Accessing user name via botman

> `$this->bot->reply("Hi! " . $this->bot->getUser()->getFirstName() . ", Welcome ");`

**Comment by HGWells07** [comment]
I've also gotten this same problem recently...
Still working out why

**Comment by christophrumpel** [comment]
Hey, there has been a change with Facebook and you cannot access `all` the fields anymore when you don't have the permission. This is why there is a new method `getUserWithFields`. Here you can read more about it https://github.com/botman/driver-facebook/pull/74

And here some info on the change on FB site: https://developers.facebook.com/docs/messenger-platform/identity/user-profile/
