### ISSUE TITLE
how to set up button's url 

### ISSUE THREAD

**Issue by jercc** [botman/botman#868]
- BotMan Version: 2.0
- PHP Version:7.1.16
- Messaging Service(s):botman
- Cache Driver:

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey @jercc , what buttons are you talking about? For Telegram or Facebook or any other messaging service?

**Comment by TheodoreRiant** [comment]
Hello I am also looking for a solution (Telegram)

**Comment by feralheart** [comment]
Hi @TheodoreRiant 
What solution are you searching? Please open a new issue with your detailed question and we will try to answer it.

**Comment by romansidorov** [comment]
For googlers.

You can use `additionalParameters()` method on `BotMan\BotMan\Messages\Outgoing\Actions\Button` class instance to reach the desired effect. For example:

```
use BotMan\BotMan\Messages\Outgoing\Actions\Button;

Button::create('Text on the button')
     ->additionalParameters([
           'url' => 'https://google.com',
     ]);
```

**Comment by aleresoftware** [comment]
> For googlers.
> 
> You can use `additionalParameters()` method on `BotMan\BotMan\Messages\Outgoing\Actions\Button` class instance to reach the desired effect. For example:
> 
> ```
> use BotMan\BotMan\Messages\Outgoing\Actions\Button;
> 
> Button::create('Text on the button')
>      ->additionalParameters([
>            'url' => 'https://google.com',
>      ]);
> ```

Does it work for custom chat widget?

**Comment by bhumitg** [comment]
> For googlers.
> 
> You can use `additionalParameters()` method on `BotMan\BotMan\Messages\Outgoing\Actions\Button` class instance to reach the desired effect. For example:
> 
> ```
> use BotMan\BotMan\Messages\Outgoing\Actions\Button;
> 
> Button::create('Text on the button')
>      ->additionalParameters([
>            'url' => 'https://google.com',
>      ]);
> ```

It does not work in Web Widget.
What is the solution for Web Widget?

**Comment by filippotoso** [comment]
Check the Web Widget sources and verify if button urls are implemented.
