### ISSUE TITLE
Cancel Question and start listen commands

### ISSUE THREAD

**Issue by oleghalin** [botman/botman#869]
- BotMan Version: #.#.#
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver: 

### Description:
Hello. I have little problem with `Question`. How i can continue to listen my common commands if `$answer` is not isInteractiveMessageReply? For example:
```
/seeds - ask Question
if i send again /seeds i should ask it again, of it will be isInteractiveMessageReply perform other action
```

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Ah ok I see what you mean. Like for `/seeds` it should always trigger the command even inside a conversation, right?  What you can do is define the command / listener like this:

```
$botman->hears('/seeds', function(BotMan $bot) {
	//.. do your stuff
})->skipsConversation();
```

Now a current conversation would be skipped and still the listener for `/seeds` will be called. Afterward the conversation will go on, if you don't want that you can use `stopsConversation` instead.
