### ISSUE TITLE
Formatted text with attachments

### ISSUE THREAD

**Issue by gborgonovo** [botman/botman#870]
- BotMan Version: 2.1.5
- PHP Version: 7.0
- Messaging Service(s): Telegram

### Description:
When I send a text message I can specify `'parse_mode' => 'HTML'` in parameters option and the message is sent and formatted as HTML.
But if I send an image the message is in plain text.

Is there any tricky-trigger to set up to get formattet text with images?

Thank you!

**Comment by christophrumpel** [comment]
Hey, I don't think images are supported by Telegram? Have you checked the docs here https://core.telegram.org/bots/api#html-style

**Comment by gborgonovo** [comment]
Yes, they are.
See sendPhoto method, it has the parse_mode parameter that can be Markdown or HTML to show bold, italic, fixed-width text or inline URLs in the media caption.
All the send[AnyMedia] methods have it.

**Comment by christophrumpel** [comment]
Hmm ok, I thought you were trying to send an image via an image tag, but you meant you are sending an attachment with text and the text is sent as plain text instead of parsed with HTML right? Can you show me your code?

**Comment by gborgonovo** [comment]
Yes, it's right.
This is my method.

```
  public function sendDailyEvents()
  {
    $botman = app('botman');
    $events = Event::where('event_date', 'like', date('d/m').'%')->get();
    foreach ($events as $event)
    {
      // Create the text of the message
      $message = '<b>'.$event->event_date.'</b>: <i>'.$event->event_description.'</i>';
      if (isset($event->event_image))
      {
        // Create attachment
        $attachment = new Image($event->event_image, [
          'custom_payload' => true,
        ]);

        // Build message object
        $message = OutgoingMessage::create($message)
          ->withAttachment($attachment);

      }
      // Send the message
      $botman->say($message, $event->ownerid, TelegramDriver::class,['parse_mode' => 'HTML']);
    }
  }
```

**Comment by christophrumpel** [comment]
Hey, just tried it out myself. The code is fine and the payload is correct as well. I just noticed that it is `not` working on the desktop client, but `it works` on the native app on my phone. So it seems that Telegram it not supporting it for all clients =/ Still on BotMan side everything is correct.

**Comment by gborgonovo** [comment]
Oh, gosh! You are right! Sorry, I was working from the PC and I didn't noticed it was working of the device. Thank you!!

**Comment by christophrumpel** [comment]
yeah same with me, but I had something similar with Facebook, so I am glad I checked it =)
