### ISSUE TITLE
[Feature] add a catchall() to be triggered for all messages without suppressing fallback() mechanic

### ISSUE THREAD

**Issue by ceyquem** [botman/botman#872]
- BotMan Version: 2.0
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I would like to have a function that would be triggered by any message received. However using `$botman->hears('.*', function ($bot) {}` does not work for me as `$botman->fallback(function($bot) {}` will never be triggered (as it assumes there was a pattern match).

### Steps To Reproduce:
The idea would be to add a `public function catchall($callback)` in BotMan.php that would be exactly the same as the `fallback` but that would be called differently, for instance like:

    if (empty($this->getBotMessages()) && ! is_null($this->catchallMessage)) {
        $this->callCatchAllMessage();
    }

Is it possible?

**Comment by gnanet** [comment]
join the request, this would be a base for my skype-groupchat-bot, which would notify me if my name is mentioned in the conversation

**Comment by christophrumpel** [comment]
@ceyquem why are you not just using a middleware? This way you can check all incoming messages, and if you are mentioned, then you can change the message to trigger a specific hears method. Have you thought about that?

**Comment by gnanet** [comment]
I cannot speak for @ceyquem  ,  but my problem is i could not even find rlevand examples, so i am unable to figure out how . The logic to hook before the bot to achieve the "listen-to-all"  is indeed middlware smell. but as an unexperienced script hacker ... :)

**Comment by christophrumpel** [comment]
Ok, so he are some examples:

* [Docs](https://botman.io/2.0/middleware)
* [Here I use the middleware to store the user if he is a new one](https://github.com/christophrumpel/bcwp-newsletterbot/blob/production/app/Http/Middleware/SaveUserMiddleware.php)
* [Here I use a middleware to add the typing indicator when a message comes in](https://github.com/christophrumpel/bcwp-laraconeu-chatbot/blob/production/app/Http/Middleware/AddTypingIndicator.php)

I hope that helps. There is a lot you can do with middlewares, so I don't think a `catchall` method is required.

**Comment by gnanet** [comment]
Now that i was typing the issue URL , a funny or misterious fact, this is MY TICKET:
https://github.com/botman/botman/issues/827
Just to note this issue has 872

**Comment by ceyquem** [comment]
As recommended I used a custom heard Middleware and it does exactly what I needed :-) thanks a lot for the help @christophrumpel 👍
