### ISSUE TITLE
An example Botman+Dialogflow

### ISSUE THREAD

**Issue by gborgonovo** [botman/botman#873]
I was trying to understand how Botman (studio) works with Dialogflow.
I was trying to manage prebuilt Agents (Small-Talk, etc.)
I hope this example can be useful to someone

```
// .env
DIALOGFLOW_TOKEN=...
```
```
// routes/botman.php
<?php
use BotMan\BotMan\Middleware\ApiAi;
use BotMan\BotMan\BotMan;

$botman = resolve('botman');

$dialogflow = ApiAi::create(env('DIALOGFLOW_TOKEN'))->listenForAction();
$botman->middleware->received($dialogflow);
$botman->hears('smalltalk(.*)', function (BotMan $bot) {
    
    $extras = $bot->getMessage()->getExtras();
    $apiReply = $extras['apiReply'];
    $apiAction = $extras['apiAction'];
    $apiIntent = $extras['apiIntent'];
    
    $bot->reply($apiReply);
     
})->middleware($dialogflow);

```
If you want to use more prebuilt Agents, the only way I found was to export the prebuild agent as zip file in the Dialogflow console and import it in my custom agent. and create a "hears" for each Intent.

Maybe more experts than me can provide better hints.

Ciao

Giorgio

**Comment by christophrumpel** [comment]
Thanks for providing the example. I haven't used the prebuild agents so far.

**Comment by alegargar** [comment]
Hello @gborgonovo I have a doubt with your code. In the hears, you wrote:

> ... 'smalltalk(.*)' ...

The docu sais:

> ... 'my_api_action' ...

What does 'smalltalk' there, which are the benefits of using it, and what parameter have it to match?
In my case, to work with dialogflow, I had to put:

>  '(. *)'

If I try to put 'mybotname(. *)' It does absolutely nothing. 

Thanks in advance

**Comment by gborgonovo** [comment]
Hi @alegargar,
you can avoid smalltalk, it is a feature used to provide responses to casual conversation. See this for more info: https://dialogflow.com/docs/agents/prebuilt-smalltalk
But if you don't need it you can go on with your code.
Giorgio

**Comment by mviljoen** [comment]
The documentation says
... 'my_api_action' ...

Should this change according to an intent, or an agent, or should it stay as-is?

**Comment by jefdigital** [comment]
Hi @mviljoen, as i understand in dialogflow an intent can be identified by an action name.

You can see this in the Default Welcome Intent with the `input.welcome` action name.

So if you name all your intents with action names like `input.asksomething`, `input.saythanks`, ..., your botman app should be able to interact with them if you set `input.*` instead of `my_api_action`

**Comment by isbkch** [comment]
The documentation is confusing. Although the documentation says `my_api_action` I was never able to make it work. The only time it worked is when I used `.*` but then no extras were passed...

**Comment by celorodovalho** [comment]
The documentation is VERY POOR about that.
Don't you guys have plans to avoid it?

**Comment by rupeszh** [comment]
i resolved the issues and got response what i did was i add DIALOGFLOW_TOKEN to Client access token and my_api-action to the Intent Action and parameters name the main issues was  required to define botman explicitly inside function my workable code was: 
use BotMan\BotMan\Middleware\ApiAi;
$config = [
                'web' => [ 
                    'matchingData' => [
                        'driver' => 'web'
                    ],
                ]
            ];
         
        DriverManager::loadDriver(\BotMan\Drivers\Web\WebDriver::class);
//        DriverManager::loadDriver(\BotMan\Drivers\AmazonAlexa\AmazonAlexaDriver::class);

        $doctrineCacheDriver = new \Doctrine\Common\Cache\PhpFileCache('cache');
        $botman = BotManFactory::create($config, new DoctrineCache($doctrineCacheDriver));
        
        $dialogflow = ApiAi::create('Client access token ')->listenForAction();
        $botman->middleware->received($dialogflow);       
       
        // Apply matching middleware per hears command
        $botman->hears('intent-action-name', function (BotMan\BotMan $bot) {
            // The incoming message matched the "my_api_action" on Dialogflow
            // Retrieve Dialogflow information:
            $extras = $bot->getMessage()->getExtras();
        
            $apiReply = $extras['apiReply'];
            $apiAction = $extras['apiAction'];
            $apiIntent = $extras['apiIntent'];
//            
            $bot->reply($apiReply);
        })->middleware($dialogflow);
