### ISSUE TITLE
Conversation getText fails

### ISSUE THREAD

**Issue by tj15** [botman/botman#874]
- BotMan Version: 2
- PHP Version: 7.1.16
- Messaging Service(s): Web driver
- Cache Driver:Web driver

### Description:
I have a wamp environment, I have created a folder and installed botman via composer. I believe that all dependencie are cache are handled by tbotman studio.

I am using the webdriver and trying to build a basic conversation using the documentation provided. The bot will listen for wwww for example and ask for the users name, it should then reply with a welcome including the username. The listen part works, when I try wwww the user is asked to provide their name but code stope there. 

There is nothing the php logs and the cache has no entry, I assume that the getText function isn't working.

The file I am using are attached.

[chatfiles.zip](https://github.com/botman/botman/files/2367424/chatfiles.zip)

**Comment by christophrumpel** [comment]
Hey, you need to set up your environment so you can see errors. Without them, it is very difficult. From your files I would `guess` that you misspelled the method `getText()`, you wrote `gettext()` which is wrong. Please try that.

**Comment by tj15** [comment]
Hi, thanks for gettig back to me. I have check the code but always use getText(). This code is really just a cut and paste from the conversation documentation (https://botman.io/2.0/conversations) and seems to partially work. I wasn't sure if this was an issues with the required dependencies

I have looked at the logging.php file but there are no logs generated (i.e Laravel.logs), is there documentation on how enable this? This would at least give me a clue.

I am really interested in the product amd want to learn but finding with the info available difficult to get started.

**Comment by christophrumpel** [comment]
Thats when I recommend using BotMan Studio for starting because most stuff is already setup. there you also have a `storage/logs/laravel.log` file where you can see all the errors. That helps a lot for debugging. Unfortunately, I cannot speak for your custom PHP application and your environment.

**Comment by tj15** [comment]
This is just an knowledge issue on my part but how do you use the BotMan studio? I have started from scratch as follows:

WAMP server
-composer 1.7.2
-php 7.2.4
-In C:\wam64\www run composer global require "botman/installer"
-Composer folder installed at AppData/Roaming/
-botman new chatbot - install process complete and and folder "chatbot" created in www  - message given: Botman studio ready! Build an amazing chatbot
Change directory to chatbot

From here how do I utilise the studio?

If I use
php artisan serve - That will start the development server at http://127.0.0.1:8000
but how do I modify that chat?

Q - how to I modify the tinker chat?

**Comment by christophrumpel** [comment]
Hey, this is not really BotMan specific. The setup is like any other Laravel application, the only difference is that you can use the botman installer like you did. After installing it you can play around with the given examples. I would recommend reading the [documentation](https://botman.io/2.0/installation) to get a better understanding of BotMan. As a start, I would check the botman rout file under `routes/botman.php`. There you have the listener and there you can define how you bot should response. For further questions like that please join the [BotMan Slack Channel](https://slack.botman.io/) and you can also check out [Marcel's course on BotMan](https://course.buildachatbot.io/) or my ebook and course about [Building Chatbots with PHP](https://store.christoph-rumpel.com/).
