### ISSUE TITLE
Start conversation when Facebook messenger is opened.

### ISSUE THREAD

**Issue by riasarkar2012** [botman/botman#875]
- BotMan Version: 2.0
- PHP Version: 7.1
- Messaging Service(s): Facebook Messenger

Description:
I have set up a botman app on client's Facebook page. I have setup the 'Get started' button for first time users, which works fine. My issue is when user comes to the page a second time, how do I load the initial conversation without 'hears' method? I want the options to load as soon as the user opens the messenger on my page. I was looking at the 'Originating message' method and it might sound silly but I could not find a suitable example on how to get the user id for an user. This does work locally but does not work on Facebook:
$user = $bot->getUser();
$bot->reply('Your ID is: '.$user->getId())

Please provide some insight on this issue.
Also, is there a way to provide a default button on the app with botman? I do not want to use persistent_menus.
Thank you.

**Comment by christophrumpel** [comment]
hey @riasarkar2012 ,

first, let me check if I understand you correctly. When the user comes back to the chat, you want the bot to start writing something before the user writes something?

You can use `originating messages` to let the bot say something, but I am not sure if this is what you want? Normally, when the user comes back to the chat, the user types something first and depending on your bot, the bot will continue where the user left off or provide something new the user can do.

There are multiple ways to the the ID from a user. I would try this `$bot->getMessage()->getSender()`. there is right now problem with Facebook and the `getuser` method.  (you can read about it [here](https://github.com/botman/driver-facebook/pull/74))

**Comment by riasarkar2012** [comment]
@christophrumpel 
Thank you for the prompt reply and as expected, it works like a charm. 
One more question, is it possible to have a default button in Facebook messenger via botman, which takes me back to any part of the conversation I choose?

Thank you.

**Comment by christophrumpel** [comment]
Hmm default button... you can create messages with buttons, but the persistent menu is the only buttons that you can always access. Or do you mean something different?

**Comment by riasarkar2012** [comment]
Yes I meant a button which is always accessible.
Ok so there seems to be no way we can provide such a button without 'persistent_menu'.
And I will close the conversation now. Thanks a lot for your help.
