### ISSUE TITLE
Facebook catch empty message

### ISSUE THREAD

**Issue by temamagic** [botman/botman#877]
- BotMan Version: 2.0
- PHP Version: PHP 7.0.31-1
- Messaging Service(s): Facebook
- Cache Driver: - 

### Description:
I want catch when message text is empty. For ex. I send sticker. fallback method don't work when I do that. 

### Steps To Reproduce:
I tried
```
$botman->hears('.*',function (BotMan $bot)...
and 
$botman->fallback(function (BotMan $bot) ...
```

How can I do that trick?

**Comment by christophrumpel** [comment]
You mean when Facebook sends an empty message? Is it even possible to send an empty message?

**Comment by temamagic** [comment]
> You mean when Facebook sends an empty message? Is it even possible to send an empty message?

No, I mean empty text, when someone sends stickers for ex. or anything else.

**Comment by christophrumpel** [comment]
Ah ok I see. For mee `$botman->hears('.*', function (BotMan $bot) {..` worked. Also stickers trigger this listener.
