### ISSUE TITLE
AskLocation is called but not getting the callback in Firsttime

### ISSUE THREAD

**Issue by dukedellington** [botman/botman#885]
- BotMan Version: 2.3
- PHP Version: 7.2
- Messaging Service(s): Facebook
- Cache Driver:

### Description:

Send Location not getting any data and not called the callback.
Sample code 

```
public function askLocation()
   {
       $question = 'Please send me your location.';
       $this->askForLocation($question, function (Location $location) {
           try {
               $this->fbLocation = [
                   'latitude' => $location->getLatitude(),
                   'longitude' => $location->getLongitude()
               ];
               $this->geoLocation = new GeoLocation($this->fbLocation['latitude'], $this->fbLocation['longitude']);
               $this->geoLocation->reverseAddress();
               $this->displayMoversList();
           } catch (\Exception $exception) {
               $this->say('You didn\'t provide me your location :(');
               $this->askLocation();
           }
       }, null, [
           'message' => [
               'quick_replies' => json_encode([
                   [
                       'content_type' => 'location'
                   ]
               ])
           ]
       ]);
   }
```

### Steps To Reproduce:
- Show Term&Condition button template in FB chatbot messenger conversation
- When user click Buttons, opens up webview.
- User read Term&Conditions, there is a Agree button in the webview. 
- When user click "I Agree", return back to conversation and asking for location.
- Showing Location Map for location and send location.
- After that nothing happens..This is happening first time. When user open webview second time and press agree button, then send location working. Conversation getting the location and continue the flow

**Comment by metalfm** [comment]
Same behavior for Telegram.

**Comment by metalfm** [comment]
@dukedellington  it seems we forgot to add TelegramLocationDriver😂

please, close the issue

**Comment by dukedellington** [comment]
@metalfm  sorry did not get you what you mean. Facebook Driver is already installed.
Not sure what you mean by FacebookLocationDriver as we are getting callback when doing the same process from webview second time.

**Comment by metalfm** [comment]
Try to load `FacebookLocationDriver::class`

**Comment by soikathood** [comment]
After analysing the flow, I found that the callback for askForLocation is not fired first time when it is called after a webview. 
We have a webview, which shows terms & condition for using the service. If user enters into the webview and click accept; then we are asking for location. In this case for first time the callback method of askForLocation is not fired. 
But if we don't show the webview; its working fine. 
Is there any session issue in BotMan side?

**Comment by christophrumpel** [comment]
So @metalfm says it is working when loading the correct location driver?
