### ISSUE TITLE
Botman Regex seems to capture quantifiers as named parameters

### ISSUE THREAD

**Issue by knox2** [botman/botman#891]
- BotMan Version: 2.0
- PHP Version: 7.2
- Messaging Service(s): Facebook
- Cache Driver: Redis

### Description:
Botman regex in Matcher.php seems to confuse quantifiers with named parameters

### Steps To Reproduce:

const PARAM_NAME_REGEX = '/\{((?:(?!\d+,?\d+?)\w)+?)\}/';
$pattern = '([0-9]{2})';
preg_replace(PARAM_NAME_REGEX, '(?<$1>.*)', $pattern)

**Comment by danbergan** [comment]
Here's a fix - in Matcher.php:

const PARAM_NAME_REGEX = '/\{((?:(?!\d+,?\d*)\w)+?)\}/';
