### ISSUE TITLE
Its posaible to accept stripe payment in fb messenger? 

### ISSUE THREAD

**Issue by pechanxur** [botman/botman#892]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I want to accept payments in fb messenger uaing stripe and botman? If yes... is there any example? Thanks! 

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Facebook itself has its own payment service in `beta`. Check it out here: https://developers.facebook.com/docs/messenger-platform/payments/

You could integrate Stripe yourself somehow with for example a Facebook Webview, but I don't know if anyone who did that already, so no example to share. If you have one, please provide it :-)
