### ISSUE TITLE
Edit message inline keyboard markup

### ISSUE THREAD

**Issue by hanc2006** [botman/botman#893]
- BotMan Version: latest
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver: Redis

### Description:
Unable to edit a message inline keyboard markup.

### Steps To Reproduce:

```
public function keyboard()
{
        return Keyboard::create()
            ->type(Keyboard::TYPE_INLINE)
            ->addRow(KeyboardButton::create('<<')->callbackData('prev'),
                KeyboardButton::create('👍')->callbackData('accept'),
                KeyboardButton::create('👎')->callbackData('decline'),
                KeyboardButton::create('>>')->callbackData('next'))
            ->toArray();
}
 
private function bookings()
{
       $this->ask('Your bookings list', function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                switch ($answer->getValue()) {
                case 'accept':
                    return $this->say(Yeahh');
                case 'decline':
                    return $this->say('Sigh!');
                case 'next':
                    $parameters = array_merge([
                        'chat_id' => $answer->getMessage()->getPayload()['chat']['id'],
                        'message_id' => $answer->getMessage()->getPayload()['message_id'],
                        'text' => 'Next booking from DB',
                    ], $this->keyboard());
                    $this->bot->sendRequest('editMessageText', $parameters);
                }
            }
        }, $this->keyboard());
}
```

### Result:
![](https://thumb.ibb.co/m8JexU/5_D8_C64_CB_E138_4_CE5_8_F5_E_DFB25_EAC2573.jpg?raw=true)
![](https://thumb.ibb.co/hxB2j9/B995_BE63_272_E_404_E_9208_8_C205_FA2_B0_C7.jpg?raw=true)

Only the text message are updated.

### One time keyboard
I tried to set the keyboard  with this property without success.
`->oneTimeKeyboard()`

### Reply Markup
I also tried to send an edit message reply markup with hard coded keyboard..but nothing. 
```
$this->bot->sendRequest('editMessageReplyMarkup',
        [
            'chat_id' => $answer->getMessage()->getPayload()['chat']['id'],
            'message_id' => $answer->getMessage()->getPayload()['message_id'],
            'inline_keyboard' => '[[{"callback_data":"prev","text":"<<"},{"callback_data":"accept","text":"👍"},{"callback_data":"decline","text":"👎"},{"callback_data":"next","text":">>"}]]',
        ]);
```

Any suggestion?

**Comment by christophrumpel** [comment]
So what is what you want? Since you want to change the keyboard, you must be talking about a `fixed` inline keyboard which is always shown?

**Comment by zheldibayev** [comment]
> So what is what you want? Since you want to change the keyboard, you must be talking about a `fixed` inline keyboard which is always shown?

Yeah how to do the fixed inline keyboard?

**Comment by errand** [comment]
Hello!
Why does $answer->getValue() works fine with Keyboard::TYPE_INLINE and doesn't with Keyboard::TYPE_KEYBOARD ?
I'm trying to make fixed keyboard and stucked with the situation whe i see the Keyboard, but when i click on the button bot doesn't react and nothing is being logged.

**The keyboard**
`   public function keyboard()
{
        return Keyboard::create()
            ->type(Keyboard::TYPE_KEYBOARD)
            ->oneTimeKeyboard()
            ->addRow(
                KeyboardButton::create('😺')->callbackData('randomCat'),
                KeyboardButton::create('🐶')->callbackData('randomDog'))
            ->toArray();
}`
**The function**
return $this->ask('Что показать?', function (Answer $answer) {
                if ($answer->isInteractiveMessageReply()) {
                    \Log::info(print_r($answer,true));
                    switch ($answer->getValue()) {
                    case 'randomDog':
                        $this->say((new App\Services\DogService)->randomDog());
                    case 'randomCat':
                        $this->say((new App\Services\CatService)->randomCat());
                    }
                }
            }, $this->keyboard());

So there is no $answer->isInteractiveMessageReply() with Keyboard::TYPE_KEYBOARD?
Any working example would be the big help,
thank you.

**Comment by Istom1n** [comment]
> P.S. for some reason Keyboard::TYPE_KEYBOARD returns empty $answer->getValue()

This happens because `Keyboard::TYPE_KEYBOARD` returns text, not value.

> So there is no $answer->isInteractiveMessageReply() with Keyboard::TYPE_KEYBOARD?

The `isInteractiveMessageReply()` method returns false, because again, it's text, not value. The documentation tells us about it:

> When passing question objects to the ask() method, the returned Answer object has a method called isInteractiveMessageReply to detect, if the user interacted with the message and clicked on a button or simply entered text.

**Comment by nullcookies** [comment]
Why is keyboard removal added?
How to override a method?
https://github.com/botman/driver-telegram/blob/master/src/TelegramDriver.php#L166-L167

**Comment by happeningzp** [comment]
Add to config/botman/telegram.php: 
`'hideInlineKeyboard' => false`

**Comment by sergx** [comment]
For some reason there is no metter what to set in
`->oneTimeKeyboard()`
It is overwrittes by this setting:
> Add to config/botman/telegram.php:
> `'hideInlineKeyboard' => false`

More strange things
in `BotMan\Drivers\Telegram\Extensions\Keyboard` there is `toArray()` method, witch has `->filter()`. And it's removes the `false` values! So there no way to set `false` in `->oneTimeKeyboard()`. But still, if i remove this `->filter()`, my keyboards still hiden:\
