### ISSUE TITLE
Using dependencies in conversation

### ISSUE THREAD

**Issue by mabar** [botman/botman#896]
Today I read a lot of botman conversations issues and they are basically all about the same. Serialization. Objects serialization is not good idea at all. PHP implementation is unsafe, private properties cannot be used, changes in code does not affect cached code, usage of unserializable objects fails.

It simply forced me to set my database connection into conversation in __wakeup method through global magic. It is really ugly and it makes me sad there is no better way to use conversation dependencies properly.

I understand that current implementation cannot be changed without huge bc breaks although not using serialization at all would be best option.
But at least there should be an option to set dependencies during wakeup. Someting like onConversationCreate event.

**Comment by mpociot** [comment]
Hi,

Thank you for the comment. You're right. The current implementation is not ideal when you want to manage dependencies in your conversations, but it provided the easiest way of writing simple code. 
I'm looking into ways to get rid of the serialization - for example by having state setter and getter methods in your conversations. So that only these values will be serialized and cached.

**Comment by metalfm** [comment]
Try to understand my decision. I solved the problem of dependency injection, but need to write a builder and redefine BotMan class.

https://github.com/botman/botman/issues/889#issuecomment-426415242

**Comment by dextervip** [comment]
Any easy workaround? I just ran in the same issue of @metalfm I can't use symfony DI

**Comment by mabar** [comment]
@dextervip Pass your dependencies through a static class wrapper. It is ugly, but simpliest workaround.
Also, make sure that nothing from your dependencies is serialized in __serialize method of conversation.

**Comment by metalfm** [comment]
don't use static class wrapper! Please provide your code https://github.com/botman/botman/issues/889#issuecomment-437417938

Stop write bad cod :)
