### ISSUE TITLE
In DriverManager.php line 173: Class 'BotMan\Drivers\Line\LineVideoDriver' not found  

### ISSUE THREAD

**Issue by kevinjon27** [botman/botman#899]
- BotMan Version: ^2.0
- PHP Version: 7.2
- Messaging Service(s):  Class 'BotMan\Drivers\Line\LineVideoDriver' not found  
- Cache Driver: -

### Description:
I tried to install Custom LineDriver repo from [https://github.com/gundamew/botman-driver-line](https://github.com/gundamew/botman-driver-line). But I got error from DriverManager.php

```Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing gundamew/botman-driver-line (master master): Cloning master from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In DriverManager.php line 173:
                                                         
  Class 'BotMan\Drivers\Line\LineVideoDriver' not found  
                                                         

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1```
                                                         
 

### Steps To Reproduce:
So, I add my `composer.json` file:

```
....
    "require": {
        "gundamew/botman-driver-line": "dev-master"
    },
    "repositories": [
        {
            "type":"package",
            "package": {
                "name": "gundamew/botman-driver-line",
                "version":"master",
                "source": {
                    "url": "https://github.com/gundamew/botman-driver-line.git",
                    "type": "git",
                    "reference":"master"
                }
            }
        }
    ],
....
```

Is it just my project or something wrong with LineDriver? How I can fixed? I need this Driver.

**Comment by mpociot** [comment]
Hi! This issue seems to be related to the botman-driver-line repository. Please open an issue on this repository.
