### ISSUE TITLE
Problem to send messages with webDriver

### ISSUE THREAD

**Issue by facunob1974** [botman/botman#904]
- BotMan Version: 2.0
- PHP Version: 7.2.10
- Messaging Service(s): webDriver
- Cache Driver: Studio

### **Description:**
Hi, i'm create a chatbot whit Facebook driver and Web Driver (web-widget). I'm having a conversation without problems but when i try to send form this method:

$botman->say('Message', 'my-recipient-user-id', WebDriver::class);

whit Facebookdriver work but whit WebDriver not;

### **Steps To Reproduce:**

use BotMan\Drivers\Web\WebDriver;
use BotMan\Drivers\Facebook;

class BotManController extends Controller{
 
public function mandaMensaje(){

        $botman = resolve('botman');
       
       $botman->say('example', 'id_origen ',WebDriver::class);
       
}
}

if I use Facebook Driver work perfectly.

Do I have to take into account any session or cookie?

**Comment by christophrumpel** [comment]
Hey, `originating` messages do not work with the WebDriver. The WebDriver does not know where to send such a request and there is no user you can send a message to like with a messenger.

In theory, you could create some implementation that triggers a message on your website or where you use the web-driver, but this is not something you can do with BotMan. You would need to implement that yourself.

**Comment by LiamRoelsWA** [comment]
Has anything changed in originating messages to the web driver or is it still not possible?
I was looking into using the bot as a middle man in sending messages from the web driver to slack and vice versa, for taking over a conversation.
