### ISSUE TITLE
Whatsapp Driver

### ISSUE THREAD

**Issue by dextervip** [botman/botman#915]
Hey,

It would be nice to have an whatsapp driver. While whatsapp api is limited, I would suggest to use waboxapp. Any better ideas?

**Comment by dextervip** [comment]
done via https://github.com/dextervip/botman-driver-waboxapp

**Comment by sherpaxit** [comment]
Hi @dextervip,  Do you have a driver to WhatsApp API Direct?

**Comment by dextervip** [comment]
Hello, I don't have since there's no public API.

**Comment by sherpaxit** [comment]
@dextervip  Yes. Here in https://360dialog-waba.api-docs.io/v1/guide/migration
360dialog offers an api to use the official api doc https://developers.facebook.com/docs/whatsapp/api/messages
This you made for waboxapp its not possible to make for 360dialog that use the whastapp api direct and its an official partner of facebook?

**Comment by dextervip** [comment]
@sherpaxit I could but I haven't got approval to use business API.

**Comment by sherpaxit** [comment]
@dextervip  Here you can use without approval..  Sandbox:  https://360dialog-waba.api-docs.io/v1/guide/sandbox#2-how-to-use-whatsapp-direct-api-sandbox

**Comment by mohapinkepane** [comment]
For anyone looking for Botman WhatsApp Cloud API driver in 2025 :  https://github.com/mohapinkepane/driver-whatsapp-cloud
