### ISSUE TITLE
Is it possible to get keyboard without text in a reply?

### ISSUE THREAD

**Issue by zheldibayev** [botman/botman#921]
I didn't want to get the text below how can I return button without the text?

$botman->hears('new', function ($bot) {
    $key = Keyboard::create()
        ->type(Keyboard::TYPE_INLINE)
        ->addRow(KeyboardButton::create('<<')->callbackData('prev'),
            KeyboardButton::create('👍')->callbackData('accept'),
            KeyboardButton::create('👎')->callbackData('decline'),
            KeyboardButton::create('>>')->callbackData('next_make'))
        ->toArray();
    $bot->reply('some text',$key);

});

**Comment by christophrumpel** [comment]
Can't try it myself, but I don't think this is possible.
