### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by max-kovpak** [botman/botman#922]
- BotMan Version: 2.4.1
- PHP Version: v7.0.27
- Messaging Service(s): telegram

### Description:
I see in the Requirements PHP >= 7.1.3 but in the composer.json php: >=7.0
can I use it with php v7.0.27 ?

**Comment by max-kovpak** [comment]
Without BotMan Studio

**Comment by christophrumpel** [comment]
Without BotMan Studio, `php v7.0.27` should be fine. Just let us know if not.

**Comment by max-kovpak** [comment]
@christophrumpel yes, it is ok, I use version 2.4.1 with symfony. Thanks.
