### ISSUE TITLE
[Slack] Unable to post ephemeral messages

### ISSUE THREAD

**Issue by JudasRiff** [botman/botman#923]
- BotMan Version: 2.4.1
- PHP Version: 7.2.10
- Messaging Service(s): Slack

### Description:
Alright, so, I did a lot of research on how to post ephemeral messages with BotMan on Slack. All sources I see say that BotMan posts ephemeral messages by default, but that's not particularely the case with me. Everything I have tried so far, hasn't given me the result that I wanted, meaning that everyone in the channel can see the bot's responses. I also tried to find the method 'chat.postEphemeral' within the whole repository, but I couldn't find it anywhere. Could anybody help me with this?

NOTE: I installed BotMan and slack-client through Composer.

### Steps To Reproduce:
```php
$botman->hears('your command', function($bot) {
    $bot->reply('respond in channel', [
        'response_type' => 'ephemeral'
    ]);
});
```

This is a code (where I edited the response_type to ephemeral) I found Marcel posting on a similar topic, except that was to post 'in_channel' messages.

**Comment by JudasRiff** [comment]
I'm closing this as I have found a different solution that works for me.

**Comment by coudenysj** [comment]
@JudasRiff Could you share the solution here?

**Comment by JudasRiff** [comment]
@coudenysj Sure, although the solution I managed to come up with has nothing to do with this package. Do note that I'm still relatively new to web developing.

Basically, I first installed only a bot user, which wasn't the right solution. Later on I realised I had to install it as an **app** and I started adding slash commands. Although, it somehow didn't really do the trick to do the same things again, because I used to run my bot locally. My boss managed to set up a subdomain on my company's DirectAdmin server. I put all of it on the server, but it still didn't work, despite having put the link to the file in the request URL. So, I asked one of my colleagues and he suggested me to use basic PHP, just like how I was taught at school, without all the BotMan stuff. Apparently that did the trick for me, so this whole package became unnecessary for my own needs.

My colleague told me to do: 
```php
<?php
var_dump($_GET, $_POST);
```

This would return a JSON response like this:
```
array(0) {
}
array(11) {
 ["token"]=>
 string(24) "[APP_TOKEN]"
 ["team_id"]=>
 string(9) "[TEAM_ID]"
 ["team_domain"]=>
 string(12) "[TEAM_DOMAIN]"
 ["channel_id"]=>
 string(9) "[SOME_CHANNEL_ID]"
 ["channel_name"]=>
 string(13) "[SOME_CHANNEL_NAME]"
 ["user_id"]=>
 string(9) "[MY_USER_ID]"
 ["user_name"]=>
 string(3) "[MY_USER_NAME]"
 ["command"]=>
 string(4) "/cmd"
 ["text"]=>
 string(0) ""
 ["response_url"]=>
 string(80) "https://hooks.slack.com/commands/[ID]/[NUMBERS]/[MORE_NUMBERS_LETTERS]"
 ["trigger_id"]=>
 string(57) "SOME_TRIGGER_ID"
}
```

This was an ephemeral response. Do note that the token isn't the bot user OAuth token, but the normal token from the app itself. So, I took note of the 'command' part within that JSON response. And then, what I did, was try to recreate one of the commands I made with the BotMan library into something that's more basic PHP:

```php
<?php

if ($_POST == '/cmd') {
echo 'Here are the commands';
};
```

This gave me just the result I wanted. And I can make as many commands like that in this same way in the same file, and it would still give me the correct answer. It's really similar to what you write with the BotMan library.

So, what I think, is that the BotMan library is more meant for the bot user itself, which possibly can't post ephemeral responses, while the way I did it more let the app itself do the work, which _does_ post ephemeral responses.

I hope this was helpful.

**Comment by roberttolton** [comment]
It's a real shame that this doesn't seem to work properly..
According to the issues and replies I've read, the following should post an ephemeral message, but it doesn't:

```
$botman->hears('your command', function($bot) {
    $bot->reply('respond in channel', [
        'response_type' => 'ephemeral'
    ]);
});
```

Any chance we can get a reply from @mpociot ..?
