### ISSUE TITLE
What is the scope of ->fallback and ->callback_id in the Question object

### ISSUE THREAD

**Issue by aledelgo** [botman/botman#924]
- BotMan Version: 2.x
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:

in the example conversation i see

`$question = Question::create("Huh - you woke me up. What do you need?")
            ->fallback('Unable to ask question')
            ->callbackId('ask_reason')`

What those methods do... when and how the fallback and the callback_id string are used ?

**Comment by christophrumpel** [comment]
These are things you can use for the Slack Driver. But actually, I never used them. So if you don't use the Slack driver, you can just leave them out.

**Comment by aledelgo** [comment]
ok, that's why...
As i'm not using the slack driver i was unable to find a call to those field/methods in the sources, so i was wondering about their utility... now it is clear!
thanks for your time
