### ISSUE TITLE
My edited button goes away. how to make it static

### ISSUE THREAD

**Issue by zheldibayev** [botman/botman#927]
$this->ask('Question', function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {

                $inlineKeyboard = ['inline_keyboard' => [
                    [
                        ['text' => 'New text', 'callback_data' => 'New text'],
                        ['text' => 'New text', 'callback_data' => 'New text22']
                    ]
                 ]];
                switch ($answer->getValue()) {

                case 'next':
                    $parameters = [
                        'chat_id' => $answer->getMessage()->getPayload()['chat']['id'],
                        'message_id' => $answer->getMessage()->getPayload()['message_id'],
                        'reply_markup' => json_encode($inlineKeyboard),
                    ];
                    $this->bot->sendRequest('editMessageReplyMarkup', $parameters);
                }
            }
     }, $this->keyboard());

**Comment by christophrumpel** [comment]
What button do you mean? Do you want to create a Telegram Inline Keyboard that is always visible?

**Comment by christophrumpel** [comment]
Ok great, then I will close this issue. I haven't used it yet, but there is a `oneTimeKeyboard` method (or similar) on the Keyboard Object, you should be able to set it to false and then the keyboard be always visible.

**Comment by kubk** [comment]
@christophrumpel Thanks for the response, but I think this issue is related to https://github.com/botman/driver-telegram/issues/44

PR is available: https://github.com/botman/driver-telegram/pull/48

**Comment by koteezy** [comment]
> I found the solution. But I would like to know your opinion too. How to create a Telegram Inline Keyboard that is always visible even the button is clicked.

Can you please provide example?
