### ISSUE TITLE
react

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [botman/botman#928]
Hi,

any chance  to update to react/socket:^1 and evenement/evenement:^3 to be integrable in modern stacks?

Best

---

  Problem 1
    - Conclusion: don't install botman/botman 2.4.1
    - Conclusion: remove evenement/evenement v3.0.1
    - Conclusion: don't install evenement/evenement v3.0.1
    - react/socket v0.5.0 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.5.1 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.6.0 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.7.0 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.7.1 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.7.2 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.8.0 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.4.3 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.4.4 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.4.5 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.4.6 requires evenement/evenement ~2.0|~1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - react/socket v0.4.0 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/socket v0.4.1 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/socket v0.4.2 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v1.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v1.1.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.1.0, v3.0.1].
    - Conclusion: don't install react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - Conclusion: don't install botman/botman 2.4.1|remove react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - Conclusion: don't install botman/botman 2.4.1|don't install react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - Installation request for evenement/evenement (locked at v3.0.1) -> satisfiable by evenement/evenement[v3.0.1].
    - Conclusion: don't install botman/botman 2.4.1|remove react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - Conclusion: don't install botman/botman 2.4.1|don't install react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - Installation request for botman/botman ^2.4 -> satisfiable by botman/botman[2.4.0, 2.4.1].
    - Conclusion: remove react/socket v1.1.0|install react/socket v0.4.0|install react/socket v0.4.1|install react/socket v0.4.2|install react/socket v0.4.3|install react/socket v0.4.4|install react/socket v0.4.5|install react/socket v0.4.6|install react/socket v0.5.0|install react/socket v0.5.1|install react/socket v0.6.0|install react/socket v0.7.0|install react/socket v0.7.1|install react/socket v0.7.2|install react/socket v0.8.0
    - botman/botman 2.4.0 requires react/socket ~0.4 -> satisfiable by react/socket[v0.4.0, v0.4.1, v0.4.2, v0.4.3, v0.4.4, v0.4.5, v0.4.6, v0.5.0, v0.5.1, v0.6.0, v0.7.0, v0.7.1, v0.7.2, v0.8.0, v0.8.1, v0.8.10, v0.8.11, v0.8.12, v0.8.2, v0.8.3, v0.8.4, v0.8.5, v0.8.6, v0.8.7, v0.8.8, v0.8.9].
    - Can only install one of: react/socket[v0.8.1, v1.1.0].
    - Can only install one of: react/socket[v0.8.10, v1.1.0].
    - Can only install one of: react/socket[v0.8.11, v1.1.0].
    - Can only install one of: react/socket[v0.8.12, v1.1.0].
    - Can only install one of: react/socket[v0.8.2, v1.1.0].
    - Can only install one of: react/socket[v0.8.3, v1.1.0].
    - Can only install one of: react/socket[v0.8.4, v1.1.0].
    - Can only install one of: react/socket[v0.8.5, v1.1.0].
    - Can only install one of: react/socket[v0.8.6, v1.1.0].
    - Can only install one of: react/socket[v0.8.7, v1.1.0].
    - Can only install one of: react/socket[v0.8.8, v1.1.0].
    - Can only install one of: react/socket[v0.8.9, v1.1.0].
    - Installation request for react/socket (locked at v1.1.0) -> satisfiable by react/socket[v1.1.0].

**Comment by isbkch** [comment]
I came to ask the same thing. Especially that it creates confusion when other packages need recent react/socket
