### ISSUE TITLE
last_ad_referral and is_payment_enabled fields are now deprecated

### ISSUE THREAD

**Issue by shahonseven** [botman/botman#930]
- BotMan Version: 2.4.0
- PHP Version: 7.1
- Messaging Service(s): Facebook
- Cache Driver: 

### Description:
Error: [BotMan\Drivers\Facebook\Exceptions\FacebookException] Error sending payload: (#100) The last_ad_referral and is_payment_enabled fields are now deprecated. Please refer to our Developer Document for more info.

### Steps To Reproduce:
```
 $this->botman->hears('test', function (BotMan $bot) {
    $bot->reply('Test ok');
 });
```

**Comment by christophrumpel** [comment]
Hey.

You missed the `Steps To Reproduce:`. Please provide that.

**Comment by shahonseven** [comment]
I have added steps to reproduce.

**Comment by christophrumpel** [comment]
Are you using the latest Facebook Driver?

**Comment by shahonseven** [comment]
Ok, upgrading driver-facebook to 1.9.4 works now.

thanks.

**Comment by christophrumpel** [comment]
Perfect 👍
