### ISSUE TITLE
use botman to search inside a database

### ISSUE THREAD

**Issue by ghost** [botman/botman#931]
I want to use BotMan to create a chatbot that will search inside a databse starting from the user input. 
Botman will hear for a phrase that will contain also the parameter to search like this: "search for name" or "search product by id" and similar.  I'm reading about web driver but I'm not sure on how to setup it for this task. What is the correct configuration to achieve this and I need to write a middleware to manage this task?

**Comment by zheldibayev** [comment]
you can use Dialogflow for this purpose

**Comment by ziobru** [comment]
I want to use an offline solution, Dialogflow is great for natural language but will not be useful for the scope of my app.

**Comment by hscstudio** [comment]
You can create a tabel (hear, reply)

```
$botman->hears('{hear}', function ($bot, $hear) {
    $results = DB::table('simple_conversation')
        ->selectRaw("*, MATCH (hear) AGAINST (? IN NATURAL LANGUAGE MODE) AS score", [$hear])
        ->whereRaw("MATCH (hear) AGAINST (? IN NATURAL LANGUAGE MODE)" , [$hear])
        ->orderByRaw('CHAR_LENGTH(hear) DESC')
        ->get();
    if(count($results)>0){
        $bot->reply($results[0]->reply);
    }
    else{
        $bot->reply('I dont understand <b>'.$hear.'</b>');
        // send report
    }
});
```
