### ISSUE TITLE
How to respond to the Get Started Button Messenger

### ISSUE THREAD

**Issue by manaka02** [botman/botman#934]
- BotMan Version: 2.3
- PHP Version: 7.2
- Messaging Service(s): Messenger
- Cache Driver: FilesystemCache

### Description:
I created a chatbot for my facebook Page and It works great. Just, if it was a new user, the bot gives no response (no log) when he uses the "Get started" button. he responds well if the user send another message after that. 

### Steps To Reproduce:
Here is a basic code when I catch the response : 
```
            $cacheDriver = new FilesystemCache('cache');
            DriverManager::loadDriver(\BotMan\Drivers\Facebook\FacebookDriver::class);
            $botman = BotManFactory::create($config, new DoctrineCache($cacheDriver));
            $listString = "Get Started|Hello|Hi|News|Start|";
            $botman->hears("($listString).*", function ($bot) {
                $beginning = new Action\GetStarted();
                $bot->startConversation($beginning);
            });
```

Did I do something wrong or there is another way to catch de "Get Started" action?

**Comment by christophrumpel** [comment]
Hey, did you read this section of the documentation? https://botman.io/2.0/driver-facebook-messenger#get-started-command

Seems like you are not using BotMan Studio and therefore cannot use the artisan command to set the GET_STARTED button. You would then need to set it manually with CURL request. Here is also some information on the Facebook Documentation https://developers.facebook.com/docs/messenger-platform/reference/messenger-profile-api/get-started-button

**Comment by manaka02** [comment]
I took a look on it and I understand nothig 😅😅. Is it possible to change my project and use Botman studio for now?

**Comment by christophrumpel** [comment]
hehe I know it is not that easy at the beginning. Most times it is easier to install BotMan Studio and then try to integrate your application there. But, theoretically, it is also possible to integrate the Studio setup into your application. But there is no good documentation on how to do that. I can't here as well.

If you want to use BotMan Studio and get more info about using it (like with the get started button), you can join the BotMan Slack channel to talk to other botman developers or there is Marcel's and mine courses available:

* [Build A Chatbot video course by Marcel Pociot](https://course.buildachatbot.io/)
* [Build Chatbots with PHP by me (book and video course)](https://store.christoph-rumpel.com/)

**Comment by manaka02** [comment]
@christophrumpel  okay, i'll try. Thank you
