### ISSUE TITLE
typesAndWaits invisible

### ISSUE THREAD

**Issue by emresaracoglu** [botman/botman#939]
- BotMan Version: 2.0
- PHP Version: 7.1.10  
- Cache Driver: SymfonyCache

### Description:
`typesAndWaits` does not appear but working (the answer comes late).

**Comment by LiamRoelsWA** [comment]
In the web driver this is not implemented, so you can't see it unless you used the js in the references issue!

**Comment by rohankhudedev** [comment]
> In the web driver this is not implemented, so you can't see it unless you used the js in the references issue!

https://github.com/botman/web-widget/issues/20

**Comment by LiamRoelsWA** [comment]
> > In the web driver this is not implemented, so you can't see it unless you used the js in the references issue!
> 
> [botman/web-widget#20](https://github.com/botman/web-widget/issues/20)

That was exactly what I was referring to
