### ISSUE TITLE
Write as visitors

### ISSUE THREAD

**Issue by emresaracoglu** [botman/botman#940]
Hi,

I want to print some terms instead of the visitor. How do I print as visitors have written?
Thank you.

**Comment by christophrumpel** [comment]
Hey, what do you mean by `as a visitor`?

**Comment by emresaracoglu** [comment]
I want to write instead of the visitor. Is there a way to do this?
![Uploading Untitled.png…]()

**Comment by christophrumpel** [comment]
With most drivers like Facebook, Telegram and co. it does not work. With the Widget like from the screenshot it `could` be possible, but I guess not out of the box.

Wouldn't it be quite confusing for the user when you do that?

**Comment by emresaracoglu** [comment]
My goal is to print old correspondence. 

For example; `onclick="botmanChatWidget.say('christophrumpel was here!');return false;"` 

So how do I do this with PHP?

**Comment by emresaracoglu** [comment]
Is not it possible? @christophrumpel

**Comment by christophrumpel** [comment]
I still don't get why you would need this. From your screenshot, this would mean all 3 messages would come from BotMan(PHP). But also if it would make sense, I'm pretty sure it is not possible with BotMan.

**Comment by emresaracoglu** [comment]
I'm recording the conversations between the visitor and the Bot. (it makes sense for the project that I want to do 😄) 
That's why I need it.

**Comment by christophrumpel** [comment]
ah ok I think I get it now 😂

I haven't worked much with the web widget, but I think you can through JS decide if you write as the user or the bot. For sure you cannot send those message from PHP. But I can't help here more, sorry.

**Comment by emresaracoglu** [comment]
I don't think this is possible with PHP. Thank you for your time.

**Comment by christophrumpel** [comment]
np, I hope I could help just a little at least.
