### ISSUE TITLE
Webhooks setup error

### ISSUE THREAD

**Issue by CarmeloCampos** [botman/botman#942]
- BotMan Version: 2.0
- PHP Version: 7.0.32
- Messaging Service(s): Facebook
- Cache Driver: 

### Description:

I try to configure my Webhooks on Facebook and it throws me the following error:

`Unable to validate the URL Response does not match challenge, expected value = "1308214606", received = "\ u003Cbr \ /> \ n \ u003Cb> Parse erro ..."
`

In my index.php of the bot does not throw any problem of syntax or something that has to see, also I have added the tokens of verification in the .env:

```
FACEBOOK_TOKEN=EAA......
FACEBOOK_VERIFICATION=1201.....
FACEBOOK_APP_SECRET=b5b5.....

VERIFY_TOKEN=1201.....
APP_SECRET=b5b5.....
APP_TOKEN=EAA......
```

**Comment by CarmeloCampos** [comment]
I must say that I am using
ubuntu server 14.04 64 bits, also followed his guide ["How to debug Facebook webhook errors"](https://christoph-rumpel.com/2017/09/botman-quick-tip-how-to-debug-facebook-webhook-errors) and nothing

**Comment by christophrumpel** [comment]
The `\ u003Cbr \ /> \ n \ u003Cb> Parse erro ...` means your webhook is throwing an error. You need to setup up error logging to find out what is wrong here and to see the error, then you will also see what is wrong in your setup.

**Comment by CarmeloCampos** [comment]
> The `\ u003Cbr \ /> \ n \ u003Cb> Parse erro ...` means your webhook is throwing an error. You need to setup up error logging to find out what is wrong here and to see the error, then you will also see what is wrong in your setup.

How to enable this process

**Comment by christophrumpel** [comment]
This depends on your setup, it is different with every setup. I use Laravel and it automatically logs are errors. If you use another framework, something similar should be provided.

**Comment by CarmeloCampos** [comment]
> Esto depende de su configuración, es diferente con cada configuración. Yo uso Laravel y automáticamente los registros son errores. Si utiliza otro marco, debe proporcionarse algo similar.

Well, use the botman studio? : v

**Comment by christophrumpel** [comment]
Yeah, for example, BotMan Studio. But in general, if you want to build a solid PHP application, you need a local environment and setup (framework) that helps you deal with such errors. I can't help you with your setup but there are lots of articles out there how to start with Laravel for example. Also I can recommend this video series on starting with Laravel which will help you a lot with BotMan Studio. https://laracasts.com/series/laravel-from-scratch-2018
