### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by AdamLew** [botman/botman#945]
### Description:

For PHP 7.3 :

composer require botman/botman

returns :

 [ErrorException]                                                                         
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?  
  

### Steps To Reproduce:

**Comment by jspaans91** [comment]
Did you try to do a composer self-update?

`composer self-update`

**Comment by Usuario001** [comment]
@jspaans91 with composer self-update works for me, but i'm in other chanel maybe. Because i'm installing a mac os enviroment with php(7.3) with brew

**Comment by Surya-Kanta** [comment]
[InvalidArgumentException]             
  Command "self-update" is not defined.

**Comment by Surya-Kanta** [comment]
> Did you try to do a composer self-update?
> 
> `composer self-update`

                                         
  [InvalidArgumentException]             
  Command "self-update" is not defined.

**Comment by vikastyagi87** [comment]
I was facing same problem, then i did -
1) First I run composer self-update command, but didn't not work for me, after running this command i was getting error.
2) Then i uninstall composer
3) Then reinstall composer again 
and my problem was fixed.

I seems issue with old composer version.

**Comment by mariordev** [comment]
> Did you try to do a composer self-update?
> 
> `composer self-update`

This did it for me.

**Comment by tushi4u** [comment]
Check your current PHP version if it's higher than 7.2 then we need execute follow below simple steps
`
1) sudo a2dismod php7.3
2) sudo service apache2 restart
3) sudo update-alternatives --set php /usr/bin/php7.2
4) php -v

**Comment by Glastis** [comment]
> Check your current PHP version if it's higher than 7.2 then execute follow below simple steps
> 
> ```
> 1) sudo a2dismod php7.3
> 2) sudo service apache2 restart
> 3) sudo update-alternatives --set php /usr/bin/php7.2
> 4) php -v
> 5) composer install
> ```

You better manually update composer rather than downgrading php.
Uninstall composer from package manager, download the last one and move it to bin path:
```
sudo apt-get remove composer && php composer-setup.php --filename=composer && sudo mv composer /usr/bin/composer
```

**Comment by blessingk** [comment]
Thanks

1) sudo a2dismod php7.3
2) sudo service apache2 restart
3) sudo update-alternatives --set php /usr/bin/php7.2
4) php -v
5) composer install
This worked for me

**Comment by Oliver-Jesingh** [comment]
> Check your current PHP version if it's higher than 7.2 then execute follow below simple steps
> 
> ```
> 1) sudo a2dismod php7.3
> 2) sudo service apache2 restart
> 3) sudo update-alternatives --set php /usr/bin/php7.2
> 4) php -v
> 5) composer install
> ```

Worked Perfectly

**Comment by mnileshgupta** [comment]
> * sudo a2dismod php7.3
> * sudo service apache2 restart
> * sudo update-alternatives --set php /usr/bin/php7.2
> * php -v
> * composer install
>   This worked for me

Thanks. Working fine.

**Comment by vitorgga** [comment]
Can try this too:
```
sudo apt-get remove composer
sudo apt autoremove	
sudo curl -s https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
```

**Comment by keringdered** [comment]
> Check your current PHP version if it's higher than 7.2 then execute follow below simple steps
> 
> ```
> 1) sudo a2dismod php7.3
> 2) sudo service apache2 restart
> 3) sudo update-alternatives --set php /usr/bin/php7.2
> 4) php -v
> 5) composer install
> ```

Thanks worked!!

**Comment by Entretoize** [comment]
> Can try this too:
> 
> ```
> sudo apt-get remove composer
> sudo apt autoremove	
> sudo curl -s https://getcomposer.org/installer | php
> sudo mv composer.phar /usr/local/bin/composer
> ```

For me it needed mv composer.phar /usr/local/bin/composer
But thank you I didn't have to downgrade php !

**Comment by gperuchon** [comment]
I used this version of composer and then my commands worked
`wget https://getcomposer.org/download/1.8.0/composer.phar`

**Comment by aashishsonawane** [comment]
> Can try this too:
> 
> ```
> sudo apt-get remove composer
> sudo apt autoremove	
> sudo curl -s https://getcomposer.org/installer | php
> sudo mv composer.phar /usr/local/bin/composer
> ```

Thanks this solution worked for me, instead of downgrading PHP version reinstalling composer itsefl did the trick for me....

**Comment by yoshimitsu7** [comment]
> Can try this too:
> 
> ```
> sudo apt-get remove composer
> sudo apt autoremove	
> sudo curl -s https://getcomposer.org/installer | php
> sudo mv composer.phar /usr/local/bin/composer
> ```

Hello , it worked for me , just had changed the mv directory , i moved it to "/usr/bin/composer" instead of  "/usr/local/bin/composer" , so thanks a lot bro

**Comment by maximehuran** [comment]
If you use the Symfony binary, you can retrieve the last version of composer and copy it to the one used by the Symfony binary : 
`mv composer.phar /usr/local/bin/composer.phar`

**Comment by agespinosa** [comment]
> Can try this too:
> 
> ```
> sudo apt-get remove composer
> sudo apt autoremove	
> sudo curl -s https://getcomposer.org/installer | php
> sudo mv composer.phar /usr/local/bin/composer
> ```

Esa es la que funciona
