### ISSUE TITLE
Botman - dialogflow

### ISSUE THREAD

**Issue by struyfv** [botman/botman#947]
Hi,

I have a question about the response dialogflow returns. Is it possible to get the facebook messenger response instead of the default response when using Botman? I want to use the quick replies in dialogflow.

Regards,
Veerle

**Comment by claretnnamocha** [comment]
To return the reply for Dialogflow, checkout the example  
```php
$botman->hears('smalltalk(.*)', function (BotMan $bot) {
  $extras = $bot->getMessage()->getExtras();
  $bot->reply($extras['apiReply']);
})->middleware($dialogflow);

```
