### ISSUE TITLE
how to fetch data from URL and give as reply in botman chatbot

### ISSUE THREAD

**Issue by Abhishekjaiz** [botman/botman#951]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I want to get response from user and send it to an url and fetch data from that url and send it in response in botman.

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey, this is actually not about BotMan. You can do just with PHP and your framework. Here is an example from BotMan Studio, where Marcel grabs a joke from an external API. When you have a string, you can then reply it easily with BotMan.

**Comment by Abhishekjaiz** [comment]
@christophrumpel can you please provide me the link.
