### ISSUE TITLE
Originating Conversation Throws InvalidArgumentException

### ISSUE THREAD

**Issue by ryanvade** [botman/botman#952]
- BotMan Version: 2.4.1
- PHP Version: 7.2.13
- Messaging Service(s): Web, BotFramework
- Cache Driver: File (default)

### Description:
When [Originating Conversations](https://botman.io/2.0/conversations#originating-conversations) Botman throws an InvalidArgument Exception during serialization. This occurs with the Example Conversation and on multiple Drivers (Tested with Web and BotFramework). 

### Steps To Reproduce:

1. Create a new Botman Project
2. Open an Artisan Tinker Shell
3. Try initiating a new Conversation
Code:
```php
use Botman\Drivers\Web\WebDriver;
use App\Conversations\ExampleConversation;
$botman = resolve("botman");
$botman->startConversation(new ExampleConversation, "123456", WebDriver::class);
```
Response:
```
InvalidArgumentException with message 'Unknown setter 'date''
```

The Conversation:
```php
namespace App\Conversations;

use Illuminate\Foundation\Inspiring;
use BotMan\BotMan\Messages\Incoming\Answer;
use BotMan\BotMan\Messages\Outgoing\Question;
use BotMan\BotMan\Messages\Outgoing\Actions\Button;
use BotMan\BotMan\Messages\Conversations\Conversation;

class ExampleConversation extends Conversation
{
    /**
     * First question
     */
    public function askReason()
    {
        $question = Question::create("Huh - you woke me up. What do you need?")
            ->fallback('Unable to ask question')
            ->callbackId('ask_reason')
            ->addButtons([
                Button::create('Tell a joke')->value('joke'),
                Button::create('Give me a fancy quote')->value('quote'),
            ]);

        return $this->ask($question, function (Answer $answer) {
            if ($answer->isInteractiveMessageReply()) {
                if ($answer->getValue() === 'joke') {
                    $joke = json_decode(file_get_contents('http://api.icndb.com/jokes/random'));
                    $this->say($joke->value->joke);
                } else {
                    $this->say(Inspiring::quote());
                }
            }
        });
    }

    /**
     * Start the conversation
     */
    public function run()
    {
        $this->askReason();
    }
}
```

I realize the WebDriver doesn't actually support originating conversations but it shouldn't throw this exception.

**Comment by Daronspence** [comment]
@ryanvade did you find a solution to this? Running into the same issue using the slack driver. I was trying to setup a schedule to start a conversation on a cron but it fails on the carbon serialization.

**Comment by christophrumpel** [comment]
Hey, I wasn't able to check the code in detail, but I've seen the error before. Found my answer to the problem in the Slack channel.

`This is a problem with the opis closure package. Try to reset it back to 2 instead of v3`

I cannot tell if this is your problem as well, but I would try that. Hope it helps!

**Comment by ryanvade** [comment]
@Daronspence 	no I didn't find a solution.  Instead I switched to another framework. 

@christophrumpel 	Thanks for the suggestion!

**Comment by Daronspence** [comment]
@ryanvade which framework did you switch to?

**Comment by ryanvade** [comment]
@Daronspence 	MS BotFramework as the bot is for MS Teams. I would have liked to stat with Botman though...

**Comment by stefro** [comment]
I'm experiencing the same thing. Did anyone ever had luck figuring this out?

**Comment by haikajymada** [comment]
I am experiencing the same situation when using the Carbon library. There is a similar issue but I'm wondering if it is already corrected in a new version of Botman ???

#871
