### ISSUE TITLE
How to check if user send emoji (stickers)

### ISSUE THREAD

**Issue by manaka02** [botman/botman#953]
- BotMan Version: 2.0.0
- PHP Version: 7.2
- Messaging Service(s): Facebook Messenger
- Cache Driver: Laravel cache

### Description: I search if there is a way to check if user send an emoji with botman response

Thanks. 

### Steps To Reproduce:

**Comment by manaka02** [comment]
I found a way to achieve this using emoji detector
`composer require p3k/emoji-detector`

**Comment by Neolot** [comment]
```php
if ( !empty($bot->getMessage()->getPayload()->get('sticker')) ) {
    $bot->reply('Sticker!');
    return false;
}
```
