### ISSUE TITLE
Dialogflow API V1 will be deprecated on October 23rd, 2019. 

### ISSUE THREAD

**Issue by LeonanCarvalho** [botman/botman#959]
### Description:
The current endpoint used by the Dialogflow middleware is `https://api.api.ai/v1/query?v=20150910`.

Many changes have been made since Api.ai becomes Dialogflow, and the futter support to API v1 is uncertain. 

Migration guide to API V2 can be found here https://dialogflow.com/docs/reference/v1-v2-migration-guide

**Comment by isbkch** [comment]
Were you able to make Botman work with DialogFlow?

**Comment by eGlobeBizCom** [comment]
test post

**Comment by genkovich** [comment]
Hi, put it in a package
https://github.com/genkovich/DialogFlowBotManMiddleware

maybe useful
