### ISSUE TITLE
Bot not responding from Microsoft Teams 

### ISSUE THREAD

**Issue by sscots** [botman/botman#960]
- BotMan Version: 2.4.1
- PHP Version: 7.2.12
- Messaging Service(s): Bot Framework (Microsoft Teams)
- Cache Driver:

### Description:
When I @mention my bot through a Microsoft Team's team, it fails to respond.

### Steps To Reproduce:
I determined where the issue is happening. 
In the `matchesRequest()` function in the `BotFrameworkDriver.php` file, it's checking for an attachment object in the request, and if it finds one, then it return `false`.
Currently when I view the request being sent from Microsoft Teams, I'm seeing that it contains an `attachment` object. If I hardcode `$noAttachments` in the `matchRequeset()` to `true`, it works.
The `attachment` object from the request just looks like an html version of the command which is as follows, fyi:
```
{
   ...
   "attachments":[{
      "contentType":"text/html",
      "content":"<div><div><span itemscope='' itemtype='http://schema.skype.com/Mention' itemid='0'>MyBot</span> My Custom Command</div>\n</div>"
   }],
   ...
}
```

My workaround now is to just remove the `attachments` object from the request, however it took me awhile to figure this out.

**Comment by guibmolina** [comment]
@sscots How did you solve this problem? I'm with the same...
