### ISSUE TITLE
Can't validate /botman url via facebook

### ISSUE THREAD

**Issue by acosonic** [botman/botman#961]
- BotMan Version: 2.0
- PHP Version :7.1
- Messaging Service(s): facebook
- Cache Driver: filesystem

### Description:
Getting this response from facebook
The URL couldn't be validated. Response does not match challenge, expected value="432937512", received=""

### Steps To Reproduce:
try this tutorial
https://christoph-rumpel.com/2017/09/build-a-facebook-chatbot-with-laravel-and-botman-studio

**Comment by Aramis-Delg** [comment]
Hi, I tried the "build a facebook chatbot with laravel and botman studio" and the mpociot's Botman- Facebook driver tutorial with ngrok , not once, I did so many attempts but I still "Can't validate de URL, try again".
Then I tried using another tunnels like burrow.io, pagekit anf serveo, but still getting the same.

Exactly, how do you resolve this problems, please.
![Screenshot_2019-04-25 JACobChatbot - Messenger - Facebook for Developers](https://user-images.githubusercontent.com/39425386/56749576-a039eb00-6747-11e9-958e-a54146d07a24.png)

**Comment by christophrumpel** [comment]
Hey, could it be that you are just missing `https://`. Did you tried that?
