### ISSUE TITLE
Facebook Messenger repeatedly sends the same message and I cannot send a reply. 

### ISSUE THREAD

**Issue by nagra** [botman/botman#962]
- BotMan Version: 2.3.3
- PHP Version: 7.1.19
- Messaging Service(s): Facebook Messenger
- Cache Driver: 

### Description:
I am aiming to make a simple Facebook Messenger bot purely based on text responses and replies. The issue is Facebook Messenger keeps sending the same messages repeatedly, and I cannot seem to get a response sent back to Messenger.

I know I am successfully receiving the messages correctly, because the content is being saved to the DB. 

The logs show the following message:
`Error sending payload: (#100) Parameter error: You cannot send messages to this id {"exception":"[object] (BotMan\\Drivers\\Facebook\\Exceptions\\FacebookException(code: 0): Error sending payload: (#100) Parameter error: You cannot send messages to this id at /app/vendor/botman/driver-facebook/src/FacebookDriver.php:505)`

- 👎After some googling, I tried to remedy the issue by returning a response `200 OK` as early as possible.
- 👎I have updated the Facebook Token numerous times with various options with no luck.

My BotManController.php file is setup as follows: 
```<?php

namespace App\Http\Controllers;

use BotMan\BotMan\BotMan;
use Illuminate\Http\Request;
use App\Conversations\ExampleConversation;
use App\Http\Middleware\AuthenticateMiddleware;
use App\Http\Middleware\IncomingMiddleware;
use App\Http\Middleware\OutgoingMiddleware;
use App\Http\Middleware\UsernameMiddleware;

class BotManController extends Controller
{
    /**
     * Place your BotMan logic here.
     */
    public function handle()
    {
        $botman = app('botman');

        $middleware = new AuthenticateMiddleware();
        $botman->middleware->received($middleware);

        $middleware = new IncomingMiddleware();
        $botman->middleware->received($middleware);

        $middleware = new OutgoingMiddleware();
        $botman->middleware->sending($middleware);

        $middleware = new UsernameMiddleware();
        $botman->middleware->received($middleware);

        $botman->listen();

        return response()->json(['OK']);
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function tinker()
    {
        return view('tinker');
    }
}
```

### Steps To Reproduce:
- Create a brand new Facebook Messenger app at https://developers.facebook.com/apps
- Create a new BotMan project with some middleware saving messages to your DB.
- Try return a simple message via `$bot->reply()`.

**Comment by soikathood** [comment]
Hi, I think your user changed his facebook password. I faced same issue. Remove his user details from DB, it will be working again. But I don't know whats the impact of changing FB password here and how to solve it programatically. User can change their FB password anytime.

**Comment by soikatchakma** [comment]
Hi @nagra , I think your user changed his facebook password. I faced same issue. Remove his user details from DB, it will be working again. @christophrumpel But I don't know whats the impact of changing FB password here and how to solve it programatically. User can change their FB password anytime.
