### ISSUE TITLE
Botman not working on facebook messenger chatbot

### ISSUE THREAD

**Issue by akhmadcoder** [botman/botman#964]
- BotMan Version: Latest
- PHP Version: 7.2
- Messaging Service(s): botman facebook messenger chatbot
- Cache Driver: 

### Description:
Hi all supporters of botman. Thanks for creating such a great app. I really appreciate it.
I created facebook messenger chatbot and added to facebook. When I add, chatbot not responding. here the following link if you write "hi" it will answer, https://booking.homealliance.com/bot
That above link is for temporary to show client how it will be the process of talking. 

I carefully set up everything with botman with facebook, but failed. So if it is possible, can you give me working version of botman with vendor everything for facebook messenger so I can easily put my codes, and required acces tokens from both sides to given botman codes and make it work.  Also here more than 3 buttons possible, so is it possible to do in pure php ?

With best regards
Akhmad 

### Steps To Reproduce:

**Comment by christophrumpel** [comment]
Hey,

If you want a working version you should use "BotMan Studio". It is a Laravel project with BotMan already included as well as everything you need to set up on your application. (Including test listeners and conversations)

Still, you need to connect this application to Facebook and there are many things that can go wrong. This is why it is very difficult to help you with like not details your provided to the problem.

I can give you some resources that should help you, but with such questions, it is better you come to the BotMan Slack channel. There are many people that could help you. This repository is only for bugs in BotMan.

**Here are the resources:**

* [BotMan Studio](https://botman.io/2.0/botman-studio)
* [BotMan Debugging Guide](https://christoph-rumpel.com/2018/11/the-ultimate-botman-chatbot-debugging-guide)
* [My articles about BotMan and Chatbots](https://christoph-rumpel.com/category/chatbots)
