### ISSUE TITLE
Disable cache for conversation

### ISSUE THREAD

**Issue by lakinmohapatra** [botman/botman#965]
- BotMan Version: #.#.# 2
- PHP Version: 7.2
- Messaging Service(s):
- Cache Driver: Symphony

### Description:
My conversation cached in such a way that it is returning same response for all keywords.
Please help. 
i WANT TO DISABLE CACHE in my php webhook . Please help.

**Comment by Edd-G** [comment]
same problem

**Comment by hossinasaadi** [comment]
use this cache driver , if you disable cache , conversation not work probably!
all caches save in cache folder

```
Create an instance
use BotMan\BotMan\Cache\DoctrineCache;
use Doctrine\Common\Cache\FilesystemCache;

$doctrineCacheDriver = new FilesystemCache(__DIR__."/cache");
$botman = BotManFactory::create($config,new DoctrineCache($doctrineCacheDriver));
```

**Comment by Kollipso** [comment]
1. You can set a conversation_cache_time key on your BotMan configuration, like that:
`'botman' => [
    'conversation_cache_time' => 30
],`
Try to set big number to make it endless or near to zero to make debug it easier.

2. You can manage cache by using commands in your logic:
`stopsConversation()`
or
`removeStoredConversation()`

3. If you want to clear conversation cache then you should remove dir 'symfony-cache' in tmp folder (/tmp or look for your Botman cache config). If you are using Botman Studio then run command:
`php artisan cache:clear`
