### ISSUE TITLE
How to send Telegram messages from Kernel Command?

### ISSUE THREAD

**Issue by kidox** [botman/botman#972]
- BotMan Version: 2.3.3
- PHP Version: 7.2
- Messaging Service(s): Telegram
- Cache Driver:

### Description:
Messages inside Command appears to be sended but they don't.

### Steps To Reproduce:
I have this code defined in app/Console/Commands/SendDailyMessage.php. The method is called correctly because I checked it with log but messages are not being sent.

```
<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;


class SendDailyMessage extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'send:dailymessage';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send a daily message to subscribed users';

    /**
     * The bot handler
     *
     * @var string
     */
    protected $botman;

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        $this->botman = app('botman');
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {

        return $this->botman->say('Message', 'telegramUserCode', TelegramDriver::class);
    }
}
```

**Comment by michaellindahl** [comment]
You need to make sure that your `TelegramDriver` class is namespaced correctly. Try adding this import: `use BotMan\Drivers\Telegram\TelegramDriver;`. Currently it seems as though it's trying to use `App\Console\Commands\TelegramDriver`. Using something like [Laravel Telescope](https://laravel.com/docs/5.8/telescope) (or looking at the error logs) might help debug these kinds of issues.
Also make sure you are using the telegram user_id and not the username.

**Comment by kidox** [comment]
Brilliant @michaellindahl. Adding `use BotMan\Drivers\Telegram\TelegramDriver;` was enough to make it work. Thank you!
