### ISSUE TITLE
Hello. telegram start button doesn't respond, but my web tinker woks well. My ngrok says  - 200 OK. 

### ISSUE THREAD

**Issue by zheldibayev** [botman/botman#974]
https://api.telegram.org/bot{my_token}/setWebhook?url=https://b486b743.ngrok.io/botman
My webhook
{"ok":true,"result":true,"description":"Webhook was set"}
But start button doesn't work

**Comment by permadi123qwe** [comment]
the possibility that there was an error on your web route / local, you can check at the storage / log / laravel.log address,

can also do clear cache

php artisan ceache: clear

like this link

https://botman.io/2.0/conversations#debugging-conversations

**Comment by zheldibayev** [comment]
> the possibility that there was an error on your web route / local, you can check at the storage / log / laravel.log address,
> 
> can also do clear cache
> 
> php artisan ceache: clear
> 
> like this link
> 
> https://botman.io/2.0/conversations#debugging-conversations

My log file is clear. I tried to clear cache before. It didn't work

**Comment by permadi123qwe** [comment]
what are u use the botman studio ??

I use it and it's in my error log, if it's still fixed, do revoke the telegram token, and post it again with psotman or

php artisan botman: register: telegram

**Comment by zheldibayev** [comment]
> what are u use the botman studio ??
> 
> I use it and it's in my error log, if it's still fixed, do revoke the telegram token, and post it again with psotman or
> 
> php artisan botman: register: telegram

YEs I use Botman Studio

**Comment by permadi123qwe** [comment]
u try it .. . . revove with new token . . . and setwebhook again or 

its not working u try with Ngrok authtoken asdqweasdqweasdqweasd frist. . . . 

try to load it with auttoken u, because I use it all and 405 is not available

**Comment by zheldibayev** [comment]
> u try it .. . . revove with new token . . . and setwebhook again or
> 
> its not working u try with Ngrok authtoken asdqweasdqweasdqweasd frist. . . .
> 
> try to load it with auttoken u, because I use it all and 405 is not available

I set a new token. I doesn't work too

**Comment by zheldibayev** [comment]
It works fine on my mac, but I migrated all my project from my mac to the laptop (Windows 10). It doesn't work. I don't know why

**Comment by permadi123qwe** [comment]
i am use windows 7, work and fine . . . . and work, 
just try again
