### ISSUE TITLE
Sending message with file attachment with slack

### ISSUE THREAD

**Issue by cbanbury** [botman/botman#979]
- BotMan Version: 2.4.1
- PHP Version: 7.1.23
- Messaging Service(s): Slack
- Cache Driver: N/a

### Description:
I'm trying to reproduce the steps shown here https://botman.io/2.0/sending#attachments to attach a generic file. 

Here's a snippet from the code, just trying to attach a test PDF

```
        $botman->hears('keyword', function($bot) {
            // Create attachment
            $attachment = new File('http://africau.edu/images/default/sample.pdf', [
                'custom_payload' => true,
            ]);

            // Build message object
            $message = OutgoingMessage::create('test')
                        ->withAttachment($attachment);

            $bot->reply($message);
        });
```

### Steps To Reproduce:
1. Setup Botman with Realtime API for slack as shown here https://botman.io/2.0/driver-slack
2. Add snippet above and try keyword.

Results in showing message test but not the file. 

NB: Attachment with PNGs work fine, Supported features section doesn't provide information on whether generic file attachment is support for slack.

**Comment by janicesn0w** [comment]
I am also facing the same issue. There is no problem attaching with PNGs. 
But when i try to attach a PDF file, the message will sent but not the file.

**Comment by rafaellannes** [comment]
Same error here...
 when i try to attach a PDF file, the message will sent but not the file.
 any solution?

**Comment by raphaelmoraes** [comment]
Hello, did anyone got the solution to the problem?

Thanks!

**Comment by naingminkhant** [comment]
Try with this.
**'custom_payload' => false,**

**Comment by rafaellannes** [comment]
> Try with this.
> **'custom_payload' => false,**


it didn't work unfortunately.

has someone else who faced this problem managed to solve it?

**Comment by prashant-thakur26** [comment]
Did anyone has resolved this problem?? i am also facing the same issue

**Comment by samarth-mistry** [comment]
> > Try with this.
> > **'custom_payload' => false,**
> 
> it didn't work unfortunately.
> 
> has someone else who faced this problem managed to solve it?

Have u got the solution, mate?
i m facing the same problem

**Comment by ranidu-harshana** [comment]
anyone solve this?

**Comment by kirkdouglasprofeciait** [comment]
No solution to this?
