### ISSUE TITLE
Allow Message objects in Questions

### ISSUE THREAD

**Issue by sschlein** [botman/botman#98]
In my opinion, it makes sense to add messages with images directly in conversations. Unfortunately, my app is only a prototype and I'm currently using the FacebookDriver only but I've added the capability there:

https://gist.github.com/sschlein/d82c41511d9e71963bcc5c84f9d5a508

Would be great to see this for all drivers (I may have time to create a PR in the future, but wanted to share the FB driver and idea directly 😺 )

**Comment by dFayet** [comment]
As of today we have the possibility to use Message in question with the SlackDriver, is it the case with all the drivers?
