### ISSUE TITLE
404 error botman studio after upload on server

### ISSUE THREAD

**Issue by Cecios0** [botman/botman#981]
- BotMan Version: ~2.0
- PHP Version: ^7.1.3
- Messaging Service(s): Facebook
- Cache Driver: Default

### Description:
Hi,
I have a problem with composer studio.
I have performed these steps:
- composer global require "botman / installer"
- botman new <name>
- Installed drivers for facebook
- php artisan serves
In local works properly
When I load all the content on the server https://ecobot.infinityapp.it/webhooks/ I get 403 forbinned error.

The routes not work.
Can you help me? Please!
 If you need, I can provide my FTP credentials in private.

Thank you

### Steps To Reproduce:
Visit
https://ecobot.infinityapp.it/webhooks/

**Comment by nachoaguirre** [comment]
hi! i solved the same issue changing the root directory of my subdomain, adding "/public" at the end of the root path in my hosting settings. 
Ex: /public_html/ecobot.infinityapp.it/public 
don't know the path of your subdomain, but the important is the public folder at the end ;)
