### ISSUE TITLE
How to use messenger template inside a conversation 

### ISSUE THREAD

**Issue by ceaser1996** [botman/botman#982]
I am unable to use messenger template inside a conversation is there any way out of it please let me know if any method is there .

**Comment by kints** [comment]
Hi! I have the same issue, is there a way to do it? I'm doing this but isn´t working and trigger a loop

$button = ButtonTemplate::create("¿En que te puedo ayudar hoy?")
           ->addButton(ElementButton::create("Estrenar una JAC")
             ->type('postback')
             ->payload('estrenar')
           )
           ->addButton(ElementButton::create("Ya tengo un JAC")
             ->type('postback')
             ->payload('yatengo')
           );
      $this->ask($button, function (Answer $answer) {
        if ($answer->getText() === 'estrenar') {
          $this->say("Excelente!!!");
          $this->preguntarTipoAuto();
        } else {
          $this->say("Estamos trabajando en ello :D");
        }
      });

**Comment by sbassah** [comment]
I know it's but just in case you still need help, I 'll suggest you replace `if ($answer->getText() === 'estrenar')` with `if ($answer->getValue() === 'estrenar') `

**Comment by christophrumpel** [comment]
You can use FB templates inside conversations, just like outside of a conversation. Everywhere where you can place plain text or a question object, you can use fb templates as well.

Just do `$this->ask($yourTemplate,...`. If this is not working it is probably a different error.
