### ISSUE TITLE
Help Request | PHP + MySQL + Botman.io | Variable Scope

### ISSUE THREAD

**Issue by BetaStacks** [botman/botman#983]
Hi all!

At the moment I am stuck finding a way to automate the script to create triggers and responses from a SQL table.  My script is able to create a working trigger for each row in the table. However, I can't seem to pull in the response from the corresponding row.  I know this has to do with variable scope and have made several attempts of passing the variable into the function with no success. 

If anyone has any input on what I'm doing wrong, what would work, or what I should google, I would really appreciate it.

 Cheers! 

Brandon

  ```
  $servername = "localhost";
    $username = "USR";
    $password = "PASS!";
    $dbname = "DB";
     	


    $botman = resolve('botman');



    // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
    } 

    $sql = "SELECT id, command, responce, function FROM commands_general";
    $result = $conn->query($sql);

    if ($result->num_rows > 0) {
    while($row = $result->fetch_assoc()) {
     $botman->hears($row['command'], function ($bot) {
        	$bot->reply($row['responce']);  	
    		});
    	

    } 
    } else {
    echo "0 results";
    }

    $conn->close();
```

**Comment by BetaStacks** [comment]
So I'm currently trying something that looks like this. 
It creates a global variable and I can pass a response from the table to reply. However only by manually defining to use $responceX (ie. $responce2). I thought a solution might be to use a counter to add the corresponding ID to the end of the variable.

 ```
   // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
    } 

    $sql = "SELECT id, command, responce, function FROM commands_general";
    $result = $conn->query($sql);


    if ($result->num_rows > 0) {

    $counter = 0;

    while($row = $result->fetch_assoc()) {

    $counter++;

    $GLOBALS['id'] = $row["id"];
    $responceId = 'responce'.$row["id"];
    $GLOBALS[$responceId] = $row['responce'];


    static $counter;

     $botman->hears($row['command'], function ($bot) {
           static $counter;

            global $id;
     			global $responce2;
        	$bot->reply($counter);  
        	
    		});
    		
    		
    }    
    } else {
    echo "0 results";
    }

    $conn->close();
```

EDIT:

This is what the code looked like when it was passing the variable.

 
 ```
   // Create connection
    $conn = new mysqli($servername, $username, $password, $dbname);
    // Check connection
    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    } 

    $sql = "SELECT id, command, responce, function FROM commands_general";
    $result = $conn->query($sql);

    if ($result->num_rows > 0) {

        while($row = $result->fetch_assoc()) {

    //$command = $row['command'];
    $responceId = 'responce'.$row["id"];
    $GLOBALS[$responceId] = $row['responce'];


     $botman->hears($row['command'], function ($bot) {
     			global $responce2;
            	$bot->reply($responce2);  	
    		});
        }    
    } else {
        echo "0 results";
    }

    $conn->close();
```

**Comment by ederluca** [comment]
I was able to resolve this issue with a similar problem but I can not resolve a bank with some pre-defined answers and I can not return the answer.

**Comment by AhmedRamadan30** [comment]
I got same error
status: 500

**Comment by yesge** [comment]
$botman->hears('.*', function ($bot) {

                 $answer=   /*******************here make the sql query************/

                $bot->reply($answer);
            });

this way I work correctly

**Comment by ahmedatef00** [comment]
is there any way to open an input field in the messenger bot and make the user type the query in it? @yesge ?!
I don't understand if * represent any thing after the  .
