### ISSUE TITLE
Is it possible to load different messages from database for different users in database?

### ISSUE THREAD

**Issue by shamnascv** [botman/botman#986]
- BotMan Version: #.#.#
- PHP Version:
- Messaging Service(s):
- Cache Driver:

### Description:
I want to build a platform where my customers should be able to create facebook messenger bots without coding. I have people who store questions and answers in database. 

How to do that? I am not able to use session variables inside botman to select user specific messages.

**Comment by christophrumpel** [comment]
Hey,

In your conversation to define yourself how to get messages. You can, for example, check the user ID and depending on that load a message from a database.

**Comment by shamnascv** [comment]
> Hey,
> 
> In your conversation to define yourself how to get messages. You can, for example, check the user ID and depending on that load a message from a database.

Thanks for the reply, Buddy!
Below is my working code where $msgID is the id of first msg which should be there in the database, ideally. 

`class ButtonConversation extends Conversation{

    public function run(){
        $msgID = 9;
        $this->startConv($msgID);

        
    }

    public function startConv($id){
        $msg = Message::find($id);
        $replymsg = Reply::where('message_id',$id)->get();
        $question = Question::create($msg->message);
        foreach ($replymsg as $answer) {
           $question->addButton(Button::create($answer->reply)->value($answer->nextId));
           
       }

       $this->ask($question, function($answer){
           $next = $answer->getValue();
           //$nextMessage = Message::where('nextId','4');
               //$this->say('Hii');
               $this->startConv($next);
           
       });

               

    }
`
I am not able to load $msgID from database since I am not able to pass variables through run() method. I tried this.

` public function run(Request $request){
        $brand_id = $request->session()->get('brand_id');
        $brand = Brand::find($brand_id);
        $messages = $brand->messages;
        $msgID = 9;
        $this->startConv($msgID);  
    }`

and run into the following error.
" Symfony\Component\Debug\Exception\FatalErrorException  : Declaration of App\Conversations\ButtonConversation::run(Illuminate\Http\Request $request) must be compatible with BotMan\BotMan\Messages\Conversations\Conversation::run()"

I think I am doing it wrong. There should be a better way, right?

**Comment by christophrumpel** [comment]
Hmm I'm not exactly sure what you want to do here. Where does the `$msgID` come from?
Generally, you can pass data to your conversation through the constructor. Just add a constructor to the conversation and pass data when you start the conversation. In the `run` method you can then use it.

But since this is not an "issue" I need to close it here. Please use the Slack channel for asking for advice. I'm also there and will try to help when I have time.
