### ISSUE TITLE
Botman + RabbitMQ

### ISSUE THREAD

**Issue by overals** [botman/botman#991]
Hi,

I have a question about the rabbitmq. Can you tell me how I can combine them? 
I thinking via Sending Middleware (Save all messages in the queue, and then send), but I could be wrong.

Maybe someone has already done it?

Regards,
Overals

**Comment by marcelnagm** [comment]
I want to ask the same because i havent figured out how to do that

**Comment by marcelnagm** [comment]
I found it, writing own middleware to do that.
https://botman.io/2.0/middleware

**Comment by marcelnagm** [comment]
https://botman.io/2.0/drivers
we need to write our own driver to perform that
