### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by abertranb** [botman/botman#993]
- BotMan Version: 2.4.1
- PHP Version:  7.2.8
- Messaging Service(s):  all
- Cache Driver: Files

### Description:

We don't receive the exception message using web driver

### Steps To Reproduce:

1. Download  botman studio
2. Install it (composer install, cp .env.example .env, php artisan key:generate)
3. Add this code at the end of routes/botman.php
```
$botman->hears('Exception', function ($bot) {
    throw new Exception();
});
$botman->exception(Exception::class, function($exception, $bot) {
    \Illuminate\Support\Facades\Log::info("Exception");
    $bot->reply('Sorry, something went wrong');
});
```
4. Start it (php artisan serve) and read logs on other terminal (tail -f storage/logs/laravel.log )
5. Go to tinker (http://localhost:8000/botman/tinker) 
6. Write "Exception"
7. We don't receive any response

Thanks!

**Comment by Ranger-X** [comment]
For workaround try this:
```
$botman->exception(Exception::class, function($exception, $bot) {
    \Illuminate\Support\Facades\Log::info("Exception");
    $bot->reply('Sorry, something went wrong');
    if (method_exists($bot->getDriver(), 'messagesHandled'))
        $bot->getDriver()->messagesHandled();
});
```

**Comment by abertranb** [comment]
Thanks!!
