### ISSUE TITLE
Botman not hearing middleware (Dialogflow)

### ISSUE THREAD

**Issue by Aramis-Delg** [botman/botman#994]
- BotMan Version: 2.0
- PHP Version: 7.3
- Cache Driver: Laravel's caché driver

Hi I have a question about Botman + Dialogflow; I was not able to make it work, Botman doesn't hear Dialogflow, I've searched in Slack and other issues and examples, followed step by step, also used ngrok, but it just doesn't work and I don't get anything in the logs,the only thing I guess that could affect the connection is dialogflow's versions:
![image](https://user-images.githubusercontent.com/39425386/54619745-b6f37080-4a2a-11e9-966d-a2a7a85c66b8.png)

I checked that version, could that be what affected my connection between botman and Dialogflow.

**Comment by quangvision** [comment]
I am having same problem, I set middleware using $dialogflow but no call to api link https://api.api.ai/v1/query?v=20150910.
Do you know why?

**Comment by isbkch** [comment]
Same issue here, changing the API version doesn't work either

**Comment by james-muriithi** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/26818458/60183597-44670d80-982f-11e9-810d-8480a28c17b1.png)
You need to know the name of the **action** you want the bot to hear. For example in the photo above the action is `smalltalk.agent.annoying`
soo your code should be
```
$botman->hears('smalltalk.agent.annoying', function(Botman $bot) {
	$extras = $bot->getMessage()->getExtras();
	$apiReply = $extras['apiReply'];
	$apiAction = $extras['apiAction'];
	$apiIntent = $extras['apiIntent'];

	$bot->typesAndWaits(1);
	$bot->reply($apiReply);
})->middleware($apiAi);
```

Hope that helps

**Comment by atsoares** [comment]
I'm having the same problem and I'm using like this:

```
   $botman->hears('input.welcome', function(BotMan $bot) {
    
    console.log('works');
    $extras = $bot->getMessage()->getExtras();
    $apiReply = $extras['apiReply'];
    $apiAction = $extras['apiAction'];
    $apiIntent = $extras['apiIntent'];
    $bot->typesAndWaits(1);
    $bot->reply($apiReply);
     
  })->middleware($dialogflow);

  $botman->listen();

```

Checking the history at Dialogflow console I can see all the sentence that I sent to botman but it can't hear or reply. Tried different actions name but nothing worked.
