### ISSUE TITLE
Upload file from web widget

### ISSUE THREAD

**Issue by isbkch** [botman/botman#998]
- BotMan Version: latest
- PHP Version: 7
- Messaging Service(s): Web
- Cache Driver: Redis

### Description:
I couldn't find anything in the official documentation but how can you trigger an upload dialog from web widget ?

**Comment by claretnnamocha** [comment]
The original interface does not support this feature but there's a walk around  
Click then link to see it https://github.com/botman/web-widget/issues/23#issuecomment-504870024

**Comment by Muhammadsodiqq** [comment]
**It looks like I have a file download in the botman widget)
**
