### ISSUE TITLE
How to set url to keyboard 

### ISSUE THREAD

**Issue by nonobott** [botman/botman#999]
Hello, could you please help me with: 

$botman->hears('/start', function (BotMan $bot) {
$keyboard = [
                        ['Buy','Sell']  
                      ];
               $tetmessage="Welcome .....";

    $bot->sendRequest("sendMessage", ["text" => $tetmessage, 'reply_markup' => json_encode([
        'keyboard' => $keyboard,
        'one_time_keyboard' => false,
        'resize_keyboard' => true
        ])
    ]);

});

Could you please update me, is there any way to set url to the buttons this way? 

Means on click Buy, customer will be redirected to Private Channel. 

Thank you!!!

**Comment by nonobott** [comment]
Finally I have find that, there no way to set link to bottom keyboard buttons. 

Solution is: 

               $inline_keyboard[] = [
               [
               'text' => 'Text1',
               'callback_data' => '1'
               ],
               [
               'text' => 'Text 2',
               'callback_data' => '2'
               ]
               ];
               
               $tetmessage="Welcome .....";

    $bot->sendRequest("sendMessage", ["text" => $tetmessage, 'reply_markup' => json_encode([
        'inline_keyboard' => $inline_keyboard,
        'one_time_keyboard' => false,
        'resize_keyboard' => true
        ])
    ]);

});

But could some one help, how to display Text 1 and Text 2 from new line, not the same line ? 

Thank you.

**Comment by Slawekslaweslawslasls** [comment]
I suppose you want something like this
https://imgur.com/eS1elqo
If so, my code was:
`reply_markup={"inline_keyboard":[[{"text":" text1 ","callback_data":"\1"}],[{"text":" text2","callback_data":"\2"}]],"resize_keyboard":true}`
